### ISSUE TITLE
Cannot complete the appointment wizard - Got AJAX Error (v1.1 Beta).

### ISSUE THREAD

**Issue by migueldelias** [alextselegidis/easyappointments#100]
Hi 
when i try to confirm the apointment
show up
"the operation could not complete due to unexpected issues.

Details
AJAX Error: error

"
can you help me
miguel.delias@gmail.com
thanks you

![image](https://cloud.githubusercontent.com/assets/16171464/12189286/6bb7b83e-b58a-11e5-95a2-0980874746bd.png)

**Comment by alextselegidis** [comment]
Hi, check out the network tab of your browser, there you will find the response for the ajax_register_appointment. 

Post it here so I can see the problem.

**Comment by migueldelias** [comment]
hi
i don't know what is
"network tab of your browser "
can you send me an application last version and instalati on and the
intruccion , install and the procces to run

have a nice day
ps
i think my problem is some configuration. my instalation is the onlly one.

best regards
thanks


On Fri, Jan 8, 2016 at 6:52 AM, Alex Tselegidis <notifications@github.com>
wrote:

> Hi, check out the network tab of your browser, there you will find the
> response for the ajax_register_appointment.
>
> Post it here so I can see the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alextselegidis/easyappointments/issues/100#issuecomment-169977027>
> .
>



-- 
 MIguel DElias
(813) 4587868

**Comment by alextselegidis** [comment]
Hey, it's quite to look the original response by pressing F12 (which will open the developer tools) and then click on the "Network" tab. Then you will see a list of the all the page network requests. Book the appointment (complete wizard, click on confirm) and then check on the list for a request that contains the "ajax_register_appointment". Select it and then check the right side of the developer tools. There is a preview tab that will show you what your server returns. 

Also enable the DEBUG constant in your config.php file.  

I cannot really send you another version to install just try the above steps.

https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading#network-panel-overview

**Comment by migueldelias** [comment]
Morning
the issue is

Error Number: 1366

Incorrect integer value: 'false' for column 'is_unavailable' at row 1

INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`,
`is_unavailable`, `id_users_provider`, `id_services`, `id_users_customer`,
`book_datetime`, `hash`) VALUES ('2016-01-21 10:15:00', '2016-01-21
10:45:00', '', 'false', '85', '13', '88', '2016-01-09 13:02:22',
'49cb7ae945aaaacfb42b36354159ede9')

Filename: C:\Apache24\htdocs\ea\system\database\DB_driver.php

Line Number: 331

How i can fix it

thank you




On Sat, Jan 9, 2016 at 6:21 AM, Alex Tselegidis <notifications@github.com>
wrote:

> Hey, it's quite to look the original response by pressing F12 (which will
> open the developer tools) and then click on the "Network" tab. Then you
> will see a list of the all the page network requests. Book the appointment
> (complete wizard, click on confirm) and then check on the list for a
> request that contains the "ajax_register_appointment". Select it and then
> check the right side of the developer tools. There is a preview tab that
> will show you what your server returns.
>
> Also enable the DEBUG constant in your config.php file.
>
> I cannot really send you another version to install just try the above
> steps.
>
>
> https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading#network-panel-overview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alextselegidis/easyappointments/issues/100#issuecomment-170226738>
> .
>



-- 
 MIguel DElias
(813) 4587868

**Comment by alextselegidis** [comment]
I have made a change to the corresponding file. Could you check if it works for you? 

(Download the package from the release-1.1 branch or just check the change from the [commit](https://github.com/alextselegidis/easyappointments/commit/636f399c91c8fbb2be9dd357698005bf24c39e00))

**Comment by alextselegidis** [comment]
Would you also mind telling me your Apache, PHP and MySQL versions so that I know where I should expect such kind of issues, because this doesn't really happen on my machine.

**Comment by migueldelias** [comment]
thank you
Apache v 2.4.18
php v 5.6.10
Mysql 5.5.47

Working OK
Thanks

**Comment by migueldelias** [comment]
Hi
Thank you for your help 
Easy is working in my laptop 
What I'm needs to do to run easy in Godaddy 
Thanks

**Comment by alextselegidis** [comment]
Hi there :)

Upload the files per FTP, export and then import your database through phpmyadmin and update the config.php values so that they match with your new server.

**Comment by migueldelias** [comment]
Hi and thank you 
Does easy work with windows 10
?
Have a nice day

**Comment by migueldelias** [comment]
Hi
Does Easy work with windows 10?
Thanks

**Comment by alextselegidis** [comment]
Yeah, sure. It doesn't have to do with the operating system. It needs an Apache server with PHP and MySQL installed.

**Comment by migueldelias** [comment]
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 347
-- 
 MIguel DElias
(813) 4587868

**Comment by alextselegidis** [comment]
I think your database credentials are wrong (the ones you entered in the config.php file).

**Comment by migueldelias** [comment]
hi please see the screen

[image: Inline image 1]
===============================

Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 347

==================================

my setting


    //
------------------------------------------------------------------------

    // General Settings

    //
------------------------------------------------------------------------

     const BASE_URL      = 'http://107.180.41.126/ea/';

//   const BASE_URL      = 'http://localhost/ea/';

//   const BASE_URL      = 'http://127.0.0.1/ea/';


    const DEBUG_MODE    = FALSE;



    //
-----------------------------------------h------------------------------

    // Database Settings

    //
------------------------------------------------------------------------

    const DB_HOST       = '107.180.41.126';

    const DB_NAME       = 'ea';

    const DB_USERNAME   = 'eauser';

    const DB_PASSWORD   = 'Abril1234';


    //
------------------------------------------------------------------------
help me
Have a nice day


On Sat, Jan 23, 2016 at 2:55 AM, Miguel D'Elias <miguel.delias@gmail.com>
wrote:

>
> A Database Error Occurred
>
> Unable to connect to your database server using the provided settings.
>
> Filename: core/Loader.php
>
> Line Number: 347
> --
>  MIguel DElias
> (813) 4587868
>



-- 
 MIguel DElias
(813) 4587868

**Comment by alextselegidis** [comment]
It's never a good idea to post your installation credentials in a public site. Your config file seems to be correct. The problem must lie somewhere else within your server. Try to run a simple php script that connects to the database and check if it really works with these credentials.

BTW you have to remove the trailing slash from the BASE_URL value (but this is not associated with the problem).

**Comment by migueldelias** [comment]
hi
i do not to do that, the php program using mysql,
can you helpme
im using godaddy host
they told me, use localhost
the ip is 107.180.41.126
i created a bd ea
and the password in my user mysql
but does not works.


On Sun, Jan 24, 2016 at 11:46 AM, Alex Tselegidis <notifications@github.com>
wrote:

> It's never a good idea to post your installation credentials in a public
> site. Your config file seems to be correct. The problem must lie somewhere
> else within your server. Try to run a simple php script that connects to
> the database and check if it really works with these credentials.
>
> BTW you have to remove the trailing slash from the BASE_URL value (but
> this is not associated with the problem).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alextselegidis/easyappointments/issues/100#issuecomment-174315264>
> .
>



-- 
 MIguel DElias
(813) 4587868

**Comment by migueldelias** [comment]
hi
i do no know what put in .

    //
------------------------------------------------------------------------
     const BASE_URL      = 'http://107.180.41.126/ea/';
//   const BASE_URL      = 'http://localhost/ea/';
//   const BASE_URL      = 'http://127.0.0.1/ea/';

    const DEBUG_MODE    = FALSE;

    //
------------------------------------------------------------------------
    // Database Settings
    //
------------------------------------------------------------------------
    const DB_HOST       = 'http://107.180.41.126';
    const DB_NAME       = 'eabd';
    const DB_USERNAME   = 'wataxservice2016';
    const DB_PASSWORD   = 'Abril@1234';

    //
------------------------------------------------------------------------

let me know what parameter i need to use
thank you

all day long ....

On Sun, Jan 24, 2016 at 1:43 PM, Miguel D'Elias <miguel.delias@gmail.com>
wrote:

> hi
> i do not to do that, the php program using mysql,
> can you helpme
> im using godaddy host
> they told me, use localhost
> the ip is 107.180.41.126
> i created a bd ea
> and the password in my user mysql
> but does not works.
>
>
> On Sun, Jan 24, 2016 at 11:46 AM, Alex Tselegidis <
> notifications@github.com> wrote:
>
>> It's never a good idea to post your installation credentials in a public
>> site. Your config file seems to be correct. The problem must lie somewhere
>> else within your server. Try to run a simple php script that connects to
>> the database and check if it really works with these credentials.
>>
>> BTW you have to remove the trailing slash from the BASE_URL value (but
>> this is not associated with the problem).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alextselegidis/easyappointments/issues/100#issuecomment-174315264>
>> .
>>
>
>
>
> --
>  MIguel DElias
> (813) 4587868
>



-- 
 MIguel DElias
(813) 4587868

**Comment by migueldelias** [comment]
Good morning 
Let me know the fields dow you need 
To ask Godaddy 
Thank you

**Comment by emanwebdev** [comment]
Hi 
there are compatibility issues with the new MySQL 5.7

MySQL 5.7 is configured to use strict mode by default, along some other changes, 
which might raise some incompatibilities with current DB_driver.php

(stable MySQL 5.7 releases were published in recent months, including latest 5.7.10, see changes https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-10.html )

These includes date default value, data integrity (truncation of data longer than specified will throw an error instead of silent cut-off), entering signed into unsigned field, and other nuances. On custom servers emulation of old behavior can be achieved, but we should not rely on it.

**Comment by migueldelias** [comment]
Hi
Good the information 
Can you help me?
I don't know what parameters have to modify in the configure.php and what to change in the Godaddy hosting
Thank you for your time 
Best regards

**Comment by migueldelias** [comment]
Hi is me again 
The application is running good in my computer

**Comment by migueldelias** [comment]
Alex
Can you send  me your applcation , to run in godaddy
please

On 1/26/16, Miguel D'Elias <miguel.delias@gmail.com> wrote:
> Hi is me again
> The application is running good in my computer
>
> Sent from my iPhone
>
>> On Jan 26, 2016, at 5:51 AM, Emmanuel <notifications@github.com> wrote:
>>
>> Hi
>> there are compatibility issues with the new MySQL 5.7
>>
>> MySQL 5.7 is configured to use strict mode by default, along some other
>> changes,
>> which might raise some incompatibilities with current DB_driver.php
>>
>> (stable MySQL 5.7 releases were published in recent months, including
>> latest 5.7.10, see changes
>> https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-10.html )
>>
>> These includes date default value, data integrity (truncation of data
>> longer than specified will throw an error instead of silent cut-off),
>> entering signed into unsigned field, and other nuances. On custom servers
>> emulation of old behavior can be achieved, but we should not rely on it.
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>


-- 
 MIguel DElias
(813) 4587868

**Comment by alextselegidis** [comment]
@emanwebdev So do you think that the problem is caused due to MySQL compatibility issues? I haven't tested the app yet in the latest version.

@miguel I'm sorry but there aren't any other files to send you. The stable version should work. Please check for additional error logs in your server.

**Comment by migueldelias** [comment]
Hi Alex 
Please send to me the stable version 
Maybe I have the wrong version 
Thenk so much

**Comment by alextselegidis** [comment]
Here's the package for v1.1

https://github.com/alextselegidis/easyappointments/releases/download/1.1.0/easyappointments_1.1.0.zip

**Comment by migueldelias** [comment]
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 347


===================

!DOCTYPE html>
<html lang="en">
<head>
<title>Database Error</title>
<style type="text/css">

::selection{ background-color: #E13300; color: white; }
::moz-selection{ background-color: #E13300; color: white; }
::webkit-selection{ background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	-webkit-box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}
</style>
</head>
<body>
	<div id="container">
		<h1>A Database Error Occurred</h1>
		<p>Unable to connect to your database server using the provided
settings.</p><p>Filename: core/Loader.php</p><p>Line Number:
347</p>	</div>
</body>
</html>

-- 
 MIguel DElias
(813) 4587868

**Comment by migueldelias** [comment]
Hi
Nobody was install Easy in godaddy ?
What can i do??
would you like my godaddy account to try??
thank you

On 1/24/16, Miguel D'Elias <miguel.delias@gmail.com> wrote:
> hi
> i do not to do that, the php program using mysql,
> can you helpme
> im using godaddy host
> they told me, use localhost
> the ip is 107.180.41.126
> i created a bd ea
> and the password in my user mysql
> but does not works.
>
>
> On Sun, Jan 24, 2016 at 11:46 AM, Alex Tselegidis
> <notifications@github.com>
> wrote:
>
>> It's never a good idea to post your installation credentials in a public
>> site. Your config file seems to be correct. The problem must lie
>> somewhere
>> else within your server. Try to run a simple php script that connects to
>> the database and check if it really works with these credentials.
>>
>> BTW you have to remove the trailing slash from the BASE_URL value (but
>> this is not associated with the problem).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alextselegidis/easyappointments/issues/100#issuecomment-174315264>
>> .
>>
>
>
>
> --
>  MIguel DElias
> (813) 4587868
>


-- 
 MIguel DElias
(813) 4587868

**Comment by migueldelias** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<title>Database Error</title>
<style type="text/css">

::selection{ background-color: #E13300; color: white; }
::moz-selection{ background-color: #E13300; color: white; }
::webkit-selection{ background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	-webkit-box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}
</style>
</head>
<body>
	<div id="container">
		<h1>A Database Error Occurred</h1>
		<p>Unable to connect to your database server using the provided
settings.</p><p>Filename: core/Loader.php</p><p>Line Number:
347</p>	</div>
</body>
</html>

On 1/28/16, Miguel D'Elias <miguel.delias@gmail.com> wrote:
> A Database Error Occurred
>
> Unable to connect to your database server using the provided settings.
>
> Filename: core/Loader.php
>
> Line Number: 347
>
>
> ===================
>
> !DOCTYPE html>
> <html lang="en">
> <head>
> <title>Database Error</title>
> <style type="text/css">
>
> ::selection{ background-color: #E13300; color: white; }
> ::moz-selection{ background-color: #E13300; color: white; }
> ::webkit-selection{ background-color: #E13300; color: white; }
>
> body {
> 	background-color: #fff;
> 	margin: 40px;
> 	font: 13px/20px normal Helvetica, Arial, sans-serif;
> 	color: #4F5155;
> }
>
> a {
> 	color: #003399;
> 	background-color: transparent;
> 	font-weight: normal;
> }
>
> h1 {
> 	color: #444;
> 	background-color: transparent;
> 	border-bottom: 1px solid #D0D0D0;
> 	font-size: 19px;
> 	font-weight: normal;
> 	margin: 0 0 14px 0;
> 	padding: 14px 15px 10px 15px;
> }
>
> code {
> 	font-family: Consolas, Monaco, Courier New, Courier, monospace;
> 	font-size: 12px;
> 	background-color: #f9f9f9;
> 	border: 1px solid #D0D0D0;
> 	color: #002166;
> 	display: block;
> 	margin: 14px 0 14px 0;
> 	padding: 12px 10px 12px 10px;
> }
>
> #container {
> 	margin: 10px;
> 	border: 1px solid #D0D0D0;
> 	-webkit-box-shadow: 0 0 8px #D0D0D0;
> }
>
> p {
> 	margin: 12px 15px 12px 15px;
> }
> </style>
> </head>
> <body>
> 	<div id="container">
> 		<h1>A Database Error Occurred</h1>
> 		<p>Unable to connect to your database server using the provided
> settings.</p><p>Filename: core/Loader.php</p><p>Line Number:
> 347</p>	</div>
> </body>
> </html>
>
> --
>  MIguel DElias
> (813) 4587868
>

    // General Settings
    // ------------------------------------------------------------------------
    const BASE_URL      = 'http://localhost/eaok';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = FALSE;

    // ------------------------------------------------------------------------
    // Database Settings
    // ------------------------------------------------------------------------
    const DB_HOST       = 'http://localhost';
    const DB_NAME       = 'ea9546';
    const DB_USERNAME   = 'wataxservice2016';
    const DB_PASSWORD   = 'Abril@1234';

    // ------------------------------------------------------------------------
    // Google Calendar Sync
    // ------------------------------------------------------------------------
    const GOOGLE_SYNC_FEATURE   = FALSE; // Enter TRUE or FALSE
    const GOOGLE_PRODUCT_NAME   = '';
    const GOOGLE_CLIENT_ID      = '';
    const GOOGLE_CLIENT_SECRET  = '';
    const GOOGLE_API_KEY        = '';
}

-- 
 MIguel DElias
(813) 4587868

**Comment by alextselegidis** [comment]
Hi, can you send me the GoDaddy Apache, Php and MySql versions? I will try to test the application in these versions.

Have you tried to contact the GoDaddy support team?

**Comment by migueldelias** [comment]
Hi
Php 5.4
Apache 2.4.9
Mysql 5.5.35

Thank

**Comment by migueldelias** [comment]
Hi
i would like give to you my account in godaddy and try
plase

On 1/29/16, Miguel D'Elias <miguel.delias@gmail.com> wrote:
> Hi
> Php 5.4
> Apache 2.4.9
> Mysql 5.5.35
>
> Thank
>
> Sent from my iPhone
>
>> On Jan 29, 2016, at 3:00 AM, Alex Tselegidis <notifications@github.com>
>> wrote:
>>
>> Hi, can you send me the GoDaddy Apache, Php and MySql versions? I will try
>> to test the application in these versions.
>>
>> Have you tried to contact the GoDaddy support team?
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>


-- 
 MIguel DElias
(813) 4587868

**Comment by migueldelias** [comment]
Hi i would like to send the Godaddy username and password to try 
Maybe is some setting on php, Apache,  allow rewrite, or MySQL 
I need your help

**Comment by migueldelias** [comment]
Wataxservice.com/Cpanel 

Wataxservice2016

Abril@1234

Thank you

**Comment by alextselegidis** [comment]
Hey miguel, please don't post credentials in public. Send them to my personal email address alextselegidis@gmail.com

By the way I couldn't login to you CPanel with these credentials. Please send me the new ones and I will check the problem personally.

**Comment by alextselegidis** [comment]
Just to clarify the situation for other users,I would like to state that Easy!Appointments v1.1 does not have any problems in GoDaddy servers.

**Comment by alextselegidis** [comment]
The problem of Miguel was due to invalid database configuration.

**Comment by emanwebdev** [comment]
@alextselegidis wrote:

> Just to clarify the situation for other users,I would like to state that Easy!Appointments v1.1 does not have any problems in GoDaddy servers.

Thanks for taking time to explain!

Best wishes to you
Emmanuel
