### ISSUE TITLE
Some Problem after Installed EasyAppointment on AWS Docker

### ISSUE THREAD

**Issue by ZeroDistance-India** [alextselegidis/easyappointments#1002]
Hi,
We have successfully installed EasyAppointment on AWS Docker, but "Working Plan Exceptions" option  in "Create Provider" Page is not showing up.
so can you help us to solve this.

**Comment by alextselegidis** [comment]
Hello! 

The working plan exceptions is a feature first introduced with Easy!Appointments v1.4

Please make sure you are running the latest version. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
