### ISSUE TITLE
Multiple Customers with same emails

### ISSUE THREAD

**Issue by HybridRCG** [alextselegidis/easyappointments#1003]
Hello,

Is it possible for us to allow multiple customers with same emails? 
Using v1.4

I tried commenting out below in Customers_model.php , but then nothing seems to work. :(

    // :: CHECK IF CUSTOMER ALREADY EXIST (FROM EMAIL).
        if ($this->exists($customer) && ! isset($customer['id']))
        {
            // Find the customer id from the database.
            $customer['id'] = $this->find_record_id($customer);
        }

**Comment by AlessioArtini** [comment]
You should follow : https://github.com/alextselegidis/easyappointments/pull/707

**Comment by alextselegidis** [comment]
Hello! 

You can also edit the Customers_model.php file, go to the "exists" method and add a "return FALSE;" at the beginning. 

Customers won't be matched after that. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by HybridRCG** [comment]
I have changed the document as requested, but the programme still says I'm not allowed to use duplicate email addresses.
Thank you.
[Customers_model.php.zip](https://github.com/alextselegidis/easyappointments/files/5959473/Customers_model.php.zip)
