### ISSUE TITLE
Add support for line breaks when displaying the service description in the frontend. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#1004]
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by olivm-fr** [comment]
Hello
Workaround to allow that + any HTML formatting in service descriptions (frontend only) :
`/assets/js/frontend_book.js` line 747 in 1.4.1
```
            $('<span/>', {
                'html': service.description.replaceAll('\n', '<br/>')
            })
```
Then, minimize or (ugly) copy file to `/assets/js/frontend_book.min.js`

**Comment by alextselegidis** [comment]
Fixed on develop.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
