### ISSUE TITLE
Google support files

### ISSUE THREAD

**Issue by aubreyz** [alextselegidis/easyappointments#1008]
I'm about to install this for a trial run. However for various reasons (although I would want Google Calendar integration) I cannot install and maintain 14,000 files, and the bulk of these are part of the google complete API

under \vendor\google\apiclient-services\src\Google\Service

A lot of this is seemingly totally irrelevant stuff to do with Youtube, street maps and so on. 

I don't see any documentation about this at all - which would be a killer for me. 
Can we somehow know which of these files/folders are actually required.....

(in fact just unzipping the installation zip onto my desktop took over 25 minutes of virus/malware checking just to go through this stuff, and it would cause a similar server overload).

**Comment by alextselegidis** [comment]
Hello! 

It's true that the vendor directory may have files that are not directly needed by the app. 

For that the production build of Easy!Appointments is using the appropriate composer parameters to create smaller bundles for production. 

So it is basically up to the package maintainer to also mark unnecessary files as non-production files, but unfortunately this is something not everyone does. 

Additionally Google has a single package for all of their services which eventually leads to you having all those files there.   Those files cannot be safely removed as by doing so, we may accidentally cause problems to live installations. 

I personally think that it is better to open a ticket to the package maintainers and ask for such improvements. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by aubreyz** [comment]
Thank you for your response. It is this part of your response that I don't understand:

You say "For that the production build of Easy!Appointments is using the appropriate composer parameters to create smaller bundles for production."

I am downloading at least what I think is the productrion build at 
https://github.com/alextselegidis/easyappointments/releases/download/1.4.1/easyappointments-1.4.1.zip

and that contains 35,000 google API related files. I'm not getting the API separately. Am I misunderstanding something. As I said my system chokes completely on that file collection (just checking it for malware is a slow and repeated issue).

**Comment by alextselegidis** [comment]
> I am downloading at least what I think is the productrion build at ... 

That's the production build correct. 

> and that contains 35,000 google API related files

That's what the google composer package contains, correct. 

> I'm not getting the API separately.

Which API? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by aubreyz** [comment]
OK so bottom line if I understand it - that I cannot install easyappointments without installing tens of thousands of files and around 0.1Gb -- correct?
