### ISSUE TITLE
Working plan exception - details pane shows incorrect details

### ISSUE THREAD

**Issue by mrkylegp** [alextselegidis/easyappointments#1011]
This is a preview of the details of a working plan exception that is set for 8:00AM to 8:00PM for 20th Feb 2021.

![image](https://user-images.githubusercontent.com/52687659/108591173-74c3ce00-73bb-11eb-9163-6ff6b16e33bd.png)

As you can see, it's not correct. However if I hit edit to double check what is in place, you can see the details are correct.

![image](https://user-images.githubusercontent.com/52687659/108591207-9d4bc800-73bb-11eb-9008-67811921688e.png)

EasyAppointments 1.4.1

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting this. 

This will be fixed for the next version 1.4.2

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
