### ISSUE TITLE
Override Service price by provider

### ISSUE THREAD

**Issue by Oddadmix** [alextselegidis/easyappointments#1014]
First I want to thank you for this great repo.

I have a question, how can I override the price of the service by the provider?

**Comment by alextselegidis** [comment]
Hello! 

For this to work you will need to perform a series of changes to the original code of the app: 

1. Store the service-provider-individual-price to the database
2. Read the price and display it in the booking page 
3. Optionally include the price in the confirmation and other post-booking views

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
