### ISSUE TITLE
dafault timezone

### ISSUE THREAD

**Issue by comunemisterbianco** [alextselegidis/easyappointments#1017]
where can i change the default timezone? i tried from Timezones.php and from database but it had no effect

**Comment by alextselegidis** [comment]
Hello! 

The default timezone is set to 'UTC' and can be found in /application/libraries/Timezones.php. 

```
/**
     * Get the default timezone value of the current system.
     *
     * @return string
     */
    public function get_default_timezone()
    {
        return 'UTC';
    }
```

The ea_users.timezone field also is set to UTC for the default value. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
