### ISSUE TITLE
Prefill the form field though url parameters

### ISSUE THREAD

**Issue by jasimp** [alextselegidis/easyappointments#1021]
How to prefill the easy appointment form field though URL query parameters?
example : https://example.com/appointment-page/?name=abcd&email=test@test.com

**Comment by alextselegidis** [comment]
Hello! 

I'm marking this as a future enhancement. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jasimp** [comment]
Thanks Alex
