### ISSUE TITLE
Adding support for reports and reminder

### ISSUE THREAD

**Issue by admiralmedia** [alextselegidis/easyappointments#1025]
I'm new on using the Easy!Appointments platform and as I was working on a project for a small beauty salon the E!A become very handy.

The feedback received from the salon personnel was if can be added the following extra functionality:
1. Sending email reminders to the customers that made appointments. Predefined periods are fine(12h/24h/36h prior to appointment).
2. Listing reports of the appointments made in a custom period of time. The reports should contain the important appointment info as date, customer name, service name, service price.
3. For canceled/deleted appointments if there is a way to add them to the report from the point 2.
4. Recurring option for any appointment
5. Book multiple services at once.

The reporting feature I think is a must as many small users make all the tax calculations based on the appointments they had as the E!A platform is the only system used for gathering such info. Also without the email reminder feature many of the appointments are missed or forget by the customer.

Many thanks for the work and dedication to E!A platform.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for using the app and for posting your suggestions here. 

Those are features that are planned for future releases. 

I'm going to close this one and open new tickets when the time comes. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
