### ISSUE TITLE
Add open source captcha

### ISSUE THREAD

**Issue by onderzoekspraktijk** [alextselegidis/easyappointments#1027]
I started using easy!appointments recently, in an iframe inside a Joomla website: and I like it a lot. 
I would like to see one new addition to the software in future: a 'friendly' open source captcha.

The existing captcha is in my experience not user friendly at all: I get several errors when trying to guess the right answer.
I see that several years ago the google recaptcha was announced as an enhancement in the software. That would be nice, but still today would present GDPR problems (which are acknowledged by Google). 
So if there is no work done yet for this google recaptcha is there any change for a more open source type of captcha as an enhancement of the software?

Best regards,
Paul

**Comment by alextselegidis** [comment]
Hello! 

Do you have a captcha library in mind? 

Can you post an example of what you would find appropriate?

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by onderzoekspraktijk** [comment]
Hi!

Thank you for responding.
In the Joomla ecosystem there is one captcha that I do like a lot.
It is made by [Les Arbres Design]([url]https://www.lesarbresdesign.info/(url)) as an element in their form component FlexiContact Plus.

They offer several captcha types, but also advice on how to create forms that do not need a captcha to evade spammers.
I am a fan of there images captcha, and used that one on this site's [contact forms]
(https://gebroedersvangelderen.nl/contact)

[open source captcha](https://user-images.githubusercontent.com/10290910/112825028-8e77c580-908b-11eb-808b-1277f3c16222.png)

The component Les Arbres Design made asks to make a choice out of 4 pictures. So a small task is necessary before sending the form.
Another component that does not requires user action is made by [Aimy extensions](https://www.aimy-extensions.com/about.html) with their [Aimy Captcha-Less Form Guard]( https://www.aimy-extensions.com/joomla/captcha-less-form-guard.html). They use black lists, and honeypots etc.

The above work locally on the web-server. 
I looked at software that works on a centralised server.
Such as the FriendlyCaptcha which has [open source code published at Github](https://github.com/FriendlyCaptcha/friendly-challenge), with the MIT license. 
They use a central server to validate their captcha, which is perhaps not ideal: the first 1000 captcha challenges a month are 'free', more need a paid subscription.
In their [website](https://friendlycaptcha.com/) they emphasise issues of privacy and security. It guarantees to be GDPR compliant.

Not open source but with more explicit privacy protections there is hCaptcha. hCaptcha protects user privacy, rewards websites, and helps companies get their data labelled. Requires a free registration on i[ts website](https://www.hcaptcha.com/). Not sure they are GDPR compliant (US based as they are).

In the Joomla ecosystem it is quite normal to work with paid extra's, permitting the developer to keep the software up-to-date. I do not know if this is perhaps also a possibility for Easy!Appointments. If it would be, I would gladly pay for such a subscription.

Best regards,
Paul

**Comment by alextselegidis** [comment]
Hello! 

Thanks for providing all these information about the available captcha options. 

It's true that one can select and integrate many of the available options out there although it's not very easy to tell how secure each one is. 

This is basically that for Easy!Appointments I'm using the most popular captcha PHP library available in the packagist repository.

In the future I will be adding support for 3rd party services too (e.g. Google reCaptcha etc) but I will skip this for now as this is not a direct priority. 

Thanks for posting nevertheless! 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
FYI a new Joomla integration is currently in the works: https://easyappointments.org/blog/new-joomla-integration-in-the-works/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by onderzoekspraktijk** [comment]
Nice!

**Comment by Martin511** [comment]
> FYI a new Joomla integration is currently in the works: https://easyappointments.org/blog/new-joomla-integration-in-the-works/
> ![](https://camo.githubusercontent.com/b6ae4c709927e0f22bb9887f12b030ab995b6802b3d5fa2134f07bc4320a1a1c/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67) 	Alex Tselegidis, Easy!Appointments Creator
> [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

Hello Alex,
I´m not sure if I understood it correct: Is there already a usable Joomla plugin or is it still in developement?

Regards from Cologne
Martin

**Comment by alextselegidis** [comment]
Hello! 

The plugin is almost done and will be released soon. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Martin511** [comment]
Wow, great news!
I´m very exited!!
