### ISSUE TITLE
Multiple Providers with same user and email address

### ISSUE THREAD

**Issue by HaxNet** [alextselegidis/easyappointments#1034]
Is it possible to create multiple providers with same user and email address?

I am handling different clients and i don't want to have to create and remember all the user/pw and emails. i can't log into 10+ different emails just to see if i get any notifications

thanks

**Comment by alextselegidis** [comment]
Hello! 

For that you will need to make an adjustment to the Providers_model.php where the email and username check takes place and basically deactivate it. 

https://github.com/alextselegidis/easyappointments/blob/1.4.1/application/models/Providers_model.php#L129

There are a couple of those more in the app for other user roles, those may need to be changed too. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
