### ISSUE TITLE
Unavailable events do not block time from services with multiple attendants. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#1043]
This may lead to receiving unintended bookings. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by kabeza** [comment]
Hi Alex
I think I solved this by replacing the following in 
application/libraries/Availability.php
Line: 342

```
$unavailability_events = $this->CI->appointments_model->get_batch([
            'is_unavailable' => TRUE,
            'DATE(start_datetime)' => $date,
            'id_users_provider' => $provider['id']
        ]);
```

for

```
$unavailability_events = $this->CI->appointments_model->get_batch([
            'is_unavailable' => TRUE,
            'id_users_provider' => $provider['id']
        ]);
```

Tried everything and worked. Now for services with attendants > 1, the date ranges (set in backend) get blocked in the frontend calendar

Is this correct? Thanks

**Comment by alextselegidis** [comment]
Hello @kabeza 

Your query would bring up unavailability events without time restrictions which will introduce a big performance penalty. 

I tried the issue again and it is now fixed on develop. 

It looks like this was related to another issue of the past so I'm closing this ticket now. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Leonex123** [comment]
Hi, Could you point me where is the issue here since i got same problem on 1.4.1 and i cant update at the moment.

Thank you.

**Comment by kabeza** [comment]
> Hi, Could you point me where is the issue here since i got same problem on 1.4.1 and i cant update at the moment.
> 
> Thank you.

read my reply above ...
https://github.com/alextselegidis/easyappointments/issues/1043#issuecomment-867993409

**Comment by Leonex123** [comment]
> > Hi, Could you point me where is the issue here since i got same problem on 1.4.1 and i cant update at the moment.
> > Thank you.
> 
> read my reply above ...
> [#1043 (comment)](https://github.com/alextselegidis/easyappointments/issues/1043#issuecomment-867993409)

I did read it but as alex said "Hello @kabeza

Your query would bring up unavailability events without time restrictions which will introduce a big performance penalty."

i would like to know is there a way to fix it without performance penalty

**Comment by kabeza** [comment]
I don't know, not an EA expert, but the patch worked fine for my needs and didn't notice that performance penalty

**Comment by Leonex123** [comment]
> Hello @kabeza
> 
> Your query would bring up unavailability events without time restrictions which will introduce a big performance penalty.
> 
> I tried the issue again and it is now fixed on develop.
> 
> It looks like this was related to another issue of the past so I'm closing this ticket now.
> 
> ![](https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

Alex,  Can you tell me what was modified to get this to work correctly?

thank you,

**Comment by alextselegidis** [comment]
Hello! 

You can try using the application/library/Availability.php from 1.4.2 in your instance but I am not sure if that will conflict with other changes 1.4.2 has and 1.4.1 doesn't. 

In any case the best would be if you update your entire instance so that you keep up to date with the latest release. 

Cheers!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Leonex123** [comment]
> Hello!
> 
> You can try using the application/library/Availability.php from 1.4.2 in your instance but I am not sure if that will conflict with other changes 1.4.2 has and 1.4.1 doesn't.
> 
> In any case the best would be if you update your entire instance so that you keep up to date with the latest release.
> 
> Cheers!
> 
> ![](https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

Availability.php from 1.4.1 and 1.4.2 are the same, it has something to do with the :

$unavailability_events = $this->CI->appointments_model->get_batch([
            'is_unavailable' => TRUE,
            **'DATE(start_datetime)' => $date,**  <<---this line
            'id_users_provider' => $provider['id']
        ]);

that line with date must be linked to some other file since when i remove it then it works ok. Are you sure its fixed in 1.4.2 ?

**Comment by Leonex123** [comment]
> Hello!
> 
> You can try using the application/library/Availability.php from 1.4.2 in your instance but I am not sure if that will conflict with other changes 1.4.2 has and 1.4.1 doesn't.
> 
> In any case the best would be if you update your entire instance so that you keep up to date with the latest release.
> 
> Cheers!
> 
> ![](https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

Alex, i tried demo on your site V1.4.2 , this issue still persists, Make provider with 1 service, service has more then 1 attendant,
for this provider add unavalible period that lasts longer than 1 da (try 3 days unavalible). Go to front end booking page and select this service and you can book it in those 3 days when unavalible is set...

**Comment by alextselegidis** [comment]
@Leonex123 Thanks for the feedback, I will try this again and consider it for 1.5. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by fat115** [comment]
Hello,
Considering date range instead of date seems to fix the issue :

>         $unavailability_events = $this->CI->appointments_model->get_batch([
>             'is_unavailable' => TRUE,
>             'DATE(start_datetime) <=' => $date,
>             'DATE(end_datetime) >=' => $date,**
>             'id_users_provider' => $provider['id']
>         ]);
