### ISSUE TITLE
Merge develop into main

### ISSUE THREAD

**Issue by vitormattos** [alextselegidis/easyappointments#1045]
@alextselegidis what is missing for this merge to be done?

**Comment by alextselegidis** [comment]
Hello! 

Following the git flow schema master only has the latest released files. 

For that the next merge from develop to master will be made once the 1.4.2 is released (soon).

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by vitormattos** [comment]
It is good then to use Projects from GitHub so that it is visible what aid has to be done in future releases.

For example:

https://github.com/LibreSign/libresign/projects
