### ISSUE TITLE
date format in german

### ISSUE THREAD

**Issue by boardaholic** [alextselegidis/easyappointments#1047]
Hello, 

i come from Germany. 
easy!appointments is a great tool, but the date display in US. 
Example 15/04/21 How can I changed in 15.04.21 ?

Thank you for your answers

**Comment by winniae** [comment]
Hi,

I think it's not available by default, I implemented it in my custom project and will try to make a pull requests this week.

--winniae

**Comment by boardaholic** [comment]
Many Thanks winniae, 

I have found the file /appointments/assets/ext/datejs/date.min.js

this is the English (United States) version

(Date.CultureInfo = {
    name: "en-US",
    englishName: "English (United States)",

when I change the file with the original file from https://github.com/datejs/Datejs/blob/master/build/date-de-DE.js ,  
then easy!appointments no longer works. 

I will wait for your solution. 

Thank you very much

**Comment by alextselegidis** [comment]
Hello! 

One of the future releases will provide more options of localization and formatting of dates, prices, addresses etc. 

For now it's true that you can set your own locale to date.js and moment.js with javascript in order to override the default behavior. 

Additionally you can change the "formatDate" method of the general_functions.js file, and replace slashes with dots. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by winniae** [comment]
@boardaholic here you go, I pushed my PR for this issue
#1060 

hope it helps

**Comment by boardaholic** [comment]
Hallo Winfried, 

 

ich habe Dir schon 2 Mails an ***@***.*** ***@***.***>  geschrieben, aber vermutlich wurden die nicht zugestellt oder sind im SPAM gelandet. 

 

Ich habe Deine Änderungen durchgeführt (siehe Anlage), aber leider wird bei mir das Datum immer noch im falschen Format angezeigt. Eventuell habe ich ja ein anderes Paket von EasyAppointments. 

 

Von bin ich sehr überzeugt und die Terminbuchung funktioniert einwandfrei, wenn nicht die englische Datumsanzeige wäre. 

 

Einen Zugriff per FTP auf den Server und dem Backend von EasyAppointments würde ich Dir geben, damit Du Dir das mal anschauen kannst. 

 

Viele Grüße

Harry Hofstetter

 

 

Von: Winfried Mosler ***@***.*** 
Gesendet: Donnerstag, 22. April 2021 13:54
An: alextselegidis/easyappointments ***@***.***>
Cc: Harry ***@***.***>; Mention ***@***.***>
Betreff: Re: [alextselegidis/easyappointments] date format in german (#1047)

 

@boardaholic <https://github.com/boardaholic>  here you go, I pushed my PR for this issue
#1060 <https://github.com/alextselegidis/easyappointments/pull/1060> 

hope it helps

**Comment by boardaholic** [comment]
Hello, 

 

I have modify this, but it doesn’t work. 

 

Regards

Harry Hofstetter

 

Von: Alex Tselegidis ***@***.*** 
Gesendet: Montag, 19. April 2021 11:17
An: alextselegidis/easyappointments ***@***.***>
Cc: Harry ***@***.***>; Author ***@***.***>
Betreff: Re: [alextselegidis/easyappointments] date format in german (#1047)

 

Hello!

One of the future releases will provide more options of localization and formatting of dates, prices, addresses etc.

For now it's true that you can set your own locale to date.js and moment.js with javascript in order to override the default behavior.

Additionally you can change the "formatDate" method of the general_functions.js file, and replace slashes with dots.


 <https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67> 

  Alex Tselegidis, Easy!Appointments Creator 
  Need a customization? Contact me in person! <https://alextselegidis.com>
