### ISSUE TITLE
Some users got same hash

### ISSUE THREAD

**Issue by cerbernar** [alextselegidis/easyappointments#1062]
Hi, i have issue when many peoples trying to make appointments at the same time. Their appointments get the same hash value. May be will be better to change
https://github.com/alextselegidis/easyappointments/blob/96b694ff61901bda7116eb0f7e6b54db95ead180/application/models/Appointments_model.php#L177
to something like 
return md5(uniqid(rand(),1));

**Comment by alextselegidis** [comment]
Hello! 

Please update to the latest version of Easy!Appointments (currently 1.4.1) as the hash generation function got replaced. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
