### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by leon1995** [alextselegidis/easyappointments#1063]
Do you plan to add support for docker?

**Comment by alextselegidis** [comment]
Hello! 

There's already support for docker: 

https://easyappointments.org/docs.html#1.4.1/docker.md

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
