### ISSUE TITLE
Maximum number of bookings per day

### ISSUE THREAD

**Issue by peterkodermac** [alextselegidis/easyappointments#1064]
Great job on this web application! 
Can you please tell me how to allow only **one** booking per day? I've tried setting "Attendants number" to 1 but I can still book a different time period for the day, that already has a booking set.

**Comment by alextselegidis** [comment]
Hello!

For that you will need to either change the working plan of your provider to only allow for one booking or change the service duration to take the entire day. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
