### ISSUE TITLE
Set minimum service duration field value to honor the value of EVENT_MINIMUM_DURATION.

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1068]
Hi Alex,

first of all, Easy!Appointments is really great. We use it for corona test bookings.

We have only two concerns with the program. Missing European/German date format (without having to tweak files, see #1047 and #1060) and the following:

There is a fix minimum interval of 15 minutes in /application/views/backend/services.php:

`<input id="service-duration" class="form-control required" type="number" min="15">`

As our interval must be 5 minutes, we had to change that value in the mentioned file or change the value in the database.

**Request**: Shorter intervals should be possible. I think the corona test scenario shows that. With that the backend calender must be improved, so booking entries are not ultrasmall and not unreadable like here:

![weekly_view_broken_with_interval_5_minutes](https://user-images.githubusercontent.com/51790093/117104737-f604ed00-ad7c-11eb-9ca3-d466c0909810.png)

There are some calendar views with flexible entries:

- calendar month
- table list

and the flexible approach should be implemented in all other views, too, independend of the interval.

Cheers

Alex

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this, that "min" attribute should be set based on the EVENT_MINIMUM_DURATION constant (application/config/constants.php) which is also 5 minutes. 

I will make sure it is updated correctly. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
fixed on develop
