### ISSUE TITLE
space character in provider's first name results in Ajax error

### ISSUE THREAD

**Issue by mueslimak3r** [alextselegidis/easyappointments#1069]
when a provider's first name is set to 'Company Supervisor' a modal pops up when actions are performed with the message 'Ajax Error: '. Maybe this causes an error in the database or something. Removing the space fixes it.

**Comment by alextselegidis** [comment]
Hello! 

I think the error has to do within something else.

Please check in storage/logs/* for more information and post them here. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closed due to inactivity.
