### ISSUE TITLE
Hardcoded index.php in urls

### ISSUE THREAD

**Issue by bukowskiadam** [alextselegidis/easyappointments#107]
There is a configuration `index_page`, but in some places it's not used and `index.php` is hardcoded.
Email notifications, backend login redirect and many more.

**Comment by alextselegidis** [comment]
Hello!

Why do you think that the index.php needs to be dynamic?

**Comment by bukowskiadam** [comment]
I don't think that it has to be dynamic. It would be strange to rename index.php to something else, but it's pretty common to use mod_rewrite to get rid of index.php in the url. It looks more clean to have url like `http://example.com/backend/`, *not* `http://example.com/index.php/backend/`. It looks better in emails, etc.

**Comment by alextselegidis** [comment]
Oh I see what you mean. Version 1.0 of Easy!Appointments uses the mod_rewrite and nice URLs for its requests but many users had problems because they couldn't configure their servers properly. This is why I decided to disable it and work with original URLs.

**Comment by bukowskiadam** [comment]
In some places still you use configured `index_page` in some other it's hardcoded. I think that I would replace those hardcoded ones on my fork. At least for email notifications.
Best regards,
Adam
