### ISSUE TITLE
Postgresql as backend db not supported

### ISSUE THREAD

**Issue by indrekmae** [alextselegidis/easyappointments#1072]
Entering welcome page data give me this error:

A PHP Error was encountered
Severity: Warning

Message: pg_query(): Query failed: ERROR: syntax error at or near "ENGINE" LINE 14: ) ENGINE InnoDB ^

Filename: postgre/postgre_driver.php

Line Number: 242

A Database Error Occurred
Error Number:

ERROR: syntax error at or near "ENGINE" LINE 14: ) ENGINE InnoDB ^

CREATE TABLE IF NOT EXISTS "ea_appointments" ( "id" SERIAL NOT NULL, "book_datetime" DATETIME NULL, "start_datetime" DATETIME NULL, "end_datetime" DATETIME NULL, "notes" TEXT NULL, "hash" TEXT NULL, "is_unavailable" SMALLINT DEFAULT '0' NOT NULL, "id_users_provider" BIGINT NULL, "id_users_customer" BIGINT NULL, "id_services" BIGINT NULL, "id_google_calendar" TEXT NULL, CONSTRAINT "pk_ea_appointments" PRIMARY KEY("id") ) ENGINE InnoDB

Filename: migrations/001_specific_calendar_sync.php

Line Number: 88

**Comment by alextselegidis** [comment]
Hello! 

There are indeed some things that are being made as raw MySQL queries and therefore postgre or other DB systems are not supported.

For now you will need to solely work with MySQL. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
