### ISSUE TITLE
Update PHPMailer

### ISSUE THREAD

**Issue by bitlogik** [alextselegidis/easyappointments#1073]
Make sure to update the PHPMailer dependency from 6.2.0 to version 6.4.1, in the lock and in the release package.

More details : 
https://github.com/advisories/GHSA-m298-fh5c-jc66
Fixed by https://github.com/PHPMailer/PHPMailer/commit/26f2848d3bbb57add5f34a467a1e3b2f9ce5cd2a

Not a big deal since the involved function is protected, so not sure a user provided input is used as an entry for this. Just better safe than sorry.

**Comment by alextselegidis** [comment]
Thanks, I'll do that. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Done in develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
