### ISSUE TITLE
Display month with the earliest available day

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1075]
Hi there,

we startet a booking which is only on sundays and excluded all sundays in the current month (may). So the earliest available booking day is in june. The calendar should automatically respect this and start with that month.

Benefit: customers don't see a month with no booking days and also don't have to change the month. secretaries are not bugged with questions like "no dates available, what can i do?". just happened today. ;)

**Comment by alextselegidis** [comment]
Hello! 

I'm marking this as a future enhancement. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by medarob** [comment]
That's a good idea. It would be great to have this feature.

**Comment by alextselegidis** [comment]
Hello! 

Yes, that's in fact an important addition. 

Marking this for 1.5

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Great, thank you!
