### ISSUE TITLE
Site is down?

### ISSUE THREAD

**Issue by nefiger** [alextselegidis/easyappointments#108]
I can't access http://easyappointments.org/ - DNS lookup failed. Is this hosted anywhere else, perhaps?

**Comment by alextselegidis** [comment]
Hi, it is just a maintenance server reboot and update of the hosting company. They have already informed me that it should last for approximately one hour.

**Comment by alextselegidis** [comment]
I am also planning to move the website to the github pages in the following weeks. I am currently redesigning the page.

**Comment by alextselegidis** [comment]
The problem still remains and it's the second time it's happening. Today evening I will move the site to the github pages. I guess that due to DNS updates of the domain the site will be reachable by tomorrow.

Thanks for noticing.

**Comment by nefiger** [comment]
Hey Alex - I appreciate the feedback. Looking forward to seeing it when all is resolved.

thanks :)

**Comment by alextselegidis** [comment]
You can see the website here: 

http://alextselegidis.github.io/easyappointments/

I will now update the nameservers of http://easyappointments.org but this will take sometime until they are active.

**Comment by nefiger** [comment]
thanks so much - i really appreciate it.
