### ISSUE TITLE
Incorrect Details/Missing Details

### ISSUE THREAD

**Issue by car-lene** [alextselegidis/easyappointments#1080]
We encountered that the appointment system did not project the details made by a colleague, luckily she had a screenshot of the approval of the appointment. Kindly check on this please.

**Comment by alextselegidis** [comment]
Hello! 

Can you please provide reproduction steps for this issues? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by car-lene** [comment]
Good Day po,

Please see below appointment calendar that did not reflect said appointment and approval of said appointment that wasn't reflected. Thank you
[cid:5b5bf78c-24c8-4642-8d3a-007ff33d85c5]

[cid:bac33952-bed5-40a1-8e86-8d2b7c5db9a7]
Thank you.


Sincerely,


[cid:7641e4d7-0e9e-4035-8eac-b0ce74b30ff4]

    Car-lene Dela Cruz

    Bria Homes Inc.

    Admin Staff

________________________________

**Comment by alextselegidis** [comment]
Hello  @car-lene 

It seems that you tried to attach more information but they didn't came along with your message. 

Can you please try again? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
