### ISSUE TITLE
Have an option to hide customer data fields during booking

### ISSUE THREAD

**Issue by Tthecreator** [alextselegidis/easyappointments#1081]
For our purposes, we only need a name and an email of the person booking. 
Because we don't need (and thus **don't want**) all the other bits of data it would be nice if we could completely hide the fields (instead of having them required/non required).

I'm making an issue here to keep things administratively neat and to get other peoples opinion. I will be working on this feature request myself though.

I was thinking about just adding another screen in settings titled "Customer fields" with a few checkboxes per field. We'll see if that is also technically the easiest to implement.

**Comment by alextselegidis** [comment]
Thanks! I will review this as soon as possible. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
