### ISSUE TITLE
Not clear how to install/setup

### ISSUE THREAD

**Issue by mazzespazze** [alextselegidis/easyappointments#1084]
In either the github README and the official website it is not really clear how to have an end-to-end procedure to install the software. Perhaps is a mistake of mine and it is clear. 

For example after installing all the dependencies, what exactly should happen after `npm start`? Because I cannot see any further message in the logs.

Regardless, I saw the docker folder (by the way, no mention at all of it in the documentation) and when I run the `docker-compose up` command and I visit the door 8000 I get this message:

![Screenshot from 2021-06-02 01-10-27](https://user-images.githubusercontent.com/25283394/120401400-291cab00-c340-11eb-9a04-6eb388bf3181.png)

Any help is appreciated. I am running it on a droplet on digital ocean with PHP + Apache Web + MySQL (though it shouldn't matter in a docker environment). 

Once again, if all these information was there, I am truly sorry for this redundant message. Otherwise I think the community will benefit from a better documentation. Thanks!

**Comment by alextselegidis** [comment]
Hello! 

It is advised to use the pre-built version from the website as there is no need to built the application. 

There is also a blog post with more details on how to setup everything from git: 

https://easyappointments.org/2021/05/24/setup-easyappointments-from-git/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
