### ISSUE TITLE
Reserved time

### ISSUE THREAD

**Issue by vidalcenter** [alextselegidis/easyappointments#1085]
The place I need to implement only allows the reservation of one person per time, but this is freely allowing the appointment.
How can I proceed?

**Comment by alextselegidis** [comment]
Hello! 

Which services/providers setup are you using? 

Can you please post here your configuration? 

Also which version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
