### ISSUE TITLE
500 HTTP Error

### ISSUE THREAD

**Issue by marvinto23** [alextselegidis/easyappointments#1086]
Hello

After installing as described in your Install Guide i get the error HTTP 500

I can send the logs u want / need.

Greets

Site: http://termin-buchung.eu

**Comment by alextselegidis** [comment]
Hello! 

In this blog post you will find useful information on how to troubleshoot Easy!Appointments: 

https://easyappointments.org/2021/05/31/how-to-troubleshoot-easyappointments/

Please post the debug log messages here. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
