### ISSUE TITLE
Set "Any Provider" as default provider

### ISSUE THREAD

**Issue by januszwajs** [alextselegidis/easyappointments#1088]
Hi, I would like to set the Any Provider option as default service provider instead being the last available option. How can I achieve this? Thanks.

**Comment by alextselegidis** [comment]
Hello! 

Edit the frontend_book.js file and change the following snippet from: 

```
            // Add the "Any Provider" entry.
            if ($('#select-provider option').length >= 1 && GlobalVariables.displayAnyProvider === '1') {
                $('#select-provider').append(new Option('- ' + EALang.any_provider + ' -', 'any-provider'));
            }
```

to 

```
           // Add the "Any Provider" entry.
            if ($('#select-provider option').length >= 1 && GlobalVariables.displayAnyProvider === '1') {
                $('#select-provider').append(new Option('- ' + EALang.any_provider + ' -', 'any-provider', true, true));
            }
```

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
