### ISSUE TITLE
The configuration file does not exist.

### ISSUE THREAD

**Issue by yasenabdelghany22** [alextselegidis/easyappointments#1095]
after deploying my project to server and updated the config.php file the system returned this message:
The configuration file does not exist.

**Comment by alextselegidis** [comment]
Hello! 

Easy!Appointments requires a `config.php` file to be present at the root directory (same folder as the index.php file). 

Is this the case for your installation? 

If not please copy the config-sample.php file and add your data.

Some time users may upload the application into multiple directories as they are not sure which one is served from the server. 

Make sure you know which directory is really public and remove any duplicate instances of Easy!Appointments. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
