### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by rastilscir** [alextselegidis/easyappointments#1099]
Good day sir, 

Upon installation of Easyappointments i have encountered "The operation could not complete due to unexpected issues."

this is from the console
***
Unexpected HTTP Error:  
Object { readyState: 4, getResponseHeader: getResponseHeader(e), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(e, t), overrideMimeType: overrideMimeType(e), statusCode: statusCode(e), abort: abort(e), state: state(), always: always(), catch: catch(e)
, … }
 
Object { url: "http://127.0.0.1/ee/easyappointments/index.php/installation/ajax_install", type: "POST", isLocal: false, global: true, processData: true, async: true, contentType: "application/x-www-form-urlencoded; charset=UTF-8", accepts: {…}, contents: {…}, responseFields: {…}, … }
 SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    jQuery 5
    <anonymous> http://127.0.0.1/ee/easyappointments/assets/js/installation.min.js?924WX:1
    jQuery 8
    <anonymous> http://127.0.0.1/ee/easyappointments/assets/js/installation.min.js?924WX:1
    jQuery 13
        e
        t
        setTimeout handler*l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
***

Thank you very much!

**Comment by alextselegidis** [comment]
Hello! 

Please check your /storage/logs/* directory for debug log files and post their content here. 

It looks like a server-side error that is happening when you trigger this request. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rastilscir** [comment]
hi sir,

these are the contents
***
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-13 07:01:55 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 113
ERROR - 2021-07-13 07:01:55 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 169
ERROR - 2021-07-13 07:45:30 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 113
ERROR - 2021-07-13 07:45:30 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 169
ERROR - 2021-07-13 07:49:42 --> Severity: Error --> Maximum execution time of 30 seconds exceeded C:\xampp\htdocs\ee\easyappointments\vendor\codeigniter\framework\system\database\drivers\mysqli\mysqli_driver.php 307
ERROR - 2021-07-13 07:56:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 113
ERROR - 2021-07-13 07:56:57 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 169
ERROR - 2021-07-13 08:02:24 --> Severity: Error --> Maximum execution time of 30 seconds exceeded C:\xampp\htdocs\ee\easyappointments\vendor\codeigniter\framework\system\database\drivers\mysqli\mysqli_driver.php 307
ERROR - 2021-07-13 08:04:48 --> Severity: error --> Exception: $name setting does not exist in database: company_name C:\xampp\htdocs\ee\easyappointments\application\models\Settings_model.php 43
ERROR - 2021-07-13 08:05:34 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 113
ERROR - 2021-07-13 08:05:34 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 169
ERROR - 2021-07-13 08:19:53 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 113
ERROR - 2021-07-13 08:19:53 --> Severity: Warning --> Invalid argument supplied for foreach() C:\xampp\htdocs\ee\easyappointments\application\views\appointments\book.php 169
ERROR - 2021-07-13 08:19:53 --> Severity: error --> Exception: $name setting does not exist in database: require_captcha C:\xampp\htdocs\ee\easyappointments\application\models\Settings_model.php 43
ERROR - 2021-07-13 08:21:54 --> Severity: Error --> Maximum execution time of 30 seconds exceeded C:\xampp\htdocs\ee\easyappointments\vendor\codeigniter\framework\system\database\drivers\mysqli\mysqli_driver.php 307
***

**Comment by alextselegidis** [comment]
Hello! 

Please reset your database (remove all the tables) and try again from scratch. 

The errors you are getting are because you do not have the required records in your database, so basically a side effect. 

Post back here if you find installation related error mesages.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rastilscir** [comment]
Thank you very much!
