### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by fgeek** [alextselegidis/easyappointments#11]
I have emailed information about security vulnerabilities to project developer's (Alex Tselegidis) email 2015-04-03 without reply. Did you receive the email?

**Comment by alextselegidis** [comment]
Yep got it! :)

**Comment by fgeek** [comment]
One month has gone already. Are you going to fix these vulnerabilities or not? If yes - what is your plan? Do you need help?

**Comment by alextselegidis** [comment]
Hello 

I am currently working in the following version Easy!Appointments. I cannot tell exactly when this is going to be released, but the fixes will be included for sure. I guess I will need the extra month. 

Still thank you very much for your concern :)

**Comment by fgeek** [comment]
Status?

**Comment by alextselegidis** [comment]
Currently working ... :)

The fixes will be posted here on GitHub but the new version will need some extra days for the other tasks. I will inform you on the fixes and then later for the release of the BETA version.
