### ISSUE TITLE
Make delete appointment via API to send emails just like the calendar page does. 

### ISSUE THREAD

**Issue by iliavivanov** [alextselegidis/easyappointments#1101]
We can delete appointment via backoffice, and it invokes POST ***/index.php/backend_api/ajax_delete_appointment.
EA send 'Appointment canceled' email to customer (if emails configured).

But if we do the same via API - DELETE ***/index.php/api/v1/appointments/:id email do not sent.

For instance, if we create an appointment via API - email was send

**Comment by alextselegidis** [comment]
Hello! 

Emails should be sent even when removing appointments via the API: 

https://github.com/alextselegidis/easyappointments/blob/master/application/controllers/api/v1/Appointments.php#L224

Does your user have the notifications setting enabled? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closed due to inactivity. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by iliavivanov** [comment]
All necessary settings enabled, email configuration is OK.

1st problem
https://github.com/alextselegidis/easyappointments/blob/master/application/libraries/Notifications.php#L159
Notifications#notify_appointment_deleted method uses `new Text($this->CI->input->post('cancel_reason'))`
**There is no post object on delete action** and `Type#__construct` failed with `InvalidArgumentException` because of null cancel_reason field of form/x-www-form-url-encoded

2nd problem
Rename `cancel_reason` to `delete_reason` everythere - it is not a cancelation - it is a deletion! That it is named at API.
This problem could be skipped if 3rd solved


3rd problem
Backend_api#ajax_delete_appointment mixes `delete_reason` and `cancel_reason` in one method - only `delete_reason` came from form (that is thay I ask you to rename `cancel_reason` to `delete_reason`)
That is why the program flow fails on https://github.com/alextselegidis/easyappointments/blob/master/application/controllers/Backend_api.php#L427
And not all emails send.

**Comment by iliavivanov** [comment]
All necessary settings enabled, email configuration is OK.

1st problem
https://github.com/alextselegidis/easyappointments/blob/master/application/libraries/Notifications.php#L159
Notifications#notify_appointment_deleted method uses `new Text($this->CI->input->post('cancel_reason'))`
**There is no post object on delete action** and `Type#__construct` failed with `InvalidArgumentException` because of null cancel_reason field of form/x-www-form-url-encoded

2nd problem
Rename `cancel_reason` to `delete_reason` everythere - it is not a cancelation - it is a deletion! That it is named at API.
This problem could be skipped if 3rd solved


3rd problem
Backend_api#ajax_delete_appointment mixes `delete_reason` and `cancel_reason` in one method - only `delete_reason` came from form (that is thay I ask you to rename `cancel_reason` to `delete_reason`)
That is why the program flow fails on https://github.com/alextselegidis/easyappointments/blob/master/application/controllers/Backend_api.php#L427
And not all emails send.

**Comment by iliavivanov** [comment]
About `new Text($this->CI->input->post('cancel_reason'))` rework it like `new Text($this->CI->input->input_stream('cancel_reason'))`

**Comment by alextselegidis** [comment]
Hello @iliavivanov, 

Thanks for getting back with additional information. 

I will have to check this one again before and make sure this does not happen. 

The post object should be there as the cancellation is a POST request, but it could be that someone also calls the URL directly which will lead to a GET request without a cancellation reason and thus cause this problem. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
This is already done on develop.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
