### ISSUE TITLE
Service and categories are not displayed

### ISSUE THREAD

**Issue by DanSman** [alextselegidis/easyappointments#1102]
Hey

I thought it would be good to create a new issue as [this one](https://github.com/alextselegidis/easyappointments/issues/976) is already closed.
But actually I have the same problem like this guy. 

As I mentioned in this issue:
>Just did a fresh install and deleted Jane Doe and the default service (Service). Doesn't matter how many services and provider I add to, it keeps that way like the picture above.

I still can't find a solution for that.
Any ideas?

**Comment by DanSman** [comment]
Lol!

I have found the solution/option. I didn't see that you have to "tick" new services under your provider :D

**Comment by alextselegidis** [comment]
Glad you found it!


<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
