### ISSUE TITLE
Make delete appointment via API to send emails (like at BO) (again)

### ISSUE THREAD

**Issue by iliavivanov** [alextselegidis/easyappointments#1105]
We can delete appointment via backoffice, and it invokes POST ***/index.php/backend_api/ajax_delete_appointment.
EA send 'Appointment canceled' email to customer (if emails configured).

But if we do the same via API - DELETE ***/index.php/api/v1/appointments/:id email do not sent.

For instance, if we create an appointment via API - email was send

All necessary settings enabled, email configuration is OK.

1st problem
https://github.com/alextselegidis/easyappointments/blob/master/application/libraries/Notifications.php#L159
Notifications#notify_appointment_deleted method uses `new Text($this->CI->input->post('cancel_reason'))`
**There is no post object on delete action** and `Type#__construct` failed with `InvalidArgumentException` because of null cancel_reason field of form/x-www-form-url-encoded

2nd problem
Rename `cancel_reason` to `delete_reason` everythere - it is not a cancelation - it is a deletion! That it is named at API.
This problem could be skipped if 3rd solved

![1](https://user-images.githubusercontent.com/4418313/128510594-0d23d8b0-3b7a-4296-87e7-6cfcdc0a0f6c.png)

![2](https://user-images.githubusercontent.com/4418313/128510598-847b6d1d-b3b7-4273-861e-3f5d72225605.png)

3rd problem
Backend_api#ajax_delete_appointment mixes `delete_reason` and `cancel_reason` in one method - only `delete_reason` came from form (that is thay I ask you to rename `cancel_reason` to `delete_reason`)
That is why the program flow fails on https://github.com/alextselegidis/easyappointments/blob/master/application/controllers/Backend_api.php#L427
And not all emails send.

About `new Text($this->CI->input->post('cancel_reason'))` rework it like `new Text($this->CI->input->input_stream('cancel_reason'))`

**Comment by iliavivanov** [comment]
cancel_reason used by book.php which invokes controllers/Appointments.php#cancel(hash) but actually it deletes an appointment an invoke `$this->notifications->notify_appointment_deleted()` and `cancel_reason` field is used with `post('cancel_reason')`.

But when I invoke API method it uses controllers/api/v1/Appointments.php#delete(id) and invoke `$this->notifications->notify_appointment_deleted()` and `cancel_reason` field is used with post() - BUT THERE IS NO POST BODY IN DELETE METHOD mapping -> you should use `input_stream('cancel_reason')`

**Comment by iliavivanov** [comment]
Also `Backend_api.php#ajax_delete_appointment()` MIXES `delete_reason` and `cancel_reason` in one method but only `delete_reason` passed from FE and operation failed on https://github.com/alextselegidis/easyappointments/blob/master/application/controllers/Backend_api.php#L427

**Comment by iliavivanov** [comment]
Here is the patch. I am not PHP person, so...


[Make_delete_appointment_via_API_to_send_emails_(like_at_BO).zip](https://github.com/alextselegidis/easyappointments/files/6946045/Make_delete_appointment_via_API_to_send_emails_.like_at_BO.zip)

**Comment by alextselegidis** [comment]
Thanks @iliavivanov, this will be fixed for 1.5

**Comment by alextselegidis** [comment]
This is already done on develop. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
