### ISSUE TITLE
Skip the first booking step if both provider and service are preselected. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#1117]
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by schubertstudio** [comment]
Hi Alex! any updates regarding this Topic on skiping first page with preselected parameters?
can I support you on this?
