### ISSUE TITLE
Add a SECURITY.md file to the repository

### ISSUE THREAD

**Issue by zidingz** [alextselegidis/easyappointments#1122]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting! I will be adding the file asap. 

Till then you can reach out to info@easyappointments.org with information about the problem.
