### ISSUE TITLE
Secretaries cannot change working plan of provider or service details

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1124]
As admin I created a provider (foto studio) and service (fotoshooting for employees) and connected them. Futhermore a secretary has rights for the new provider. So far so good. For the first time I logged in as secretary to see if everything is fine. 

Problem: While everything seems to be set up correctly, the secretary cannot

1. change working plan of provider -> has to be done often, f.e. for creating new dates -> important
2. change service details -> needs to be changed from time to time, f.e. for changing location or intervall -> nice to have

Workaround is that admins have to do the work or secretaries get admin rights. Both is not wanted.

So my question is... am I missing something or can it be "activated" or patched somehow? If not, are there plans to give secretaries more possibilities for those things?

Note: Even providers cannot change their own working plan, which is strange.

Related to: #854

**Comment by alextselegidis** [comment]
Hello! 

> change working plan of provider -> has to be done often, f.e. for creating new dates -> important

You can manually change the "users" column for the secretary role (see ea_roles table) and set its value to `15`. 

This will unlock the users page to the secretary user role. 

> change service details -> needs to be changed from time to time, f.e. for changing location or intervall -> nice to have

Same here, change the "services" column value to `15` and the services page will also appear for secretaries. 

Hope that helps!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thank you, didn't know of that and I think it's not in the documentation.

I tried it out but unfortunately this doesn't help much. Yes, with that change you can unlock users and services for secretaries, but it's like admin rights -> all secretaries then have rights to change all users, providers and services, even those they have no rights for. They can even assign other services to themself and add new admins. ;) So appropriate restrictions like in the calendar view are missing.

Hoping for unclosing this and a solution somewhen. Keep up the good work!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi Alex,

any chance for re-open this? See my last comment why setting 15 in ea_roles is a bad solution. We still live with the workaround that admins have to do the work.

**Comment by alextselegidis** [comment]
Hello! 

It looks like I'll rework the permissions system in the near future to allow for more flexibility on the available app resources and the existing user roles. 

I'll keep this ticket closed for now as this is a specific use case but will address this once the new permissions system becomes available. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thank you!
