### ISSUE TITLE
Define only 2 Slots & allow multiple attendees to register

### ISSUE THREAD

**Issue by phenomeus** [alextselegidis/easyappointments#1128]
hi

thank you for the great tool. I somehow don't understand how to define the "multiple Attendees" feature.

i want to define 2 times lots on 2 different days for a zoom meeting 90mins, max 50 people. Then I want to allow interested attendees to register one of this slots. I also want to deactivate every other times etc, but only the 2 given slots. 

is this even possible? thank you in advance for the help

**Comment by phenomeus** [comment]
ok i figured it out, I edited the providers working plan by removing every working time and "adding working plan exception" two times. 

there I opened a short window of working hour. after that I modified my Service to be "fixed" and have "50" attendees.

**Comment by alextselegidis** [comment]
Hello! 

I'm glad you figured this out. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
