### ISSUE TITLE
Resend updated Mails / .ics files when Service Informations are updated 

### ISSUE THREAD

**Issue by phenomeus** [alextselegidis/easyappointments#1129]
it would be awesome to manually trigger or automatically resend to every registered Attendant an updated Mail with .ics file as soon as the admin changes something inside the service details.

**example:** 
max. 50 attandees should be able to register for an upcoming webinar. NO zoom link and password is posted inside the service details (yet).  

one evening before the event, the admin edits the service details and adds zoom link and password instead of the description. 
all registered 50 attandees are getting an update email with the new description inside and can login on the next day.

**Comment by alextselegidis** [comment]
Hello! 

At the time being, even though the service changes their appointments will not directly change. 

This is why the application does not send any additional email for that. 

If you change the service of an appointment to another one, then a notification will be sent of course. 

I will skip this feature as only appointment related changes will trigger a notification. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by phenomeus** [comment]
thanks for replying. 

so if I have 50 appointments with "service 1" (without Link), I then can duplicate "service 1" to "service 2", change the description and add a link. if I then go through every of the 50 appointments and change them from service 1 to service 2, every of the 50 appointments will get an automatic notification resend?
