### ISSUE TITLE
Multi appointments in one slot

### ISSUE THREAD

**Issue by ghena** [alextselegidis/easyappointments#1130]
Hi guys,
is possibile to setup multiple appointments to one slot.
For example:  setup 20 max appointments in one slot.

Please let me know.
regards.

**Comment by alextselegidis** [comment]
Hello! 

Yes this is possible by configured the `Attendants Number` field of the service. 

This property allows for multiple appointments at the same time slot. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
