### ISSUE TITLE
Add support for custom fields on customers  

### ISSUE THREAD

**Issue by KaijuDeluxe** [alextselegidis/easyappointments#1133]
I would like to add a field "customer number" for example which the user must fill in. This field should also be available in the REST API

**Comment by alextselegidis** [comment]
Hello! 

Is this going to be an internal field? 

I think in general it would be helpful to have an internal reference ID field for all the resources of the application. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by KaijuDeluxe** [comment]
Hey, no the user should be able to enter in it while registering. Great would be if we can make it mandatory. For example a user can olny book if he added a customer number

**Comment by JanC** [comment]
hey,
I was looking for a similar feature where the admin would  be able to add additional custome customer field such as `Social Security Number` and set whether this field is required or not.

**Comment by alextselegidis** [comment]
This is now part of `develop`

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
