### ISSUE TITLE
Add date, from and till query parameters to the filter the appointments index results by date.

### ISSUE THREAD

**Issue by KaijuDeluxe** [alextselegidis/easyappointments#1134]
Would be great if we could do

.../appointments/start=2021-09-26 to get all scheduled appointments for today

**Comment by alextselegidis** [comment]
Hello! 

This will be added for v1.5. 

Star and follow the project and stay up to date with the latest development updates!

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by KaijuDeluxe** [comment]
Top :) Whats your release cycle?

**Comment by alextselegidis** [comment]
Version 1.5 is scheduled for release within October

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by MopheusDG** [comment]
Hi @alextselegidis I think date range could be even more usefull...

.../appointments?startFrom=2021-09-26&startTo=2021-09-30

Or something like that probably. Just my 2 cents.

Thanks.

**Comment by alextselegidis** [comment]
The following parameters are available: 

* date -> filter for a single date 
* from -> start from date and in the future 
* end -> end till date and to the past
