### ISSUE TITLE
Add Encryption

### ISSUE THREAD

**Issue by KaijuDeluxe** [alextselegidis/easyappointments#1136]
Why are the email adresses and names not encrpted in the database, would be necassary to be gdpr safe

**Comment by alextselegidis** [comment]
Hello! 

At the moment Easy!Appointments is a self hosted solution which means that each instance and data is completely owned by the company/professional that maintains the installation. 

For that, Easy!Appointments is already GDPR ready and encryption is something that could be applied at the server level for additional protection if needed.

In the future, where more services will become available for the ecosystem, encryption will be properly added to the app. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
