### ISSUE TITLE
Does this support Office 365 Calendars?

### ISSUE THREAD

**Issue by jagadeesh-s2104** [alextselegidis/easyappointments#1139]
Hello Guys! 

Does EasyAppointments support Office 365 Calendars? 
Say if my mailbox is in Office 365, does it work?

**Comment by alextselegidis** [comment]
Hello! 

There is no Office 365 support right now, but it will come some time in the future. 

For now you can use the Google Calendar synchronization feature and pretty soon CalDAV to exchange events between different applications. 

<small>
<table style">
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
