### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by gustawdaniel-acaisoft** [alextselegidis/easyappointments#1156]
I clonned repo and typed `docker-compose up` in `docker` directory. I have the following errors

![2021-10-29_22-24](https://user-images.githubusercontent.com/89576647/139497647-4faa775b-5cd0-42c5-9e53-d3178b51468a.png)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting, let me check that and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

It looks like your root `config.php` DB credentials are wrong. 

Please update your local `config.php` as described in the docker documentation: 

https://easyappointments.org/docs.html#1.4.2/docker.md

```
// ------------------------------------------------------------------------
    // DATABASE SETTINGS
    // ------------------------------------------------------------------------

    const DB_HOST       = 'easyappointments-database:3306';
    const DB_NAME       = 'easyappointments';
    const DB_USERNAME   = 'root';
    const DB_PASSWORD   = 'root';
```

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
