### ISSUE TITLE
Separator symbol for DMY date format

### ISSUE THREAD

**Issue by EdRoxter** [alextselegidis/easyappointments#1159]
It would be great to be able to define the date format not only in terms of its order, but also the separator used. AFAIC, in most countries with DMY format, the slash isn't common and rather associated with the US M/D/Y format, which can be confusing: When I, a Western European, see a date like 07/01/2021, I automatically assume it's July 1st, 2021.

So the most flexible approach would be to add an option to define the separator symbol used wherever a date is shown. For that setting, full stop (.) or slash (/) would come to mind

An easier (yet likely viable) way would be to simply change the slashes into full stops for outputting "DMY" date format. I am quite sure that the format "31.12.2021" is common in the majority of countries where that date format is used.

Any thoughts?

I'd gladly contribute either change if this idea is generally approved of.

**Comment by alextselegidis** [comment]
Hello! 

In the future there will be more precise locale setting that will replace the date and time format settings that we do have now. 

Changing the separator would be temporary fix but will not work for each country unfortunately. 

For this I will close this ticket but in the meantime, you can go through the PHP and JS files and replace "/" with ".". 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
