### ISSUE TITLE
Book advance timeout not taken into account for proposed appointments

### ISSUE THREAD

**Issue by ericferon** [alextselegidis/easyappointments#116]
According to me, when someone is booking an appointment, he is always in "manage mode", that is the "book advance timeout" is not taken into account.
This is due to a bug in the file application/controllers/appointments.php, around line 314 : you have to change the last parameter in the call to "calculate_available_hours" : 
(bool)$_POST['manage_mode']) is always true.
You have to replace it by :
filter_var($_POST['manage_mode'], FILTER_VALIDATE_BOOLEAN)
credit : http://stackoverflow.com/questions/4775294/parsing-a-string-into-a-boolean-value-in-php
Best regards,

**Comment by alextselegidis** [comment]
Oh thanks for reporting that, I will check it out and get back to you as soon as possible.

**Comment by alextselegidis** [comment]
You are definitely right. I have applied the fix and changed the "calculate_available_hours" method so that it always takes into concern the book_advance_timeout setting.
