### ISSUE TITLE
Feature Request: add a button/link for heading to homepage of site

### ISSUE THREAD

**Issue by blastg** [alextselegidis/easyappointments#1160]
It would be nice to add a button/link (maybe on bottom side) for coming back to "master site" homepage expecially where  easyappointments is launched from a link and not shown in iframe.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for sharing your suggestion!  

You can currently set the company link under the settings page and that will appear in the booking page footer. 

That should suffice for most cases without disrupting the look and feel of the booking page too much. 

For this, I will be closing the ticket but if anyone wants to add custom HTML to the booking page you will need to modify the following file: 

```
/application/views/appointments/book.php
```

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
