### ISSUE TITLE
Feature Request: add company logo

### ISSUE THREAD

**Issue by blastg** [alextselegidis/easyappointments#1164]
Just for improve visibility a company logo field should be useful next to "company-name" field

**Comment by alextselegidis** [comment]
Hi @blastg!

This is a duplicate: 

https://github.com/alextselegidis/easyappointments/issues/789

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
