### ISSUE TITLE
Easyappointments with Wix

### ISSUE THREAD

**Issue by wismeg6** [alextselegidis/easyappointments#1169]
I’m confused on how to install this on Wix or even if you can install this on Wix

**Comment by alextselegidis** [comment]
Hello! 

There is currently no official support for Wix site but what you can do is to install Easy!Appointments on another server and include the booking page via an iframe. 

https://support.wix.com/en/article/wix-editor-embedding-a-site-or-a-widget

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
