### ISSUE TITLE
CodeIgniter Version out of support

### ISSUE THREAD

**Issue by cadague** [alextselegidis/easyappointments#117]
I noticed that the version of CodeIgniter is now EOL. I suggest upgrading to 3.0.x to keep things secure.

**Comment by alextselegidis** [comment]
Hi, yes I know. I didn't update all the vendor fingers of the app for v1.1 but I'm planning to do so in v1.2.

I have already created a ticket for that.
https://github.com/alextselegidis/easyappointments/issues/63

Thanks for posting anyway :)
