### ISSUE TITLE
"Unexpected Issues" error on Safari

### ISSUE THREAD

**Issue by ronliskey** [alextselegidis/easyappointments#1170]
Application works in Chrome desktop, but in Safari desktop and mobile, and Chrome mobile, it produces the "Unexpected Issues" popup error. No error message is added to the log files.

After closing the error popup, the application seems to function, but  dates are not removed from the calendar, and it is not possible to choose an appointment.

Maybe this hints to a solution?
https://stackoverflow.com/questions/18778814/jquery-ajax-call-often-not-working-on-safari-6

**Comment by alextselegidis** [comment]
Hello! 

Are you using this under an https domain?

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ronliskey** [comment]
Yes, it’s an https domain.

**Comment by alextselegidis** [comment]
Great, and is your BASE_URL config value also configured to use HTTPS?

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ronliskey** [comment]
That was the problem. Thank you. :-)
