### ISSUE TITLE
disable/hide service if no free slot is available / show number of available slots in service title

### ISSUE THREAD

**Issue by medarob** [alextselegidis/easyappointments#1172]
Hi,

A user wanted to book an appointment but there was no free slot available. To make it clear for the user it would be good to not give the user the option to select this service.
Is there a way to disable or hide the service in the dropdown menu when there are no free slots available anymore?

Maybe add something like "[no slots available]" or "[full]" to the service or make it customizable so that the user can chose between "disabling" or "hiding" the service if there are no free slots available anymore.

Or would it be a good idea to show the number of free slots in the service title so that people will know how many slots are still available? And if there are no slots available anymore, disable or hide them.

Service 1 [5 free slots available]
Service 2 [no slots available] - disabled

If people change their booking so that free slots will be available at a later time the service will be activated again like

Service 1 [5 free slots available]
Service 2 [1 slots available]

![grafik](https://user-images.githubusercontent.com/33951787/143439610-8015faec-002b-4d7e-96b0-98c95e8f3423.png)

![grafik](https://user-images.githubusercontent.com/33951787/143439780-cce6da70-72b4-4e36-b68c-fdacad484fdc.png)

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Good idea. What additionally could work is a message in step 2 that there are no slots available and hide the calendar. Why? As users don't know if or when there are slot, they will try to skip several months forward just to realise that there are no slots available.

**Comment by alextselegidis** [comment]
Hello! 

That's a good idea but there's a design conflict which blocks us from proceeding with its implementation. Although we can calculate availability and available slots for any service that has more than one attendant, we can only do that once we know the preferred appointment date and not earlier. 

That means that we could first display the available slots at the date-time selection step, right next to each displayed slot. There is another ticket that aims to automatically jump into the next available date directly or return an error message stating that there is no available date for the selected appointment and the users may try a different service/provider or other combination. 

For this I will be closing this ticket for now and leave the current functionality as is at the time being. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
