### ISSUE TITLE
Show "not available" entries in provider working plan

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1173]
Hi,

in the tab user -> username x -> working plan there are 3 sections:

- working plan
- breaks
- working plan exceptions

What's missing here are the "not available" entries that you can create in the calendar.

I would love to have it there as 4. section, too. It's easier to edit/show it there and also gives a better overview, because you would not have to navigate through providers and weeks/months in the calendar view.

Cheers

**Comment by alextselegidis** [comment]
Hello! 

Yes for consistency's sake, that would be a good thing to do but at the same time unavailabilities are actual appointment records unlike working hours, breaks, and exceptions. 

I will skip this for now as I aim to create a more flexible availability setup for the next major version (one that allows you to define periods of available dates and intervals). 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
