### ISSUE TITLE
How to configure email notifications from gmail address?

### ISSUE THREAD

**Issue by openSourcerer9000** [alextselegidis/easyappointments#1174]
Is this described in the docs? I've never set up programmatic emails at all before, I'm not seeing anything about email notifications.

**Comment by alextselegidis** [comment]
Hello! 

Yes, please check the framework documentation on developers.easyappointments.org

https://developers.easyappointments.org/framework/libraries/email.html?highlight=email#email-preferences

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
