### ISSUE TITLE
Timezone selection does not work

### ISSUE THREAD

**Issue by DeveloperWil** [alextselegidis/easyappointments#1176]
When selecting the timezone picker I would expect the time to change to that timezone.  It does not.

There is something fundamentally wrong with the code behind the timezone selector.

On https://demo.easyappointments.org/  I select the last time slot on my detected timezone "Sydney (+10:00)" which is  11:45pm.
If I then change the timezone to "NSW (+10:00)" the time that is selected comes back as 8:30pm.  

This is the same timezone so the time should not change.  You can flip around the same +10:00 timezones and the time slot randomly changes and is incorrect,

In fact, if you change the timezone to anything, regardless of the wrong time being calculated, the very first time slot is always selected.
https://www.loom.com/share/8be7f2492dfe428280d55386e35240f6

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reaching out and posting this ticket!

It good be that the internal time zone matching is wrong for this part of the world. 

Let me check that and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
So I just tried on demo.easyappointments.org and get the same time. 
![Animation2](https://user-images.githubusercontent.com/4527441/146002804-af75f894-95e4-4afd-91c8-938a81d31642.gif)

Should I configure this in a certain way to reproduce the problematic behavior? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by DeveloperWil** [comment]
Thanks for testing Alex.

You will need some test data with multiple time slots.

Choose a time slot that isn't the very first slot.

Change the time zone.

You will see that after you change the time zone, the very first time slot is always selected and the time is not correct.

Regards,
Wil.

**Comment by alextselegidis** [comment]
I'll try that thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Later reply on this post but this issue does not see to happen with the latest 1.5 package. 

I'll be closing this but feel free to post with more information if available. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
