### ISSUE TITLE
Google Calendar and notification mail problem

### ISSUE THREAD

**Issue by ericferon** [alextselegidis/easyappointments#118]
The same problem with testing the value of 'manage_mode' as in issue #116 generates incorrect Google Calendar event creation and email notification.
In file application/controllers/appointments.php, in function ajax_register_appointment, a line should be added after the first statement "$post_data = $_POST['post_data'];" :
$post_data['manage_mode'] = filter_var($post_data['manage_mode'], FILTER_VALIDATE_BOOLEAN);
This will make working the 2 tests around line 400 and 428.
Similarly, around line 425, 
$send_provider = $this->providers_model->get_setting('notifications', $provider['id']);
should be replaced by :
$send_provider = filter_var($this->providers_model
                        ->get_setting('notifications', $provider['id']), FILTER_VALIDATE_BOOLEAN);
to make sure that the test around line 465 "if ($send_provider == TRUE)" is working.
Similarly, around line 455, 
$send_customer = $this->settings_model->get_setting('customer_notifications');
should be replaced by :
$send_customer = filter_var($this->settings_model
                                           ->get_setting('customer_notifications'), FILTER_VALIDATE_BOOLEAN);
to make sure that the test around line 460 "if ((bool)$send_customer === TRUE)" is working.
Best regards,
Eric

**Comment by alextselegidis** [comment]
Hmmm I guess I have to do some refactoring....

**Comment by alextselegidis** [comment]
I sanitized all the boolean values with the filter_var just to make sure it will work in any case. This code will be refactored in a future version because there are some parts that I really don't like. But the fixes are good enough for a revision release (v1.1.1). 

Please inform me if you find any other issues. Thank you very much :)
