### ISSUE TITLE
Remove or hide Timezone dropdown

### ISSUE THREAD

**Issue by mdmiko** [alextselegidis/easyappointments#1180]
I'd like to remove timezone dropdown from appointment date and hour selection page
is possible?

**Comment by alextselegidis** [comment]
Hello!

You can add add the "hidden" attribute to the select-timezone form group as shown below. 

```
<div class="form-group" hidden>
  <label for="select-timezone"><?= lang('timezone') ?></label>
  <?= render_timezone_dropdown('id="select-timezone" class="form-control" value="UTC"'); ?>
</div>
```

in the file application/views/appointments/book.php

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by VIPWebdesign** [comment]
Thanks for the answer but in 1.5.x there is (by me) no application/views/appointments/book.php which is descrivbe above.
In which file is it now?

Regards

Eric

**Comment by VIPWebdesign** [comment]
Thanks for the answer i found the new location
