### ISSUE TITLE
Microsoft Office 365 Calendar Integation

### ISSUE THREAD

**Issue by jahvari** [alextselegidis/easyappointments#1183]
Do you have any plans to integrate office 365 calendar sync?

**Comment by alextselegidis** [comment]
Hi @jahvari! 

Yes, but it will be added to the premium services that will become available later this year. 

The upcoming CalDAV integration (v1.5) may also help you add your provider calendars to external applications. 

Start and follow the project for more exciting updates!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
