### ISSUE TITLE
css syntax for root element

### ISSUE THREAD

**Issue by supersmart-at** [alextselegidis/easyappointments#1184]
Hi Alex, I figured out a syntax issue within (assets/css/layouts/booking_layout.scss) in my case it was the frontend.css where the <root> element ist used without prefixed ":" my css variables were not initialized correctly then. 

=> i used the `:root {...}` and now its all fine.

documentation sample:  https://www.w3schools.com/css/css3_variables.asp

**Comment by alextselegidis** [comment]
Hello @supersmart-at! 

Thanks ❤️   I'll check this out!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello @supersmart-at! 

I checked this now and it looks like there's a misunderstanding or something is not clear enough on this and it makes sense as this is a recent and non-yet-released change we're dealing with 😃 

Basically the files you are referring to are not using the native CSS features (like `var` or similar), but instead [use the Sass syntax](https://sass-lang.com/) which allows for variables, mixins, nesting and tons of other features. 

For that you will need to use the gulp tasks to compile the`*.scss` files to `.css`, which can then be parsed by the browser without problems.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
