### ISSUE TITLE
Errors aren't shown on install form?

### ISSUE THREAD

**Issue by curtisvo** [alextselegidis/easyappointments#1187]
I got the app set up in apache 2 on windows with maria db, and was confused why the button on the initial install form (where the user enters the admin and company information) wasn't doing anything. 

On debugging the javascript I see that the validation method is failing, but the error is not being displayed. For example in the screenshot the password is too short and the field is being highlighted but the message is not shown.

![InkedScreenshot 2022-01-24 at 09-16-09 Installation Easy Appointments_LI](https://user-images.githubusercontent.com/19171122/150803969-844e0d87-58f8-4840-b710-1c0af212989a.jpg)

Hope I'm not the only one seeing that problem. I'm excited to see if I can adapt this project to work for booking shifts at our cooperative!

**Comment by alextselegidis** [comment]
Hello!

Thanks for mentioning this, we should display errors in the page. 

Let me fix this for 1.5

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop
