### ISSUE TITLE
1.5.0-dev.1

### ISSUE THREAD

**Issue by Khaled-Proof** [alextselegidis/easyappointments#1190]
Hi alextselegidis, thanks for the great work.

 I tried to install the 1.5.0-dev.1 version but it appears that the installation script ist not working.  In the installation.php we have 
"php component('config_script')"
"php component('language_script') "

but these php's do not exist in the components folder. I replaced each of them with 
"php component('js_lang_script.php') "
"php component('js_vars_script.php') "

but still the installation script not working.

**Comment by mokkin** [comment]
That's true. I think he is referring to this:

![grafik](https://user-images.githubusercontent.com/2938748/151077415-89d42495-f689-47c0-a28c-9219397b5897.png)

**Comment by alextselegidis** [comment]
Thanks! That's indeed an issue. For now please use the `php index.php console install` command if you have access to the terminal. A new dev package will become available soon. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by mokkin** [comment]
I installed it successfully with your command but I cannot login:

![grafik](https://user-images.githubusercontent.com/2938748/152042572-b964f8d7-f957-47d9-8b8a-2a559fd818e4.png)

**Comment by Khaled-Proof** [comment]
i installed successfully and it is working. in my case for some reason I had to copy all needed modules from node_modules and add it to assets/vendor manually and also change sass to css and change some css layout code.

**Comment by vithusel** [comment]
I just wanted to quickly mention that i am also having the same issue as @Khaled-Proof  
Clicking Login gives the below error
![image](https://user-images.githubusercontent.com/31311292/152666198-39c9a507-a8da-4214-8682-2f98d78a7c0a.png)
Trying to reset the password also gives a similar error 
![image](https://user-images.githubusercontent.com/31311292/152666217-c2b90930-dc5b-408f-aecd-d706c53c5b3e.png)
