### ISSUE TITLE
Google Calendar Sync

### ISSUE THREAD

**Issue by manoeuvrelawliet** [alextselegidis/easyappointments#1193]
I've discovered google-sync url in order to sync to Google Calendar :
base_url/index.php/google/sync/id_users_provider

It was successcfully synced, but only about 3-4 month of data was succesfully synced.
Please help.

**Comment by alextselegidis** [comment]
Hello! 

Already answered here: 

https://groups.google.com/g/easy-appointments/c/cJ8Sswfqkco

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
