### ISSUE TITLE
Appointment with image 

### ISSUE THREAD

**Issue by Khaled-Proof** [alextselegidis/easyappointments#1194]
Hi , 
I would like to ask if there is any possibility for the clients to upload a file type when they book an appointment.

**Comment by alextselegidis** [comment]
Hello! 

Modify `/application/views/book.php` and add a new input file field. 

Then in the `/assets/js/frontend_book_api.js` you will be able to first upload the file and then proceed with the `ajax_register_appointment` request. 

Later on in the backend you can read the stored image file again. 

The developers site may also help you with this: 

https://developers.easyappointments.org/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
