### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ugintl** [alextselegidis/easyappointments#1197]
I downloaded 1.5 dev from the website. When I launch the app, I see 2 slashes after domain like this http://mysite.com//index.php/installation thus I get page not found error. When I remove the slash, I see installation page like this. Please note that similar setting worked for 1.4.2.

![easy](https://user-images.githubusercontent.com/12570802/152718979-e2c4915b-dcd0-4b63-82ad-b25aeaaa1575.jpeg)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for sharing this, installation is indeed broken with the 1.5.0-dev.1 package. 

A new package will be rolled out today fixing this issue. 

Stay tuned for future updates!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by tapmeppe** [comment]
Hello hello there.
The problem is still present both:
- on the currently latest version (v1.5.2) and 
- on the version currently generated when running the build command.

**Comment by alextselegidis** [comment]
Did you download the prebuilt file? 

https://github.com/alextselegidis/easyappointments/releases/download/1.5.2/easyappointments-1.5.2.zip

--

<img src="https://easyappointments.org/logo.png" width="40" height="40">

Alex Tselegidis, Easy!Appointments Creator
<a href="https://easyappointments.org/premium">
    <strong>Go Premium:</strong> Custom Dev, Hosting, Support, Rebrand & more →
</a>
