### ISSUE TITLE
Multi business

### ISSUE THREAD

**Issue by ugintl** [alextselegidis/easyappointments#1198]
Is it possible to make it multi business?

I see that people cannot register. They can only login. Why is that?

**Comment by ugintl** [comment]
Actually, the problem is that for example if there are 1000 providers then the client will have problem finding the desired provider.

**Comment by alextselegidis** [comment]
Hello! 

Easy!Appointments is implemented from the scope of a single business. 

If there are concern conflicts for your use case, I would advise to create multiple installations to manage them more efficiently. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
