### ISSUE TITLE
Delete old appointments

### ISSUE THREAD

**Issue by ICS35** [alextselegidis/easyappointments#1202]
Hello,

I have a lots of old appointments in my database so the available date picker is slow to display.

Is there a safe method to delete old appointment in the database ?

Can i execute this delete request without breaking anything :
`DELETE FROM ea_appointments WHERE end_datetime < '2021-01-01'`

Thank you.

**Comment by alextselegidis** [comment]
Hello! 

Yes the following query looks good: 

DELETE FROM ea_appointments WHERE end_datetime < '2021-01-01'

But before you do that, make sure you take a back up of your database. 

You might need this data in the future 😉 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
