### ISSUE TITLE
E-mail validation

### ISSUE THREAD

**Issue by martinhalfer** [alextselegidis/easyappointments#121]
The email validation function in general_functions.js allows non-ASCII characters (danish æ-ø-å characters are a problem for my installation). As an example, æøå@domain.com, which will trigger an error message later during the booking process.

Since i couldn't figure out how to edit the regular expression in the validateEmail function, i added a separate function to take care of those characters ... The problem is still there for other languages, though.

`validateEmailb: function (email) {
        var ru = /[æøå]/;
        return ru.test(email);
    },`

**Comment by alextselegidis** [comment]
I changed the email validation regex to RFC822 which will block emails like your. This will be released with v1.2 (around April 2016). 

Thank you very much for posting this :+1:
