### ISSUE TITLE
Possibility to book multi-day Appointments

### ISSUE THREAD

**Issue by TheBienek** [alextselegidis/easyappointments#1223]
I wanted to know, if it is possible to make an appointment for two days. Let's say I want the User to book an appointment regarding a training appointment which will take place on Monday from 12:00 to 16:00 and also thuesday 08:00 to 13:00.
Is this at all possible?

**Comment by alextselegidis** [comment]
Hello!

Right now it is not possible to create such appointments. 

The reason behind this is also the way availability is being configured, the working plans etc.

Changing that requires code adjustments that cannot be easily described within a post.

For that you may contact [info@easyappointments.org](mailto:info@easyappointments.org) and order your customization package.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
