### ISSUE TITLE
2 serious security issues in user management

### ISSUE THREAD

**Issue by Mips2648** [alextselegidis/easyappointments#1225]
Anyone having a working login / password will be able to take over any others user account in the system: 
when saving "actual user setting" / "current account" the user_id of the current user is pass with the request, which is not an issue as such (but that's useless), and that ID is used to update the user record in DB! 
Knowing that by default the userID of the first user, which is an admin user, is "1", there is some chance to be able to take over the default admin user in only one try; if not we just have to try all IDs (e.a. from 1 to 100) to take control of the first hundred users, there is a lot of chance to get at least one admin in that list ;-)

It is very easy to fix that breach: instead of taking the user_id from the request, the user_id from the session must be used so a logged in user can only update is own record.

That's not all: the interface does not propose to change the role of our users but if we add an additional value in the array with key 'id_roles' we can change the role of any users, including ourself. 
Again, knowing that by default the roleId of the admin role is "1", it is very easy to upgrade our own role to be an admin.

The fix is also very easy to implement: the array passed to the model to save user must be cleaned, allowed keys must be whitelisted and only them should be passed; so in this case "id_roles" would be at least unset from the array or preferably an array will be rebuild with only explicit whitelisted keys

Generally speaking, data passed to a model should be whitelisted & cleaned: it is not safe to simply pass all data received in the request to the model, the controller need to validated that keys are allowed for the context and value are corrects.

**Comment by alextselegidis** [comment]
Hello @Mips2648, 

Thanks for sharing all this information. 

I'll do run some tests and verify any pending issues so that they are fixed for the upcoming 1.5. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@Mips2648 Thanks for posting this, I already applied white listing to the account update and will do the same in all other related requests. 

This will be released with 1.5, so stay star/watch the project and stay tuned with future updates!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
