### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by dj0c0ol** [alextselegidis/easyappointments#1227]
Hi Alex thanks for your hard work this was implemented in a hospital and i can't wait for the 1.5.0 with the new calendar overview.

However can you implement a feature to search for appointments and when you find that certain appointment to have a dedicated button within the edit appointment to delete it. Thank you

**Comment by alextselegidis** [comment]
Hello! 

Glad to know Easy!Appointments serves you well. 

Sure, the upcoming 1.5 will have the features you have requested. 

Star and follow the project and stay tuned with future updates. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
