### ISSUE TITLE
date picker excluding (deactivating in ui) some dates

### ISSUE THREAD

**Issue by tanielkirikal** [alextselegidis/easyappointments#1228]
In version 1.5.0-dev when I uncheck all days in providers working plan and add there a few exceptions then the calendar (date selector) on booking page starts deactivating some dates.

![Clipboard01](https://user-images.githubusercontent.com/36533962/160837339-9e8469ca-08fa-41c4-893c-e7a7d6112f83.jpg)

and result is

![Clipboard02](https://user-images.githubusercontent.com/36533962/160837367-90b40848-a051-4862-8b3f-6ac10bdf7713.jpg)

In 2022/05 are deactivated days 1-9, in 2022/06 are deactivated days 3-10, in 2022/07 days 5-10 etc.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting this, I will take a closer look at the latest 1.5-dev package and let you know if I can reproduce this.  

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

This PR fixes this problem: 

https://github.com/alextselegidis/easyappointments/pull/1267

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
