### ISSUE TITLE
[v1.5.0-dev.2] Email still required to modify appointments

### ISSUE THREAD

**Issue by DumahBrazorf** [alextselegidis/easyappointments#1231]
In Settings/Booking we can set the email not required to book an appointment.
This setting not work in appointment editing. We cannot modify the appointment without inserting an email.
This setting works in the customer profile editing page.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this! I will make sure it's resolved before the stable release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by JanC** [comment]
@DumahBrazorf  @alextselegidis  if you are referencing the "Invalid email address." message when saving or creating an appointment, I fixed it in the linked PR
