### ISSUE TITLE
Make customer email non unique

### ISSUE THREAD

**Issue by JanC** [alextselegidis/easyappointments#1235]
Hi,
I have the use case where the appointments are entered by a secretary after a phone call with the customer. Not all customers have an email address. I found and posted in this ticket with a suggestion to make the email not mandatory. That ticket was eventually closed https://github.com/alextselegidis/easyappointments/issues/376#issuecomment-938709252

I thought a simple workaround could be to use the same dummy email address for all customers who don't provide one (such as `noemail@example.com`. There is however an explicit check for this preventing it

https://github.com/alextselegidis/easyappointments/blob/44af526a6fc5e898bc1e0132b2af9eb3a9b2c466/application/models/Customers_model.php#L121-L125

I wonder why there is such a restriction is really needed. By commenting out the code above + this block, different customers could have the same email

https://github.com/alextselegidis/easyappointments/blob/44af526a6fc5e898bc1e0132b2af9eb3a9b2c466/application/models/Customers_model.php#L47-L51

Another use case for allowing non unique emails is when booking an appointment for two different customers where both users provide a corporate email such as `info@mycompany.com`. Those are two different users but they just provide the same email address

wdyt?
cheers

**Comment by aparrot89** [comment]
Ok.
When I make two appointments with different first and last names but the same address the first and last names are overwritten by the second entry.
I haven't checked in db what happens but that's why I said that.

**Comment by JanC** [comment]
ok I see this is already being addressed in the upcoming 1.5 version in the dev branch. So I close this ticket
