### ISSUE TITLE
No accses for index

### ISSUE THREAD

**Issue by dogukansahil** [alextselegidis/easyappointments#1236]
Not allowing an appointment through the index. How can I make only logged in users authorized for this job?

**Comment by dogukansahil** [comment]
> Not allowing an appointment through the index. How can I make only logged in users authorized for this job?

and mandatory e-mail should be removed. not everyone has an email 😂

**Comment by Mips2648** [comment]
![image](https://user-images.githubusercontent.com/41119856/164167543-85bf9126-2ee5-429a-85f7-8922573729bf.png)
So you like your own message? 🤣 




> > Not allowing an appointment through the index. How can I make only logged in users authorized for this job?
> 
> and mandatory e-mail should be removed. not everyone has an email

For sure password creation can be done by other mean than email but still this is quite usual and anyway this is how it is done in this app so if you want that only logged user can book appointment, how do you expect they will be able to create a user account without an email address?

**Comment by dogukansahil** [comment]
> 

Sorry, I'm new here 😂 My only problem is removing the e-mail requirement. Is there a definitive solution to this?

**Comment by Mips2648** [comment]
Maybe do a quick search on past issues posted here like this one? https://github.com/alextselegidis/easyappointments/issues/376
