### ISSUE TITLE
Changing the Email format

### ISSUE THREAD

**Issue by dogukansahil** [alextselegidis/easyappointments#1238]
**x@x** is enough but  I want to change this format.
I want to enforce .com or remove the @ sign
Which file should I change for this?

**Comment by alextselegidis** [comment]
Hello! 

You will need to change the general_functions.js file that has a validateEmail function. 

You may also need to change the validate method following model classes:

* Customers_model.php
* Providers_model.php
* Secretaries_model.php
* Admins_model.php

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
