### ISSUE TITLE
Is there a way to create a user that's both a provider and an admin?

### ISSUE THREAD

**Issue by SamGreenwood1** [alextselegidis/easyappointments#1251]

**Comment by alextselegidis** [comment]
Hello! 

Right now the role and permissions system would not allow that directly, but it makes sense for users to be able to accept bookings and also maintain their administrative role. 

For that I'll allow admin and secretary users to also accept appointments: 

https://github.com/alextselegidis/easyappointments/issues/1265

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
