### ISSUE TITLE
(web)hooks

### ISSUE THREAD

**Issue by coderofsalvation** [alextselegidis/easyappointments#1254]
Great project, thanks for this :heart: 

is there some example/way of reacting to database events?
That would make the system hyper-extendable by anybody (compared to burdening the maintainer of this project with niche feature-requests).

Imho some kindof php-snippet/function which monkeypatches the SQL function would suffice already.
I could imagine defining something like including a custom php-file (`rules.php` e.g.):

```
$hooks = array(
  /* regex */                           /* rule function */
  "/UPDATE sometable/" => function(sql,$values){
     // do something like calling URL etc
  }
)
```

even better would be exposing the SQL database-events (update/delete/insert) as webhooks, but I guess that also requires more UI-work.

**Comment by alextselegidis** [comment]
Hello! 

There's already a feature ticket for the upcoming 1.5 version that will tackle this specific issue: 

https://github.com/alextselegidis/easyappointments/issues/581

Star and follow the project and stay tuned for future updates. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
