### ISSUE TITLE
Issues with Gmail

### ISSUE THREAD

**Issue by IgortsDEV** [alextselegidis/easyappointments#1256]
I tried to enable less secure apps on Gmail to send the e-mails using smtp... always worked ( previous installation of easyappointments) but now having issues ... on their website is saying that requires oAUTH there is any way to do it ? or any implementation already?

**Comment by alextselegidis** [comment]
Hello! 

It is possible that Google has disallowed SMTP based email delivery, even with less secured apps which means that email messages should from now own be sent via HTTP requests using the corresponding API. 

There is no implementation for that, so I would advise you to use a different SMTP account for your emails. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
