### ISSUE TITLE
Google notification regarding OAuth out-of-band flow on easyappointments OAuth 2.0

### ISSUE THREAD

**Issue by mundoayala** [alextselegidis/easyappointments#1257]
Been using easyappointments with great success connected with Google Calendar API. Recently Google started sending alert emails about deprecation and blocking of requests "OAuth client(s) will be blocked on Oct 3, 2022" refencing this article: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

I was wondering if other of users of easyappointments with Google Calendar API got the same notification as I did. Google notification follows:

>Starting October 3, 2022, we will block OOB requests to Google’s OAuth 2.0 authorization endpoint for existing clients. Apps using OOB in testing mode will not be affected. However, we strongly recommend you to migrate them to safer methods as these apps will be immediately blocked when switching to in production status.
>
>Note: New OOB usage has already been disallowed since February 28, 2022.
>
>Below are key dates for compliance
>
>September 5, 2022: A user-facing warning message may be displayed to non-compliant OAuth requests
>October 3, 2022: The OOB flow is blocked for all clients and users will see the error page.
>Please check out our recent blog post about Making Google OAuth interactions safer for more information.
>
>What do I need to do?
>Migrate your app(s) to an appropriate alternative method by following these instructions:
>
>Determine your app(s) client type from your Google Cloud project by following the client links below.
>Migrate your app(s) to a more secure alternative method by following the instructions in the blog post above for your client type.
>If necessary, you may request a one-time extension for migrating your app until January 31, 2023. Keep in mind that all OOB authorization requests will be blocked on February 1, 2023.
>
>The following OAuth client(s) will be blocked on Oct 3, 2022.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for sharing this! 

I haven't received this notification yet, nor have I seen it mentioned somewhere else. 

It'll be great if there is anyone else that can confirm this. 

Normally that should not be an issue for Easy!Appointments, as we are not using the OOB flow, this will not be an issue for existing installations. 

Do let us know if you face any other Google Sync related issues. 

Cheers!

Alex

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
