### ISSUE TITLE
Notifications problems

### ISSUE THREAD

**Issue by scorpion97429** [alextselegidis/easyappointments#1261]
Hello,

I'm testing version 1.5 and I have a problem with notifications. I receive them only when I cancel an appointment.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting this, I will take a closer look and get backt you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
So I just checked the latest develop state and I got notifications normally on new appointment registration. 

It could be that this is just a 1.5-dev.2 issue, but it will certainly work in the upcoming alpha package I'm preparing. 

Please make sure the customers have the email field enabled as well (settings > booking) and that the customer notifications are enabled. 

Also use valid email addresses for your tests. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
