### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by Khaled-Proof** [alextselegidis/easyappointments#1266]
Hey guys, 

i am trying to implement a rating system for providers for easyappointments. did any one try this ?
thankful for your ideas.

**Comment by alextselegidis** [comment]
Hello! 

The best place to start would be the Easy!Appointments framework documentation: 

https://developers.easyappointments.org/framework

This way you will get a better understanding on how the app currently works and you will be able to add your own changes. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
