### ISSUE TITLE
Captcha package requirement issue

### ISSUE THREAD

**Issue by jeroenvds** [alextselegidis/easyappointments#1268]
The current develop branch depends on gregwar/captcha, which has a problematic dependency on symfony/finder without version restriction. This will create a dependency on PHP8. 

This package is no longer maintained, so it would be good to remove this dependency.

A new fork exists which is being maintained:
https://codeberg.org/S1SYPHOS/php-simple-captcha

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

> This package is no longer maintained, so it would be good to remove this dependency.

You mean `gregwar/captcha` is not maintained any more? 

After performing some changes I managed to make this package work with PHP8+ for 1.4.3

Did you try that version already? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by jeroenvds** [comment]
I didn't try yet with PHP8, but I noticed this issue on Github for gregwar/catpcha:
https://github.com/Gregwar/Captcha/issues/103

The last commit is 5 months ago, and pull requests are not being considered.

**Comment by alextselegidis** [comment]
I see, let me check this in more detail and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

Alright after checking this issue, it looks like this is a composer.lock problem. 

The Symfony / Finder package did indeed lock to a version that requires PHP8, so updating the lock file fixed it. 

I will wait for some time but will replace the package if it still fails to update and fix any upcoming issues.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
