### ISSUE TITLE
Links in header contain index.php

### ISSUE THREAD

**Issue by thijslemmens** [alextselegidis/easyappointments#127]
The 1.0 version used links like:
href="<?php echo $base_url; ?>backend/settings"

Now this has become:
href="<?php echo $base_url; ?>/index.php/backend/settings"

Is there a good reason to do that?

Shouldn't you use site_url('backend/settings') ?

I'm not writing a lot of php, and I'm not familiar with CodeIgniter, that's why I'm ask. I'm happy to send in a pull request with the fix if you confirm I am correct.

By the way, I just upgraded, and my URL's containing index.php if I click around. I'm using an NGINX config instead of .htaccess and a subfolder.

**Comment by alextselegidis** [comment]
Actually you're definitely right. It was supposed to be like that but I didn't know about the URL helper back then and the `site_url` method so this is why I've written that manually. 

I will mark this as an enhancement and give you the time to integrate it within the application. 

Thanks for noticing :)
