### ISSUE TITLE
CSS Stylesheets and all functionality disappears after adding SSL security certificate

### ISSUE THREAD

**Issue by openSourcerer9000** [alextselegidis/easyappointments#1271]
So I hosted a copy of easyappointments, installed with Softaculous. The GUI worked great until I installed an SSL security certificate. Now the CSS Stylesheets and all UI functionality stopped working when viewing in https. Apparently resources with http: break when using https, however, it's not obvious from search in the repo which imports may be breaking down. 

The email functionality doesn't work without SSL, so a certificate is needed. Hopefully there's a quick fix for this, I'm brand new to this wordpress/php stuff.

As http:
![image](https://user-images.githubusercontent.com/61931826/171773603-7e3aaa7b-42e4-4491-9d43-5b107bc35815.png)

As https:
![image](https://user-images.githubusercontent.com/61931826/171773642-ec159dc5-fc5b-4e60-abb4-52b3e0b996f2.png)

**Comment by bositman** [comment]
You probably have to change the base_url in config.php to https...

**Comment by openSourcerer9000** [comment]
Dope, I love an easy solution, thanks
