### ISSUE TITLE
Ability to configure email templates -- more informative email subject lines

### ISSUE THREAD

**Issue by hesco** [alextselegidis/easyappointments#1273]
As a customer, when I have confirmed an appointment in the user interface, 
I would like the subject line for my confirmation email to read:
Your appointment w/ {service_provider} for {service_title} for {date} at {time} has been booked.

As a service provider, when a customer confirms an appointment,
I would like the subject line for the notification email I receive to read:
An appointment for {date} at {time} has been booked by {customer} for {service_title}.

As an administrator, I would like to be able to configure these subject lines, 
in fact the entire text of the emails myself, using replacement tokens 
inserted from a drop down menu of supported tokens.

**Comment by alextselegidis** [comment]
Hello! 

You can modify the /application/libraries/Notifications.php and /engine/Notifications/Email.php to add more methods for emails that have different content. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
