### ISSUE TITLE
view note in calendar appointments

### ISSUE THREAD

**Issue by angelofonte** [alextselegidis/easyappointments#1275]
hello,

I want view note in calendar appointments, is possible ??

help me

**Comment by alextselegidis** [comment]
Hello! 

This is already answered here: 

https://groups.google.com/g/easy-appointments/c/0z3mhWmVSxw/m/PvYy7LF9AQAJ

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
