### ISSUE TITLE
Blank page after install

### ISSUE THREAD

**Issue by AlainReve** [alextselegidis/easyappointments#1280]
The blank page after a new installation is rather discouraging. 
Could you please change it so that it at least says something?
For example, a list of possible causes, a link to the support group, etc?

**Comment by alextselegidis** [comment]
Hello @AlainReve! 

> The blank page after a new installation is rather discouraging.

I'm sorry to hear that you had problems installing Easy!Appointments. 

The fact is that the installation process is very simple for anyone installing other similar self hosted apps (basically only needs to copy config.php and open the app in your browser). 

> Could you please change it so that it at least says something?

Right now the content has everything you need but I'm planning to release some installation videos to make this even simpler. 

You other installation questions are answered in the support group: 

https://groups.google.com/g/easy-appointments/c/7LyyeOGCDs4

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
