### ISSUE TITLE
Gmail clients don't receive notifications

### ISSUE THREAD

**Issue by Duski55** [alextselegidis/easyappointments#1286]
Hi Alex, thank you for your very useful app. But I have a problem with e-mail notifications which I'm not able to solve :-(

First of all I used the default setting for e-mail notifications like described here 
https://easyappointments.org/2022/05/16/how-to-fix-email-delivery-problems/.
Notifications worked well except of gmail clients.

Then I set a custom SMTP server like this:
$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = 'mail'; // 'mail' or 'smtp'
$config['mailtype'] = 'html'; // or 'text'
$config['smtp_host'] = 'mail.vivaldi.net';
$config[‘smtp_auth’] = 'TRUE';
$config['smtp_user'] = 'xxxx@vivaldi.net'; 
$config['smtp_pass'] = 'yyyy;
$config['smtp_crypto'] = 'tls'; // 'ssl' or 'tls'
$config['smtp_port'] = 587;
This configuration works well too, but again only outside gmail clients.

Can you advise me on a solution ?

Thanx in advance
Duski

**Comment by alextselegidis** [comment]
Hello! 

Are you getting SMTP related error in the log files of the app? 

Cause if not, it could be that the SMTP server it self has an issue or your mails are being bounced by Gmail. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Duski55** [comment]
Thank you for you response, Alex.
But:
1.	Where can I find log files of your app ?
2.	What can I do, if this this problem causes Google ? That is why I don’t use SMTP server from Google, but from Vivaldi

Regards, Duski.

**Comment by alextselegidis** [comment]
Check this post for more information on how to troubleshoot E!A

https://easyappointments.org/2021/05/31/how-to-troubleshoot-easyappointments

For Delivery problems you may test this post: 

https://easyappointments.org/2022/05/16/how-to-fix-email-delivery-problems

Create a new ticket in case you find a PHP related error
