### ISSUE TITLE
Feature Request: Blocking an appointment without a unique link

### ISSUE THREAD

**Issue by YehudaEi** [alextselegidis/easyappointments#1291]
Hey @alextselegidis,

I want to allow people to book an appointment only through a unique link (let's say the id of the service will be based on uuid4 and if it does not appear as a parameter in the link then an error message will be showed).

At the moment I tried to make this change myself and it is a bit difficult because all the data of the meeting types is loaded as JSON inside the HTML and not through a request to the server.

I would appreciate it if you could add this option soon.

Thank you so much for all your work!

**Comment by alextselegidis** [comment]
Hello! 

The upcoming 1.5 version will allow you to mark services and providers as private, so people will only be able to book them internally or if they have their booking link. 

Stay tuned and update once this release becomes stable! 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
