### ISSUE TITLE
Download files from /storage/backups and /storage/uploads

### ISSUE THREAD

**Issue by robert-hedler** [alextselegidis/easyappointments#1293]
Hi Team good day. Today i installed version 1.4.3 of EA to test. I am using Nginx on CentOS7 and PHP7.4.

I was able to download backups from backups folder just putting the complete file name. I guess this should not happen right?

Example: https://book.easite.com/storage/backups/easyappointments-backup-2022-08-07-021210.gz
Doing this you will be able to download the backup from your server.

I added this on my NGINX config and solved, i can not download backups or upload files from my server.
    **```
location /storage/backups { return 404 https://book.i9networks.net.br; }
location /storage/uploads { return 404 https://book.i9networks.net.br; }
```**

Is that correct or i am doing some mess?

**Comment by alextselegidis** [comment]
Hello! 

You will need to deny access to the entire directory (except the uploads directory). 

This is something you will need to configure on your NGINX server. 

For apache there are already some .htaccess files that do this, but of couse those do not apply to an NGINX environment: 

https://github.com/alextselegidis/easyappointments/blob/master/storage/logs/.htaccess

This is how you can do the same for NGINX: 

https://serverfault.com/questions/137907/how-to-restrict-access-to-directory-and-subdirs

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by robert-hedler** [comment]
Thanks for the solution and awesome job done on the project!

**Comment by alextselegidis** [comment]
Glad to know you like it!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
