### ISSUE TITLE
how to stop browser base timezone selection

### ISSUE THREAD

**Issue by redquantum** [alextselegidis/easyappointments#1294]
Hello, I want to default selection UTC in appointments page. Currently, the city is automatically selected according to the browser location. How can I stop this? I always want UTC to be selected.

Thank you.

**Comment by alextselegidis** [comment]
Hello! 

Disable this line: 

https://github.com/alextselegidis/easyappointments/blob/master/assets/js/frontend_book.js#L133

Update the .min file as well. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
