### ISSUE TITLE
Localization management system

### ISSUE THREAD

**Issue by cn-tools** [alextselegidis/easyappointments#1299]
What do you think of localization management systems like Crowdin or Transifex?

Can this be activated for this project?

In that case, other peoples could easily help to make more languages available.
Also it is shown which phrases are not translated yet.

**Comment by alextselegidis** [comment]
Hello! 

A localization management system would be great! I will consider enabling this in the near future. 

Till then, you can find more information on how to help with translations on this blog post: 

https://easyappointments.org/2021/06/21/help-with-translations

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
