### ISSUE TITLE
backed access error (cache??) and problem with 2 calendars for a user

### ISSUE THREAD

**Issue by hans-vb** [alextselegidis/easyappointments#130]
I can see some errors as are:

a) Backend login is failing sometimes, if you use correct access data you are redirected to /user/login, without any message and using the URL for /backend I have the same result. It seems to be a cache problem but many times, the only solution I can find is to use a URL like:
/backend?nocache=1234 (rand number)

b) In the same way, once inside the application if you click on "Calendar" (/backend) again we have the same result, and we have to login using a URL like the one in point a)

c) Sometimes we can see AJAX error messages, using firebug (console tab) we can see 500 Errors, What's the problem?

Another problem detected is that one user can have various calendars and if a hour is occupied in one of them, it steel appers to be free in the other calendar. We think this is an error, cause the technician has that hour busy in the other calendar.

Is it possible to confirm dates? A customer asks for a date and automatically it's assigned to the him. It would be great if we could validate the dates, due to a user can have more than one calendar.

Best regards.

**Comment by emanwebdev** [comment]
@hans-vb i'd suggest you to open a new "issue"/feature request for

> Is it possible to confirm dates?

**Comment by hans-vb** [comment]
any comment for this?

"Another problem detected is that one user can have various calendars and if a hour is occupied in one of them, it steel appers to be free in the other calendar. We think this is an error, cause the technician has that hour busy in the other calendar."

**Comment by alextselegidis** [comment]
Let's discuss this step by step: 

a + b) I cannot really reproduce the problem. 

Have you made any modifications to the source? 

Easy!Appointments is just using PHP's session system so all I can think is that something in the server might be configured to prevent storing session information or the browser does not store the session ID cookie. 

c) Enable the DEBUG mode from the config.php file and check for error logs in the server (application/logs or apache error logs). 

Please clarify the following: 

> Another problem detected is that one user can have various calendars and if a hour is occupied in  one of them, it steel appers to be free in the other calendar. We think this is an error, cause the technician has that hour busy in the other calendar.

The following is unfortunately not possible at the moment: 

> Is it possible to confirm dates? A customer asks for a date and automatically it's assigned to the him. It would be great if we could validate the dates, due to a user can have more than one calendar.
