### ISSUE TITLE
Cannot connect to Installation page from local build

### ISSUE THREAD

**Issue by Juangunner4** [alextselegidis/easyappointments#1301]
I have installed necessary tools for installing the application installation, but my server is not recognizing it for some reason. All files are in htdocs in apache and it is running on port 80. Changes necessary settings as intructed on config.php

![image](https://user-images.githubusercontent.com/29739445/189386945-89665926-0373-45b4-b071-40d57b218550.png)

**Comment by alextselegidis** [comment]
Hello! 

As you can see you are getting a 500 error which means that something in your installation is not configured correctly. 

Check out this guide on more info on how to troubleshoot E!A: 

https://easyappointments.org/2021/05/31/how-to-troubleshoot-easyappointments/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
