### ISSUE TITLE
Base_url trailing slashes and session_start() failed to initialize storage module.

### ISSUE THREAD

**Issue by bsawlor** [alextselegidis/easyappointments#1309]
Setup: Ubuntu 20.04
Nginx: 1.18.0
MySQL: Server version: 8.0.30-0ubuntu0.20.04.2 (Ubuntu)
PHP: PHP 7.4.3 (cli) (built: Aug 17 2022 13:29:56) ( NTS )
nodejs: v10.19.0

I am trying to install and setup an instance (to hopefully get running and modify) as an internal tool. My config has the following:
`    const BASE_URL      = 'http://vs-tools/scheduler';`
I ran into what I believe is #1192 as the install page when loaded kept showing me 
"Invalid Configuration Detected"
"Please remove any trailing slashes from your "BASE_URL" setting of the root "config.php" file and try again."

With the comments indicating the fix was in the devel version, I grabbed 1.5dev2 and setup a seperate instance, removing the previous sites-enable file so the setup is still in place if needed.  But now I see the same message as well as a php error at the top of the page.  This did affect the db before, dispite not actually being able to click install, possibly due to the error mentioned above.  But now it can't connect?
```
A PHP Error was encountered
Severity

Warning
Message

session_start(): Failed to initialize storage module: user (path: /var/www/scheduler/application/config/../../storage/sessions)
Filename

Session/Session.php
Line Number

127
```

The way I have my /etc/nginx/sites-available (and symlinked sites-enabled to) file configured, I want the url for this to be vs-tools/scheduler, but that comes back with a 404 error, and only vs-tools responds with the install page, as well the 'Remember to use' url on the install page points to vs-tools, rather then vs-tools/scheduler.  Am I missing something that would force it to use the desired url?

```
server {
        listen 80;
        listen [::]:80;

        root /var/www/scheduler;
        index index.php index.html index.htm index.nginx-debian.html;

        server_name vs-tools;

        location /scheduler/ {
                try_files $uri $uri/ /index.php$is_args$args;
                # root /var/www/scheduler;
                if (!-e $request_filename){
                        rewrite ^(.*)$ /index.php?/$1 last;
                }
        }

        #location /test-scheduler {
                #try_files $uri $uri/ /index.php;
                # root /var/www/test-scheduler;

                # Make an internal redirect if the file is not found
                #error_page 404 = /fetch$uri;
        #}

        location ~ \.php? {
                # fastcgi_split_path_info ^(.+\.php)(/.+)$;
                # A handy function that became available in 0.7.31 that breaks down
                # The path information based on the provided regex expression
                # This is handy for requests such as file.php/some/paths/here/

                fastcgi_param  PATH_INFO          $fastcgi_path_info;
                fastcgi_param  PATH_TRANSLATED    $document_root$fastcgi_path_info;

                fastcgi_param  QUERY_STRING       $query_string;
                fastcgi_param  REQUEST_METHOD     $request_method;
                fastcgi_param  CONTENT_TYPE       $content_type;
                fastcgi_param  CONTENT_LENGTH     $content_length;

                fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
                # fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_nam>
                fastcgi_param  SCRIPT_FILENAME    $request_filename;
                fastcgi_param  REQUEST_URI        $request_uri;
                fastcgi_param  DOCUMENT_URI       $document_uri;
                fastcgi_param  DOCUMENT_ROOT      $document_root;
                fastcgi_param  SERVER_PROTOCOL    $server_protocol;

                fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
                fastcgi_param  SERVER_SOFTWARE    nginx;

                fastcgi_param  REMOTE_ADDR        $remote_addr;
                fastcgi_param  REMOTE_PORT        $remote_port;
                fastcgi_param  SERVER_ADDR        $server_addr;
                fastcgi_param  SERVER_PORT        $server_port;
                fastcgi_param  SERVER_NAME        $server_name;

                # fastcgi_pass   unix:/var/run/php5-fpm.sock;
                # fastcgi_index  index.php;
                include snippets/fastcgi-php.conf;
                fastcgi_pass   unix:/var/run/php/php7.4-fpm.sock;
                # fastcgi_pass 127.0.0.1:9000;
        }

        location ~ /\.ht {
                deny all;
        }
        if (!-e $request_filename){
                rewrite ^(.*)$ /index.php?/$1 last;
        }
}
```

**Comment by bsawlor** [comment]
Also note, I want to have [this](http://cronicle.net/) setup on vs-tools/cron so using nginx and moving this off the root is very desired.

**Comment by alextselegidis** [comment]
Hello! 

It looks like the storage/sessions directory is not writable and therefore the app cannot initiate any PHP sessions. 

You can either make the directory writable or configure your installation to use a different session setup.

https://developers.easyappointments.org/framework/libraries/sessions.html?highlight=sessions

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by bsawlor** [comment]
Just fixed permissions, but the response is still coming up when there is no trailing /.
`Please remove any trailing slashes from your "BASE_URL" setting of the root "config.php" file and try again.`

config.php
`const BASE_URL      = 'http://vs-tools/scheduler';`

**Comment by alextselegidis** [comment]
Hello! 

Can you confirm you are using the 1.5.0-dev.2 package? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by bsawlor** [comment]
Yeah, I was seeing this response on both 1.5dev2 as well as 1.4.3.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for confirming this, I will need to see if I can reproduce this as well, as it looks like there is an underlying routing issue with your config. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by theking81** [comment]
> Hello!
> 
> Thanks for confirming this, I will need to see if I can reproduce this as well, as it looks like there is an underlying routing issue with your config.
> 
> ![](https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	Alex Tselegidis, Easy!Appointments Creator
> [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

Did you manage to find out a solution to this issue? thnx

**Comment by alextselegidis** [comment]
@theking81 I cannot reproduce this issue, so any help would be great ;) Feel free to provide more information as requested in this ticket: https://github.com/alextselegidis/easyappointments/issues/1311#issuecomment-1322093859

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
