### ISSUE TITLE
Base_url trailing slashes

### ISSUE THREAD

**Issue by bsawlor** [alextselegidis/easyappointments#1311]
Just fixed permissions, but the response is still coming up when there is no trailing /.
`Please remove any trailing slashes from your "BASE_URL" setting of the root "config.php" file and try again.`

config.php
`const BASE_URL      = 'http://vs-tools/scheduler';`

_Originally posted by @bsawlor in https://github.com/alextselegidis/easyappointments/issues/1309#issuecomment-1265397018_

**Comment by bsawlor** [comment]
I've gone so far as to adjust everything to try and eliminate the possibility
`const BASE_URL      = 'http://vs-tools.scheduler';`

/etc/nginx/sites-available/vs-tools.scheduler (first part of the file)
```
server {
        listen 80;
        listen [::]:80;

        root /var/www/vs-tools.scheduler;
        index index.php index.html index.htm index.nginx-debian.html;

        server_name vs-tools.scheduler;

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
                # root /var/www/scheduler;
                if (!-e $request_filename){
                        rewrite ^(.*)$ /index.php?/$1 last;
                }
                #error_page 404 = /fetch$uri
        }

        #location /test-scheduler {
                #try_files $uri $uri/ /index.php;
                # root /var/www/test-scheduler;

                # Make an internal redirect if the file is not found
                #error_page 404 = /fetch$uri;
        #}
```

/etc/nginx/sites-enabled/ (symlink)
`vs-tools.scheduler -> ../sites-available/vs-tools.scheduler`

Everything in /var/www/vs-tools.scheduler has www-data ownership

Even with those changes, and restarting and/or reloading nginx, http://vs-tools/ still reverts to http://vs-tools/index.php/installation with the trailing slash message, and http://vs-tools.scheduler/ which I would expect to have the installation page as per the new config, has 'Site can't be reached'. It looks like any changes at this point aren't affecting the site and the url it is/should be accessible from.

**Comment by bsawlor** [comment]
Using a dedicated port does allow it to change, but the trailing slash message still appears when there isn't one.  Is something affecting the importing code?  Trying to run 1.5.0-dev.2. Is it posible this message is a false negative?

**Comment by Seriousness** [comment]
Using the latest dev a friend of mine came up with the same error... no change in the config does prevent the messsage

**Comment by alextselegidis** [comment]
Hello! 

The message should actually only appear if in the root config.php there is a trailing slash in the BASE_URL value. 

Are you suggesting that you get the error without this being the case? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by bsawlor** [comment]
That seems to be the case. In all the attempts, I've made sure to not have
a trailing slash but the message always comes up.

**Comment by theking81** [comment]
I also have to report this issue with the BASE_URL error
![image](https://user-images.githubusercontent.com/25663895/202463694-ab666b92-146f-4710-bfc6-afcfd730a147.png)

**Comment by alextselegidis** [comment]
@theking81 Could you please post here the URL that you use for the installation page in your screenshot and the value of the BASE_URL const of your local config.php file? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Seriousness** [comment]
I wouldnt expose an unfinished install url via an issue. 

I've managed to work the install by setting the config manually and using the cli install (php index.php console install) maybe that helps you?

**Comment by error08** [comment]
It seems the problem is in application/config/config.php, the Config.BASE_URL is not considered here. Only try to automatic build the right url.

`
$protocol =
    (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on')
    || (isset($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443)
    || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
        ? 'https://' : 'http://';

$domain = $_SERVER['HTTP_HOST'] ?? 'localhost';

$request_uri = dirname($_SERVER['SCRIPT_NAME']);

$config['base_url'] = trim($protocol . $domain . $request_uri, '/');`

I set the 
`$config['base_url'] = Config::BASE_URL;`
like in version 1.4.3 and it works.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for providing all this info. 

It looks like under certain environments, there is a URL detection issue. 

Unfortunately I cannot currently reproduce this issue, but feel free to drop a message on info@easyappointments.org to troubleshoot this before the stable release.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by skerbis** [comment]
Sane here tested with 1.5.0-dev.2 ... 

Server Config: 


<details>
<summary>System report (PHP 8.1.14, MariaDB 10.6.11)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.0-dev |


| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.14     |
|       OPcache | yes        |
|        Xdebug | no         |


| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.6.11 |
| Character set | utf8mb4         |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.2 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |

</details>

**Comment by alextselegidis** [comment]
Thanks @skerbis, you you add the following debug command at the top of the root index.php file and post here the results? 

```
var_dump($_SERVER);
die();
```

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by skerbis** [comment]
@alextselegidis 
> and post here the results?
sure, here are the results: 
```
array(42) { 
    ["USER"]=> string(26) "easy.my.tld_5w45kzhcsaw" 
    ["HOME"]=> string(30) "/var/www/vhosts/easy.my.tld" 
    ["SCRIPT_NAME"]=> string(10) "/index.php" 
    ["REQUEST_URI"]=> string(1) "/" ["QUERY_STRING"]=> string(0) "" 
    ["REQUEST_METHOD"]=> string(3) "GET" 
    ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.0" 
    ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" 
    ["REMOTE_PORT"]=> string(5) "33666" 
    ["SCRIPT_FILENAME"]=> string(49) "/var/www/vhosts/easy.my.tld/httpdocs/index.php" 
    ["SERVER_ADMIN"]=> string(18) "[no address given]" 
    ["CONTEXT_DOCUMENT_ROOT"]=> string(39) "/var/www/vhosts/easy.my.tld/httpdocs" 
    ["CONTEXT_PREFIX"]=> string(0) "" 
    ["REQUEST_SCHEME"]=> string(5) "https"
    ["DOCUMENT_ROOT"]=> string(39) "/var/www/vhosts/easy.my.tld/httpdocs" 
    ["REMOTE_ADDR"]=> string(13) "XX.XX.XX.XX" 
    ["SERVER_PORT"]=> string(3) "443" 
    ["SERVER_ADDR"]=> string(11) "XX.XX.XX.XX" 
    ["SERVER_NAME"]=> string(14) "easy.my.tld" 
    ["SERVER_SOFTWARE"]=> string(6) "Apache" 
    ["SERVER_SIGNATURE"]=> string(60) "Apache Server at easy.my.tld Port 443" 
    ["PATH"]=> string(70) "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin" 
    ["HTTP_COOKIE"]=> string(89) "csrf_cookie=043d4f5321fda9d0e90f84c263efde16; ea_session=e7kstmdh27tmte8fhvdiqshro0n35p6e" 
    ["HTTP_ACCEPT_ENCODING"]=> string(17) "gzip, deflate, br" 
    ["HTTP_ACCEPT_LANGUAGE"]=> string(14) "de-DE,de;q=0.9" 
    ["HTTP_USER_AGENT"]=> string(117) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" 
    ["HTTP_ACCEPT"]=> string(63) "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" ["HTTP_CONNECTION"]=> string(5) "close" 
    ["HTTP_X_ACCEL_INTERNAL"]=> string(31) "/internal-nginx-static-location" ["HTTP_X_REAL_IP"]=> string(13) "87.139.18.144" 
    ["HTTP_HOST"]=> string(14) "easy.my.tld" 
    ["proxy-nokeepalive"]=> string(1) "1" 
    ["HTTPS"]=> string(2) "on" 
    ["PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY"]=> string(1) "0" 
    ["PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY"]=> string(1) "0" 
    ["SCRIPT_URI"]=> string(23) "https://easy.my.tld/" 
    ["SCRIPT_URL"]=> string(1) "/" 
    ["UNIQUE_ID"]=> string(27) "Y9eE1049xvrJnUwBPWBWHQAAAAA" 
    ["FCGI_ROLE"]=> string(9) "RESPONDER" 
    ["PHP_SELF"]=> string(10) "/index.php" 
    ["REQUEST_TIME_FLOAT"]=> float(1675068631.641263) 
    ["REQUEST_TIME"]=> int(1675068631) }
```

**Comment by alextselegidis** [comment]
Hello @skerbis, 

Thanks a ton for providing this! Checking at the $_SERVER array, I do not really see how the problem occurred, because in the installation page your `vars('base_url')`  value should be `http://easy.my.tld` and not `http://easy.my.tld/`. 

Could you please open the installation page and type `vars('base_url')` in the dev tools console and page here the result? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Thanks @skerbis, so you still get this message

`Please remove any trailing slashes from your "BASE_URL" setting of the root "config.php" file and try again.`

Even though you do not have the trailing slash right? 

The file that is responsible for this message is the `assets/js/pages/installation.js`


````
// Validate the base URL setting (must not contain any trailing slash).
    if (vars('base_url').slice(-1) === '/') {
        App.Utils.Message.show(
            'Invalid Configuration Detected',
            'Please remove any trailing slashes from your "BASE_URL" setting of the root "config.php" file and try again.'
        );
        $install.prop('disabled', true).fadeTo('0.4');
    }
```

With this if condition, we check if the vars('base_url') ends with a trailing "/"

Since your `vars('base_url')` value does not end with a slash, then it cannot be that you see this error. 

Could you confirm this? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello @skerbis, 

Did you had any time to check on this? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by skerbis** [comment]
Sorry no. I will check it later this week.

**Comment by alextselegidis** [comment]
@skerbis Thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by skerbis** [comment]
I've checked it on a new system - it works. Thanks

**Comment by alextselegidis** [comment]
Wonderful, thanks for your help!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
