### ISSUE TITLE
Change Appointment Title and Appointment Information

### ISSUE THREAD

**Issue by bstnsolari** [alextselegidis/easyappointments#1315]
Hello everyone

I want to do some changes on the backend calendar, specifically on the default view: 

What I would like to change is the appointment title. It shows "Service Name" - "Customer First Name" + " " + "Customer Last Name". I'm looking at the code, but so far the only way of _"changing"_ it is on the fullcalendar.min.js file (assets/ext/jquery-fullcalendar). 

At first I tried to make changes on backend_calendar_default_view.min.js but no success so far.

Appartenly, what is filling the title name is a variable declared as d (d.title) and var d is declared as t.footprint.eventDef. Does anyone know where I can modify that? 

![imagen](https://user-images.githubusercontent.com/94856416/197597715-1122b9e9-4b64-4324-9d97-81a5829772f1.png)

![imagen](https://user-images.githubusercontent.com/94856416/197597868-e32ea301-a433-467c-8509-8e0fb418cafd.png)

 Hope everyone is doing great and thank you, in advance!

**Comment by alextselegidis** [comment]
Hello! 

By default, the app will use the minified files in production for better performance. 

You can change that by enabling the DEBUG_MODE flag in the root config.php file. 

The best way though to work with this is to set up E!A from git locally and work with the sources. 

https://easyappointments.org/2021/05/24/setup-easyappointments-from-git/

Then build your changes with "gulp build" and deploy back. 

If you are not familiar with how this works then modify the non minified files and then updated the minified files manually by using an online JS-minifcation site, such as:

https://skalman.github.io/UglifyJS-online/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
