### ISSUE TITLE
Notifications not working when deleting an appointment via API

### ISSUE THREAD

**Issue by ddobbelaere** [alextselegidis/easyappointments#1318]
In v1.4.3, when deleting an appointment via the REST API, no notifications are being sent.
Google Calendar synchronization is working fine though.

I think this is caused as follows. When performing an HTTP DELETE  on `api/v1/appointments/:id`, no POST parameter `cancel_reason` is being sent with the request, and [this code](https://github.com/alextselegidis/easyappointments/blob/44af526a6fc5e898bc1e0132b2af9eb3a9b2c466/application/libraries/Notifications.php#L173) will throw (as `$this->CI->input->post('cancel_reason')` is `null` and `Text` constructor will bail out), but it will get silently caught in the same method.

**Comment by ddobbelaere** [comment]
Appending `?? ''` to `$this->CI->input->post('cancel_reason')` indeed 'fixes' it. A better fix that also allows the cancel reason to be set via the API might be wanted though.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this!

Were you able to reproduce this with the currently available 1.5-dev.2 release as well? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ddobbelaere** [comment]
Oh, I did not notice that this code has been revised in the `develop` branch.

I've tested it, and this issue does not appear in 1.5-dev.2.

**Comment by alextselegidis** [comment]
Hello! Indeed this particular code was refactor and I confirm the problem will not appear in 1.5 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
