### ISSUE TITLE
Sorting API results in ascending order is broken (v1.5.0-dev.2)

### ISSUE THREAD

**Issue by ddobbelaere** [alextselegidis/easyappointments#1322]
Sorting API resulting in incrementing order (using "+") does not work anymore in v1.5.0-dev.2 (it used to work in v1.4.3).

E.g. `GET /index.php/api/v1/appointments?sort=+start` return the following:

```json
{"success":false,"message":"Invalid sort direction operator provided (expected \"-\" or \"+\"): s","trace":[]}
```

I think the issue has to do with HTML encoding of the "+" sign, as `GET /index.php/api/v1/appointments?sort=%2bstart` seems to work.
Sorting in descending order (with minus sign) works as expected.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting this! It will be fixed before the stable release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

This is fixed and will be released with the next E!A version.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
