### ISSUE TITLE
GET sorted unavailabilities via API is broken (v1.5.0-dev.2)

### ISSUE THREAD

**Issue by ddobbelaere** [alextselegidis/easyappointments#1323]
Sorting unavailabilities via API is broken (v1.5.0-dev.2).

E.g. (in descending order, as otherwise #1322 pops out, which is probably unrelated) `GET /index.php/api/v1/unavailabilities?sort=-start` returns:

```
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC LIMIT 20' at line 5

SELECT * FROM `ea_appointments` WHERE `delete_datetime` IS NULL AND `is_unavailability` = 1 ORDER BY DESC LIMIT 20

Filename: models/Unavailabilities_model.php

Line Number: 286
```

**Comment by alextselegidis** [comment]
Hello! 

This is fixed and will be released with the next E!A version.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
