### ISSUE TITLE
I'm having issues building this locally...

### ISSUE THREAD

**Issue by masterfugazi** [alextselegidis/easyappointments#1324]
After I run 'npm start' shouldn't the application build locally via XAMPP? I tried finding it on port 3000 and 8000 no luck. Additionally, I did follow the docs and I have both npm and composer installed.

**Comment by masterfugazi** [comment]
I was able to get it working after correctly setting both my db creds and base url and then by running npm update, npm start, and npm run build.

**Comment by alextselegidis** [comment]
Hello! 

Glad to know you solved this. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
