### ISSUE TITLE
issue with install docker 

### ISSUE THREAD

**Issue by killmasta93** [alextselegidis/easyappointments#1335]
Hi
I was wondering if someone could shed some light on the issue im having 
Currently trying to install with docker compose but im getting an error 
![image](https://user-images.githubusercontent.com/13953629/206747223-a2e292e9-e6d6-4a66-9d64-b73a85e17d0c.png)

i was reading a bit and found this https://github.com/alextselegidis/easyappointments/issues/941

but not sure why i would need to install NPM on the host when the software is in a docker container?
In this case what would be the correct steps?

Thank you 

```
git clone https://github.com/alextselegidis/easyappointments.git
cd easyappointments
cp config-sample.php config.php
$EDITOR config.php
npm install && composer install
cd docker && docker-compose up
```

**Comment by alextselegidis** [comment]
Hello! 

You forgot to install the composer dependencies. 

Check out this guide for more information. 

https://easyappointments.org/2021/05/24/setup-easyappointments-from-git/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by killmasta93** [comment]
Hi there thank you for the reply, i did the following but im getting this error


![image](https://user-images.githubusercontent.com/13953629/207520209-8dfabf7b-349f-43b2-8331-1c8f28f4789f.png)

**Comment by killmasta93** [comment]
https://github.com/StarWhiz/docker_deployment_notes/tree/master/easyappointments
Solved using this guide
