### ISSUE TITLE
Load Page with HTTPS

### ISSUE THREAD

**Issue by bstnsolari** [alextselegidis/easyappointments#1339]
Hello everyone, hope you're doing well.

I loaded the proyect to my hosting, so the application is accessed on the web, but I'm running into the issue that the page loads with a HTTP connection instead of a HTTPS connection.

On my hosting config (for this app) I also have AutoSSL Domain Validated, but still runs with a HTTP connection.

Inside the proyect... is there any file that I have to make a change to run the app with HTTPS connection?

**Version Used: ** 1.4.3

**Comment by patrickus33** [comment]
Hello, You can do that by putting a .htaccess at the root of your install with 

<IfModule mod_rewrite.c>

 # Rewrite the URL to force https .
 RewriteEngine On

 # Compliant with hstspreload.org : first redirect to https if needed
 RewriteCond %{HTTPS} !=on
 RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

</IfModule>

**Comment by alextselegidis** [comment]
Also check this article if you are using NGNIX

https://serversforhackers.com/c/redirect-http-to-https-nginx

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
