### ISSUE TITLE
Add the location and notes fields to the appointment email notifications (if a value was provided). 

### ISSUE THREAD

**Issue by arladmin** [alextselegidis/easyappointments#1341]
When booking an appointment, i often add data to the `Location` and the `Notes` fields, e.g. to include the Google Meet link.

But, in the email sent to the `Provider` and the `Customer` this data is never included!

**Comment by alextselegidis** [comment]
Pushed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by iriikoad** [comment]
I would also add address, vity and zipcode to the location when booked:

booking.php:
```php
            if (empty($appointment['location']) && !empty($service['location'])) {
                $appointment['location'] = $service['location'];
            }
            // if not location: use the full address given when book
            if (empty($appointment['location'])) {
                $appointment['location'] = $customer['address'] . ' ' . $customer['zip_code'] . ' ' . $customer['city'];
            }
```
