### ISSUE TITLE
Deeplink to provider booking page

### ISSUE THREAD

**Issue by diskbuster** [alextselegidis/easyappointments#1342]
I looking for a feature to guide the user direct to a provider with a deeplink for booking an appointment.

What could be a good start to add this feature?

**Comment by alextselegidis** [comment]
Hello! 

Check out this blog post: 

https://easyappointments.org/2021/09/27/share-your-booking-links/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
