### ISSUE TITLE
Question: Adding a second address for user input.

### ISSUE THREAD

**Issue by Juangunner4** [alextselegidis/easyappointments#1343]
Working on adding a second address when user inputs their local address and would like to add the moving to address.

**Comment by alextselegidis** [comment]
Hello! 

There are several places that would need to be adjusted for the new information to display everywhere nicely. 

The best thing you could do, is to duplicate the existing address field and use the developer resources available on https://developers.easyappointments.org. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
