### ISSUE TITLE
recaptcha not loading

### ISSUE THREAD

**Issue by ml247** [alextselegidis/easyappointments#1344]
![Untitled](https://user-images.githubusercontent.com/111323707/221695209-08705d79-2f7a-4923-972b-66da8e84bf55.png)
![Untitled2](https://user-images.githubusercontent.com/111323707/221695223-1f2be4e6-cf7f-44dc-baf5-64d35223a222.png)

**Comment by ml247** [comment]
Resolved. Checked the Dockerfile you have and emulated that into my own Dockerfile. Mainly the problem was that the gd  php extension was installed but not configured with --with-freetype --with-jpeg
At least I think that is what it was.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

Which docker configuration were you using? The one from the master branch or the one from develop? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Alright I see, thanks for providing all this info! 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
