### ISSUE TITLE
default date / lead times

### ISSUE THREAD

**Issue by ml247** [alextselegidis/easyappointments#1346]
Has anyone successfully implemented a booking lead time? For example, we are unable to prepare for a booking unless it is made at least 2 days in advance. 
I tried implementing a min date of 2 days but the date picker will default to 2 days ahead, even if the day in question is not available to book. It even seems to let you go ahead and book that unavailable date.
Is there some way to make the default date 'null' such that the date is not selected, as this I think would resolve the issue?

**Comment by ml247** [comment]
Realised the way to do it = set the minDate: '+2d', within frontend_book.js

**Comment by alextselegidis** [comment]
Hello! 

There is a setting for that called "book advance timeout" and you can find it under the Business Logic tab of the settings page.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Physioweb** [comment]
Hi Alex,
Your program is awesome.

Blocking short term scheduling is what I need, but "**book advance timeout**" is not part of the Business Logic tab in my settings page. I'm on version 1.5.0.

However, if you can tell me the path to "**frontend_book.js**", I'll be OK too.
Kind regards

**Comment by Physioweb** [comment]
Thanks Alex, you are right. I can see the setting. Because I was looking for "book advance timeout" I thought it was something else. I thought it meant a timeout after booking. I've tested the timeout with 1200 (20 hours) and it works as intended. So good!
