### ISSUE TITLE
German translation of october is wrong

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1350]
It's Oktober, not October. Sorry for not sending a pull request...

https://github.com/alextselegidis/easyappointments/blob/2255c847781c16510a215878ff4058d57ac3c122/application/language/german/translations_lang.php#L258

**Comment by alextselegidis** [comment]
Fixed! Thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
