### ISSUE TITLE
The URI you submitted has disallowed characters

### ISSUE THREAD

**Issue by Shalomco1123** [alextselegidis/easyappointments#1353]
Good day all,
I install the easyappoitment in my server url: https://cal.bama.bio/easyappointments/
and i have this error: https://prnt.sc/vX3roP3Gd3dI              ???
See please attached screen shoot
in console:
![aaaqqww](https://user-images.githubusercontent.com/130908029/232310350-77060cda-1d06-4fdd-8610-0917681d7929.png)

jquery.min.js?6398SW:2          GET https://cal.bama.bio/easyappointments/index.php?/appointments/ajax_get_unavailable_dates&provider_id=any-provider&service_id=1&selected_date=2023-04-16&csrfToken=acbc984f05716e8e23abf06d980920f6&manage_mode=false&appointment_id= 400
send @ jquery.min.js?6398SW:2
ajax @ jquery.min.js?6398SW:2
exports.getUnavailableDates @ frontend_book_api.min.js?6398SW:258
(anonymous) @ frontend_book.min.js?6398SW:239
dispatch @ jquery.min.js?6398SW:2
v.handle @ jquery.min.js?6398SW:2
trigger @ jquery.min.js?6398SW:2
(anonymous) @ jquery.min.js?6398SW:2
each @ jquery.min.js?6398SW:2
each @ jquery.min.js?6398SW:2
trigger @ jquery.min.js?6398SW:2
exports.initialize @ frontend_book.min.js?6398SW:155
(anonymous) @ (index):767
e @ jquery.min.js?6398SW:2
t @ jquery.min.js?6398SW:2
setTimeout (async)
(anonymous) @ jquery.min.js?6398SW:2
c @ jquery.min.js?6398SW:2
fireWith @ jquery.min.js?6398SW:2
fire @ jquery.min.js?6398SW:2
c @ jquery.min.js?6398SW:2
fireWith @ jquery.min.js?6398SW:2
ready @ jquery.min.js?6398SW:2
B @ jquery.min.js?6398SW:2
general_functions.min.js?6398SW:316 Unexpected HTTP Error:  {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …} {url: 'https://cal.bama.bio/easyappointments/index.php?/a…3abf06d980920f6&manage_mode=false&appointment_id=', type: 'GET', isLocal: false, global: true, processData: true, …}
exports.ajaxFailureHandler @ general_functions.min.js?6398SW:316
(anonymous) @ general_functions.min.js?6398SW:30
dispatch @ jquery.min.js?6398SW:2
v.handle @ jquery.min.js?6398SW:2
trigger @ jquery.min.js?6398SW:2
l @ jquery.min.js?6398SW:2
(anonymous) @ jquery.min.js?6398SW:2
load (async)
send @ jquery.min.js?6398SW:2
ajax @ jquery.min.js?6398SW:2
exports.getUnavailableDates @ frontend_book_api.min.js?6398SW:258
(anonymous) @ frontend_book.min.js?6398SW:239
dispatch @ jquery.min.js?6398SW:2
v.handle @ jquery.min.js?6398SW:2
trigger @ jquery.min.js?6398SW:2
(anonymous) @ jquery.min.js?6398SW:2
each @ jquery.min.js?6398SW:2
each @ jquery.min.js?6398SW:2
trigger @ jquery.min.js?6398SW:2
exports.initialize @ frontend_book.min.js?6398SW:155
(anonymous) @ (index):767
e @ jquery.min.js?6398SW:2
t @ jquery.min.js?6398SW:2
setTimeout (async)
(anonymous) @ jquery.min.js?6398SW:2
c @ jquery.min.js?6398SW:2
fireWith @ jquery.min.js?6398SW:2
fire @ jquery.min.js?6398SW:2
c @ jquery.min.js?6398SW:2
fireWith @ jquery.min.js?6398SW:2
ready @ jquery.min.js?6398SW:2
B @ jquery.min.js?6398SW:2

**Comment by Shalomco1123** [comment]
More info about error in logs
ERROR - 2023-04-16 12:53:18 --> Severity: error --> Exception: Class 'EA\Engine\Notifications\Email' not found /home/calbamab/domains/cal.bama.bio/public_html/easyappointments/application/libraries/Notifications.php 64
ERROR - 2023-04-16 13:44:16 --> Severity: Warning --> preg_match(): Compilation failed: range out of order in character class at offset 16 /home/calbamab/domains/cal.bama.bio/public_html/easyappointments/system/core/URI.php 346
ERROR - 2023-04-16 14:40:58 --> Severity: Warning --> preg_match(): Compilation failed: range out of order in character class at offset 16 /home/calbamab/domains/cal.bama.bio/public_html/easyappointments/system/core/URI.php 346

**Comment by alextselegidis** [comment]
Hello! 

Which PHP version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Shalomco1123** [comment]
PHP 7.4

**Comment by Shalomco1123** [comment]
Screen shot attached
![eab](https://user-images.githubusercontent.com/130908029/232448988-e6dd999c-dd97-4a52-a3e6-d588a0383393.png)

**Comment by Shalomco1123** [comment]
The same issue in console
![eab2](https://user-images.githubusercontent.com/130908029/232479067-364cf955-4dfd-4ac3-8983-bbf147f7f2e5.png)

**Comment by Shalomco1123** [comment]
The same issue in console
![eab2](https://user-images.githubusercontent.com/130908029/232479239-1f022352-190a-4623-9316-2c049a9ea67c.png)

**Comment by alextselegidis** [comment]
Hello! 

This is already a thread here, so I'll close this ticket for now, until we find reproduction steps: 

https://groups.google.com/g/easy-appointments/c/DJj96ZMHYbw

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
