### ISSUE TITLE
Google calendar API Scopes?

### ISSUE THREAD

**Issue by Shalomco1123** [alextselegidis/easyappointments#1359]
Hello,
When trying to enable google sync for provider the popup window notice that my app not verify so i take al the steps to fill the request but still cant complete this task because lack of Scopes: https://prnt.sc/FCplFXfdsiRW
what scopes permissions i need to request here...?

Thanks

**Comment by alextselegidis** [comment]
Hello! 

Already answered here: 

https://groups.google.com/g/easy-appointments/c/QgZ8gmQdM2k

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
