### ISSUE TITLE
Google translate confused by language attribute in html tag

### ISSUE THREAD

**Issue by oliverwelter** [alextselegidis/easyappointments#1360]
Independent of the selected language all websites include
`<html lang="en">`
which confuses browsers like Chrome providing automatic translation mechanisms using Google Translate.
E.g. when selecting language "German" Chrome is still detecting "English" as language and asks user if they want to translate from "English" to "German" which leads to interesting side effects like interpreting German words and English and translate them into other german words.

The underlying problem might be the hardcoded `<html lang="en">` in each view.

On solution is deactivating the application of Google Translate by using:

-  `<html translate="no">`
-  `<meta name="google" content="notranslate">`

Alternatively the attribute lang of the html tag needs to be set dependent on the currently configured language setting of the session.

**Comment by oliverwelter** [comment]
Using `<html translate="no">` avoids the application of translation but the Chrome browser still suggest translation but without any effect to the web page which is even more confusing for the user.

Therefor using `<meta name="google" content="notranslate">` causes more appropriate behavior by not suggesting any automatic translation.

**Comment by alextselegidis** [comment]
Hello!

Thanks for submitting this, I will fix this before the final 1.5 release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
