### ISSUE TITLE
Bug - Incorrect array key in Google.php (using v1.5.0-dev.3)

### ISSUE THREAD

**Issue by brackenhill-mob** [alextselegidis/easyappointments#1362]
Just learning my way around this fantastic app.

There is a code error in the sync code

`ERROR - 2023-05-06 12:25:02 --> Severity: Warning --> Undefined array key "is_unavailable" /srv/http/hosts/diary/application/controllers/Google.php 152`

If the key is changed to "is_unavailability" (as it used higher up in the code), syncing starts

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

You are right, the key was changed lately and all the places that refer to it need to be updated accordingly. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
