### ISSUE TITLE
Possible bug - Google Sync Fails with missing fields error (v1.5.0-dev3)

### ISSUE THREAD

**Issue by brackenhill-mob** [alextselegidis/easyappointments#1363]
Appointments sync from EA to Google but fail to sync Google appointments into EA with this error 

```
ERROR - 2023-05-06 12:30:02 --> Google - Sync completed with an error (provider ID "2"): Not all required fields are provided: Array
(
    [start_datetime] => 2023-07-04 09:00:00   
    [end_datetime] => 2023-07-04 17:00:00   
    [is_unavailability] => 1   
    [location] => Windsor   
    [notes] => Legoland with Boys    
    [id_users_provider] => 2   
    [id_google_calendar] => rjg9d70qa3p77bb4raddge5hn8   
    [id_users_customer] =>   
    [id_services] =>   
)
```

This appointment is being pulled from my Google calendar.

As a new user coming from another calendar app, I am used to entering appointments, using Thunderbird and Gmail, in my bookings calendar so that people making appointments can't book that slot. I assume that EA is meant to work the same way. Am I correct? 

So... should EA not ignore calendar elements that are not present on the Google calendar side?

**Comment by brackenhill-mob** [comment]
Update

Just tried to delete an EA appointment in Google Calendar app and the sync fails. I assume that this is because the EA one was created after the Google one above and so the error that one throws is cancelling the rest of the incoming sync.

This is going to cause me major issues as I have a lot of pre-existing appointments to import into EA.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

Could you please write back here with the version you are using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

Thanks for the feedback, I will take a look and let you know in case I find something. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by jubisa** [comment]
I am also experiencing a 500 error, in the last step of the initial calendar synchronization. I click on "Enable Sync", I go through all the steps and then, after I click on "enable" in the last Google confirmation screen I get 500 error. The URL that fails is this. I use example.com to depersonalize it:

https://www.example.com/appointments/index.php/google/oauth_callback?code=XXXXXXX&scope=https://www.googleapis.com/auth/calendar

By the ay, Alex, your product is amazing and I cannot wait for the final 1.5 version.

**Comment by alextselegidis** [comment]
Thanks for the feedback @jubisa! I'll check this and report back. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@brackenhill-mob Fixed on develop

@jubisa The error you are getting is different than the on of this ticket. Feel free to open a new issue with the error description so that we take it from there ;) 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
