### ISSUE TITLE
enhance google-calendar-sync.md

### ISSUE THREAD

**Issue by hesco** [alextselegidis/easyappointments#1364]
At least add missing links to the documentation for google-calendar-sync.md.  
Work through the steps, and clarify wherever appropriate.

**Comment by alextselegidis** [comment]
Hello! 

I am working on an updated documentation for developers so the activation of the google sync feature becomes easier to follow. 

This will all be hosted on the developers.easyappointments.org page, so stay tuned with our social media for the site update release. 


<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by hesco** [comment]
Thank you.  I was unable to successfully test it for my own installation.  Would love to be able to do so by the time the potential client who requested this circles back ready to consider signing on.
