### ISSUE TITLE
Sync all the providers without errors, when the user clicks on the "sync" button and "all" is selected in the calendar page.

### ISSUE THREAD

**Issue by brackenhill-mob** [alextselegidis/easyappointments#1365]
EA Version 1.5.0-dev.3

Another Google syncing bug. I was syncing after deleting an appointment in my Google Calendar using the online Google Calendar app.

```ERROR - 2023-05-12 16:29:55 --> Google - Sync completed with an error (provider ID "all"): Providers_model::find(): Argument #1 ($provider_id) must be of type int, string given, called in /srv/http/hosts/diary/application/controllers/Google.php on line 70```

The MySQL DB data table shows the ID as an int.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for sharing this, it will be fixed!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by brackenhill-mob** [comment]
Still present in v1.5.0-dev4

**Comment by alextselegidis** [comment]
Hello! 

Yes, this issue hasn't be worked on. 

I will update this in the next couple of days.
 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
