### ISSUE TITLE
ENHANCEMENT - Mail Server Settings to config.php (code supplied)

### ISSUE THREAD

**Issue by brackenhill-mob** [alextselegidis/easyappointments#1366]
EA version 1.5.0-dev.3

Move email server settings into \<install folder\>/config.php

I don't know how Github works with PRs etc, so I'll post my code changes into replies to this message.

HTH

**Comment by brackenhill-mob** [comment]
config.php

Add the following lines:

```    //
    // EMAIL SETTINGS
    //
    const EMAIL_PROTOCOL        = 'mail'; // mail or smtp
    const EMAIL_MAILTYPE        = 'html'; // html or text
    const EMAIL_SMTP_DEBUG      = '0';    // 0 or 1
    const EMAIL_SMTP_AUTH       = TRUE;   // TRUE or FALSE for anonymous relay
    const EMAIL_SMTP_HOST       = '';
    const EMAIL_SMTP_USER       = '';
    const EMAIL_SMTP_PASSWORD   = '';
    const EMAIL_SMTP_CRYPTO     = 'ssl';  // ssl or tls
    const EMAIL_SMTP_PORT       = 25;
```

**Comment by brackenhill-mob** [comment]
\<install folder\>/application/config/email.php

Replace whole file with this block

```
<?php defined('BASEPATH') or exit('No direct script access allowed');

// Add custom values by settings them to the $config array.
// Example: $config['smtp_host'] = 'smtp.gmail.com';
// @link https://codeigniter.com/user_guide/libraries/email.html

$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = Config::EMAIL_PROTOCOL;
$config['mailtype'] = Config::EMAIL_MAILTYPE;
$config['smtp_debug'] = Config::EMAIL_SMTP_DEBUG;
$config['smtp_auth'] = Config::EMAIL_SMTP_AUTH;
$config['smtp_host'] = Config::EMAIL_SMTP_HOST;
$config['smtp_user'] = Config::EMAIL_SMTP_USER;
$config['smtp_pass'] = Config::EMAIL_SMTP_PASSWORD;
$config['smtp_crypto'] = Config::EMAIL_SMTP_CRYPTO;
$config['smtp_port'] = Config::EMAIL_SMTP_PORT;
```

**Comment by alextselegidis** [comment]
Hello! 

Thanks for providing those! 

In the past I had already thought about doing this but the original reason of the root config.php was to be a very basic and simple place for data to reside. 

For the mail server settings I am actually planning to create a new page in the UI to allow the user to override them without changing the server files.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
