### ISSUE TITLE
Missing support for ARM host

### ISSUE THREAD

**Issue by guba91** [alextselegidis/easyappointments#1367]
Hi, i'm trying to run on a arm machine with docker.

`no matching manifest for linux/arm64/v8 in the manifest list entries`

need to add support for arm64 :)
Thanks!

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this issue. 

I guess you tried to run the docker configuration of the repository, am I right? 

If so, which branch did you use? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
