### ISSUE TITLE
Invalid responsive behavior in frontend booking wizard (step #2 - appointment date & time).

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#137]
The appointment hours will not be displayed correctly in a certain viewport width as shown in the screenshot below. 

![ea-responsive-issue](https://cloud.githubusercontent.com/assets/4527441/13555071/9b6ca4bc-e3b7-11e5-8c4e-658cf8b145cd.png)

**Comment by alextselegidis** [comment]
Same in customer-details form: 

![ea-responsive-issue-2](https://cloud.githubusercontent.com/assets/4527441/13555086/c5d2d834-e3b7-11e5-920d-4949bae63499.png)

**Comment by martinhalfer** [comment]
I fixed the behavior in my installation by changing wizard frame 2 and 3 in book.php from`

`<div class="frame-content row">
                            <div class="col-md-6">`
to
`<div class="frame-content row">
                            <div class="col-sm-6">`

My guess is that the selector in frontend css: @media(max-width:768px) and bootstrap col-md-6  (992px) class creates the invalid behavior in viewports between 768px and 992px.
