### ISSUE TITLE
Set the FullCalendar locale property.

### ISSUE THREAD

**Issue by eltorio** [alextselegidis/easyappointments#1372]
On the dev branch I have the Fullcalendar not localized.
My first workaround is to force `locale: 'fr'`

```diff
diff --git a/assets/js/utils/calendar_default_view.js b/assets/js/utils/calendar_default_view.js
index cd28ca89..7de760a6 100755
--- a/assets/js/utils/calendar_default_view.js
+++ b/assets/js/utils/calendar_default_view.js
@@ -1451,6 +1451,7 @@ App.Utils.CalendarDefaultView = (function () {
 
         // Initialize page calendar
         fullCalendar = new FullCalendar.Calendar($calendar[0], {
+            locale: 'fr',
             initialView,
             nowIndicator: true,
             height: getCalendarHeight(),
diff --git a/assets/js/utils/calendar_table_view.js b/assets/js/utils/calendar_table_view.js
index 29b49279..8c3a2a0d 100755
--- a/assets/js/utils/calendar_table_view.js
+++ b/assets/js/utils/calendar_table_view.js
@@ -676,6 +676,7 @@ App.Utils.CalendarTableView = (function () {
         const firstWeekdayNumber = App.Utils.Date.getWeekdayId(firstWeekday);
 
         const fullCalendar = new FullCalendar.Calendar($wrapper[0], {
+            locale: 'fr',
             initialView: 'timeGridDay',
             nowIndicator: true,
             height: getCalendarHeight(),
```

But it might be better to use Fullcalendar alllocales or to dymically sets the locale

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this! I will merge and release this accordingly with the next package. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

This is merged in develop. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
