### ISSUE TITLE
build docker container on master fails.

### ISSUE THREAD

**Issue by Stainless5166** [alextselegidis/easyappointments#1377]
Good morning and happy Monday, just ran the docker build on the server Dockerfile on Master and got the following error.

 => ERROR [4/5] RUN pecl install xdebug     && docker-php-ext-enable xdebug                                                                                                                                  2.1s
------
 > [4/5] RUN pecl install xdebug     && docker-php-ext-enable xdebug:
#0 2.066 pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
#0 2.066 No valid packages found
#0 2.066 install failed
------
Dockerfile:14
--------------------
  13 |
  14 | >>> RUN pecl install xdebug \
  15 | >>>     && docker-php-ext-enable xdebug
  16 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pecl install xdebug     && docker-php-ext-enable xdebug" did not complete successfully: exit code: 1

**Comment by alextselegidis** [comment]
Hello! 

Please try the docker set up on develop branch, as it has the updated configuration. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
