### ISSUE TITLE
[Feature Request] Draggable slider for appointment duration

### ISSUE THREAD

**Issue by noor8380** [alextselegidis/easyappointments#138]
It would be great if there is a draggable slider for choosing the duration of the appointment. 

Some can choose one hour and others can choose half an hour or in multiples of the unit time.

**Comment by alextselegidis** [comment]
Do you mean in frontend or in backend?

**Comment by noor8380** [comment]
In the frontend.

**Comment by alextselegidis** [comment]
I'm pretty sure that the majority of the users will need a pre-configured service duration because otherswise the plan get go out of control without even noticing. Thus I will not implement this feature. 

Thanks for posting though :+1:

**Comment by emanwebdev** [comment]
@noor8380 mentioning HTML5  <input type="range">
