### ISSUE TITLE
instalação

### ISSUE THREAD

**Issue by reginaldoamartins** [alextselegidis/easyappointments#1385]
Nova versao não instala.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for your message. 

For your best support please write your messages in English. 

Also please provide more information about the problem.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
