### ISSUE TITLE
UTC default timezone

### ISSUE THREAD

**Issue by patrickus33** [alextselegidis/easyappointments#1386]
The problem with UTC is that it's the default timezone and can't be set.
It should be possible to select the default timezone like for langage.

**Comment by patrickus33** [comment]
Hello,

Yes, I did see this possibility.
It's just to avoid errors when creating new users.
In general, all users are going to be on the same timezone, so if we could set this timezone as the default, that would be great.

**Comment by alextselegidis** [comment]
I see the point and also think that this might actually benefit more people. 

I will close this in favor of #1390. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
