### ISSUE TITLE
Unable to choose the last time slot

### ISSUE THREAD

**Issue by jhonfredi** [alextselegidis/easyappointments#1392]
When the slot time does not match the duration of the service, the calendar do not show the last time slot out of the range, that is ok, but when I selected the last available time slot, it just return an alert with "undefined" description, according to the configuration it should let me select the last time slot.

This is a service with duration: 45 minutes, slot step: 15 minutes, the connection end time is 06:00 pm
![image](https://github.com/alextselegidis/easyappointments/assets/5972774/ea48e0c4-5325-4d64-8bd0-97020e445e5a)

Thanks

**Comment by alextselegidis** [comment]
Hello!

Judging from the user interface, this does not look like the original Easy!Appointments application. 

Please make sure you are using the app from here: 

https://easyappointments.org/

Feel free to open a new ticket in case you have a problem with our app :)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
