### ISSUE TITLE
Matomo's analytics support send only data to site ID 1

### ISSUE THREAD

**Issue by billmetangmo** [alextselegidis/easyappointments#1395]
Hello,

Thanks for sharing this awesome work with the community.

Currently, when activating the Matomo integration, we can just specify the hostname URL.
This cause data to be sent to idsite=1. This is OK if you have one instance dedicated to easyappointments.
However, if you use one Matomo instance to manage multiple websites.
The tracing data are sent to an existing website with idsite=1.

Possible solution:
In addition to Matomo URL in the integration UI, we can add the idsite number where you want data to be send in.

**Comment by billmetangmo** [comment]
Hello @alextselegidis ,

I don't see idsite in the setting pages ?
It's just the URL that we can set

**Comment by alextselegidis** [comment]
Hello! 

I checked this again and you are totally right, we need a second setting for Matomo for the siteid. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
