### ISSUE TITLE
cookie notice blocked by Brave and then display nothing

### ISSUE THREAD

**Issue by antsfiles** [alextselegidis/easyappointments#1398]
Hello,
If I active the "cookie notice", the browser Brave blocks the script "cookieconsent.js" and then, you have nothing displayed in the booking page.

**Comment by iriikoad** [comment]
I see in the network tab in developer mode "blocked". If I deactivate Brave protection it works again.. I'll see if I can do a screenshot.
it's on Ubuntu 23.04.

**Comment by iriikoad** [comment]
Brave v1.57.47 
![easyppointments-block-cookiecontent](https://github.com/alextselegidis/easyappointments/assets/46171505/4ee5b84f-1349-4dd0-ab7f-65967ae57f60)
![easyppointments-block-cookiecontent2](https://github.com/alextselegidis/easyappointments/assets/46171505/998dd26f-30e8-4b9d-baa3-e609e6e80424)
![easyppointments-block-cookiecontent3](https://github.com/alextselegidis/easyappointments/assets/46171505/9b6d805f-e83f-463f-88a2-ba1f3af1fd9b)
![easyppointments-block-cookiecontent4](https://github.com/alextselegidis/easyappointments/assets/46171505/8a94ac8b-f258-42db-855a-49f65717d498)
![easyppointments-block-cookiecontent5](https://github.com/alextselegidis/easyappointments/assets/46171505/600a828e-7fd1-4275-b778-516cee7041b1)

It's considered as tracker.
