### ISSUE TITLE
Feature request: One resource, multiple vendors

### ISSUE THREAD

**Issue by JiroMusik** [alextselegidis/easyappointments#1400]
Hi, I got a feature request, maybe you find a way to integrate that in a simple form:
I got a room (music studio) which can be booked for the following:
Booking by my clients for a single music session (they will be there alone)
Booking by anyone (public) for a Co-Session with a provider on the same room.

Currently I got two Providers - the room and the person itself - to allow synchronizing with 2 different Google calendars - but the room could be booked for both events at the same time.
I would love to have one resource calendar (the room) and two (or more) different google calendars (room and provider(n) calendar)

**Comment by alextselegidis** [comment]
Hello! 

This is a great feature addition indeed and is planned for the upcoming SaaS versions of the app (at the time being) 

For this I will need to close this ticket (for now at least)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by JiroMusik** [comment]
Wir sind quasi Nachbarn, gib mir dieses Feature in der Self-Hosted Version, bitte :(
