### ISSUE TITLE
Send the appointment notifications to the language of the recipient instead of the currently logged in user language 

### ISSUE THREAD

**Issue by iriikoad** [alextselegidis/easyappointments#1402]
If the client is french, he receives a french email : OK
If the provider session is in english, when he modify the rdv, the email sent to the client is in english: the language used to create the email is not the language of the client bu the language of the session.

**Comment by alextselegidis** [comment]
Hello! 

I'm not sure if that is wrong, but I guess in that case we can set the default `config.php` language value to all newly created customers or allow the user to define the language from the appointments modal. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
