### ISSUE TITLE
Failed to initialize storage module

### ISSUE THREAD

**Issue by ionesculiviucristian** [alextselegidis/easyappointments#1405]
Hello. I'm having this warning when accessing the app:
```
A PHP ERROR WAS ENCOUNTERED
SEVERITY
Warning

MESSAGE
session_start(): Failed to initialize storage module: user (path: /var/www/html/application/config/../../storage/sessions)

FILENAME
Session/Session.php

LINE NUMBER
127
```
If I change the permissions to 0777 for storage it works (or point to /tmp in config).

I'm on version: dev-1.5.0.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

It is now patched. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
