### ISSUE TITLE
Last Name mandatory field bug

### ISSUE THREAD

**Issue by besendorf** [alextselegidis/easyappointments#1409]
In the administrator settings I set the Last name field to not mandatory. In the user frontend it is also not marked with * as mandatory. However in the next step of booking an appointment I get this error message:
```
Not all required fields are provided: Array ( [first_name] => Janik [last_name] => [email] => jb@reporter-ohne-grenzen.de [ip] => 213.235.133.39 [type] => privacy-policy ) 
```

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this, it's fixed already. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
