### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Forsskieken** [alextselegidis/easyappointments#1413]
Hi There,

What a great product I'm trying the 1.5.dev4 out.

1. Is there a chance we can adapt pm/am to 24u in the global settings?
    FOUND IT

2. It would be nice that we set a Preference for Providers if a booker does't choose one.
    Freddy wants to book a appointment and he doesn't have any preference for ether Michael, Barbara or  Tina.
    If all 3 are availabl e the program would than book per preference set by the administrator.
 
3. Can we delete the time zone in the views for the clients?

**Comment by alextselegidis** [comment]
Hello! 

Glad to know that you liked the version so far. 

Regarding the preference there's the any-provider setting that will let the app pick a provider for the client (the one with the most free time)

For point 3, that will be done in a future release as 1.5 has a feature freeze
