### ISSUE TITLE
Normal Kalendar all vieuw

### ISSUE THREAD

**Issue by Forsskieken** [alextselegidis/easyappointments#1416]
Hi,
The normal kalendar view only shows no events.
As a admin or provider I'll have to choose a provider to vieuw possible events.
Is there a possibility to see all bokked events in kalendar view ALL?

Kind regards

**Comment by alextselegidis** [comment]
Hello! 

Yes this is part of the upcoming 1.5 release, which will be released in a couple of days. 

Stay tuned for more updates 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
