### ISSUE TITLE
calendar > table view > service [Service filter work after code fix]

### ISSUE THREAD

**Issue by rabongithub** [alextselegidis/easyappointments#1417]
Hello, 

version 1.5.0-dev.4

shows all services when nothing selected in Service. but even if one or many selected in Service, all disappear from calendar. Could somebody else confirm about it.

Thanks and Regards.

**Comment by MoDuLah** [comment]
Works fine on my end.

**Comment by rabongithub** [comment]
Thanks a lot Alex. Now "Service filter" working in table view.
