### ISSUE TITLE
Do not allow a customer to book the same hours multiple times

### ISSUE THREAD

**Issue by radar155** [alextselegidis/easyappointments#1420]
I'm using version 1.5.0-dev.4

A service with more than 1 attendants can be booked by the same customer multiple times (at the same day and time).

When I say "the same customer ", I mean a customer that's using the same email address in different booking attempts.

I guess this shoud be prevented.

**Comment by alextselegidis** [comment]
Hello! 

This is an interesting topic as customers might need to book for multiple people that accompany them. 

But in general it makes more sense that they do this with a different name and email address. 

For that I just added a new check that will not allow them to book, if they have booked already. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rabongithub** [comment]
Hello!

This is an interesting but fact is that same customer reserve for own self and also for others with own name and email.

**Comment by alextselegidis** [comment]
Hello! 

That is true indeed, but they should use different input for this.

You can disable customer matching by making email an optional field (starting from 1.5) 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rabongithub** [comment]
Hello! 

How about to show Warning message  to customer that This time already reserved for you, do you want to continue to reserve (with condition YES / NO) ?

**Comment by alextselegidis** [comment]
Hello! 

That might help a little bit, but still I find this is more like an edge case. 

I mean for the most part, customers know they have a booking already. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
