### ISSUE TITLE
Appointment Month Picker

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1422]
I'm using version 1.5.0-dev.4.

The month picker is not dynamic.
Theme selected: Any
![image](https://github.com/alextselegidis/easyappointments/assets/7404959/1a3ee72d-e23f-4673-b6a1-1367c6fe145c)

I have fixed the issue on my end by removing the material_green.min.css from application/views/layouts/backend_layout.php

**Comment by alextselegidis** [comment]
Thanks for reporting this, I've updated the company_color_style.php file to style this dropdown 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by MoDuLah** [comment]
@alextselegidis Same applies to Existing Customer Pick on button hovering.

**Comment by alextselegidis** [comment]
Right I had fixed that one too
