### ISSUE TITLE
Calendar > Month View

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1424]
Can someone explain what is that #/1? Shouldn't be just the day abbreviation?
![image](https://github.com/alextselegidis/easyappointments/assets/7404959/a64a928a-e758-42f9-89ae-89e71dee14de)

**Comment by alextselegidis** [comment]
Hello! 

This is already fixed on develop and will be shipped with the upcoming Alpha release in a couple of days: 

![image](https://github.com/alextselegidis/easyappointments/assets/4527441/71b9915f-1d0f-48d2-9d41-92ffa0334edf)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rabongithub** [comment]
Hello!

I have in the SETTINGS > GENERAL SETTINGS > LOCALIZATION > Date Format : DMY. I have taken off // dayHeaderFormat: columnFormat,  now in my calendar Week view shows: Wed 11/1  (does not show anymore like: Wed 1/11 )
