### ISSUE TITLE
Invalid Requirement?

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1426]
views/components/appointments_modal.php

                                <div class="mb-3">
                                    <label for="customer-notes" class="form-label">
                                        <?= lang('notes') ?>
                                        <?php if ($require_zip_code): ?>
                                            <span class="text-danger">*</span>
                                        <?php endif ?>
                                    </label>
                                    <textarea id="customer-notes" rows="2"
                                              class="<?= $require_zip_code ? 'required' : '' ?> form-control"></textarea>
                                </div>

Shouldn't it be $require_notes instead?

**Comment by alextselegidis** [comment]
Hello! 

You are totally right, this is fixed now. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
