### ISSUE TITLE
Add Services Colorpicker Bug

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1427]
When you add a service the colour picker is disabled.
It only becomes enabled after you have saved the services and went back to edit it.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this, that's a minor bug that'll be fixed soon. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
