### ISSUE TITLE
Manual Booking Bug

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1428]
I will give an example easy to recreate.
You have an appointment (A) at 9:30 - 10:30 with provider X
And from calendar you add a new appointment (B) at 9:15 - 10:00. You still have the option to choose provider X.

**Comment by rabongithub** [comment]
yes it is. when you book by frontend, ok no overlapping. but manual adding at backend, you have to check yourself, is it overlapping or no. but think this way, you have more control, maybe you are a teacher and you want to book for many at the same time.

**Comment by MoDuLah** [comment]
I think that if you are a teacher you can just increase the Attendants on
the services page.

**Comment by rabongithub** [comment]
yes that should be more logical. i just found out about it two days before. have to fix this.
