### ISSUE TITLE
existing-customers-list:hover non dynamic 

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1429]
Probably like the dropdown menu this one dodged the business colour settings.
![Screenshot 2023-10-16 143603](https://github.com/alextselegidis/easyappointments/assets/7404959/171446ff-2fa1-43be-9fb9-082b68267415)

**Comment by alextselegidis** [comment]
Good catch!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
