### ISSUE TITLE
Encryption key in your config file???

### ISSUE THREAD

**Issue by rillzp** [alextselegidis/easyappointments#143]
I've just downloaded a Easyappointments

Everything looks very great and i had no problem when setting up the database ETC, But when im trying to open the site i get this error message

"In order to use the Session class you are required to set an encryption key in your config file.

There is nothing about encryotion key in the config file and the tutorial dosn't mention anything about it..
I've been googling around abit and tried adding code like $config['encryption_key'] = "YOUR KEY"; but no luck.. I really dont know what to do here. please point me in the right direction!

Thanks in advance

Best regards

**Comment by alextselegidis** [comment]
Hello! Make sure that you have the mcrypt extension installed and then try to add an encryption key to the /application/config/config.php. These are the following links from the CodeIgniter documentation (in case you haven't seen them yet): 

- https://ellislab.com/codeigniter/user-guide/libraries/sessions.html
- https://ellislab.com/codeigniter/user-guide/libraries/encryption.html
