### ISSUE TITLE
SERVICES > DETAILS > Attendants Number (Booking does not check/work. version 1.5.0-dev.4)

### ISSUE THREAD

**Issue by rabongithub** [alextselegidis/easyappointments#1430]
Hello,

version 1.5.0-dev.4

Service having 1 Attendant and that Service  attached to multiple provider. frontend booking let to make appointment for the same date and time by another provider (when having 1 Attendant, it should not make the same time available for that date to reserve for other provider )

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this issue. 

If the attendants number is 1 and two different customers book two different providers, then there is no actual conflict in the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rabongithub** [comment]
Hello! 

Thanks for reply and bit more .......!

One (not more than one) customer can be served at a time on the spot, but having many providers attached to the same service, what to do ! according to E!A - means I have to  create similar service (lets say service time 30 minutes) multiple times and attach individually to each provider. this will confuse also customer when booking, why similar service written multiple times, and also for admin at the backend so much editing and not so much logical.

**Comment by alextselegidis** [comment]
Hello! 

I'm not sure I can follow your example. 

Could you please elaborate? 

Thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by rabongithub** [comment]
Hello! Thank you again for checking out.

Tattoo studio. there is only one chair (means that place cannot serve more than one customer at a time) in the studio. but there are many Tattoo artist. so in EA, I have created service and multiple providers attached to that service.  lets say customer have booked service 8.11.2023 from 10am to 12 am. problem is , some another customer can book also on the same time 8.11.2023 from 10am to 12 am. but that studio cannot serve two customers at the same time. I do not find any options in EA to prevent such.

Is there any in your EA, you know better ? 

I thought to create in EA > SERVICES > DETAILS > Add Provider's Number - how many provider can serve that service at the same time. if null means EA will work how it is now but if it has example:  1 (Provider's Number), EA will not allow to reserve the same time for another provider. How to implement ... . some code  will be greatly appreciated.   Thanks & Regards.
