### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by deepakkuma24** [alextselegidis/easyappointments#1433]
Hello I  submit 3 vulnerability on huntr. huntr dev is a security community that finds and fixes vulnerability in oss. please go and check vulnerability on huntr 
1. https://huntr.com/bounties/0dc59dcd-6504-48fd-8290-8c8b01a44dce/
2.  https://huntr.com/bounties/495c2356-f5a8-4e80-8614-70033bc9abf5/
3. https://huntr.com/bounties/0f4eba10-c6c3-4e5a-96a5-85b0923ee064/

**Comment by alextselegidis** [comment]
Hello! 

Thanks for post this, I will check huntr.dev directly. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by deepakkuma24** [comment]
Still open all vulnerabilities. please fix its on https://huntr.com/
