### ISSUE TITLE
WeekNumber Not inlined

### ISSUE THREAD

**Issue by rabongithub** [alextselegidis/easyappointments#1436]
Hello!

When enabled WeekNumber .

Regards.
![week number not inlined](https://github.com/alextselegidis/easyappointments/assets/20057838/8954b647-a1f7-4ae3-b423-3bc6c911962e)

**Comment by rabongithub** [comment]
booking.js
App.Utils.UI.initializeDatepicker($selectDate, {
            weekNumbers: true,
            inline: true,
            minDate: moment().subtract(1, 'day').set({hours: 23, minutes: 59, seconds: 59}).toDate(),
            maxDate: moment().add(vars('future_booking_limit'), 'days').toDate(),
            onChange: (selectedDates) => {
                App.Http.Booking.getAvailableHours(moment(selectedDates[0]).format('YYYY-MM-DD'));
                updateConfirmFrame();
            },

**Comment by alextselegidis** [comment]
That would require some additional style in the general.scss file 

Will fix once week number display is supported in the app 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
