### ISSUE TITLE
"not available" not working over multiple days

### ISSUE THREAD

**Issue by sOUTHX1337** [alextselegidis/easyappointments#1443]
when adding a "not available" block it only remote the first day from the selection

if i block for example from 01.01.2024 till 31.01.2024 only the first day is blocked

**Comment by rabongithub** [comment]
01.01.2024 till 31.01.2023  (either 01.01.2023 till 31.01.2023 ) ?

**Comment by sOUTHX1337** [comment]
sorry, typo - fixed

**Comment by alextselegidis** [comment]
Hello! 

Did you try this with the latest version too (1.5-dev.4)? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I just checked again and could not reproduce this 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
