### ISSUE TITLE
Enable 24/7 working plan

### ISSUE THREAD

**Issue by tboHammu** [alextselegidis/easyappointments#1451]
Hi,

we'd like to use EasyAppointments for a rental service that is open 24/7. Is it possible to implement this somehow? Setting working plan from 00:00 to 23:59 does not allow overnight appointments, 00:00 to 00:00 does not allow any appointments at all.

**Comment by rabongithub** [comment]
Setting working plan like 00:01 to 23:59 ?

**Comment by tboHammu** [comment]
> Setting working plan like 00:01 to 23:59 ?
I'm pretty sure we tried that and it does not work as we'd like.

**Comment by alextselegidis** [comment]
Hello! 

Unfortunately there is currently no support for cross-day booking from the booking page. 

This is something we will need to work on. 

Duplicate: 

https://github.com/alextselegidis/easyappointments/issues/1432

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
