### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by r-a-cristian-93** [alextselegidis/easyappointments#1459]
Phone number input field of customer information form has no validation, you can write anything.

It should be expected to restrict input only to numbers.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for the ticket. 

There is already soft phone number validation added to 1.5 

https://github.com/alextselegidis/easyappointments/blob/develop/assets/js/utils/validation.js#L39

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
