### ISSUE TITLE
Installation troubleshooting

### ISSUE THREAD

**Issue by NadMat** [alextselegidis/easyappointments#146]
Please, be kind. I really don't know much about programming!
I followed carefulley every step of the installation as described, after making sure that the web server I'm using has all the needed Apache 2.4, PHP etc...

When I get to the part where I reach the intallation's folder to begin the configuration process, I get this message:

"The server can not find the requested page:
 host.com/.../public_html/easy/index.php/installation/index (port 80)"

Anyone can help?
Thank you.

**Comment by alextselegidis** [comment]
Hello, I can tell that the `BASE_URL` value in your config.php file is not correct. You will have to enter the HTTP URL that points to your website and not the path in your server. 

This field expects something like `http://website.com/easyappointments-directory`.

**Comment by NadMat** [comment]
thought I had it correct!
I'll triple-check it then! ;-)
Thanks
