### ISSUE TITLE
Add from email/name and reply-to settings in the email.php configuration file 

### ISSUE THREAD

**Issue by Thomas-git** [alextselegidis/easyappointments#1465]
When sending an email, my provider don’t allow to override the From address. So sending an email with my company email wont work.
I had to set company email to the mailer daemon address for mail notification to work.
What would be great is to have:
A 'from' setting in config/email.php
And company email/company name used in 'Reply to' field.

It should be easy enough for me to add. I just need help for available classes and appropriate files.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

That's a good hint as I've seen this happen again in the past. 

Will add this to the upcoming version. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

This one just got pushed on `develop`. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Thomas-git** [comment]
Great thank you!
