### ISSUE TITLE
Build Project Assets won't run

### ISSUE THREAD

**Issue by ReinerNippes** [alextselegidis/easyappointments#1467]
Hi Alex, 

with [commit c6aa24](https://github.com/alextselegidis/easyappointments/commit/c6aa24c4ec6f152b72c92048f28ba059519d92aa) you create assets/vendor/index.html but in the [start-container file there is a check](https://github.com/alextselegidis/easyappointments/blob/develop/docker/php-fpm/start-container#L16) if the directoy assets/vendor exists. So I guess the npx gulp compile will never be executed. 

Or did I miss something?

Regards,
Reiner

**Comment by alextselegidis** [comment]
Hello! 

You are totally right,I just ignored the entire assets/vendor directory

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
