### ISSUE TITLE
When frontend application loading it showing following error

### ISSUE THREAD

**Issue by santu-git** [alextselegidis/easyappointments#147]
The operation could not complete due to unexpected issues.

Details
DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

**Comment by alextselegidis** [comment]
Hello! This is a very common PHP problem but the solution is easy. Take a look at the following StackOverflow post: 

http://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings
