### ISSUE TITLE
Add entrys via API

### ISSUE THREAD

**Issue by Jumbo125** [alextselegidis/easyappointments#1470]
Profilfoto von Andreas Rottmann
Andreas Rottmann
12:02 (vor 23 Minuten) 
an Easy!Appointments - Support Group
Hello
i'm looking for a Appointment app and found this great project!

My problem: i need to set a specific time range for the bookings. For e.g. the user need to set a specific indivudal date. The booking range is a calculated time of this entry. 

okay, that's really specific. so i would create a full booking form. after the user fill in all values, the datepicker append on the end of the form and contains the timerange

The submit button only works, when all fileds are filled.  
now i need to book the termin with the url api like:
url/appointements/.....?firstname=xxx&lastname=xxx&specific_date=xxxx&email=xxxxx&time=xxxx&date=xxxxx

is this possible?
thank you a lot

**Comment by alextselegidis** [comment]
Hello! 

Thanks for your message. 

Already replied here:

https://groups.google.com/g/easy-appointments/c/GM2KjFb-GPc

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
