### ISSUE TITLE
Back-End Booking Color Correspondance

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1472]
While on back-end manually setting up an appointment, it would be nice when you change service to give the pre-selected color the services have when the customer books through the form.

I've been trying a few things to make it work but with no luck.

Hope this is implemented.

Kind regards.

**Comment by alextselegidis** [comment]
Hello! 

This is already implemented in the available 1.5 state (develop branch)

You may check it in there

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
