### ISSUE TITLE
BUG Appointment Modal

### ISSUE THREAD

**Issue by MoDuLah** [alextselegidis/easyappointments#1473]
Instead of highlighting the missing required field (which i know is provider's notes it gives this error instead.
![image](https://github.com/alextselegidis/easyappointments/assets/7404959/f822ce41-b9c5-43d8-a9de-cf76dfe36f5c)

Also the provider's notes don't get a dynamic red * when required.
![image](https://github.com/alextselegidis/easyappointments/assets/7404959/563f88f1-753b-4e58-8cc5-efd1c6f97687)

**Comment by alextselegidis** [comment]
Hello! 

Thanks, I will take a closer look into this one 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ToT-2020-PA** [comment]
Hello, I have a problem with Easy. When I create the schedule and click the final button to confirm. It sits there waiting, takes a while to respond and when it comes up with an Apache error 443. What could be happening. Since the page has an ssl certificate...

**Comment by alextselegidis** [comment]
@ToT-2020-PA If you see constant loading in the screen, this means that there is an error that is not visible on screen. 

Check out this guide for further troubleshooting info: 

https://easyappointments.org/2021/05/31/how-to-troubleshoot-easyappointments/

Post any errors here so that we can checkk this further

**Comment by alextselegidis** [comment]
The original issue of this ticket is now resolved. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
