### ISSUE TITLE
Enhancement of Webhook Payload with Detailed Information for WhatsApp Integration

### ISSUE THREAD

**Issue by alanpereiracoelho** [alextselegidis/easyappointments#1475]
Hello EasyAppointments Team,

I am currently utilizing EasyAppointments and am very impressed with the tool. However, I've encountered a limitation regarding the data provided by webhooks, which affects the integration I am developing for sending notifications via WhatsApp to both clients and service providers.
Issue:

The webhooks from EasyAppointments, upon creation of a new appointment, only send the IDs related to the appointment, service provider, and client. This limits the ability to send personalized WhatsApp notifications, as crucial information such as phone numbers is not included.
Current Webhook Data:

The data sent by the webhook currently includes only numerical identifiers and basic appointment details, as exemplified below:

json

{
  "id": 5,
  "create_datetime": "2024-03-12 14:13:06",
  "update_datetime": "2024-03-12 14:33:18",
  "start_datetime": "2024-03-14 09:00:00",
  "end_datetime": "2024-03-14 13:00:00",
  "status": "Under Review",
  "id_users_provider": 4,
  "id_users_customer": 8,
  "id_services": 2
}

Proposed Solution:

It would be ideal if the webhooks could transmit more detailed information, similar to what is sent via email when an appointment is created. Specifically, including the phone numbers of both the client and the service provider in the webhook payload would facilitate the automation of WhatsApp notifications, improving communication and the overall experience for both clients and providers.
Justification:

Incorporating this information into the webhooks would eliminate the need for additional queries to obtain contact details, streamlining the integration process and providing a more seamless and automated user experience.

Thank you for your attention, and I am available to discuss this request further.

Best regards,

Alan

**Comment by alextselegidis** [comment]
Hello! 

I will add this to the implementation for the next package. 

For now you can call the API to fetch the required information 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
