### ISSUE TITLE
Small change to booking.js output

### ISSUE THREAD

**Issue by tm8544** [alextselegidis/easyappointments#1477]
This is not an error report but a suggestion to make a small change to output.

(https://github.com/alextselegidis/easyappointments/blob/ebe8f84ba18809efeec3f0dd76095ff119968ba2/assets/js/pages/booking.js#L847)
-   'text': '[' + lang('duration') + ' ' + service.duration + ' ' + lang('minutes') + ']' 
+  'text': '[' + lang('duration') + ': ' + service.duration + ' ' + lang('minutes') + ']' 
                
                
https://github.com/alextselegidis/easyappointments/blob/ebe8f84ba18809efeec3f0dd76095ff119968ba2/assets/js/pages/booking.js#L853                                
-  'text': '[' + lang('price') + ' ' + service.price + ' ' + service.currency + ']'
+  'text': '[' + lang('price') + ': ' + service.price + ' ' + service.currency + ']'
                                
https://github.com/alextselegidis/easyappointments/blob/ebe8f84ba18809efeec3f0dd76095ff119968ba2/assets/js/pages/booking.js#L859
-  'text': '[' + lang('location') + ' ' + service.location + ']'
+ 'text': '[' + lang('location') + ': ' + service.location + ']'

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this, but the display has already changed for the upcoming 1.5 release (see develop branch). 

Cheers!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
