### ISSUE TITLE
Getting blank page after installation.

### ISSUE THREAD

**Issue by maximusmusterus1** [alextselegidis/easyappointments#148]
Hi there,

I followed the installation guide and did the following steps:
- copied the files to a directory accessible via http
- chown everything to www:www
- renamed config-sample.php to config.php
- edited config.php with mysql credentials/host and base URL, also set DEBUG_MODE to TRUE.

When I try to access index.php I will get a 200 OK but no content.

I'm running nginx 1.8.1, php 5.6.20 and mariadb 10.0.23.

Logs say that the request was fulfilled with 200 OK, nothing special about that request in nginx and php-fpms error logs.

PHP is working (there are apps like owncloud etc. working on the server).

The server enforces HTTPS with a valid certificate, but that shouldn't be a problem right?

Any ideas?

Thanks! I'm very interested in this great application.

**Comment by scosu** [comment]
Hi,

I am having the same issue. Adding something like echo("hello world"); to src/system/core/CodeIgniter.php will display that but nothing else is displayed. DEBUG_MODE is TRUE here as well. No errors.

I am using:
apache 2.4.10
mysql 5.5.49
php 5.6.20
on Debian Jessie

The server uses HTTP, not HTTPS.

**Comment by alextselegidis** [comment]
Did you check the server's error logs?

**Comment by maximusmusterus1** [comment]
@scosu I think we got the same issue here. The PHP file get executed correctly, 'include's work, adding print("something") shows up on the page but nothing more. :( Thanks for your post, because I can now cross of nginx and HTTPS from my "possible problems" list.

@alextselegidis For me, nothing special in the error logs. From that point it looks like the page was served successfully. But I'll check the PHP logging settings later, maybe the log level is to low or something.

**Comment by icecoldfire** [comment]
Can I check your config file?

**Comment by TrustyTristan** [comment]
I have the same issue

MySQL 5.6.30
PHP 5.6.20
Apache 2.4.18

class Config {
    // ------------------------------------------------------------------------
    // General Settings
    // ------------------------------------------------------------------------
    const BASE_URL      = 'http://schedule.domain.com;
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = TRUE;

    // ------------------------------------------------------------------------
    // Database Settings
    // ------------------------------------------------------------------------
    const DB_HOST       = 'localhost';
    const DB_NAME       = 'useraccount_easyappointments';
    const DB_USERNAME   = 'useraccount_admin';
    const DB_PASSWORD   = 'password';
}

**Comment by alextselegidis** [comment]
You BASE_URL seems to be missing a single quote at the end of the domain, or is this just a typo?

In general whenever you see a blank page that means that PHP has crashed with a fatal error. If you have the DEBUG_MODE enabled this will go either to the apache/nginx error logs, or in the application/logs directory. 

Unfortunately I cannot help you without knowing the exact error :(

**Comment by TrustyTristan** [comment]
Sorry that is just a typo.

DEBUG_MODE is TRUE nothing in the error logs

¯\_(ツ)_/¯

**Comment by alextselegidis** [comment]
Can you send me a pm the URL of your installation? <alextselegidis@gmail.com>

**Comment by Emanuele20** [comment]
Hi! Mee too...upload on my server, create mysql db, edit and rename config.php writing: const BASE_URL      = 'http://www.exampledomain.com/agenda'; and my db connection data....have a 403 access forbidden but if i add to BASE URL /src open the front-end? where is installation? and installation for? i ve created db and fill data into config.php...installation for admin ? thx regards Emanuele

**Comment by dunatotatos** [comment]
Hi,
I have exactly the same problem, with the same protocol of installation.
Based on echo-debugging (yes, I know..., but without log file, what can I do ?), I found the problematic line : 

    $CI = new $class();
l.309 in system/core/CodeIgniter.php
An echo before displays the result on the blank page. An echo after does not have any effect.
I continue my investigation and come back if I have a solution.

**Comment by Emanuele20** [comment]
Thanks for your interest now im involved in other projects and as soon as I
can I will try to find issue or build other things in that project... in
two is better! ;-)

2016-10-02 16:15 GMT+02:00 dunatotatos <notifications@github.com>:

**Comment by dunatotatos** [comment]
A bit more debugging.
The `$class` variable contains 'appointments' in both cases (on a working installation, and on a non-working installation).

The next step is to find why this class is not known.

**Comment by hermannschwaerzlerUIBK** [comment]
Hi,
do not use `echo` for debugging (it may break other things as it generates output that interferes with output of the application). Use `error_log` instead.
So add e.g. 
`error_log("About to set CI to new $class", 3, '/tmp/my_EA_debug.log');`
before and e.g.
`error_log("CI is now ". print_r($CI, true), 3, '/tmp/my_EA_debug.log');`
after `$CI = new $class();`

This will log a lot of information to a file named `my_EA_debug.log` below `/tmp` (If your OS is using _systemd_ it will put this file into some "private" directory. So you have to find it: run 
`find /tmp -name my_EA_debug.log`
as root to see where it is).

But maybe this is all overkill:
Which OS, web-server and php-version are you using?
Which version of easyappointments? How did you get it (git checkout, zip-download, ...)?
Into which directory did you install it?
How is your web-server configured to serve EA from this directory?
Are you sure you have set BASE_URL and the DB_... consts correctly?
Which LANGUAGE did you configure?

Greetings
Hermann

**Comment by dunatotatos** [comment]
Thank you for your reply.
The versions : 
* Debian Sid 4.7.0-1-amd64
* Apache 2.4.23-5
* PHP 7.0
* mysql-server 5.6.30-1
* easyappointments commit 58c996a8398f412b821a66abd26a66f20f3d9ca (last commit of the master branched managed by alextselegidis retrieved by `git clone`

EA is installed in /var/www/html/booking. Apache is configured to serve /var/www/html :

    <VirtualHost *:80>
        [...]
        DocumentRoot /var/www/html

And the config.php file :

    class Config {
        // ------------------------------------------------------------------------
        // General Settings
        // ------------------------------------------------------------------------
        const BASE_URL      = 'http://localhost/booking';
        const LANGUAGE      = 'english';
        const DEBUG_MODE    = TRUE;
    
        // ------------------------------------------------------------------------
        // Database Settings
        // ------------------------------------------------------------------------
        const DB_HOST       = 'localhost';
        const DB_NAME       = 'easy';
        const DB_USERNAME   = 'easy';
        const DB_PASSWORD   = 'easy';
    
        // ------------------------------------------------------------------------
        // Google Calendar Sync
        // ------------------------------------------------------------------------
        const GOOGLE_SYNC_FEATURE   = FALSE; // Enter TRUE or FALSE
        const GOOGLE_PRODUCT_NAME   = '';
        const GOOGLE_CLIENT_ID      = '';
        const GOOGLE_CLIENT_SECRET  = '';
        const GOOGLE_API_KEY        = '';
    }
I triple-checked the database settings, and tested the credentials and database privileges through `mysql`. The language does not matter. The problem is encountered with chinese, english, french, and hungarian languages, at least.

**Comment by hermannschwaerzlerUIBK** [comment]
I just checked the whole procedure again. It works for me. This is what I did (this is just a quick test and not necessarily the best way to do it - especially the "ln -s" part):
```
cd /var/www/
mkdir easy
cd easy
git clone https://github.com/alextselegidis/easyappointments.git
cd ..
ln -s easy/easyappointments/src booking
cp booking/config-sample.php booking/config.php
# edit config.php to be the same as you posted earlier
mysql -u root -p
> create database easy;
> grant all on easy.* to 'easy'@'localhost' identified by 'easy';
> quit
```

Pointing my browser to "http://localhost/booking" redirected me to the installation page. After filling it in I had a working installation.

So what may be your problem?
Some thoughts (try in this order):
* Did you do this linking/copying from _clone/src_ to `booking`?
* Retry everything with a new path (not `booking`) and access the installation either with another browser or with a fully stopped (all windows and tabs) and newly started browser or with one in which all cookies related to "localhost" are deleted.
* I am not using php7 but an earlier version. Can you test it with another version?

Greetings
Hermann

**Comment by dunatotatos** [comment]
My previous installation was not a link, but a copy of the src content to html/booking/

I removed all the previous installation, the database, and the mysql user, then exactly followed your steps. The symptoms are exactly the same: blank page without any error. I also tried to open the URL in an other new and never-used browser, without success.
I followed your steps again, while replacing booking/ by booking2/ (in the config.php file as well). Same problem.

I removed PHP 7 and installed PHP 5.6.26-1  instead, then reloaded apache. Same problem.

I have an installation of the same kind which works on another computer (same OS, same apache and PHP versions, ...). I will try to reproduce exactly the state of the working installation, and let you know as soon as I have something interesting.

Thank you for your help :)
Duna

**Comment by dunatotatos** [comment]
This issue was because of the @ in front of the mysql_connect function in src/system/database/drivers/mysql/mysql_driver.php. usually, it comes from a bad configuration of the SQL server credentials, or bad configuration of the SQL server itself.

This issue had been fixed.
