### ISSUE TITLE
implementing version 1.5-dev4

### ISSUE THREAD

**Issue by wimr0001** [alextselegidis/easyappointments#1492]
See my notes in attached document.
[remarks ea1.5.pdf](https://github.com/alextselegidis/easyappointments/files/14889715/remarks.ea1.5.pdf)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for providing your feedback. 

Some of the issues are already patched in the `develop` branch that has the latest changes of the app. 

The following will need to be considered for a feature release: 

>  I noticed you make use of the Moment.js package.

Moment will be replaced with day.js or another updated library. 

FYI you can still use Google SMTP to send message with the app, but you need to create an app-specific-password from within the Google panel to do this 

Star and follow the project for more updates on releases.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
