### ISSUE TITLE
I am having trouble getting this to work

### ISSUE THREAD

**Issue by chibibar** [alextselegidis/easyappointments#150]
I am hosting my site with fatcow.com  
I follow this https://github.com/alextselegidis/easyappointments/wiki/Installation-Guide
and when I did the /backend, I was getting SQL error that table didn't exist.
I went into my assets/sql folder and load the table structure.sql and now I'm getting an internal error when trying to run the /backend.

I am currently running MySQL 5.5.44
PHP 5.3

I am wondering if I shouldn't have run the .sql into my database (the instruction didn't tell me do) but when I run the website with index.php/backend it said it couldn't find a table. So I know it can access the MySQL but not the table.

**Comment by icecoldfire** [comment]
Are you sure that the login information in your config.php correct is? 

I don't think this is a code issue but probably a misconfiguration.

**Comment by chibibar** [comment]
This is my initial error when I install fresh (with all the correct credentials)
This is a blank database. I didn't see any instruction to run any .sql before it
(I had to recreate the database since I was mucking around and mess it up) 
Error Number: 1146

Table 'akondb2.ea_settings' doesn't exist

SELECT * FROM (`ea_settings`) WHERE `name` = 'company_name'

Filename: /hermes/walnaweb11a/b2274/moo.royalmaidencom/akon/models/settings_model.php

Line Number: 44
