### ISSUE TITLE
Synchronise with google calendar

### ISSUE THREAD

**Issue by butso** [alextselegidis/easyappointments#151]
Hello,

I Have try to sync with google calendar and get this message.
Could you tell me what is wrong?

Thanks! 
Easy!Appointmant 1.1.1

![screen shot 2016-05-09 at 07 52 00](https://cloud.githubusercontent.com/assets/19260100/15104876/1708ae72-15bd-11e6-9751-2993a5cbb708.png)

**Comment by icecoldfire** [comment]
The error says it all...
