### ISSUE TITLE
Setup sms api gateway in addition to emails

### ISSUE THREAD

**Issue by xamyp** [alextselegidis/easyappointments#1538]
Good morning,

I saw that there were already closed topics for this type of request. I'm new to php and I would like to add my php code to send an SMS when an appointment is booked or modified or deleted. I have already set up SMTP and it works.

For my tests I use this:
`curl -X "POST" "https://rest.nexmo.com/sms/json" \
  -d "from=Vonage APIs" \
  -d "text=My message" \
  -d "to=33601020304" \
  -d "api_key=123456789" \
  -d "api_secret=xxxxxxxxxxxxx"`

And I would like to do things well but I don't really know the php programming language.
I retrieved the variables I wanted to put in my message:
- `<?= e($customer['phone_number']) ?>`
- `<?= e($appointment_link) ?>`
- `<?= format_date_time($appointment['start_datetime']) ?>`
- `<?= format_date_time($appointment['end_datetime']) ?>`
- `<?= e($service['name']) ?>`

For the following result:
Your appointment: From `<?= format_date_time($appointment['start_datetime']) ?>` to `<?= format_date_time($appointment['end_datetime']) ?>` for `<?= e($service['name']) ?>`
To modify your appointment: `<?= e($appointment_link) ?>`

Thanks a lot for your help.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

I trust this might be a helpful feature, but it is offered as part of the Premium Services: 

https://easyappointments.org/get-a-free-quote

Will therefore skip (at least for now).

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
