### ISSUE TITLE
Another missing translation

### ISSUE THREAD

**Issue by tm8544** [alextselegidis/easyappointments#1543]
In assets\vendor\fullcalendar\index.global.min.js there is `viewHint:"$0 view"`, which leaves word `view` untranslated.
For example in table view, only half of the hint is translated from English `List View` to Finnish `Lista view`.
![image](https://github.com/alextselegidis/easyappointments/assets/15167679/11e4a12f-f6ea-4729-9537-e30b081b5608)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for reporting this. 

This is an issue of FullCalendar that I cannot fix unfortunately. 

Feel free to open a ticket in the project's repo: 

https://github.com/fullcalendar/fullcalendar

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
