### ISSUE TITLE
Appointment management modal is not updated after appointment duration resize.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#155]
After re-sizing an appointment in the calendar and then hitting the "edit" button of the popover element, the modal will contain the old duration. If the user doesn't see this he will save old duration again.

**Comment by jeryfast** [comment]
Hello Mr. alextselegidis, 

I am using a previous version of easyappointments (for about a month) and have already invested a few weeks of programming and customizing the application. 

I found this bug about a day ago and I **can`t  afford** to lose my work by going to the last version. I would be glad, if you could pass the information needed to resolve this bug. I am hand debugging and trying to resolve it in /assets/js/backend_calendar_default_view.js where the resize callback is called. 

Thank you in advance!
Jernej

**Comment by alextselegidis** [comment]
Hello Jernej, 

thanks for posting, the following commit solves the issue: 

7aae2f359bd5e1e97d4d55b3cfd1ac54b087523d

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jeryfast** [comment]
Thank you very much! This application is great.

Regards
