### ISSUE TITLE
SMTP Google

### ISSUE THREAD

**Issue by chuchet14** [alextselegidis/easyappointments#1554]
Hello,

How do I configure the email.php file for Google SMTP?

I did this:

$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = 'smtp'; // or 'smtp'
$config['mailtype'] = 'html'; // or 'text'
$config['smtp_debug'] = '0'; // or '1'
$config['smtp_auth'] = TRUE; //or FALSE for anonymous relay.
$config['smtp_host'] = '[smtp-relay.gmail.com](http://smtp-relay.gmail.com/)';
$config['smtp_user'] = '[rendez-vous@celiaclaudon-psychologue.fr](mailto:rendez-vous@celiaclaudon-psychologue.fr)';
$config['smtp_pass'] = '*********';
$config['smtp_crypto'] = 'tls'; // or 'tls'
$config['smtp_port'] = 587

But it doesn't work.

**Comment by alextselegidis** [comment]
Already clarified with personal email: one needs app-specific passwords from google for this 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
