### ISSUE TITLE
django backend

### ISSUE THREAD

**Issue by i-salameh95** [alextselegidis/easyappointments#1555]
Hello, 
I have seen this software, and its exactly the same for what I'm working on.
Is this calendar easy to use with **Django** framework ?
I have already seen that its build in PHP, but my website is built on Django, 

could I use the frontend code ? any help would be appreciated

**Comment by alextselegidis** [comment]
Hello! 

Already answered this question on Discord ;)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
