### ISSUE TITLE
A few issues with 1.5.0-beta.1

### ISSUE THREAD

**Issue by SapitoSucio** [alextselegidis/easyappointments#1556]
I configured a provider, a service and the time zones to be Merida -6 GMT

When I visit the booking page I don't see any available hour. Also, the time zone selected it's not the default one, although it's the same time zone

![image](https://github.com/alextselegidis/easyappointments/assets/7357354/8594b597-fc81-47fe-b02d-fd85d04acecb)

With some testing I realized that the only way to successfully create an appointment it's by visitng the full link which already includes the service parameter: http://localhost/ezlapha/index.php/?provider=2&service=2

![image](https://github.com/alextselegidis/easyappointments/assets/7357354/f4f72cbc-3507-4475-bd8d-f93c6f78ba33)

**Comment by alextselegidis** [comment]
Fixed

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
