### ISSUE TITLE
Bug: Custom fields are added outside the div of default fields

### ISSUE THREAD

**Issue by CarlSinclair** [alextselegidis/easyappointments#1557]
This is causing custom fields to not conform to the layout:
![image](https://github.com/alextselegidis/easyappointments/assets/69092633/63e9982f-d831-4b03-b128-90bd3a2d00ed)

It seems that ```/application/views/pages/booking_settings.php``` is the relevant template.

Another possible bug is that the "Booking page" link seems broken. In all my tests it's pointing at ```index.php```, which is the appointment wizard. Unless that's a URL rewrite situation that I'm not aware of.

**Comment by alextselegidis** [comment]
Fixed

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
