### ISSUE TITLE
ARM V8 Support

### ISSUE THREAD

**Issue by sissinho997** [alextselegidis/easyappointments#1561]
I want to install EasyApp on my Linux/arm64/v8 machine, but it's not working. Could you guide me on where to find a compatible image?

**Comment by alextselegidis** [comment]
Hello! 

You can clone the Docker image repo and build the image by running `./build.sh 1.5.0`

https://github.com/alextselegidis/easyappointments-docker

That will by default build on your preferred architecture. 

I will also make sure future tags have cross architecture compatibility

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by peaklabs-dev** [comment]
Can you please release an image with a cross platform manifest as I am adding your image to [Coolify](https://github.com/coollabsio/coolify/pull/3763) and we would need cross platform so ARM support as well otherwise I would have to set a platform flag (which is a downside). Thank you.

**Comment by alextselegidis** [comment]
Hello! 

Sure, I will take a closer look into this for the next published images. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
