### ISSUE TITLE
Fix various 1.5.0 API issues

### ISSUE THREAD

**Issue by DumahBrazorf** [alextselegidis/easyappointments#1562]
I just get 404 pages when trying to get categories list with API. 
Also, the API documentation for 1.5.0 may need corrections. I see "categoryId" in the services response but 1.5.0 now respond "serviceCategoryId". This is also a pity having to use different words in my program code for different API versions.
Providers API call returns a php error before response. (json_decode(): Passing null to parameter #1 ($json) of type string is deprecated      in    models/Providers_model.php line 892) and also a warning (Cannot modify header information - headers already sent by (output started at /var/www/html/system/core/Exceptions.php:283)    in   core/Common.php line 574)

It would be very useful if you add the ea_appointments.update_date_time field in the API appointments response, so we can see whenever someone modified the appointment.
And with this addition, the possibility to get appointments list created/edited since a defined datetime, so we don't need to get the full list every time to check for modifications.

Thanks.

**Comment by alextselegidis** [comment]
Hello! 

Which documentation page are you using for while developing your client? 

For now please check this config file for an accurate description of the API 

https://github.com/alextselegidis/easyappointments/blob/main/openapi.yml

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by DumahBrazorf** [comment]
Hi,
the api docs on your main site. https://easyappointments.org/docs.html#1.5.0/rest-api.md
Calling service_categories returns 404 too.

**Comment by alextselegidis** [comment]
Hello! 

That had to do with some late refactoring I had done before the 1.5 release.

The docs will be updated but instead of categories use service_categories for your requests and things will work out right. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Docs were updated

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Re-open to check the other issues

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by DumahBrazorf** [comment]
service_categories does not work either, it returns the "404 Page Not Found | Easy!Appointments" html
I have a couple of categories added via backend page. 
all the others api calls work, except the providers issue.

**Comment by EagleDelux** [comment]
> Re-open to check the other issues

https://github.com/alextselegidis/easyappointments/blob/e45fcf30b579a9a2a03bbbb35efb96556f1ad426/application/config/routes.php#L133C1-L133C52

this needs to be changed to `route_api_resource($route, 'Service_categories', 'api/v1/');`

**Comment by alextselegidis** [comment]
Good catch @EagleDelux, just updated this

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by lwkask8** [comment]
acabei de puxar a versão latest e continua com o mesmo problema nessa rota de api

**Comment by alextselegidis** [comment]
@lwkask8 

For your best support please write your message in English. 

This fix will be released with 1.5.1 which is almost ready for release.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
