### ISSUE TITLE
Set the displayed language with a URL query parameter

### ISSUE THREAD

**Issue by CarlSinclair** [alextselegidis/easyappointments#1566]
Is it possible to localize the booking widget using a language parameter in the URL? That would make it easy to make the iframe match the language of the parent page. If not, is there another way to do this currently without having users manually select translations? Or having the translation button get clicked automatically based on the language/URL of the parent page? Because as far as I can tell, the language selection is done using JS and not via URI.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting your question. 

We will be adding this in the next release. 

Currently this is not possible, but you should be able to change the language with a GET parameter. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by CarlSinclair** [comment]
![image](https://github.com/user-attachments/assets/1fb44ceb-fdd5-4987-a624-a26ade626810)

It seems the language files aren't publicly accessible, not at the requested URL ```language/**/translations_lang.php``` or at the correct URL ```application/language/**/translations_lang.php```.

Is this simply a matter of surfacing this file (likely by overriding rewrite rules) or is it more complex than that?

**Comment by alextselegidis** [comment]
Hello! 

Can you try with "?language=spanish"?

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by CarlSinclair** [comment]
That's working perfectly! Thank you! I was trying with language codes like `es`. I never thought to use the full language name.

**Comment by CarlSinclair** [comment]
Note that it's only working when appended to the root domain. Appending it to `index.php` or `?embed` doesn't work. Embed never did anything for me though so it's all good.
