### ISSUE TITLE
1.5.0 not working on mobile brower

### ISSUE THREAD

**Issue by vijay-huang** [alextselegidis/easyappointments#1567]
Version 1.5.0 works properly on mobile browsers, but it cannot proceed to the next step on the customer information submission form page.

Note: I am using a subdomain.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this case. 

Are you getting any errors? 

Is it possible that you share a screenshot? 

Also you can pm me the URL address to troubleshoot the problem. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by vijay-huang** [comment]
I continued testing on different devices and found that there are no issues on computers and Android devices.

However, on iPhone and iPad, the customer information submission page does not work. There are no error messages, but the next step button is unresponsive.
![Uploading IMG_7200.jpg…]()

**Comment by vijay-huang** [comment]
Setting the time format to HH:MM can resolve the issue.

Looking forward to compatibility with the H:MM AM/PM format.
