### ISSUE TITLE
Incorrect setting assigned to $require_first_name variable

### ISSUE THREAD

**Issue by EagleDelux** [alextselegidis/easyappointments#1581]
https://github.com/alextselegidis/easyappointments/blob/e45fcf30b579a9a2a03bbbb35efb96556f1ad426/application/models/Customers_model.php#L100C8-L100C100

**Comment by alextselegidis** [comment]
Good catch, thanks for reporting this!

This will go to the next patch release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
