### ISSUE TITLE
Fix the date parsing issue on Safari web browsers during the booking process

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#1584]
Only happens with the regular time format (not with military) and it will not allow the user to complete the booking.

<img width="515" alt="Screenshot 2024-08-12 at 08 49 23" src="https://github.com/user-attachments/assets/c16e4e84-3c66-4404-bd90-bcd8a3e4e4e7">

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by charlfields** [comment]
Like you said, I had to change the time format to military time to allow the users using safari to book appointments, will welcome the next release that fixes this bug. Thank you so much!

**Comment by thinhlegolas** [comment]
> Like you said, I had to change the time format to military time to allow the users using safari to book appointments, will welcome the next release that fixes this bug. Thank you so much!

I'm having the same issue. Pardon my ignorance but how donyou change time format to military?

**Comment by alextselegidis** [comment]
Hello! 

This can be done in the General Settings page (there is a time format dropdown). 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

This is already fixed and will be part of the next maintenance version

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
