### ISSUE TITLE
Updates to german translations

### ISSUE THREAD

**Issue by herzogmedia** [alextselegidis/easyappointments#1586]
Hi there, 
for our own use we updated some translations in german for better intelligibility. You can find them in #1585

**Comment by alextselegidis** [comment]
Hello! 

Thanks for sharing this. 

We'll merge accordingly. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Merged
