### ISSUE TITLE
"Disallowed Key Characters" project upload to production server.

### ISSUE THREAD

**Issue by saleh77** [alextselegidis/easyappointments#159]
Hi, after uploading files I´m getting this error (Disallowed Key Characters.).

**Comment by alextselegidis** [comment]
Hello, this must be a server configuration issue, and unfortunately it hadn't occurred to me before. I would suggest you taking a look at the following links or search the web for other solutions. 

https://ellislab.com/forums/viewthread/235259
https://support.mozilla.org/en-US/questions/1086134

**Comment by saleh77** [comment]
The problem was in the browser cookies. after i have deleted all  cookies it worked!

**Comment by saleh77** [comment]
The problem was in the browser cookies. after i have deleted all cookies it worked!

**Comment by alextselegidis** [comment]
Nice :)
