### ISSUE TITLE
Environment variables for general SMTP configuration

### ISSUE THREAD

**Issue by Wittemberg** [alextselegidis/easyappointments#1594]
Is it possible to include Environment Variables for the general SMTP configuration in Docker?
This makes configuration more practical and we don't need to directly edit the configuration file...

And congratulations on the project.

**Comment by alextselegidis** [comment]
Hello! 

Let's move this ticket to the docker repo 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
