### ISSUE TITLE
Question about GPL License

### ISSUE THREAD

**Issue by ryanhugh** [alextselegidis/easyappointments#1601]
Hey all! 

Great work making Easy Appointments, it looks like a great product! 

I have a question around licensing. I am working on a project to take a few pieces of software (eg. An Appointment Scheduling tool like Easy Appointments and a few other pieces of software) and sell them as one bundle. I saw the GPL license on this repo and am happy to share any changes we make to the Easy Appointments software with you if you'd like. 

Would the GPL license require me to share modifications to other pieces of the bundle as well? The other pieces have different licenses, and because of that, I think that would prevent me from using Easy Appointments :/ 

Let me know! 
Ryan

**Comment by alextselegidis** [comment]
Hello! 

> Would the GPL license require me to share modifications to other pieces of the bundle as well? The other pieces have different licenses, and because of that, I think that would prevent me from using Easy Appointments :/

Yes that's right 

You will find more info at 

https://www.gnu.org/licenses/gpl-3.0.en.html

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
