### ISSUE TITLE
Wordpress plugin not working - Nothing displayed

### ISSUE THREAD

**Issue by mrkylegp** [alextselegidis/easyappointments#1602]
I have installed the wordpress plugin and it connects successfully. I add the shortcode to the page but nothing appears.

I am using EA 1.5. Php 8.3 for wordpress.

![image](https://github.com/user-attachments/assets/6b097070-782a-4bb2-86fa-56749101330f)

**Comment by alextselegidis** [comment]
Hello! 

Please check this thread

https://groups.google.com/g/easy-appointments/c/yhtUX4cgQcY

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by mrkylegp** [comment]
> Hello!
> 
> Please check this thread
> 
> https://groups.google.com/g/easy-appointments/c/yhtUX4cgQcY
> 
> ![](https://camo.githubusercontent.com/b6ae4c709927e0f22bb9887f12b030ab995b6802b3d5fa2134f07bc4320a1a1c/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	Alex Tselegidis, Easy!Appointments Creator
> [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

I have replied to the thread.

**Comment by alextselegidis** [comment]
Hello! 

Right, just saw that. I will take a closer look into this and reply back in the Support Group. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
