### ISSUE TITLE
Renaming the word "customer"

### ISSUE THREAD

**Issue by jxs714** [alextselegidis/easyappointments#1604]
Hey guys,

Is there anyway to rename the word "customer" to anything else like "client"?

**Comment by alextselegidis** [comment]
Hello! 

Sure, you can update the /application/language/*/translations_lang.php file contents
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
