### ISSUE TITLE
Flexible hours

### ISSUE THREAD

**Issue by barbuslex** [alextselegidis/easyappointments#1608]
Hi,

Is it possible to make flexible hours (ex: 10:00am to 12:am on 1st appointment and 10:15 to 10:45 to 2nd) ?

Thanks

**Comment by alextselegidis** [comment]
Hello! 

Unfortunately not at the time being. 

Feel free to reach out to info@easyappointments.org and get a free quote on a custom package that works exactly the way you want it to. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
