### ISSUE TITLE
composer detected issues

### ISSUE THREAD

**Issue by stephangriesel** [alextselegidis/easyappointments#1609]
i receive the following error after installing. 
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

anyone encountered the same issue?

**Comment by alextselegidis** [comment]
Hello! 

You will need to upgrade your php CLI version to 8.1 or later 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by stephangriesel** [comment]
I have already upgraded to 8.1 but still getting the same message.

Here is the version I am currently running:
PHP 8.1.30 (cli) (built: Sep 27 2024 04:07:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.30, Copyright (c), by Zend Technologies

**Comment by stephangriesel** [comment]
I have managed to fix the php version on my server but when I go to the installation directory I see the CodeIgniter script: <?php
/**
 * CodeIgniter
