### ISSUE TITLE
Breaks bug when Time Format is set to regular

### ISSUE THREAD

**Issue by alxlab-zone66x** [alextselegidis/easyappointments#1611]
When the **Time Format** is set to `regular` in the **General Settings** the a bug occurs when setting the time of **Breaks** in the **Business Logic** settings or **Providers Working Plan**.

For example if you set the break time from 11:00 am to 3:00 pm it will force it to 11:00am to 12:00 pm.

This is because the event handler in **working_plan.js** for saving the break has the time format hardcoded to `'HH:mm'` for the start and end of the break on line **537** and **539** respectively. This results in the am/pm being ignored so it triggers the condition that auto corrects the break end time when the start time is past it.

I will be submitting a PR shortly.

**Comment by alextselegidis** [comment]
Great thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Merged
