### ISSUE TITLE
"Next" button doesn’t respond after the customer form is filled out in phone browsers (android or apple)

### ISSUE THREAD

**Issue by AhadMomin** [alextselegidis/easyappointments#1616]
booking form on mobile browsers, the "Next" button doesn’t respond after the customer form is filled out. I've tested this across multiple mobile browsers, and the issue persists.

**Comment by AhadMomin** [comment]
Hello yes the demo isn't working either. Tested on safari google chrome aswelll as firefox on the phone

**Comment by ansulagrawal** [comment]
@AhadMomin its working in your domain can you tell me how it worked?

**Comment by AhadMomin** [comment]
it not working for me on my phone, not sure how its working for you what phone are you using??. Alex said this issue will be fixed in next release

**Comment by ansulagrawal** [comment]
Sorry, I was asking about visibility of service and provider options in booking page. I didn't read the full question, sorry for that.

**Comment by aaron4mufc** [comment]
Hi, facing the same issue as well. Please help.

**Comment by aaron4mufc** [comment]
Setting the time format to HH:MM can resolve the issue.

Looking forward to compatibility with the H:MM AM/PM format.

**Comment by AhadMomin** [comment]
Yeah it actually fixed the issue with setting HH:MM for time date, interesting....alex i hope you are seeing this

**Comment by alextselegidis** [comment]
Hello!

Are you testing with a iOS device? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by AhadMomin** [comment]
I am testing on both. Keep me updated

Thanks

**Comment by WajdyEssam** [comment]
The same issue on Mac/Safari cannot be able to click with the next button if the timing setting is HH:MM AM/PM

**Comment by AhadMomin** [comment]
Thank you alex! Looking forward to the new release

**Comment by aaron4mufc** [comment]
Thank you, Alex!
