### ISSUE TITLE
Changing the navigation menu

### ISSUE THREAD

**Issue by DerErzengel** [alextselegidis/easyappointments#1619]
Is there a way to display a navigation menu after or during the booking so that the user can also return to the original website?
 
I have installed EasyAppointments on my Ubuntu LAMP server and as I am having difficulties using an iframe to display the booking page correctly on the original website, I would like to use the local (/easyappointments) version. However, there is no way to navigate there, so in the worst case the user is “trapped” on this website and cannot access the original page with a link.

**Comment by alextselegidis** [comment]
Hello! 

This will require some code changes. 

You can modify Booking_confirmation.php to return a custom redirect URL. 

Possibly the booking_confirmation.js might also need to be changed

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
