### ISSUE TITLE
Failed to load resource: the server responded with a status of 524 ()

### ISSUE THREAD

**Issue by eemirtekin** [alextselegidis/easyappointments#1623]
I have installed easyappointments 1.5.0. 
Thank you all community. 
I have a bit problem below. How can I fix the problem?
This problem occurs when I try to create a new appointment.

Thanks in advance.
nginx 1.21.4
PHP 8.2
MySQL 5.7.44

<img width="1257" alt="Screenshot 2024-11-28 at 20 43 02" src="https://github.com/user-attachments/assets/80499660-3be8-4338-aa13-9d24fe7c150c">

**Comment by alextselegidis** [comment]
Hello! 

This seems to be a server configuration related issue. 

I would suggest you contact the hosting support or consider reaching out to info@easyappointments.org for more info on the available Managed Hosting plans. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
