### ISSUE TITLE
Cannot add "New Event" by clicking on the calendar area on mobile

### ISSUE THREAD

**Issue by shadirok** [alextselegidis/easyappointments#1627]
**Summary**:
When trying to add a new event by clicking on the calendar area on mobile devices, the action does not trigger any response, making it impossible to create a new event directly from the calendar interface.

**Steps to Reproduce:**
Open the https://demo.easyappointments.org/ on a mobile device.
Navigate to the calendar view. (As admin)
Tap on an empty area of the calendar to add a new event.
Observe that no response occurs (new event form doesn't appear).
**Expected Behavior:**
Tapping on the empty area of the calendar should trigger the "Add New Event" form to appear, allowing the user to create a new event.

**Actual Behavior:**
Nothing happens when tapping on the empty area of the calendar. The "Add New Event" functionality does not trigger.

Device/OS Information:
Device: [e.g., iPhone 12, Samsung Galaxy S20]
OS: [e.g., iOS 16, Android 12]

![image](https://github.com/user-attachments/assets/9212b972-44d4-46d8-9f80-ff2d637fb422)

**Comment by alextselegidis** [comment]
Hello!

Thanks for submitting this ticket. 

Please press and hold on a slot to get a selection. 

Although not that obvious, this behavior originates from the FullCalendar widget we're using. 

I will try to improve that if possible 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by shadirok** [comment]
Thank you very much
