### ISSUE TITLE
CodeIgniter 4

### ISSUE THREAD

**Issue by jpimbert** [alextselegidis/easyappointments#1628]
Is it considered to use CodeIgniter 4 in a future version ?
I plan to add features in Easy!Appointment, and I would to use PHPUnit. The use of PHPUnit is tricky with CodeIgniter 3.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

Although there will some time be a framework upgrade, I'm not yet sure which one will better fit for the project. 

Being said, PHPUnit already works with the current set up (see the test directory for some sample checks)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
