### ISSUE TITLE
Book in blocks

### ISSUE THREAD

**Issue by jfreak53** [alextselegidis/easyappointments#1631]
I've been searching everywhere but can't find it. Is there anyway to book in blocks for a particular service? I want customers to be able to book in 1 week increments a service, and when confirmed it blocks out 7 days from start day.

**Comment by alextselegidis** [comment]
Hello! 

That does not work automatically (that would require some code changes). 

You could add an unavailability period after a booking manually in the calendar. 

Alternatively, you could reach out to info@easyappointments.org and order a custom package that would do this automatically. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
