### ISSUE TITLE
BUG (+fix): No color change in the appointment modal window (in the backend calendar)

### ISSUE THREAD

**Issue by maurocsound** [alextselegidis/easyappointments#1641]
Hi,
I think I found a bug. In the modal window displayed when you want to create/edit an appointment in the backend calendar view, when you change the service there is no color change, even if you've defined a specific color for that service (in the services form).

https://github.com/alextselegidis/easyappointments/blob/272300359409ae5624eb95e2c751b930a10f2d1a/assets/js/components/appointments_modal.js#L369C34-L369C35

I think I found the fix. In the code linked above, this:

```
            if (service?.color) {
                App.Components.ColorSelection.getColor($appointmentColor, service.color);
            }
```

should be instead:

```
            if (service?.color) {
                App.Components.ColorSelection.setColor($appointmentColor, service.color);
            }
```

**Comment by alextselegidis** [comment]
Thanks, merged

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
