### ISSUE TITLE
Allow Provider to specify select dates in a month to provide service

### ISSUE THREAD

**Issue by ganeshk85** [alextselegidis/easyappointments#165]
Hello Alex,
Firstly, great job on this project. I have been using easy appointments for one of my projects. Its pretty easy to use with efficient user interface. However, I was wondering, if you could add a feature, wherein the provider is allowed to specify select(certain) dates or start/end date of their service. So, with this requirement, only those specific dates will be available for customers to book in the calendar for that provider. 
If you are open to contributions, I would like to offer work on this project and provide my contributions.
Again, thank you for such great work on this project.

**Comment by alextselegidis** [comment]
Hello! Glad you like the project :) 

So you mean to pick a date range (e.g. from 15/04/2016 - 17/05/2016 or just from 15/04/2016 without an expiration time) and only during this time the customers will be able to book the appointments?

Hmm yeah that would be nice. You are free to make pull request but please do in the develop branch as this is where I prepare the next releases.

**Comment by ganeshk85** [comment]
Yes, one way your are correct. However, to elaborate more, I would say, provider should be given an option of selecting a range of dates(e.g. 15/06/2016 to 15/08/2016) or provider can only select specific dates(e.g. service is available only on 16/06/2016, 19/06/2016, 20/06/2016, 21/06/2016 and 22/06/2016).
Certainly, provider can have an option of just selecting the start date of his service without any end date.

Also, there are few more feature enhancements that can be added to this project, which I would mention it later in a new issue. For time being, I will fork your project and work on the above date selection feature for provider.  Once its ready, I will make pull request on the develop branch.

Again, thank you for your cooperation.

**Comment by stevenhorner** [comment]
@ganeshk85 Did you manage to implement this feature, this is exactly what I would like too?

**Comment by ganeshk85** [comment]
@stevenhorner I am half way done, still need to test it on my development version. Probably I would make a pull request for this feature in next couple of weeks.

**Comment by soulsb** [comment]
@ganeshk85 That would be awesome. I would like this feature too.

**Comment by absolutejam** [comment]
This is the killer missing feature!

Again, kudos on the work so far though :+1:

**Comment by absolutejam** [comment]
Anyone know if there's a temporary hack for this? I just need a single day to be bookable for parent-teacher conferences.

**Comment by hermannschwaerzlerUIBK** [comment]
1. In the "working plan" of the respective provider make the day of week you are planning this conferences at the only available one.
2. Then go to the calender and add for that provider one "Unavailable" period that start today and ends the day before the conferences and another one starting the day after the conferences and ending in ten years or so.

Number 1 of this is a bit superfluous but you may do it anyway for clarity...

**Comment by absolutejam** [comment]
Ah, great idea. I'll see if I can edit all of our providers in the relevant
tables as we have around 80.

**Comment by alextselegidis** [comment]
I see that many people have interest for this feature. I will consider this for v1.3 :)

**Comment by alextselegidis** [comment]
Sadly due to lack of time this feature will be postponed for a future release.
