### ISSUE TITLE
DateTime issue

### ISSUE THREAD

**Issue by sheria** [alextselegidis/easyappointments#168]
Hi guys can anyone assist me with the bellow error? please
I am having the issue on the live application but on my localhost i don't have such issue
and where can I change the timezone?
"DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
Close
"

**Comment by alextselegidis** [comment]
Hello! You will have to set a timezone in your server (edit php.ini file). 

Hint: http://stackoverflow.com/a/16765214/1718162

PHP Manual: http://php.net/manual/en/timezones.php
