### ISSUE TITLE
Add new field to Clients/Patients?

### ISSUE THREAD

**Issue by felipecorrea9** [alextselegidis/easyappointments#169]
Is there any way to add a new field to the clientes form?

Regards

**Comment by alextselegidis** [comment]
Only be modifying the code base. You will also have to change the respective models, controllers, view and javascript files in order to get it work correctly. What field do you need exactly?

**Comment by felipecorrea9** [comment]
Thanks, I was able to add one more field to the User Model.

Regards!

**Comment by r-morgenstern** [comment]
Hi felipecorrea9, would you share with the community which steeps you did? Like a shot guide. I guess a lot of users of E!A will be interested and thankful.

Thank you in advance!
