### ISSUE TITLE
How can i add appointment hours as i'm selecting the date but no hours are shown and i can't proceed ? Please help me! I am on localhost XAMPP Server

### ISSUE THREAD

**Issue by Hamzajaved960** [alextselegidis/easyappointments#170]
How can i add appointment hours as i'm selecting the date but no hours are shown and i can't proceed ? Please help me!

![hhh](https://cloud.githubusercontent.com/assets/20135288/16353761/1984455c-3a99-11e6-844c-24e53f7582fb.PNG)
![how](https://cloud.githubusercontent.com/assets/20135288/16353762/1988e7ec-3a99-11e6-955a-15b80ecb5bc0.PNG)

**Comment by alextselegidis** [comment]
Answered in [support group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!category-topic/easy-appointments/2fqYgQVDG9w).
