### ISSUE TITLE
Google Calendar Sync - Wrong Timezone for Appointments

### ISSUE THREAD

**Issue by felipecorrea9** [alextselegidis/easyappointments#171]
I have successfully sync my calendar with my Google account, but the problem is that the hours are different. Probably a time zone issue. The thing is I don't know where or how to fix this.

Regards,

**Comment by alextselegidis** [comment]
I think this is the correct ticket for the problem. I will try to fix it asap for v1.2

Can you give me only an example of invalid syncing?

**Comment by felipecorrea9** [comment]
I was able to fix this by doing this:
At google_sync.php
Replace every "$event->setStart()" for $event->setStart(array('dateTime' => str_replace(" ","T",$appointment['start_datetime']),'timeZone' => 'My/TimeZone'));

Same With the "$event->setEnd($end);"

That fixed the sync from EA google. Then I had a problem syncing from Google to EA. So I was able to fix that at "google.php".
The problem was that I had set my default timezone in php and also Google sends the time with the timezone, but the thing is that strtotime() thinks that the timezone that google send is for it to adjust the time an not a referencial value, so I was able to fix my problem my chaing the timezone for two "00".
ie: $event_start = strtotime(str_replace("-03","-00",str_replace("-04","-00",$google_event->getStart()->getDateTime())));

I know it not the best way to fix it but it worked for me.
Maybe it could give you a hint of how to make a better fix.

Best Regards,

**Comment by alextselegidis** [comment]
That's more than enough info to fix the bug. Thank you very much for posting :+1:

**Comment by felipecorrea9** [comment]
no problem!

Regards

**Comment by tsiolas** [comment]
Hello,
I was able to correct this problem in a more simple way: I just added this line as first line to config.php

date_default_timezone_set('Europe/Athens'); //your timezone here

Since config.php is loaded always, I found that this is a very good way to correct it without modifying code.
Thanks for your awesome script and I hope this works for you also.

**Comment by alextselegidis** [comment]
Yeah tsiolas comment is right. I've already commented this in the following ticket: 

https://github.com/alextselegidis/easyappointments/issues/22

Just set the correct PHP timezone in your server and the synced appointments will have the correct datetime.

**Comment by jamrizzi** [comment]
This does not work for me. My server is returning the correct time with I run the following bash command.

```sh
date
```

However, php returns an incorrect time, I think UTC.

**Comment by jamrizzi** [comment]
Ah, I figured out my problem. I didn't set the timezone in the php.ini file. I thought php would get the timezone from the operating system, but I guess not.

http://www.inmotionhosting.com/support/website/php/setting-the-timezone-for-php-in-the-phpini-file

**Comment by Sibgha228** [comment]
I have set Pacific (GMT-7:00) in my google calendar. But in CalendarList: list API response I get "America/NewYork" in timeZone. which is (GMT-5:00).

**Comment by alextselegidis** [comment]
@Sibgha228 That must be the timezone used by your server. You can change that in your php.ini file `date.timezone` value.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by miqmago** [comment]
This could be an option in step 2, so the user could select their preferred timezone...

**Comment by alextselegidis** [comment]
This one is fixed with (#313)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
