### ISSUE TITLE
Add Docker container for Easy!Appointments development. 

### ISSUE THREAD

**Issue by mojtabacazi** [alextselegidis/easyappointments#176]
Create a ready to use docker container for easy appointments.
Suggested Stack: PHP5.6, Apache, MySQL 5.6.

**Comment by alextselegidis** [comment]
Can you provide more information about what is it that you need?

**Comment by mojtabacazi** [comment]
Description updated

**Comment by alextselegidis** [comment]
I'm currently making development workflow changes which might integrate extra tools. Once this is stabilized I will provide a container for Docker.

**Comment by srikarm** [comment]
https://hub.docker.com/r/srikarm/easyappts/

**Comment by circa10a** [comment]
I wasn't satisfied with the docker container that was previously provided because of the need of docker compose. So here is one I created that is ready out of the box.

https://hub.docker.com/r/fev2/easyappts/

**Comment by alextselegidis** [comment]
Thanks 👍

**Comment by jamrizzi** [comment]
Could we use the Dockerfile I built? The existing Docker container is HUGE (almost 13 times bigger) and does not support adding settings via environment variables.

https://github.com/jamrizzi/easyappointments-docker
https://hub.docker.com/r/jamrizzi/easyappointments/tags/

**Comment by alextselegidis** [comment]
Develop branch has now a new Docker configuration that fits for both development and production. 

Pull Request: https://github.com/alextselegidis/easyappointments/pull/317

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
