### ISSUE TITLE
 The server responded with a status of 404

### ISSUE THREAD

**Issue by sripush** [alextselegidis/easyappointments#179]
![error](https://cloud.githubusercontent.com/assets/17062011/16893497/523c765c-4b57-11e6-9f6a-2a6f8daa7371.png)

**Comment by alextselegidis** [comment]
Hello, when do you get this error?

**Comment by sripush** [comment]
In Localhost its working fine.But if i run in server when i select the option from dropdown i am getting this error

**Comment by alextselegidis** [comment]
Can you send me a pm with your installation URL (alextselegidis@gmail.com)?
