### ISSUE TITLE
Duration is not changing when adding a new appointment

### ISSUE THREAD

**Issue by bwlaren** [alextselegidis/easyappointments#18]
In the calendar when addning a new appointment the time for the "Start Date / Time" and "End Date / Time" are automatically set for the first service but when selecting a new service the "Start Date / Time" and "End Date / Time" is not adjusted to the selected service time (you now have to set that manually, which is easy to forget and might cause problems).

Hope you understand what I mean.

**Comment by alextselegidis** [comment]
Confirmed! Will be fixed in version 1.1
