### ISSUE TITLE
Unexpected Issues (AJAX Error: Internal Server Error) on Internet Explorer 11

### ISSUE THREAD

**Issue by r-morgenstern** [alextselegidis/easyappointments#188]
I have a plain installation of E!A. By accessing E!A with Internet Explorer 11 the following Error pop-up appears. It happens multiple times by initial access, by choosing a Service, Date etc. no availabilities will be offered.

Any ideas?

Unexpected Issues
The operation could not complete due to unexpected issues.

Details:
AJAX Error: Internal Server Error

**Comment by srikarm** [comment]
Happens in chrome as well...

![image](https://cloud.githubusercontent.com/assets/12801277/17180333/f22a02d4-53d0-11e6-934d-97c1058c7c4b.png)

**Comment by BramVanroy** [comment]
Seems like something isn't serialized correctly. Maybe PHP is showing a warning somewhere which returns an unexpected JSON string.

**Comment by r-morgenstern** [comment]
Unfortunately the issue occurs also with v1.2.0 Alpha 1 - "AJAX Error: Forbidden"

**Comment by v1ctoralex** [comment]
Having the same issue, on a local server everything works perfectly, on web server I do have the same error after importing the database. No idea what missconfiguration could cause this error.

**Comment by blackrainb0w** [comment]
I'm facing the same issue on Safari after validating an appointment and clicking the link to get back to the main page, this error popped up (but the appointment was fine).

**Comment by r-morgenstern** [comment]
I spend some time to drill more into that topic.

The issue occurs in file "frontend_book_api.js" by function "exports.getAvailableHours = function(selDate) {". The function is making a ajax **post request** to get the available hours. On Firefox the request it is working properly but on IE it responses with a 403 (Forbidden) error.

I changed it to a **get request**. Therefore I also had to adapt the function "ajax_get_available_hours()" in file "Appointments.php" from $_POST to $_GET.

**Now it is working properly!**

It seams the issue belongs to my server (Apache) settings, but I don't know how to solve it. Any suggestions?

**Comment by r-morgenstern** [comment]
Hi Alex, any suggestions why GET is working in stead of POST on my server?

**Comment by alextselegidis** [comment]
Hi, I cannot really tell what the problem is without checking its' configuration or running some test changes directly on your machine. 

My advise would be to reset any configuration you have and start from the beginning again in order to find the offending setting. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sam1902** [comment]
This may be a security feature to so that the JS doesn't POST (send) data in the background while the user is writting passwords and so. Therefore GET (fetch) would be more appropriate and should not trigger any security feature.
