### ISSUE TITLE
Unexpected Issues (No Details)

### ISSUE THREAD

**Issue by tduder** [alextselegidis/easyappointments#189]
When clicking on the link to the booking page, http://aluatan.com/book-online/    the app comes up with the following error. I've pasted the developer tools network report below. No details are listed. It looks like it's trying to pull up Google Maps API for some reason. Is there a place in the Easy!Appointments code somewhere that does this?

Unexpected Issues
The operation could not complete due to unexpected issues.
Details

Thanks,

<img width="737" alt="screen shot 2016-07-28 at 09 12 38" src="https://cloud.githubusercontent.com/assets/20703977/17213858/3a3574b8-54a4-11e6-9c78-7a0dd0a880d8.png">

**Comment by tduder** [comment]
`Array[1]
0
:
Object
code
:
0
file
:
"/var/www/vhosts/aluatan.com/httpdocs/book/application/controllers/appointments.php"
line
:
571
message
:
"DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone."
previous
:
null
trace
:
"#0 /var/www/vhosts/aluatan.com/httpdocs/book/application/controllers/appointments.php(571): DateTime->__construct('17:00')↵#1 /var/www/vhosts/aluatan.com/httpdocs/book/application/controllers/appointments.php(312): Appointments->get_provider_available_time_periods('86', '04-08-2016', Array)↵#2 [internal function]: Appointments->ajax_get_available_hours()↵#3 /var/www/vhosts/aluatan.com/httpdocs/book/system/core/CodeIgniter.php(360): call_user_func_array(Array, Array)↵#4 /var/www/vhosts/aluatan.com/httpdocs/book/index.php(229): require_once('/var/www/vhosts...')↵#5 {main}"
__proto__
:
Object
length
:
1
__proto__
:
Array[0]
__proto__
:
Object
__defineGetter__
:
__defineGetter__()
__defineSetter__
:
__defineSetter__()
__lookupGetter__
:
__lookupGetter__()
__lookupSetter__
:
__lookupSetter__()
constructor
:
Object()
hasOwnProperty
:
hasOwnProperty()
isPrototypeOf
:
isPrototypeOf()
propertyIsEnumerable
:
propertyIsEnumerable()
toLocaleString
:
toLocaleString()
toString
:
toString()
valueOf
:
valueOf()
get __proto__
:
__proto__()
set __proto__
:
__proto__()
`

**Comment by alextselegidis** [comment]
Hello! Take a look at this issue: 

https://github.com/alextselegidis/easyappointments/issues/168
