### ISSUE TITLE
Search for all available times, not only at a specific provider

### ISSUE THREAD

**Issue by bwlaren** [alextselegidis/easyappointments#19]
Some customers may not care about what provider they got, they may just want to find a time that fits them best and therefore there is no need to look through all the service providers to find a time to book.

**Comment by alextselegidis** [comment]
So, would you suggest something like "With Any Provider" selection in the providers listbox?

**Comment by bwlaren** [comment]
Yeah, that was exactly what I meant :) Not sure how to assign the booking to the provider though... maybe do it at random or let the customer choose at a later stage or something..

**Comment by alextselegidis** [comment]
I will assign the appointment to the first provider user that is free at the selected time period.

Will implement it for version 1.1 ;)
