### ISSUE TITLE
Control start hours

### ISSUE THREAD

**Issue by partnerwerk** [alextselegidis/easyappointments#190]
First of all:
Thanks for this great piece of work!

In order to maintain fixed start hours I would need an option to block subsequent times.

Right now users get presented open slots every 30 minutes. I would like to reduce these and control which ones are shown, best on a daily basis.

So instead of 10:00, 10:30, 11:30, 12:00, 12.30 it should only show 10:00 and 11.30.

A first approach might be, to have an option to control the time distance between two free appointments.

Thank you again.

**Comment by alextselegidis** [comment]
This is now possible with the latest relase by setting the availabilities type to fixed :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
