### ISSUE TITLE
Customer receives the confirmation email of provider

### ISSUE THREAD

**Issue by ChamesBont** [alextselegidis/easyappointments#192]
I noticed, that the customer receives the confirmation an the confirmation email of the provider as well.

**Comment by hermannschwaerzlerUIBK** [comment]
I can confirm this. This is even visible in the mail headers of the mail sent to the provider: the To: field contains both addresses - the one of the provider as well as the customer.

When a date is cancelled by the customer it's somewhat the other way around: the provider gets two mails - one to her/himself and one that is intended for the customer but contains in the To: field the provider's address as well.

**Comment by alextselegidis** [comment]
Fixed!
