### ISSUE TITLE
Wrong start an end time between 30th October and 25th March 

### ISSUE THREAD

**Issue by ChamesBont** [alextselegidis/easyappointments#193]
Hi,
if you set a start and end time for the "unavailabe time" and "appointments", for example
START: 29/11.2016 - 09:00 o'clock until END: 29/11/2016 - 10:00 o'clock
the entry in the calendar looks like START: 29/11.2016 - 08:00 o'clock until END: 29/11/2016 - 09:00 o'clock. So 1 hour is missing. 
That happens also if you set an appointment with the appointment-button. The end time is behind the the start time. But the thing is - that happens only in some months like november.

Is there a solution for that bug?
Thanks.

**Comment by ChamesBont** [comment]
I made some test. The bug appears only between 30th October and 25th March every year.
Maybe that will help you.

**Comment by gertje5** [comment]
I also did some testing and this (between 30oct and 25mar) is only happening in the backend section and not in the frontend.
When I see the dates then I think it has something to do with winter and summer times. Maybe this will help to find a solution.

**Comment by alextselegidis** [comment]
Hello, thanks for posting! 

I will fix the problem before the final v1.2 package. Make sure that you'll update to the latest release.

**Comment by alextselegidis** [comment]
Commit: https://github.com/alextselegidis/easyappointments/commit/81b3eb9bd3e2c8a13e75deeca42d46c5e0b55b59
