### ISSUE TITLE
Appointment Canceling - Unexpected Errors - No record matches the provided hash. 

### ISSUE THREAD

**Issue by r-morgenstern** [alextselegidis/easyappointments#198]
Cancelling of an already booked appointment via the booking-link results in:

# Unexpected Errors
No record matches the provided hash.

> #0 [internal function]: Appointments->cancel('3058809e3b92de7...')
> #1 /mnt/webu/b0/10/56776610/htdocs/_applications/easyappointments/system/core/CodeIgniter.php(360): call_user_func_array(Array, Array)
> #2 /mnt/webu/b0/10/56776610/htdocs/_applications/easyappointments/index.php(229): require_once('/mnt/webu/b0/10...')
> #3 {main}

**Comment by r-morgenstern** [comment]
Problem doesn't occur in v1.2.0 Alpha 1

**Comment by alextselegidis** [comment]
Hmm strange, but if the problem does not occur in the newer version I will mark close this issue. You can re-open it again if you find a similar issue.
