### ISSUE TITLE
Question: Add new menu item for quick booking page access.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#20]
It would be nice if backend users could quickly navigate to frontend booking wizard but without editing the browser's URL address, just by pressing a menu item at the backend menu bar. What do you think?

(Will only be included if users find it usefull)

**Comment by bwlaren** [comment]
Yeah, I think that could be useful, since some backend-users might find the frontend booking wizard easier to use and want to easily navigate between front- and backend.

**Comment by lauromolina** [comment]
Yes please!!
ᐧ

*Lauro Molina *

c: +52 (662) 290 3551
t:  @loudder <http://twitter.com/loudder>
In: http://www.linkedin.com/in/lauromolina

"Viajamos, no para cambiar de lugar, sino para cambiar de ideas" Alphose
Karr

**Comment by alextselegidis** [comment]
Ok seems that this will be helpful ... singed v1.1!

**Comment by kawish** [comment]
Thanks .

Waiting for the release

Please provide a tentative date for the release even a beta release

**Comment by alextselegidis** [comment]
Hi, I will post development updates regularly :)

**Comment by lucianpp** [comment]
Hi, would be great if a pop-up window will be displayed only.
Thank you for this great tool!!!

**Comment by alextselegidis** [comment]
Hello, 

so you mean that the booking page must be opened in a new separate tab/window?

**Comment by lucianpp** [comment]
Hi,
It can be helpful for some people if the front-end page will open in a pop-up from back-end, with a Quick Appointment button or something ;) 
Also I had a POST about the end date of an appointment from back-end wizard, could that be automatically filled according to service duration and if the user want to change it to be editable but filled correctly.
Thank you!!

**Comment by lucianpp** [comment]
Hi, regarding this request, I would like to add a link to the front-end wizard, in the the back-end so adding new appointments will be much easier but the front-end part inserts each time a new client even if the client already has passed appointments. 
How I can integrate the 'Select existing customer' option  in the last page of the wizard?
Please advise!!
Thank you!!

**Comment by lucianpp** [comment]
![image](https://cloud.githubusercontent.com/assets/14198181/10584333/55428ef0-769a-11e5-8b05-e32da3d6a9d0.png)

**Comment by lucianpp** [comment]
i managed to add this part but how i fill the list?
