### ISSUE TITLE
Tried to install the "develop" version...

### ISSUE THREAD

**Issue by danysz** [alextselegidis/easyappointments#200]
Hi

I tried to install the "develop" version and the install was smooth but at the end I got error :

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET `last_activity` = 1472897624, `user_data` = 'a:7:{s:9:\"user_data\";s:0:\"\"' at line 1

UPDATE SET `last_activity` = 1472897624, `user_data` = 'a:7:{s:9:\"user_data\";s:0:\"\";s:14:\"captcha_phrase\";s:5:\"ss3zp\";s:8:\"dest_url\";s:50:\"http://appointment.scop-sys.info/index.php/backend\";s:7:\"user_id\";s:2:\"84\";s:10:\"user_email\";s:16:\"danysz@gmail.com\";s:9:\"role_slug\";s:5:\"admin\";s:8:\"username\";s:5:\"admin\";}' WHERE `session_id` = '58bb1bf54a62cf004fddf0f2d60c7a76'

Filename: libraries/Session.php

Line Number: 306

I have a MySQL 5.6.31 - MySQL Community Server (GPL)

Thanks

Daniel

**Comment by danysz** [comment]
Not relevant...
Clean installation saved the issue...

**Comment by alextselegidis** [comment]
ok, i'll close the issue then :)
