### ISSUE TITLE
More Customer Fields

### ISSUE THREAD

**Issue by cybricks** [alextselegidis/easyappointments#202]
Hi! Pls guide us a little as we are facing issue in adding a field to customer details. Need this for a garage and would like to add car make & model for each customer.

Thanks!

**Comment by zalikhaosky** [comment]
I've the same issue...Please guide us. Need it urgently.
Thanks in advance!

**Comment by alextselegidis** [comment]
Hello, here is an older post from the support group that explains what needs to be done in order to add custom fields into the app. 

https://groups.google.com/forum/#!searchin/easy-appointments/custom$20fields|sort:relevance/easy-appointments/-Qg1k6Zhjes/lDQ2jntyFAAJ

**Comment by Elvin-Xhimitiku** [comment]
any guide on how to do this for V. 1.3.2?

**Comment by alextselegidis** [comment]
@Elvin-Xhimitiku the same principles apply to v1.3.2 as well. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
