### ISSUE TITLE
PHP 7 Error

### ISSUE THREAD

**Issue by jwelmac** [alextselegidis/easyappointments#204]
I get the following error when starting the installation on an Ubuntu server running PHP 7.
PHP Fatal error:  Cannot use EA\\Engine\\Types\\String as String because 'String' is a special class name in /..../easyappointments/src/application/controllers/Appointments.php on line 14

**Comment by jwelmac** [comment]
I was able to fix it by changing all references to String to SafeString.

**Comment by alextselegidis** [comment]
Hey, thanks for reporting. 

I haven't yet checked the app with PHP7, but I'll do it as soon as possible. Maybe there are some other issues there.

**Comment by ianmin2** [comment]
Thanks @jwelmac , I am having a similar problem on php7. Let me check your solution out.
