### ISSUE TITLE
PHP requirement: 5.3 in the wiki, but at least 5.4 due to use of [] array syntax

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [alextselegidis/easyappointments#207]
The development branch contains code that is incompatible with PHP version 5.3 (which is mentioned as a minimum requirement in the Wiki (https://github.com/alextselegidis/easyappointments/wiki/Installation-Guide point 1.)).
PHP 5.3 does not support "[]" for declaring an array but this syntax is used all over the place in the development branch.
As far as I can tell changing the minimum requirement is probably the way to go as there is really *a lot of* new style array syntax. :-)

**Comment by alextselegidis** [comment]
Hi, the requirement in the wiki stands for v1.1 where there aren't any [] used for arrays. But php v5.3 is no longer supported and thus v1.2 is only going to support the v5.4 and newer versions. Since this is the case I have started using newer features of the language ;)
