### ISSUE TITLE
Integrate CalDAV Protocol for appointment syncing

### ISSUE THREAD

**Issue by viegelinsch** [alextselegidis/easyappointments#209]
Hi,

I would like to become independent from Google or any other cloud service. I host my own CalDAV server so it ould be consequent to subscribe to Easy!Appointments as additional CalDAV ressource.
## Use case

Similar to the existing Google sync a configurable sync with a CalDAV calendar.
I would suggest parameters like:

```
const CALDAV_SYNC_FEATURE   = FALSE; // Enter TRUE or FALSE
const CALDAV_URL      = '';
const CALDAV_LOGIN_NAME   = '';
const CALDAV_PASSWORD  = '';
```

The CalDav ressource can be an iCloud account, a [own,next]cloud calendar or a Google calendar.

**Or**

If syncing is to complex to implement, maybe it is easier to integrate [sabre/dav](http://sabre.io/) to offer the calendars with the bookings via CalDav. It would be one more calendar ressource to subscribe to, but this shouldn't be a problem.

Sponsoring (e.g. via [Bountysource](https://www.bountysource.com/) or [FreedomSponsors](https://freedomsponsors.org/)) is an option.

With best regards,
Hendrik Eggers

**Comment by alextselegidis** [comment]
Hello Hendrik, 

thanks for posting! The CalDAV protocol seems to be very interesting. I will definitely check this out for a future release. 

I'm currently preparing v1.2 for Beta release so it's a bit too late for this release but it may be integrated for v1.3. 

In any case I am accepting donation through PayPal: paypal.me/alextselegidis

**Comment by law** [comment]
Seconded

**Comment by MarkChr65** [comment]
Ohh, this feature would be great for me! At this moment i have to pay monthly for the CalDAV Feature to sync with my Smartphone and Thunderbird / Lightning.  I want to be independent from Google Cal. I would donate for this feature! Is something planned about this? Actually i'm using this expensive service:  https://de.doctena.de/  :-/

Hope to hear from you

Best Mark

**Comment by alextselegidis** [comment]
Unfortunately this feature will not make it for v1.3, I'm actually almost done with the coding of the new release and will proceed to a beta release in the following days. 

Stay tuned for further updates :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by barrydegraaff** [comment]
@alextselegidis any news on the CalDAV support?

If not, I would like to start programming on this, in order to support at least a subset of the caldav standard.

But in case anyone already started, I want to avoid the issue.

What is the best way to extend on this code?

We need some sort of REST API specification so
server/dav/username/calendar  or something like that and than the classes to deal with the conversion of the data in the database to CalDAV.

We can start with a read-only CalDAV so people can at least see the calendars from easyappointments.

**Comment by mokkin** [comment]
@alextselegidis and @barrydegraaff I am also very excited about this feature and in my opinion this is a must have as we are working around Google & Co. with our own infrastructure such as nextcloud for calendars for example. Actually we are using a proprietary booking app that doesn't support CalDAV as well so we have to sync manually...
Is this planned in the closer future?
Can we support you to help implementing this? The issue starter has already suggested two options for donations.

**Comment by alextselegidis** [comment]
Hello @barrydegraaff, @mokkin thank you for your interest, I find this a great feature too and also think that will make the integration with other systems so much easier. Unfortunately other tasks are being prioritized for the v1.4 so that the overall performance and user experience is enhanced. I cannot promise an integration soon. Any help is always appreciated though, stay tuned for updates :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by stratus-ss** [comment]
I'd like to see this as well. I administer both Nextcloud and Zimbra. I would love to see this feature. Thanks for your work!

**Comment by joshp23** [comment]
CalDAV would make this unstoppable!

**Comment by samtuke** [comment]
We need this too. Currently using Harmonizely.

**Comment by skylarmt** [comment]
I will donate up to $50 to the project when this is implemented.  The sooner it's done the more money I'll donate.  Right now I have to manually add events to both my main calendar (synced between all my devices with Nextcloud) and E!A, which is not an acceptable long-term solution.

I'll even accept a script that runs via cron to sync the calendars with each other.  If I end up taking a couple hours and writing some code for this, I'm keeping the $50.

**Comment by mokkin** [comment]
I made the beginning here and created a bounty at [bountysourc.com](https://www.bountysource.com/issues/38115699-integrate-caldav-protocol-for-appointment-syncing)
Maybe others can join the bounty and @alextselegidis can give some information how much time/money will be needed.

**Comment by mocig** [comment]
Is the requested feature to connect/sync an easyappointment calendar over CalDAV
or to SHOW/IMPORT an external CalDAV ressource inside easyappointment?

**Comment by skylarmt** [comment]
@mocig I think the ideal feature would be new appointments appearing on a CalDAV calendar, and for events on the CalDAV calendar to appear in E!A as unavailable times.

**Comment by mpellegrin** [comment]
I just added 50$ to the bounty.

If you need an example for a CalDAV client, I added a software I wrote and I used to use : https://github.com/mpellegrin/weather-table ; it retrieves the events from CalDAV and parse it with ICS Parser.

I can also provide you a full access to a demo Nextcloud instance with the CalDAV server enabled to test/develop the software, as well as help to debug if you need.

**Comment by skylarmt** [comment]
@alextselegidis FYI the bounty for this issue is now at $200.

https://www.bountysource.com/issues/38115699-integrate-caldav-protocol-for-appointment-syncing

**Comment by JOduMonT** [comment]
> Unfortunately other tasks are being prioritized for the v1.4 so that the overall performance and user experience is enhanced. I cannot promise an integration soon.

of course https://harmonizely.com is not self hosted but it support CalDav since a while ago.

**Comment by mokkin** [comment]
I already tried this, but it has no group capabilities which means you have to register separate accounts per user and resource, no matter if it's the free or paid version.

**Comment by Escobar523523** [comment]
..... 5 mounths later :-)

First of all, thanks for easy appointments. 
Its a great piece of software.
But please, double please, tripple please with sugar on top, add caldav support!!!
If u need money to realize it, name it; if u need help, tell it. 
I am sure there will be a solution for all of this, just name it and dont let people beg for allmost 4 years!
I would love to use easy appointments in our small team (3 Users). 
It would totaly fit for our needs, if there would be caldav sync.

written in a mood created by a mixture of google_api_pain, frustration and a tiny bit of hope for change

**Comment by madkiss** [comment]
@alextselegidis How much money would it take to implement this and when could this be done?

**Comment by mokkin** [comment]
I definitely would support this with money too and I would really like it, if @alextselegidis could realize.

Otherwise, if he has no free capacities for it, I could imagine to collect money, give the job to a developer and ideally finish the implementation with a pull request to the main repository.

**Comment by alextselegidis** [comment]
Hello everyone, 

Thank you very much for your support and contributions on this. 

At the moment the v1.4.0 is almost ready and I'm working on the final touches before the beta comes out. 

More work is required for this item to be properly done, as you all know that synchronization is not an easy topic. 

Since there's much interest on this ticket, I've raised the bounty to 1000$, if this is met I will prioritize and make the changes for the next release. 

Otherwise it will still remain open but will be added in a future release.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mokkin** [comment]
The CalDAV feature should also consider different available calendars in one CalDAV server. This could be a second provider or a resource such as a room or a device required. Here is an example how other booking tool manage it:

![grafik](https://user-images.githubusercontent.com/2938748/97169827-02373e80-178b-11eb-8cf6-2fc2e8cae753.png)

I already pledged 100,- to the bounty and I am sure I can collect more. Are there any others wanting this asap?

**Comment by law** [comment]
In for $100.  Let's get this done!

**Comment by skylarmt** [comment]
I just increased my part of the bounty from $50 to $150.

**Comment by actionitservices** [comment]
Very interested also!
I am investigating this as I would like easyappointments to output a CalDav file as .ics or .xml from the MySQL database. 
.ics are standard file format, just need to know the tables, fields from easyappointments to output the .ics on a private url or file output to .ics as cronjob.
Then use vdirsyncer to sync with SOGo CalDav (.xml or .ics files) .. cronjob.
https://github.com/pimutils/vdirsyncer
I will also put in cash and/or time, if this can be done!
Cheers
Neil

**Comment by actionitservices** [comment]
Thinking of writing a perl or bash script using the easyappointments API output to a iCal or jCal file for syncing.
All that data is there in JSON from the API.
https://easyappointments.org/docs.html#1.3.2/rest-api.md
Cheers

**Comment by actionitservices** [comment]
Update: I should be resting this weekend, however made great progress on a bash script called easy2ical (v0.11.7) and couldn't help myself. 
-  So far it is one (1) way sync and I have only tested importing .ics files into Thunderbird, successfully.
-  I need to test the .ics output files with vdirsyncer and CalDav server.
-  Hopefully I can use vdirsyncer for CalDav and easy2ical .ics files, to merge, de-dupe and use results to PUT into easyAppointments as JSON to enable two (2) way sync.
- I will add easy2ical and README to my github site once it is ready for public release :-)
![image](https://user-images.githubusercontent.com/73832461/99893318-30486980-2cca-11eb-941d-85fe2ecf7a19.png)
Cheers
Neil

**Comment by actionitservices** [comment]
Update: EasyAppointments have added google calendar sync and some php cli commands in v1.4.1, however this is limited to google calendars only and some limitations. 
I have made major progress on my project. I have renamed it to easyDAV. 
- 2 way syncing is working :-)
- Currently I am using events from the assigned CalDAV calendar as unavailability in easyAppointments. 
- Future version will include CardDAV sync, to sync contacts with easyAppointment customers. This will allow events to be add as appointments, looking up the customers details in the easyAppointments DB. 
- Need to add delete/dedupe when going from  CalDAV to easyAppointments API.
- Need to test reoccurring events with above.
- Going to add a cli and webgui to register CalDAV calendar to the easyAppointments providerId and set vdirsync configuration files.
-  Plan to include a install script, to setup paths, cron and logrotate.
![image](https://user-images.githubusercontent.com/73832461/109244798-153a4800-782b-11eb-80e3-5e39b0746892.png)
Cheers
Neil

**Comment by mokkin** [comment]
That sounds great @actionitservices ! If there is any way we can support you, no matter if it's testing, translating or funding, please let us know as we are awaiting an open source CalDAV syncing booking tool since a long time.

**Comment by mokkin** [comment]
I've raised our bounty about $250,-. Now only $285,- are missing and it's up to the rest of the community to make this feature happen.

Is there anybody else who wants to have a Google free synchronisation for CalDAV (Nextcloud and others)?

**Comment by vitormattos** [comment]
Can I do this, how do I receive?
@mokkin, @skylarmt , @law

**Comment by skylarmt** [comment]
> Can I do this, how do I receive?

If you contribute code that closes this issue, you can go to the BountySource page and claim the bounty.

**Comment by mokkin** [comment]
> Can I do this, how do I receive?

Of course you can! Maybe you should coordinate with the maintainer of the project @alextselegidis

**Comment by vitormattos** [comment]
I have already created 4 PR in the project for different purposes from the requirements of this issue, I am waiting for comments, review and approval (#1044, #1048, #1049 and #1050)

**Comment by mokkin** [comment]
Unfortunately there seems to be no progress in the bounty nor in the development.
I have found a promising new project called [Calendso](https://calendso.com/) and the already have CalDAV on their roadmap: https://github.com/calendso/calendso/discussions/62

**Comment by vitormattos** [comment]
Hi @alextselegidis 

What do you think about creating an easyAppointments organization here on GitHub, moving the project to the organization and putting more people helping you in the management?

**Comment by alextselegidis** [comment]
Hello! 

Thanks for your support and contributions, all of them will be reviewed and integrated for 1.5.0, which is coming this fall. 

This ticket got delayed because of the implementation of other enhancements but it will make it for the next release. 

Keep up with the development progress! 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by jdaviescoates** [comment]
> This ticket got delayed because of the implementation of other enhancements but it will make it for the next release.

Sorry, just to be clear, do you mean CalDAV will be in 1.5 or 1.6? 

Thanks for all your great work! :)

**Comment by alextselegidis** [comment]
It will be in 1.5, which is scheduled for September/October 2021 🚀 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by ecutsa** [comment]
any updates for 1.5 ?

**Comment by jdaviescoates** [comment]
> any updates for 1.5 ?

You can follow progress here https://github.com/alextselegidis/easyappointments/milestone/9

**Comment by alextselegidis** [comment]
Hello! 

Almost all planned code maintenance is completed, which means that the only thing left to be done will be the implementation of the remaining 1.5 features before we reach the alpha release state. 

Just like @jdaviescoates, you can spectate the progress under the milestones page. 

Cheers!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Utopiah** [comment]
Very nice, I'm coming from Harmonizely but also deGoogle so having CalDav integration to work with e.g NextCloud but also Outlook is very exciting. I'm monitoring Releases, eager to be able to try!

**Comment by 12nick12** [comment]
This is the only missing thing right now for me. What would be a fair amount to donate to get this completed?

**Comment by KJ7LNW** [comment]
> Unfortunately there seems to be no progress in the bounty nor in the development.
> I have found a promising new project called [Calendso](https://calendso.com/) and the already have CalDAV on their roadmap: https://github.com/calendso/calendso/discussions/62

They are now cal.com, and also still open-source: https://github.com/calcom/cal.com

**Comment by alextselegidis** [comment]
Hello! 

Just a quick reminder here on this ticket: CalDAV support is coming with 1.5, which will be released this September 2022. 

Stay tuned!

Alex

**Comment by Utopiah** [comment]
Very exciting @alextselegidis . I recently cancelled my plan on Harmonizely due to their acquisition (I feel it's not part of a big "machine" rather than a carefully crafted product with a developer I could chat with directly) but that is precisely the 1 feature preventing me from switching to this solution.

Eager to try as soon as it's out!

**Comment by alextselegidis** [comment]
@Utopiah Glad to welcome you onboard, this is the last feature I'm working on for 1.5 so it will be soon be there for you to work with ;)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Utopiah** [comment]
This is especially exciting for me in terms of consulting. It means I could rely one could rely on payment e.g https://github.com/alextselegidis/easyappointments/pull/672 or more recently https://github.com/alextselegidis/easyappointments/pull/1310 to provide short consultancy sessions or workshops and rely on their own self-hosted open-source infrastructure, e.g a Jitsi server, even enabling/disabling feature based on the type of sessions booked. All that is impossible without a reliable way to insure that time slots are available. Can't wait to try that.

**Comment by olivierlambert** [comment]
Hey! Also taking a look here. Caldav support could be a game changer :) Eager to see that release!

**Comment by wokawoka** [comment]
+1

**Comment by skylarmt** [comment]
Here's some fairly recent PHP code I found for connecting to a CalDAV server as a client: https://github.com/agendav/agendav/tree/main/web/src/CalDAV

It has the same license as E!A so copying it won't create any legal issues.

**Comment by alextselegidis** [comment]
Hello @skylarmt, thanks for sharing!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Svetlana-T** [comment]
+1 would be good if this worked with self hosted Baikal server please, happy to test once it's available for testing

**Comment by giacomoarru** [comment]
Hey folks, I've just found out about this project today, as I wish to integrate a booking interface with Zimbra 10 OS, which works with Caldav.
It looks like the development to integrate Caldav is already ongoing, I just wanted to check what's missing, what is the supposed timeline and how can I help to get this done.

Jack

**Comment by alextselegidis** [comment]
Hello! 

CalDAV will be there in a couple of days. 

Please star and follow the project and stay up to date with the latest changes. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Almost there! 

![giphy](https://github.com/alextselegidis/easyappointments/assets/4527441/4387baf6-6ddd-4115-942f-79b535dcb64e)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by isgroup** [comment]
Any update on this feature? Thanks!!

**Comment by alextselegidis** [comment]
Feature completed on develop!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Fuseteam** [comment]
Yay!

**Comment by Aaaamu** [comment]
Hey, this is awesome news! I imediatly updated to 1.5.0. I also found your doc page that gives advice on the installation of baikal and ends with the following passage:
> While trying to enable the CalDAV sync from the Easy!Appointments calendar page, use the following credentials after clicking on "Enable Sync" > "CalDAV".

>    URL: http://baikal:8100/dav.php
    Username:
    Password: 

That sounds reasonable, but I can not find any button or link that says "enable sync" on the backend's calendar page! Neither can I find a caldav section under settings>integrations.

I had a look into the code, but also a search for the phrase "Enable Sync" didnt return any meaningful result… Can you help me out here? What am I missing. I have left disabled google calendar in my config.php

**Comment by skylarmt** [comment]
> I had a look into the code, but also a search for the phrase "Enable Sync" didnt return any meaningful result… Can you help me out here? What am I missing. I have left disabled google calendar in my config.php

I had the same issue. In the dropdown on the top-left of the calendar page, you need to select your provider name. Then the button will appear in the top-right.

**Comment by Aaaamu** [comment]
Thank you.!!! hat solved it. Suggest to add that information to the calDav.md
I take it, this works without setting the provider in the config file manually (which i did in the process)?
