### ISSUE TITLE
Mass-importing users via. MySQL

### ISSUE THREAD

**Issue by absolutejam** [alextselegidis/easyappointments#210]
Hi,

So far, I have managed to add a user manually into 'ea_users' and assign them a service in 'ea_services_providers', but I've hit a snag in 'ea_user_settings' - I don't know how the passwords/salts are generated.

If anyone could help, I'd greatly appreciate it.

Regards,
James.

**Comment by hermannschwaerzlerUIBK** [comment]
Hi James,

salts are generated in [generate_salt()](https://github.com/alextselegidis/easyappointments/blob/master/src/application/helpers/general_helper.php#L70-L74)
Such a salt is then used to hash the (plain text) password in [hash_password()](https://github.com/alextselegidis/easyappointments/blob/master/src/application/helpers/general_helper.php#L51-L63)

Greetings
Hermann

**Comment by absolutejam** [comment]
Thanks for pointing those out. I've generated a random salt along the same lines as yours (I guess it doesn't really matter as long as the salt is stored), but my hash came out differently.

From the `hash_password` function, I can see that we're prepending the plaintext password with the first half of the salt and appending the second half of the salt. But I don't know what the following is doing...
```
    for ($i = 0; $i < 100000; $i++) {
        $hash = hash('sha256', $hash);
    }
```

Sorry to be a pest, but I'm trying to wrap up a little script to import directly into the databases from CSV so I can easily edit my users.

Thanks for your continued support.

**Comment by hermannschwaerzlerUIBK** [comment]
Hi James,
first for the records: I am not one of the developers so these are not "my lines". :-)

Yes you are right, you can choose any salt as long as you store it in the respective column of the users table.
The for-loop is doing nothing but taking the salted hash and re-hashing it 100,000 times. I guess to make brute force attacks much more expensive.
Are you writing that import-script in php? 
* If yes just take and use these to functions don't implement them on you own.
* If no, why not? :-)

Greetings
Hermann

**Comment by alextselegidis** [comment]
Hermann is right, the the passwords are hashed multiple times with the salt string to make rainbow tables useless in case of a database compromise. So this is just a security measure. 

https://en.wikipedia.org/wiki/Rainbow_table

**Comment by absolutejam** [comment]
Thanks for your replies. I thought it was as much, but I've just never seen it done before. I guess, as long as the password they enter matches it at the end, nobody cares!

I'm not using PHP purely because I have no PHP knowledge. It will probably be written in PowerShell (As I can sync it directly from AD) or Python.

Thanks again!
