### ISSUE TITLE
Changed business logic

### ISSUE THREAD

**Issue by alexbn71** [alextselegidis/easyappointments#212]
moved start working hour at 08:00 but calendar shows always not working from 09:00 (the default value)

![image](https://cloud.githubusercontent.com/assets/20998190/19203674/d419ebec-8cd8-11e6-9046-84323afcd847.png)

![image](https://cloud.githubusercontent.com/assets/20998190/19203685/e74cbfa0-8cd8-11e6-8a9b-6051bd63d7c4.png)

**Comment by alextselegidis** [comment]
I guess you already figured this out, but you will have to change the working plan of the provider as well. The working plan of the settings page stands for the default plan.

**Comment by alexbn71** [comment]
Yes I understood, at this point I do not understand what is for the same
settings in the general section if in calendar view it is used those of
provider.

Il 8 ott 2016 10:15, "Alex Tselegidis" <notifications@github.com> ha
scritto:
