### ISSUE TITLE
Problem when customers have same email address

### ISSUE THREAD

**Issue by Koppadeke** [alextselegidis/easyappointments#213]
Hi,

Firstly, many thanks for alextselegidis for a great program!

We have issue with calendar, we have customers who are working in same company and have same email address (for an example customerservice@company.com)

When customer1 books appointment with his personal information, appoinments show correctly in backend calendar

But when customer2 books appointment with his personal information then backend calender shows two appoinments for customer2 and customer1 name is not show in backend calendar. Appoinment that was booked by customer1 is still in calendar but with customer2 personal information.

I suppose that if customers have same email address calendar updates last customer info for all appointment that was made with same email address?

Best Regards,
Koppa

**Comment by alextselegidis** [comment]
Hello Koppa, 

yeah that's right. The email address is used to distinguish the customer records and whenever customers use the same email the customer's info are getting updated. 
 
I think this behavior is pretty reasonable if you want to have appointment history for a specific customer, so I would advise your customers to use separate email addresses for the appointments. 

Or maybe you have another suggestion how to solve this?

**Comment by Koppadeke** [comment]
Hello Alex,

Thank you for your answer!

In our case if customer´s info is updated when name and email match for previous record, this will eliminates problem.
This method will also help if customer books appointment with his email address to another person who don´t have email address (for example older relative)

Can you tell me which file handels this record update, I can try to modify code to fit our purposes?

- Koppa

**Comment by alextselegidis** [comment]
Hmm ok I see you point, and it actually makes sense. There could be a problem though when the customers makes a typo in the name and then the records are not matched. 

In any case you can change the current behavior by modifying the /application/models/customers_model.php. There you will find the "exists" method which only checks for an email.

**Comment by Koppadeke** [comment]
Thanks for the advice, I successfully modified the code.
