### ISSUE TITLE
Combined Calendar

### ISSUE THREAD

**Issue by RobinFlikkema** [alextselegidis/easyappointments#214]
I would like to have a Calendar View which shows all appointments. At the moment it is only possible to show the appointments for one provider, or for one service AFAIK

**Comment by alextselegidis** [comment]
Hello, this feature is implemented in the upcoming v1.2. You can test it now by downloading the [Alpha package](https://github.com/alextselegidis/easyappointments/releases/download/1.2.0-alpha.1/easyappointments_1.2.0_alpha.1.zip) and setting the calendar view to "table" for all the provider records. 

The Beta package will be available soon with some bugfixing :)

**Comment by RobinFlikkema** [comment]
Thank you for the answer, I'll check the alpha out!
