### ISSUE TITLE
Delete customer problem

### ISSUE THREAD

**Issue by matteoventuri7** [alextselegidis/easyappointments#215]
Chrome 53.0.2785.143 m
Delete customer problem. URL: /index.php/backend/customers

**Comment by alextselegidis** [comment]
Can you tell me under which version the error happens?

Are there any error logs (console or logs directory)?

Thanks

**Comment by matteoventuri7** [comment]
Hi. Version 1.1 variable id customer is undefined. Customer list contains
only one customer and i try to delete it.

Il 17 ott 2016 22:09, "Alex Tselegidis" <notifications@github.com> ha
scritto:

**Comment by matteoventuri7** [comment]
I think it is graphic problem. When i try to delete a customer, i see dialog confirmation eand i see only on button (cancel) and when i click it i abort operation.
![unnamed image](https://cloud.githubusercontent.com/assets/5465117/19478696/d63a41c4-9543-11e6-94d9-7412070d2746.png)

**Comment by alextselegidis** [comment]
I was able to reproduce the problem. It only happens if italian is set as the displayed language! I will fix this for v1.2, thank you very much for posting :)
