### ISSUE TITLE
Wrong appointment period ->related to Issue #193

### ISSUE THREAD

**Issue by ChamesBont** [alextselegidis/easyappointments#220]
Hi Alex,

thank you for fixing the Bug #193 . I recognized another Bug which is related with this one.
I you set the start time an choose an appointment (between 30th October and 25th March), the end time is calculated wrong. I seems, that the appointment time is subtracted from the start time, so the end time is behind the start time.

[https://github.com/alextselegidis/easyappointments/issues/193]

**Comment by ChamesBont** [comment]
I think the problem is in this lines (289-295 -> backend_calendar_appointments_modal.js):

// Automatically update the service duration.
            $.each(GlobalVariables.availableServices, function(indexService, service) {
                if (service.id == sid) {
                    var start = $('#start-datetime').datepicker('getDate');
                    $('#end-datetime').datepicker('setDate', new Date(start.getTime() + service.duration * 60000));
                    return false; // break loop
                }
            });

**Comment by alextselegidis** [comment]
Yeah you are right, it seems that overall the "getDate" is making weird things. I will replace it there as well. Thanks for posting 👍

**Comment by ChamesBont** [comment]
Thanks for fixing.
But if you first set the start time for the appointment and then choose an appointment from the list, the end time is calculated wrong too.

**Comment by alextselegidis** [comment]
Oh, it seems that there is a problem with the "setDate". I'll fix it :)

**Comment by ChamesBont** [comment]
I noticed some other strange thing. If I set an appointment with the following start time 06/12/2016 10:00 then I get this end time 12/06/2016 10:30.
So the month and the day is switched.

**Comment by alextselegidis** [comment]
Ok I'll check this out as well.

**Comment by alextselegidis** [comment]
@ChamesBont I've updated the datetimepicker addon and it seems that it works correctly. Could you double-check it please?

**Comment by ChamesBont** [comment]
I've tested it too. Now it's working correctly.
Great work ;)

**Comment by alextselegidis** [comment]
Great!
