### ISSUE TITLE
Division for company departmens so i can pick one during reservation

### ISSUE THREAD

**Issue by p0zi** [alextselegidis/easyappointments#222]
It will be good to have possibility to define company departments with different addresses so we can pick one during reservation.

**Comment by alextselegidis** [comment]
This request is also a bit generic. Currently it is possible to create various providers which could also represent different departments. The addresses are not displayed in the frontend anyway but services can be grouped and contain the respective description with address info etc. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
