### ISSUE TITLE
Add support for online payment methods

### ISSUE THREAD

**Issue by p0zi** [alextselegidis/easyappointments#228]

**Comment by alextselegidis** [comment]
This ticket is too generic. In the future payment support will be added but gradually for each payment gateway. I also plan to make this modular so a module system needs to be built first. So leave it for later :) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
