### ISSUE TITLE
Open a workday or hours

### ISSUE THREAD

**Issue by gertje5** [alextselegidis/easyappointments#229]
Normal the most of us are not working on Sunday but sometimes there is a Sunday or some hours of an normally closed evening I want to be open.
Is there a way to fix that?

**Comment by alextselegidis** [comment]
Well unfortunately you cannot explicitly enable some specific days out of the working plan. I will mark this as a feature. Thanks for posting :)

**Comment by popod** [comment]
This issue is resolved by working plan exceptions : https://easyappointments.org/2021/01/26/working-plan-exceptions-explained/

Right ?

**Comment by alextselegidis** [comment]
Hello @popod, you are totally right, I must have forgotten this 😁 

Closing as this is already solved 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
