### ISSUE TITLE
Time not displaying on page 2 and can't access backed

### ISSUE THREAD

**Issue by kawish** [alextselegidis/easyappointments#23]
My config file is good and the software was also working till yesterday 

But now it says doesn't display any time slot on the booking page neither is it showing the backend

My host is Sixserve (Free Plan)

**Comment by alextselegidis** [comment]
Can you provide a link so that I can see it live?

**Comment by kawish** [comment]
The link is
www.medcare4u.com/appointment/

**Comment by alextselegidis** [comment]
Have you registered any services or providers from the backend? Check the "Configuration" section from this page:

https://github.com/alextselegidis/easyappointments/wiki/Installation-Guide

**Comment by alextselegidis** [comment]
I just saw that you too have problems with mod_rewrite. I guess that you will not be able to solve it because you are in a free hosting plan. You will have to wait for the new version where I will remove all mod_rewrite stuff so that you will not such problems.

**Comment by kawish** [comment]
Sorry. But maybe you are mistaken

My hosting plan is from GO DADDY
Ultimate plan

**Comment by kawish** [comment]
Please assist me on how to fix this .
I have a paid hosting plan from GO DADDY

**Comment by alextselegidis** [comment]
ok, if you go to the login page without the url rewrite you can see that the app is working

http://www.medcare4u.com/appointment/index.php/user/login

but we get an error in other pages. Can you check the apache error logs and provide information here?

**Comment by kawish** [comment]
The error page is totally blank (Screenshot as attachment)

Nothing happens after clicking on the login button on the backend page

**Comment by alextselegidis** [comment]
There must be some error because the AJAX requests are getting an HTTP 500 status code which means "Internal Server Error". 

Try to enable the CodeIgniter log functionality: 
https://easyappointments.wordpress.com/2015/04/27/easyhints-enable-error-logging

**Comment by kawish** [comment]
After enabling the log functionality , there is only one file in the
specified directory

Named - index.html

Directory path - public_html/appointment/application/logs

Attaching the file as attachment

**Comment by kawish** [comment]
Alex please reply with a solution ASAP

**Comment by alextselegidis** [comment]
Hello 

Now I get the following messages in my browser's console: 

Failed to load resource: the server responded with a status of 404 (Not Found)
www.medcare4u.com/:1 XMLHttpRequest cannot load http://medcare4u.com/appointment/appointments/ajax_get_available_hours. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.medcare4u.com' is therefore not allowed access. The response had HTTP status code 404.

Do you want to try uploading the code from the GitHub repository. It is in dev state right now but it might work for your case. 

Reply back when you've done it.

**Comment by kawish** [comment]
As suggested by you , I have uploaded the files from GITHUB

Please provide step by step info on how to configure it and access the backend

The directory of the appointment system is

www.medcare4u.com/appointment

**Comment by kawish** [comment]
As suggested by you , I have uploaded the files from GITHUB

Please provide step by step info on how to configure it and access the backend

The directory of the appointment system is

www.medcare4u.com/appointment

**Comment by edioilha** [comment]
Hi there! It is 500 warning now!! Its file/folder permission! How is it there, look for permissions!

**Comment by edioilha** [comment]
One more thing! Is the folder name /appointments/ or /appointment/?

**Comment by kawish** [comment]
The folder is named as appointment

**Comment by alextselegidis** [comment]
I have the 403 error  - Permission denied.

Also when I visit the following link I get another message which I pretty sure should fill some entries in the error logs.

http://www.medcare4u.com/appointment/index.php

But overall I suppose this must be just a permission problem.
