### ISSUE TITLE
Order providers alphabetically (Forename or surname)

### ISSUE THREAD

**Issue by absolutejam** [alextselegidis/easyappointments#231]
Hi,

I tried having a go at this myself, but it turns out I'm useless with PHP. Any chance this could be implemented, or is there dirty hack to sort the entries that are provided on-page? This affects the front and back end.

Thanks!

**Comment by alextselegidis** [comment]
Hello, someone asked a similar question in the support group. Unfortunately this is not possible at the moment but there is a quick fix you could apply with some basic programming skills ;) 

Take a look at the this thread: https://groups.google.com/forum/#!category-topic/easy-appointments/P5jZXWtDhOE

I have created a new feature ticket for your requests: https://groups.google.com/forum/#!category-topic/easy-appointments/P5jZXWtDhOE
