### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by gonzalo-** [alextselegidis/easyappointments#232]
Hi guys,

I have a blank page after installation, my setup is a little bit different as the normal:

OpenBSD 5.9
PHP-5.6.18
httpd (native OpenBSD web server)
MySQL

class Config {
    // ------------------------------------------------------------------------
    // General Settings
    // ------------------------------------------------------------------------
    const BASE_URL      = 'https://agenda.domain.com';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = TRUE;

    // ------------------------------------------------------------------------
    // Database Settings
    // ------------------------------------------------------------------------
    const DB_HOST       = '127.0.0.1';
    const DB_NAME       = 'DB';
    const DB_USERNAME   = 'USR';
    const DB_PASSWORD   = 'PASS';

On httpd's logs only can see this:

[03/Nov/2016:12:55:36 -0300] "GET / HTTP/1.1" 200 0

No errors.

Any ideas?

**Comment by alextselegidis** [comment]
Hmm, I cannot understand what the problem can be. Do you have any error logs in /application/logs directory?

**Comment by gonzalo-** [comment]
No, nothing, just the index:

application/logs> ls -al
total 12
drwxr-xr-x   2 www  www  512 Nov  3 17:43 .
drwxr-xr-x  15 www  www  512 Feb 14  2016 ..
-rw-r--r--   1 www  www  114 Feb 14  2016 index.html

**Comment by alextselegidis** [comment]
Is it possible to install apache and test it again? I havent' tested the app with httpd yet.

**Comment by gonzalo-** [comment]
Tryed also with nginx and the same, keep in mind that OpenBSD use chroot() on web servers.

**Comment by alextselegidis** [comment]
I've never configured a web server within OpenBSD to be honest, so I cannot tell what could go wrong. Maybe someone else with more experience on this could help. Try posting in the [support group](https://groups.google.com/forum/#!forum/easy-appointments).

**Comment by alextselegidis** [comment]
Have you been able to solve your problem?

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by gonzalo-** [comment]
No, no really, no time now. Sorry

**Comment by alextselegidis** [comment]
This is unfortunate, but thank you anyway for posting :) 

I will close this issue though as there isn't anything I can fix for your case. Feel free to post again once you have more info. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
