### ISSUE TITLE
Duplicate availabilities with short service duration and unavailabilities ignorance.

### ISSUE THREAD

**Issue by absolutejam** [alextselegidis/easyappointments#236]
One of my users is experiencing a weird bug - They have all the time windows in the day presenting to the user multiple times in the front end. As well as this, these time windows are ignoring the 'Unavailable' periods.

![image](https://cloud.githubusercontent.com/assets/6817942/20099355/0649efa0-a5b0-11e6-9149-f2570703f288.png)

And nothing looks awry in MySQL:
![image](https://cloud.githubusercontent.com/assets/6817942/20099381/2199b7f4-a5b0-11e6-833f-1125d46744f2.png)

When I check the back-end, her calendar looks perfectly normal
  - An 'unavailable' window that I have added for all providers that blocks out everything except appointments on the 17th,
  - Manual 'unavailable' windows that the user has added.
  - Successfully registered appointments by users.

**Comment by absolutejam** [comment]
Tried removing some of the duplicate 'unavailable' slots but the issue persists.

**Comment by alextselegidis** [comment]
Hmm, just being curious but how's that you have appointments that do not have a customer or service IDs?

**Comment by absolutejam** [comment]
They're 'unavailable' slots? Or are they still missing data? Which IDs do you mean?

**Comment by alextselegidis** [comment]
I mean the NULL values for the `hash`, `id_users_customers`and `id_services` columns in your database screenshot.

**Comment by absolutejam** [comment]
Erm, I dunno haha. The top two were manually inserted via a SQL statement for all my providers but the others weren't. I can perhaps check another user to see if they have the same NULL values? I just assumed that I unavailable = 1 then the others would be NULL

Get Outlook for iOS




On Wed, Nov 9, 2016 at 6:45 PM +0000, "Alex Tselegidis" <notifications@github.com> wrote:












I mean the NULL values for the hash, id_users_customersand id_services columns in your database screenshot.

**Comment by alextselegidis** [comment]
Could you please make a backup of your database, remove the records that have the NULL values and then try again.

**Comment by alextselegidis** [comment]
Oh sorry, I just saw that unavailable entries (or google synced events) can accept NULL values in these fields, so this won't be a problem. Could you please send me your installation URL with a PM (alextselegidis@gmail.com).

**Comment by absolutejam** [comment]
Just letting you know that it seems to occur to all of the providers once they hit a threshold of a certain amount of bookings (I'm not sure how many) as the staff with a few bookings it hasn't occurred to, but it is now affecting everyone once they get a few bookings on the system.

If you need access to the box, I can give you it.

**Comment by alextselegidis** [comment]
Yeah, it seems that there is a bug in the availabilities calculation. Access to the box would be great in order to examine the issue internally. 

Thanks for reporting ;)
