### ISSUE TITLE
Installation process not detailed enough to create a Docker image

### ISSUE THREAD

**Issue by matgnt** [alextselegidis/easyappointments#237]
Hi all,

I'm trying to install easyappointments in a Docker container.
I think the installation guide provided here:
http://easyappointments.org/docs.html#1.2.0/installation-guide.md
is not enough. Questions I have:
Which php modules have to be enabled?
Are the provided versions of apache/php/mysql are really very strict? Or should it also work with slightly newer versions?
Could you maybe even provide a minimum php.ini config?

After I point my browser to the install directory, I just get a page loading forever. After hours of hours of debugging through the code, I figured out it might be an issue with the sessions. The save_path was empty and thus, it didn't do anything. After providing this, at least I get a 200 OK (and a session file written to that directory). But still, nothing more. No tables in the DB, etc. Mysqli works fine from an example php script I've copied into the same directory. phpinfo() works as well.

If you could bring a bit more light into the requirements, that would be great.

If anyone else is interested in a Docker image, let me know. Or maybe someone already created one?

Cheers,
Matthias

**Comment by alextselegidis** [comment]
Hello Matthias, 

I understand what you mean with your message and I will try to improve the server requirements description of the documentation. There are already [some existing Docker containers out there](https://github.com/alextselegidis/easyappointments/issues/176) which might help you install the project or even give some ideas on how to enhance your own container. 

I am planning to release an official Docker image at some point in the near future so stay tuned :) 

Thanks for posting!
