### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sofrr** [alextselegidis/easyappointments#238]
Hello,
After uploading the files at web server ( in subdirectory)  and editing config.php , i get HTTP ERROR 500.
The error log : 
[12-Nov-2016 13:56:44 Europe/Athens] PHP Parse error:  syntax error, unexpected '[' in .../public_html/easyappointments/application/config/config.php on line 345

My web server configuration : 

Web Server : Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.3.29
Database Version	5.6.34

**Comment by alextselegidis** [comment]
Hello! 

As the error states there is an unexpected value in your config.php file. Find the breaking '[' and remove it. I double checked the released package and there was no issue there.

**Comment by hermannschwaerzlerUIBK** [comment]
Hi Alex,

most probably this is related to #207 as @sofrr is maybe (he didn't tell us) trying to use easyappointments 1.2 with PHP 5.3.29.

Greetings
Hermann

**Comment by alextselegidis** [comment]
Yeah Herman you are right! 

I think I replied too fast in this issue. So there you have it: Easy!Appointments minimum PHP requirement is v5.4.

http://easyappointments.org/docs.html#1.2.0/installation-guide.md

**Comment by sofrr** [comment]
Hello !
Indeed Herman I tried to use easyappointments_1.2.0 in web server with PHP Version: 5.3.29.
So i must contact hosting company to upgrade PHP version to 5.4

Thanks

**Comment by alextselegidis** [comment]
Actually I would advise you to update to 5.6 because the other versions are not supported any more. 

http://php.net/supported-versions.php
