### ISSUE TITLE
Provide dedicated URL for separate provider/service bookings.

### ISSUE THREAD

**Issue by kawish** [alextselegidis/easyappointments#24]
Provide a systems by which we don't have to select a service and a service provider instead we can have a URL of the service page of a provider where the user can directly book an appointment with only that service provider

By using this method we can make a profile page of a service provider on our website and then put a button which would be linked to the service page of the service provider in order to book an appointment

Whereas the current selection process can be used to book appointments with all service providers as well

**Comment by alextselegidis** [comment]
This is a very nice idea indeed! I will consider it for a future release :)

**Comment by kawish** [comment]
Please consider it in v 1.1

Also what is the expected release date of v1.1

**Comment by alextselegidis** [comment]
Unfortunately I cannot tell. I used to have a plan for this release but I do not have the time to be precise, so I cannot say anything for sure. It will be sometime soon though so stay tuned.

**Comment by alextselegidis** [comment]
Thanks to a donation from Calvin Uijlen this issue will be added to v1.2

**Comment by alextselegidis** [comment]
Done
