### ISSUE TITLE
Set default sessions save_path directory because many servers do not have this option set.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#241]
By default CodeIgniter will read the "session.save_path" directive in "php.ini" in order to get the correct place for the sessions storage. This directive though might not be there which will lead to an application crash. 

**Important:** The sessions directory need to be writable.

**Comment by davidbgeek** [comment]
Any ETA on when 1.2.1 will be released? I couldn't access setup without manually incorporating this commit in my installation.

**Comment by alextselegidis** [comment]
I cannot give a certain date but it will be released really soon (in a matter of some weeks). Follow the project to get updates on new releases and updates :)

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
