### ISSUE TITLE
Add new system-wide setting for remove "Any Provider" option of the booking page.

### ISSUE THREAD

**Issue by jirijanata** [alextselegidis/easyappointments#247]
Hello,

I added two Providers and now I can see in booking appointment this two providers and also -Any provider-. Can you add option to disable this "-All providers-"?

There is also a bug - if I choose "-All providers-", I can see only appointments for first provider and only for current month (I have appointments for first provider on every Tuesday and for second provider on every Wednesday).  I can create "new issue" specially for this bug, if you need it.

![image](https://cloud.githubusercontent.com/assets/14040091/20396281/f77f89de-ace5-11e6-85ae-b58fe70e3445.png)

![image](https://cloud.githubusercontent.com/assets/14040091/20396328/1ccb9354-ace6-11e6-9f3b-3d83721f4fd3.png)

**Comment by p0zi** [comment]
Yes i admint there's a bug when we select "Any Provider" it loads only first found provider and not merge them all for selected service. I have quick solution for this if you need a fixture asap. Update method Appointments::ajax_get_unavailable_dates() with this code:

`    /**
	 * [AJAX] Get Unavailable Dates
	 *
	 * Get an array with the available dates of a specific provider, service and month
	 * of the year. Provide the "provider_id", "service_id" and "selected_date" as GET
	 * parameters to the request. The "selected_date" parameter must have the Y-m-d format.
	 *
	 * @return string Returns a JSON array with the dates that are unavailable.
	 */
	public function ajax_get_unavailable_dates() {
		try {
			$provider_id = $this->input->get('provider_id');
			$service_id = $this->input->get('service_id');
			$selected_date = new DateTime($this->input->get('selected_date'));
			$number_of_days = (int)$selected_date->format('t');
			$unavailable_dates = array();

            $provider_ids = array();

			// Handle the "Any Provider" case.
			if ($provider_id === ANY_PROVIDER) {
				//$provider_id = $this->_search_any_provider($service_id, $this->input->get('selected_date'));

                for ($i=1; $i <= $number_of_days; $i++) {
                    $current_date = new DateTime($selected_date->format('Y-m') . '-' . $i);

                    if ($current_date < new DateTime(date('Y-m-d 00:00:00'))) { // Past dates become immediately unavailable.
                        continue;
                    }

                    $provider_id = $this->_search_any_provider($service_id, $current_date->format('Y-m-d'));

                    if (null !== $provider_id && !in_array($provider_id, $provider_ids)) {
                        $provider_ids[] = $provider_id;
                    }
                }

				if (empty($provider_ids)) { // No provider is available in the selected date.
					for ($i=1; $i<=$number_of_days; $i++) {
						$current_date = new DateTime($selected_date->format('Y-m') . '-' . $i);
						$unavailable_dates[] = $current_date->format('Y-m-d');
					}
					echo json_encode($unavailable_dates);
					return;
				}
			} else {
			    $provider_ids = array($provider_id);
            }

			// Get the available time periods for every day of this month.
			$this->load->model('services_model');
            $service_duration = (int)$this->services_model->get_value('duration', $service_id);
			$availabilities_type = (int)$this->services_model->get_value('availabilities_type', $service_id);

			for ($i=1; $i<=$number_of_days; $i++) {
				$current_date = new DateTime($selected_date->format('Y-m') . '-' . $i);
                $has_available_hours = false;

				if ($current_date < new DateTime(date('Y-m-d 00:00:00'))) { // Past dates become immediately unavailable.
					$unavailable_dates[] = $current_date->format('Y-m-d');
					continue;
				}

                foreach ($provider_ids as $provider_id) {
                    $empty_periods = $this->_get_provider_available_time_periods($provider_id,
                            $current_date->format('Y-m-d'));

                    $available_hours = $this->_calculate_available_hours($empty_periods, $current_date->format('Y-m-d'),
                            $service_duration, false, $availabilities_type);

                    if (!empty($available_hours)) {
                        $has_available_hours = true;
                        break;
                    }
                }

				if (!$has_available_hours) {
					$unavailable_dates[] = $current_date->format('Y-m-d');
				}
			}

			echo json_encode($unavailable_dates);
		} catch(Exception $exc) {
            echo json_encode(array(
                'exceptions' => array(exceptionToJavaScript($exc))
            ));
        }
	}`

**Comment by jirijanata** [comment]
Thank you very much for your quick response. It's not so urgent. Do you also have a solution just for "disabling" Any Provider?

**Comment by p0zi** [comment]
Assuming you have any provider defined you can comment out those lines from file src/assets/js/frontend_book.js

// Add the "Any Provider" entry.
            if ($('#select-provider option').length >= 1) {
                $('#select-provider').append(new Option('- ' +EALang['any_provider'] + ' -', 'any-provider'));
            }

**Comment by alextselegidis** [comment]
I also think that this entry must be optional for anyone that might want to enable it. I will create a setting in the admin in a future relase. Thanks for posting :) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by kealist** [comment]
Is there a reason why this bug is labeled as an enhancement rather than a bug?

**Comment by alextselegidis** [comment]
Because there is no bug in the "Any Provider" functonality, there are only cases where it makes sense to have this option and cases that it doesn't :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by kealist** [comment]
Hmm.  There is a bug and fix mentioned above....while we didn't test the fix, it doesn't appear to have been mentioned as incorporated.

"any provider" has proven a huge headache by causing double-booking fairly often and since updating from 1.1.2 to 1.2 recently (to see if the double booking issue--which was mentioned above, now not showing all available times (Not showing all providers availability).  We had to manually disable it because it just causes confusion for clients.

**Comment by alextselegidis** [comment]
Ok I see your point, either as a bug or enhancement it will be addressed with the next release. Just for your info there are some users that requested this feature and therefore I included it by default but I understand that such feature shall stay optional. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bullmoose20** [comment]
In the commit that I made, this is an option you can enable ot disable in the back office general settings.

**Comment by alextselegidis** [comment]
Got a solution proposal in the support group: 

https://groups.google.com/forum/#!category-topic/easy-appointments/d9VnNSYdNU0

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
Hi Alex,

You'll find a patch applicable for 1.3.1 in the develop branch as stated in Issue #475.
Hope it helps.
