### ISSUE TITLE
UPGRADING TO 1.2 /update does not work

### ISSUE THREAD

**Issue by bcherup** [alextselegidis/easyappointments#250]
Issue 1 . Going to the /update link with the backend returns you to the login page. 

Issue 2 . I'm unable to login as the page does not change but if I enter the wrong password it will notify

**Comment by alextselegidis** [comment]
So I assume that you've uploaded the new version files, opened to the /backend/update link on your browser, redirect to /backend/login page where you cannot log in. 

Do you get an error when you try to log in, except from invalid credentials?

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bcherup** [comment]
I get no error when trying to login only when using invalid credentials.

**Comment by icecoldfire** [comment]
I think I have the same issue. The request give back this response:

```
<!DOCTYPE html>
<html lang="en">
<head>
<title>Database Error</title>
<style type="text/css">

::selection{ background-color: #E13300; color: white; }
::moz-selection{ background-color: #E13300; color: white; }
::webkit-selection{ background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	-webkit-box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}
</style>
</head>
<body>
	<div id="container">
		<h1>A Database Error Occurred</h1>
		<p>Error Number: 1064</p><p>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SET `last_activity` = 1480330883, `user_data` = 'a:3:{s:9:\"user_data\";s:0:\"\"' at line 1</p><p>UPDATE  SET `last_activity` = 1480330883, `user_data` = 'a:3:{s:9:\"user_data\";s:0:\"\";s:14:\"captcha_phrase\";s:5:\"7fmkv\";s:7:\"user_id\";i:84;}'
WHERE `session_id` = '89bc236c40a070ba30e5c6258eb42a81'</p><p>Filename: libraries/Session.php</p><p>Line Number: 306</p>	</div>
</body>
</html>
```

**Comment by icecoldfire** [comment]
Is the issue coming from that I use an MySQL server and not an MariaDB server?

**Comment by icecoldfire** [comment]
#200 Has the same problem as it looks. The know solution is to use an clean installation?

**Comment by alextselegidis** [comment]
@icecoldfire 

I think you'll have to modify the session handling in your installation. CodeIgniter is quirky in some servers where session configuration is not fixed. Open your `/application/config/config.php` file and replace the session configuration with the following: 

```
$config['sess_driver']             = 'files';
$config['sess_cookie_name']		   = 'ea_session';
$config['sess_expiration']		   = 7200;
$config['sess_save_path']          = __DIR__ . '/../../storage/sessions';
$config['sess_match_ip']		   = FALSE;
$config['sess_time_to_update']	   = 300;
$config['sess_regenerate_destroy'] = FALSE;
```` 

Create a new directory with write permissions at `/storage/sessions` and try again. The PHP sessions will now be written in the filesystem.

**Comment by icecoldfire** [comment]
@alextselegidis 

The solution you have proposed doesn't work for my installation. An clean installation gives me the same error.

**Comment by icecoldfire** [comment]
I have resolved the problem. Deleting all the files of the previous installation and then uploading the new files work. Was this a problem of my ftp client or give old files that aren't overwritten problems?

Maybe change the update strategy on the website?

**Comment by alextselegidis** [comment]
Hmm, this is strange indeed. I think the error does not occur in every server as I have tried it on my servers without having any problems. I plan to make the update procedure easier in the future, but I need to implement some other stuff beforehand. 

In any case the message states that the error comes from the session handling of CodeIgniter. I have to search the functionality there further. But I'm glad you solved your problem :) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
