### ISSUE TITLE
Fix displaying issues on the Frontend

### ISSUE THREAD

**Issue by MrRhub** [alextselegidis/easyappointments#26]
Strangely, with a too long description for a service, I ended-up with some positionning problems (text behind the bottom part of the frontend).

I found at that the .frame-container had a fixed height. 
I simply commented the height definition line to solve the problem.

#book-appointment-wizard .wizard-frame .frame-container {
    /*height: 370px;*/
    margin-bottom: 10px;
}

Then we want also to let the footer stay on the bottom part. A simple clear:both; solves the issue.

#book-appointment-wizard #frame-footer {
    clear:both;
    padding: 10px;
    text-align: center;
    border-top: 1px solid #EEE;
    background: #FAFAFA;
}

Hoping it can help someone else ;)
Have a good day,
Rhub

**Comment by alextselegidis** [comment]
Hi there, is this for v1.0 or v1.1?

**Comment by tmcb82** [comment]
When will 1.1 be released with bootstrap?

**Comment by alextselegidis** [comment]
I cannot tell a date for sure but once the main features are implemented I will post updates about an upcoming BETA version.
