### ISSUE TITLE
Google Calendar Issue

### ISSUE THREAD

**Issue by thevdo** [alextselegidis/easyappointments#263]
Getting this error:

TypeError: Cannot read property 'getUTCFullYear' of null
![screen shot 2016-12-11 at 2 08 48 pm](https://cloud.githubusercontent.com/assets/24507621/21080623/826a7a04-bfab-11e6-959a-40d5c97e0bb7.png)

**Comment by alextselegidis** [comment]
Does the google calendar syncing work in the backend?

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by thevdo** [comment]
I got it working by enabling calendar syncing - it seemed after that was setup the "Add to Google Calendar" was functional.

It was all working nice for about 2 days then suddenly it has stopped when i go to my url /book/ I just get a blank page. 

I wonder if this is related to me setting up the google calendar sync as that is the last thing I did?

**Comment by thevdo** [comment]
With DEBUG_MODE on here's what I am getting:

> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: mkdir(): Invalid path
> 
> Filename: drivers/Session_files_driver.php
> 
> Line Number: 117
> 
> A PHP Error was encountered
> 
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at myserverblablabla/book/system/core/Exceptions.php:272)
> 
> Filename: core/Common.php
> 
> Line Number: 568
> 
> An uncaught Exception was encountered
> 
> Type: Exception
> 
> Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.
> 
> Filename: /myserverblablabla/book/system/libraries/Session/drivers/Session_files_driver.php
> 
> Line Number: 119

**Comment by alextselegidis** [comment]
Edit your php.ini session.save_path value and set it to a valid path on your server.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
