### ISSUE TITLE
Backend login problem with php 7.10

### ISSUE THREAD

**Issue by matteoventuri7** [alextselegidis/easyappointments#269]
Fresh installation. PHP 7.10
I try to login into backend but login page refresh without errors and ask again username and password.

Changed to PHP 7.0.14 all is ok!

**Comment by alextselegidis** [comment]
I haven't tested the application yet with PHP 7.1. This will be done once there's a stable release of this new version. 

Thanks for posting though ;) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
