### ISSUE TITLE
Installation problem(online)

### ISSUE THREAD

**Issue by huxis** [alextselegidis/easyappointments#271]
Hi,

I have an issue when I try to install EasyAppointments, I filled the config.php and I added a new folder in the storage folder because I had an issue with sessions storage. Now I'm getting a 503 Error Page not found with a title tag : Error 404 when the installation is starting (index.php/installation/index). 

If someone have an idea, thanks ! :)

Application -> config
    $config['sess_save_path']          = __DIR__ . '/../../storage/session/';

**Comment by alextselegidis** [comment]
Hi there, 

this must be a server misconfiguration problem. Make sure that you have the correct BASE_URL value in the root config.php and that no URL rewrite messes the request. 

For test purposes, I would also recommend you to create test file (test.php) in the root folder of the project and then try to access it from the browser. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by huxis** [comment]
I've checked the BASE_URL value and it seems good (no trailing slash). I've tried to access to test.php and it worked.

**Comment by xymantec** [comment]
Yes, it sounds most likely a permissions issue, make sure your application has read and write access to that folder. If you're using apache its www-data

**Comment by xymantec** [comment]
Can you tell me more about your setup, What OS, you using apache? what version of php?

**Comment by huxis** [comment]
It's a modx cloud server(Linux), with an nginx server. The version of php is 5.6.26.
The installation folder of easyappointments, is on chmod 755,

Thanks for your help @xymantec :-)

**Comment by huxis** [comment]
I've found that when I install EasyAppointments in the root of the server, it works, but I can't let it in the root, it's only when I try to install it in a subfolder. Any similar case with mine ? 

Thanks !

**Comment by alextselegidis** [comment]
Is this a subdomain?

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by huxis** [comment]
@alextselegidis No it's not

**Comment by alextselegidis** [comment]
Could you please send me a link of your installation? alextselegidis@gmail.com

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by huxis** [comment]
We found another way to install it, the server was the problem. 
Thanks for your help !

**Comment by alextselegidis** [comment]
Glad you've solved your problem :)

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by shakisha** [comment]
> We found another way to install it, the server was the problem.
> Thanks for your help !

hey @huxis , i have exactly your same problem and i cannot figure out what can be the issue. 

Can you help? I will be very glad if you can give me an hint about it

**Comment by huxis** [comment]
> 
> 
> > We found another way to install it, the server was the problem.
> > Thanks for your help !
> 
> hey @huxis , i have exactly your same problem and i cannot figure out what can be the issue.
> 
> Can you help? I will be very glad if you can give me an hint about it

I wish I could help you, but we installed it on a shared hosting on another of our servers.

We didn't had access to the modx server configuration and we didn't had the time to do further verifications.

I wish you a good luck in your research :)
