### ISSUE TITLE
possibility to search customer via API...

### ISSUE THREAD

**Issue by danysz** [alextselegidis/easyappointments#272]
Hi

Today I understand that is possible to make a "search" by using api ?q=<keyword>

How is possible if I want to search by more than one keyword ?

Thanks

Daniel

**Comment by alextselegidis** [comment]
Hello, 

unfortunately what you want is not possible. The API integrates more or less the same functionality as the app itself which means that you can only filter by one keyword at a time. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
