### ISSUE TITLE
customer is not "selected"

### ISSUE THREAD

**Issue by danysz** [alextselegidis/easyappointments#274]
Hi

I have the latest version installed.
For some reason sometimes the "select" (click) on a customer in the list of customers is not selecting the customer. The background color is changing the color but the "green" margin is not added so I can't edit or delete or anything else.
The "data" in the fields is update to the relevant data but not the appointments.

I found the problem on Safari Version 10.0.2 (12602.3.12.0.1) and Firefox 50.1.0
Refreshing the page few times makes the system work again...

Thanks

Daniel

**Comment by alextselegidis** [comment]
Hello, I cannot reproduce the problem, how many customers do you have?

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by danysz** [comment]
about 5-6...
we can make a Skype or any other remove view/control session so you can see it..
