### ISSUE TITLE
configuration problem need help 

### ISSUE THREAD

**Issue by Ashok537** [alextselegidis/easyappointments#275]
i downloaded everything , added database in mysql , installed , all i can see when i am opening src is 

JD & Co
1
2
3
4
Select Service & Provider

Select Service  
Select Provider  
Next
Powered By Easy!Appointments | English | Login

this thing . 
when i open index.php/backend it says 
Page Not Found - Error 404

Unfortunately the page you requested does not exist. Please check your browser URL or head to another location using the buttons below.

Book Appointment Backend Section

what do i do . what should be the base url ? 
i am doing it in my xampp

**Comment by alextselegidis** [comment]
The BASE_URL must point to your installation root directory without a trailing slash. 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
