### ISSUE TITLE
Update FullCalendar dependency.

### ISSUE THREAD

**Issue by kazi-shahin** [alextselegidis/easyappointments#276]
Hi,
I am using Easy Appointment updated version where Full Calendar Version is v1.6.1. But Full Calendar updated version is : v3.1.0  

Easy appointment uses full calendar version v1.6.1, which has a time selection bug. 
below the link for reference:
https://github.com/fullcalendar/fullcalendar/issues/2945 

This is latest example of Full Calendar where time slot click is working fine:
http://jsfiddle.net/slyvain/y8ugsvnL/ 

Is there are any updated version where Easy Appointment is using latest Full Calendar?

**Comment by kazi-shahin** [comment]
@alextselegidis Thanks for your initiative. Any updates for this issue?

**Comment by alextselegidis** [comment]
Will be updated with v1.3 :)

**Comment by kazi-shahin** [comment]
Great. When you are planing to bring that update?
