### ISSUE TITLE
Install problem (Parse error in /application/config/config.php on line 345)

### ISSUE THREAD

**Issue by illuswing** [alextselegidis/easyappointments#277]
Do a clean install and modify the config.php file with nothing,

Try to turn on debug mode and got this error message.

`Parse error: syntax error, unexpected '[' in /php/appointment/application/config/config.php on line 345
`

**Comment by hermannschwaerzlerUIBK** [comment]
Hi @illuswing 
looks like you are using php version 5.3 (or less). Minimum version for easyappointments 1.2 is 5.4.
Looks like @alextselegidis forgot to update the wiki (although he "promised" to do it in  #207).

Greetings
Hermann

**Comment by illuswing** [comment]
Thanks @hermannschwaerzlerUIBK 

Had found out the problem couple minutes ago, thanks for reply!
