### ISSUE TITLE
problem in installation on xamp

### ISSUE THREAD

**Issue by willingtone** [alextselegidis/easyappointments#281]
Unexpected Issues
$name setting does not exist in database: company_name

#0 C:\xampp\htdocs\easyappointments\src\application\controllers\Appointments.php(69): Settings_Model->get_setting('company_name')
#1 [internal function]: Appointments->index()
#2 C:\xampp\htdocs\easyappointments\src\system\core\CodeIgniter.php(514): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\easyappointments\src\index.php(353): require_once('C:\\xampp\\htdocs...')
#4 {main}

**Comment by alextselegidis** [comment]
Hi there, 

you'll have to install the app before using it. Refer to the documentation guide: http://easyappointments.org/docs.html#1.2.0/installation-guide.md

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Chetanr** [comment]
Hi,
I get the same error. I have attached the screenshot as well for your reference.
<img width="1438" alt="Screen Shot 2019-11-26 at 8 43 04 pm" src="https://user-images.githubusercontent.com/5353603/69646199-650ceb00-108d-11ea-9742-88d40e7fc994.png">

**Comment by alextselegidis** [comment]
@Chetanr you're missing some entries in the database. 

Follow the guide of this video for a complete installation

https://www.youtube.com/watch?v=TnyVVOF0oh0

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
