### ISSUE TITLE
Advice asking

### ISSUE THREAD

**Issue by dukeMaster** [alextselegidis/easyappointments#292]
Hi.
I would like to know: would it be possible to manage several iterations of this app from another web app (via a dashboard)?

Because, actually I'm working on a project which aims to provide an appointment manager to some enterprises. And those appointments manager will be managed from another web app.
Where I got stuck is that client must be able to make some appointments with each of these enterprises via a form and I just can't figure out how to handle this.
I also don't know how to make several iterations of easyAppointments on a single server.

If you could give me some tips to handle this, it would be nice.

**Comment by circa10a** [comment]
could run multiple instances of my docker image and publish different ports - https://hub.docker.com/r/circa10a/easyappts/

**Comment by alextselegidis** [comment]
Yeah containers and virtualization is a really good idea but you'll still have to create the dashboard that handles all the data.

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by dukeMaster** [comment]
Yeah of course I'll create this dashboard. I'm just looking for a way to have multiple versions of this app.
I'm going to try circa10 link.
Thanks for answer.
