### ISSUE TITLE
PHP 7 compatibility 

### ISSUE THREAD

**Issue by tommybaloukz** [alextselegidis/easyappointments#293]
Hello,

I was wondering if there would be any compatibility issues if upgrading to PHP 7?

Thank you, 

Tommy

**Comment by alextselegidis** [comment]
Hi there, 

sure you can update to PHP7, there were not problems so far :) 

<small>
<table>
<tr>
<td><img src="https://dl.dropboxusercontent.com/u/27545985/easyappointments/ea-logo-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
