### ISSUE TITLE
Unable to install easyappointments with NGINX

### ISSUE THREAD

**Issue by CDevCom** [alextselegidis/easyappointments#294]
Hello,

I'm trying to install "easyappointments" with nginx server but it's not working.

**Versions** 

- Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linu
- PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
- nginx version: nginx/1.6.2
- mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3

Here is my nginx configuration file (ea)

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html/ea;
	index index.php index.html index.htm

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

  location ~* \.php$ {
    try_files $uri =404

    fastcgi_intercept_errors on;

    fastcgi_index   index.php;
    fastcgi_pass    unix:/var/run/php5-fpm.sock;

    include fastcgi_params;

    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
  }

}
```

**Explanation**

I'm getting php & mysql running with nginx, but when i'm trying to browse to the "easyappointments" directory it's not working and it returns a 404 not found, and the URL seems a bit weird 

1. I browse to : "http://my-server-ip/index.php"
2. I get : "http://my-server-ip/index.php/installation/index"

Could you please help me resolve this ?

**Comment by ndastur** [comment]
You need the apache equivalent rewrite rules. Try adding
```
if (!-e $request_filename){
                rewrite ^(.*)$ /index.php?/$1 last;
        }
```

to your location / block directive

**Comment by alextselegidis** [comment]
Have you been able to install the app?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by radical-equanimity** [comment]
@ndastur Could you provide an example? Here's what I've got now but still strange address and 404:

`location /book {
        alias /var/www/easyappointments;
        index index.php;
        location ~ \.php$ {
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          include fastcgi_params;
          if (!-e $request_filename){
                rewrite ^(.*)$ /index.php?/$1 last;
          }
          fastcgi_param SCRIPT_FILENAME $request_filename;
      }
}`

**Comment by alextselegidis** [comment]
@radical-equanimity A quick search gave me those: 

- https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter
- http://kbeezie.com/nginx-and-codeigniter/
- https://stackoverflow.com/questions/19347306/nginx-rewrite-rule-for-codeigniter
- https://stackoverflow.com/questions/32113089/configuring-codeigniter-on-nginx

I hope this helps :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by radical-equanimity** [comment]
Thanks Alex, good work with this software. I was able to find a solution- here is my /etc/nginx/sites-available/easyappointments:
```
location /book {
        alias /var/www/easyappointments;
        index index.php;
location ~ \.php {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # A handy function that became available in 0.7.31 that breaks down
        # The path information based on the provided regex expression
        # This is handy for requests such as file.php/some/paths/here/

        fastcgi_param  PATH_INFO          $fastcgi_path_info;
        fastcgi_param  PATH_TRANSLATED    $document_root$fastcgi_path_info;

        fastcgi_param  QUERY_STRING       $query_string;
        fastcgi_param  REQUEST_METHOD     $request_method;
        fastcgi_param  CONTENT_TYPE       $content_type;
        fastcgi_param  CONTENT_LENGTH     $content_length;

        fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
#        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param  SCRIPT_FILENAME    $request_filename;
        fastcgi_param  REQUEST_URI        $request_uri;
        fastcgi_param  DOCUMENT_URI       $document_uri;
        fastcgi_param  DOCUMENT_ROOT      $document_root;
        fastcgi_param  SERVER_PROTOCOL    $server_protocol;

        fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
        fastcgi_param  SERVER_SOFTWARE    nginx;

        fastcgi_param  REMOTE_ADDR        $remote_addr;
        fastcgi_param  REMOTE_PORT        $remote_port;
        fastcgi_param  SERVER_ADDR        $server_addr;
        fastcgi_param  SERVER_PORT        $server_port;
        fastcgi_param  SERVER_NAME        $server_name;

        fastcgi_pass   unix:/var/run/php5-fpm.sock;
        fastcgi_index  index.php;
}
}
```

**Comment by alextselegidis** [comment]
@radical-equanimity Great to read this!

Hope it'll serve you well :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sfratini** [comment]
Just wanting to confirm that the fix posted by @ndastur works! I was having the same issue with nginx. Just in case this is my conf file (nginx + php7 + fpm):

```
server {

	index index.php;

	server_name easyappointments.mydomain.com;
	
	root /var/www/html/easyappointments;

	location ~ \.php$ {
       include snippets/fastcgi-php.conf;
       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
	}

	if (!-e $request_filename){
        rewrite ^(.*)$ /index.php?/$1 last;
    }

	access_log /var/log/nginx/easyappointments-access.log nginx;
	error_log /var/log/nginx/easyappointments-error.log;

}

```

**Comment by jeffmikels** [comment]
If anyone else stumbles upon this, you don't need to use an if block, you can simply use this:

	location /appointments {
		try_files $uri $uri/ /appointments/index.php;
	}

notice the slashes... they are important

Also, this assumes that you already have your server set up to process php.
