### ISSUE TITLE
Nothing happens when clicking on Install button

### ISSUE THREAD

**Issue by peterbrinck** [alextselegidis/easyappointments#295]
Hi

I've looked through the issues, and in the docs, and I've tried different things to fix the issue, but nothing seems to work.

Whatever I try, the URL is `index.php/installation/index`, and the `Install Easy!Appoitments` button doesn't work and gives no javascript error in console.

I have no clue what to look for now
Any ideas?

**Comment by LukeMcLachlan** [comment]
is 
    const DEBUG_MODE    = TRUE; 
in the config.php file

**Comment by peterbrinck** [comment]
It is now
Should a debugbar or something else be visible on the frontend?

**Comment by LukeMcLachlan** [comment]
yes you should see a bunch of errors now. when I installed the problem was the temporary sessions directory, there isn't one on my shared host, so I had to specify:

`session.save_path = "/tmp"`

in the php.ini file.

**Comment by peterbrinck** [comment]
No errors are shown

**Comment by LukeMcLachlan** [comment]
What about under dir storage/logs have any error file's been created there

**Comment by peterbrinck** [comment]
I have a log file from friday, but that's something with the database, I misspelled the username
Besides that, nothing

**Comment by LukeMcLachlan** [comment]
wish I could help more, sorry.

**Comment by alextselegidis** [comment]
So are there any entries in the apache error log file? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacobandrews96** [comment]
I figured it out! I've been having this issue for awhile. With Mamp I was running PHP 7.1.1 & I switched it so it was running PHP 5.6.30 - I wasn't sure if it's work with 7.0.15. So I reverted to 5.6.3 and it works :)
