### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by pcmartkl** [alextselegidis/easyappointments#299]
Suggest to include Unavailable by Providers.

**Comment by alextselegidis** [comment]
Could you describe me with some examples what is that you mean by "Unavailable by Providers"? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
