### ISSUE TITLE
Add color coding configuration for services.

### ISSUE THREAD

**Issue by pcmartkl** [alextselegidis/easyappointments#300]
Suggest to have color code for Services to display on the calendar.

**Comment by alextselegidis** [comment]
This one is cool! I'll mark is as a feature :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by JLCarbwood** [comment]
Are you considering this for the next release?

**Comment by alextselegidis** [comment]
Closing this in favor of #422 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
