### ISSUE TITLE
Automatically reload the backend calendar events. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#301]
As new events might be booked constantly it would makes sense to refresh the backend calendar automatically (every # seconds), without showing the loading spinner to the user. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Harryjholmes** [comment]
Hi 
Did you manage to complete this?

**Comment by alextselegidis** [comment]
@Harryjholmes Setting this for v1.4.0 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
