### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by jacek-1210** [alextselegidis/easyappointments#303]
Hi,

sorry, my english is not very well.

I can't install easyappointments. Debug in config.php (in root EA folder)  is set TRUE, in browser above initial page I get:

_A PHP Error was encountered
Severity: Warning
Message: mysqli::real_connect(): Persistent connections are disabled. Downgrading to normal
Filename: mysqli/mysqli_driver.php
Line Number: 204_

When I fill initial page and push "Install EA", I get:

_The operation could not complete due to unexpected issues._

Details -> _The installation could not be completed due to an unexpected issue. Please check the browser's console for more information._

Into logs is:

![easyapp1](https://cloud.githubusercontent.com/assets/13505686/24239754/6ad29364-0faf-11e7-851a-06c595467a32.jpg)

is the same error or another & what about this ? I can't downgrading php

**Comment by alextselegidis** [comment]
This is a server configuration issue. Edit `application/config/database.php` and set `pconnect => FALSE`. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacek-1210** [comment]
Thx. Ok, so, I changed pconnect -> FALSE. Now, I dont get pconnect error, I erase database and create new, import structure.sql & data.sql, but still can't go initial page - I get: 

_The installation could not be completed due to an unexpected issue. Please check the browser's console for more information._

In logs I found: 

_$name settings does not exist in database company_name_

I write manual company name into database and go one step more. Now I get: 

_AJAX Error: SyntaxError: Unexpected token < in JSON at position 0_

I look at:

![easyapp2](https://cloud.githubusercontent.com/assets/13505686/24290570/bfa1a0b6-1085-11e7-8546-20c35b20306c.jpg)


in the red circle is double slash - is it right or error ? Problem with symlinsk ? .htaccess ?

**Comment by jacek-1210** [comment]
Hmm, I try v 1.1 and this version -probably- works. Problem is only on v 1.2 (?)

**Comment by alextselegidis** [comment]
Remove all the tables in your database and head to `http://{ea-installation}/index.php/installation`. You will need to reinstall the app as some data are not present. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by henkvalk** [comment]
Hi I have the same problem. I tried to remove the tables and reinstall it more times.
The problem stays;

In my chrome console I see the following javascript error after loading the appointment page:

```
frontend_book_api.js:246 Uncaught TypeError: unavailableDates.indexOf is not a function
    at _applyUnavailableDates (frontend_book_api.js:246)
    at Object.<anonymous> (frontend_book_api.js:225)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```
﻿
Do you have any idea?

​

**Comment by henkvalk** [comment]
Solved by adding timezone in index.php

date_default_timezone_set('Europe/Amsterdam');

**Comment by alextselegidis** [comment]
@tomvbb You should go for a newer version (currently v1.3.1). 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by tomvbb** [comment]
Hi, thanks for your response,
I have tried v1.3.1 and v1.3.2 and both give ajax error, status code 403 forbidden, as shown in picture

![screenshot6044](https://user-images.githubusercontent.com/42912019/45252201-158cb300-b353-11e8-854f-54249f10070e.jpg)

**Comment by alextselegidis** [comment]
@tomvbb This seems to be a server issue, unfortunately I cannot tell why the server is giving 403. 

Can you please check your Apache/NGINX configuration and make sure there's no 403 rule for such URLs? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by tomvbb** [comment]
Hello,

many thanks for your help. It's solved. The problem was that I force HSTS in htaccess, but in config.php  ther const BASE_URL was http:// instead of https://

now it's installed and works fine.

best regards
