### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Daical** [alextselegidis/easyappointments#304]
hello
struggling to see easy appointments
error:
A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: controllers/Appointments.php
Line Number: 28

can you help

**Comment by alextselegidis** [comment]
Hi, can you make sure that the connection credentials are correct (in root config.php file)?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
