### ISSUE TITLE
EasyBlue Time Called in random order

### ISSUE THREAD

**Issue by jacobandrews96** [alextselegidis/easyappointments#307]
<img width="196" alt="screen shot 2017-03-27 at 11 12 33 pm" src="https://cloud.githubusercontent.com/assets/24920817/24387443/26e83158-1343-11e7-890c-00f80d90690a.png">
--
Hi, the image above shows the times are displayed not in order. Is this through the function that calls them? If so, how can I fix?

This error only started last night.

**Comment by jacobandrews96** [comment]
Also, 6:30 doesn't show up on any of the days at all.

**Comment by bullmoose20** [comment]
Did the sort i mentioned help with the order problem? As for missing times, it's usually related to the store hours and the working plan for the service provider. Can you share that to shed some light?

**Comment by jacobandrews96** [comment]
<img width="1422" alt="screen shot 2017-03-28 at 8 02 25 am" src="https://cloud.githubusercontent.com/assets/24920817/24403888/f213c2c2-138c-11e7-850f-0c54b1183391.png">
-
Above shows that the times for 6:30 are mostly open, yet on the days that have it open still do not show 6:30. In both the providers working plan and the overall plan has 6:30 available, there are also no appointments at that time currently too. 
--
I just did the sort and that works, so thank you for reminding me haha!

**Comment by bullmoose20** [comment]
Do me a favor and change the interval time from 30 to 15 and see what happens.

I think there is some funky logic that they use that creates a buffer....I was seeing this on both builds at the time but had too many other things to investigate that I left it to later. I actually saw it at the closing time as well, where the last appointment would not show up as an availability.

By setting the time from 30 to 15, I think the system will only buffer the first and last 15 minutes of the day if my theory is correct.

Sorry I can't be more informative on this but Craig should be awake in about 3 hours. :-)

**Comment by bullmoose20** [comment]
Here is something else that I discovered and hoping that Craig can shed some light. After having discovered that the root of my gateway timeout was when I set the value to 60 for the interval. Well, that little line exists in 3 different places, but they are not all set to 60. Two are set to 15 and one is set to 60.
![2017-03-28 08_45_04-microsoft edge](https://cloud.githubusercontent.com/assets/12549033/24405534/3aef7288-1393-11e7-82a4-d83a7b303ff0.png)

Craig, was this set like this on purpose, or was it simply an oversite?

I am adding this "interval time" as a backend setting so I will keep all three of these in sync as opposed to out of sync.

Thanks,
Nick

**Comment by bullmoose20** [comment]
So in my version that I will be submitting to Craig to merge with his Easyblue, I will have the following added to the settings page:
![2017-03-28 09_01_50-photos](https://cloud.githubusercontent.com/assets/12549033/24406158/7233a1cc-1395-11e7-9189-a4370c39c599.png)

In addition to this, I will be adding a setting to:
- "Show Price of Service when Price is 0" - yes/no
- "Show "-Any Provider-" - yes/no

And at some time in the future, if time permits, the ability to set css colors and give some people options instead of just blue (Craig) and green (Alex)

Any other settings that I should consider to add to the backend?

**Comment by jacobandrews96** [comment]
<img width="431" alt="screen shot 2017-03-28 at 2 36 08 pm" src="https://cloud.githubusercontent.com/assets/24920817/24421337/e7240516-13c3-11e7-9e9f-f897bdfea88d.png">


This is how I fixed the ordering of the times to match AM/PM - just using the sort puts 12(noon) last. 
-
I think those are great that you thought of, I'll try and think of something else to add as well

**Comment by bullmoose20** [comment]
There is another one that Craig wants I think... start of week. either Monday to Sunday (EasyBlue) or Monday to Sunday (E!A).

**Comment by alextselegidis** [comment]
Hello everyone! 

You may post issues that have to do with EasyBlue fork on its own repository 

https://github.com/CraigT543/EasyBlue

Thanks :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
