### ISSUE TITLE
Can not delete secretary 

### ISSUE THREAD

**Issue by tommybaloukz** [alextselegidis/easyappointments#308]
Hello, 

When I try to delete the a secretary from the administrator section I get the following error, 

Uncaught TypeError: this.delete is not a function
    at HTMLButtonElement.<anonymous> (backend_users_secretaries.js:123)
    at HTMLButtonElement.<anonymous> (jquery-ui.min.js:11)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.q.handle (jquery.min.js:3)

Any ideas on how to fix this issue?

Thanks

**Comment by alextselegidis** [comment]
Hi, thanks for posting. 

I already found the error and it will be corrected with the latest release. For now you can download the patched file: 
[backend_users_secretaries.zip](https://github.com/alextselegidis/easyappointments/files/919478/backend_users_secretaries.zip)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
