### ISSUE TITLE
can anybody help me to intergrate easy appointments into my website project ?? i need it for university 

### ISSUE THREAD

**Issue by jihadismail8** [alextselegidis/easyappointments#314]

**Comment by alextselegidis** [comment]
Hello, please refer to specific problems that you might have. It may be better for you to use the official support group for your integration. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
