### ISSUE TITLE
Calendar doesn't update when Attendants number changes

### ISSUE THREAD

**Issue by Abbashan** [alextselegidis/easyappointments#315]
Hi, 
People make an appointment when the Attendants number for a service was 1 ,  so now next 2 weeks are unavailable. Then i changed the Attendants number to 2 but still next 2 weeks are unavailable. 

I think for now it should be available for next 2 weeks but it doesn't. 

Best.

**Comment by alextselegidis** [comment]
Hello, 

unfortunately I cannot reproduce the problem, when I change the attendants number to 2, I'm getting quite normally new slots for appointments.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
After further testing the issue can be reproduced. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Abbashan** [comment]
Hi Alex, 

When this bug will be fixed could you give information?

Best Regards.

**Comment by Abbashan** [comment]
Hi Alex,

Are there any update for this bug?

Best Regards.
