### ISSUE TITLE
Send email notifications to admin and secretary users. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#316]
Admin and secretary users must receive scheduling notifications as well if the "Receive Notifications" setting is enabled. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by guiqis** [comment]
Any news about it? I've installed the script but only the costumers are receiving email notifications
