### ISSUE TITLE
wordpress plugin

### ISSUE THREAD

**Issue by valentinomarra** [alextselegidis/easyappointments#322]
Hi,

the Wordpress plugin is no more available on WP.org?

**Comment by alextselegidis** [comment]
Hi there, 

unfortunately there were some complication with the wordpress plugin and I'll have to upload it again. 

For now you can download it from the official Easy!Appointments website. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
