### ISSUE TITLE
Force customer to only one appointment

### ISSUE THREAD

**Issue by humboldtux** [alextselegidis/easyappointments#327]
As is, a customer could book mulltiple appointments. I would like to force customer to book only one appointment. How can i do this please?

**Comment by humboldtux** [comment]
At best only one appointment by service, but one for the entire lifecycle of the account would work fine too.

**Comment by alextselegidis** [comment]
You can add a new if statement in the Appointments_model.php when validation happens that will check if the current customer account has already an appointment. 

If yes then you can through an Exception and the user will not be able to proceed with the booking. 

File to edit `/application/models/Appointments_model.php`, modify the `validate` method. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Benhalsing** [comment]
Hi alextselegidis,

How could the validation be that only one customer registers per day?

Thanks,

**Comment by alextselegidis** [comment]
Getting the number of appointments per day would look like this: 

```
$this->db->get_where('ea_appointments', ['DATE(start_datetime)' => '2019-02-19'])->num_rows(); 
```

With this in hand you can check if it's equal 1 or greater and if show throw an exception. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Benhalsing** [comment]
Thanks for the help,
But I can not validate

$client = $appointment['id_users_customer'];
            $query = $this->db->simple_query("SELECT * FROM ea_appointments WHERE id_users_customer = '$cliente' and date(start_datetime) = '2019-02-21'");
            if ($query->num_rows > 0)
            {
                throw new Exception('Ya se registro');
                
            }

Thanks

**Comment by Benhalsing** [comment]
is Work!

$num_rows = $this->db
            ->select('*')
            ->from('ea_appointments')
            ->where("date_format(start_datetime,'%Y-%m-%d')", date('Y-m-d', strtotime($appointment['start_datetime'])) )
            ->where('id_users_customer', $appointment['id_users_customer'])
            ->get()->num_rows();
            if ($num_rows > 0)
            {
                throw new Exception('Already Registered');
            }

**Comment by Benhalsing** [comment]
Hi alextselegidis,

It works well for me that a user can not register on the same day but as an administrator does not allow me to edit because he is already registered on the same day as he could solve it?

Thanks
