### ISSUE TITLE
hitting install and getting "The operation could not complete due to unexpected issues."

### ISSUE THREAD

**Issue by vivioney** [alextselegidis/easyappointments#331]
Hi Ive installed database, changed config.php loaded the installation page and I'm getting "The operation could not complete due to unexpected issues." checked error log and it states:

index:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
/easy//index.php/installation/ajax_install Failed to load resource: the server responded with a status of 500 (Internal Server Error)
installation.js:71 The installation could not be completed due to an unexpected issue. Please check the browser's console for more information. Object error Internal Server Error
/easy//index.php/installation/ajax_install Failed to load resource: the server responded with a status of 500 (Internal Server Error)
installation.js:71 The installation could not be completed due to an unexpected issue. Please check the browser's console for more information. Object error Internal Server Error
/easy//index.php/installation/ajax_install Failed to load resource: the server responded with a status of 500 (Internal Server Error)
installation.js:71 The installation could not be completed due to an unexpected issue. Please check the browser's console for more information. Object error Internal Server Error
/easy//index.php/installation/ajax_install Failed to load resource: the server responded with a status of 500 (Internal Server Error)
installation.js:71 The installation could not be completed due to an unexpected issue. Please check the browser's console for more information. Object error Internal Server Error
/easy//index.php/installation/ajax_install Failed to load resource: the server responded with a status of 500 (Internal Server Error)
installation.js:71 The installation could not be completed due to an unexpected issue. Please check the browser's console for more information. Object error Internal Server Error

Any clue anyone?

**Comment by alextselegidis** [comment]
There are error logs on your server that describe the PHP error. Could you please post them here? 

https://unix.stackexchange.com/questions/38978/where-are-apache-file-access-logs-stored

http://blog.codeasite.com/how-do-i-find-apache-http-server-log-files

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Any updates on this? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Simon55** [comment]
Hi, i have the same issues non errors are in server logs..to be something wrong. just Crome not found source //index.php/installation/ajax_install  not found Any help ? Thank you.

**Comment by alextselegidis** [comment]
@Simon55 Can you share a link where I can try the installation?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
