### ISSUE TITLE
How can I make the application directly offer the first available date instead of suggesting the current date?

### ISSUE THREAD

**Issue by ahmedi2l** [alextselegidis/easyappointments#335]
Hello
Thank you for this wonderful application.
I tested it and it works very well. Brovo for work.

How can I make the application directly offer the first available date instead of suggesting the current date?

For example, if I put the application online now (in June) and wish the first booking date starts in 3 months (in September). How to make the booking calendar offer the first available date directly in September instead of suggesting the current date with a message asking to select another date.

If this is not possible via the web interface, in what part of the code can I change this?

Have you used a framework to develop the application? If yes which one?

Thanks!

**Comment by alextselegidis** [comment]
Hello @ahmedi2l, I'm glad you like the app! 

Unfortunately there is no current way to do this directly so you will have to create full date unavailabilities till the next date come. 

There is already [another issue](https://github.com/alextselegidis/easyappointments/issues/165) that requests the same thing so I will close this one. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ahmedi2l** [comment]
Thanks for your reply.
But I managed to do almost what I want by changing the "defaultDate" value for datepicker in assets/js/frontend_book.js file
I put
DefaultDate: Date (2017,9,1)
instead of
DefaultDate: Date.today ().

To automate that, we could imagine doing something like that
DefaultDate: getTheNextAvailableDate ()

What do you think?

And you did not answer me about the used framework.
If you agree for this change, I could try to do it and make a pull request.

**Comment by alextselegidis** [comment]
You can use the default date property of the datepicker to set the initial date but the use case you are requesting is a bit more complicated than that. 

There must be a mechanism in the system that will block any appointment that is within an inactive date period and this will also have to be displayed and handled in the back-end section of the app. 

This requires more time to impement and this is why it's not integrated yet. Feel free to make your pull requests if you want though and we can further discuss the required modifications there. 

PS: I'm using the CodeIgniter framework (v3.1.4). 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by olivdee** [comment]
Γεια σου Αλέξη,

I was wondering why the suggested quick & dirty solution produces very unexpected results.
For example if I am using `defaultDate: Date (2022,4,1)`, the calendar shows all kinds of different days + months in 2028, changing on each browser refresh... Is this a bug, or am I missing another setting crucial for this quickfix to work? Using EA v1.4.1.

Thanks in advance!

Με εκτίμηση,
Κωνσταντίνος
