### ISSUE TITLE
Full day appointment with multiple attendants are not being taken into concern during availabilities generation.

### ISSUE THREAD

**Issue by dthunder746** [alextselegidis/easyappointments#337]
Hey,

Trying to create one fullday appointment per week, with a maximum of 8 attendees per appointment. Settings as following:

Service Settings
- Service duration: 480 mins (8 hrs)
- Attendants Number: 8

Provider Settings
- Working Plan: Tuesday - 9:00 to 17:00 (8 hour work day) 

When I test the bookings, I can only have 1 attendee per appointment, not 8. If I reduce the service duration to an hour (for example), I am able to book multiple attendees per appointment.

I can think of an obvious work around for this, which is having one service per attendee, but I'd like to know what I'm doing wrong.

thanks!

**Comment by alextselegidis** [comment]
Hi, 

I tried to reproduce the problem but it worked fine in my setup. 

Can you check if your provider's working plan has any breaks? These must be removed in order for him to accept full day appointments. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by dthunder746** [comment]
Hi Alex,

Thanks for taking a look at this.
My provider has no breaks. The company working plan also reflects the providers working plan, same day and hours with no breaks. I have attached screenshots of the service and provider settings, maybe I've messed up one of the simple settings?
![ss1](https://user-images.githubusercontent.com/13672246/27313066-8f066230-559e-11e7-9b8b-89de0929cc97.png)
![ss2](https://user-images.githubusercontent.com/13672246/27313073-944cd7ec-559e-11e7-982a-d0e1c85e6c4e.png)
![ss3](https://user-images.githubusercontent.com/13672246/27313087-a4a65c1c-559e-11e7-9e08-a607d8f71e3f.png)

Really scratching my head over this one...

**Comment by alextselegidis** [comment]
I'm sorry, I cannot really reproduce this ... 

Are you using E!A v1.2.1? 

![github-test-provider](https://user-images.githubusercontent.com/4527441/27515635-7f043d54-59a8-11e7-9dd9-72708a741d14.png)

![github-test-working-plan](https://user-images.githubusercontent.com/4527441/27515638-81042b78-59a8-11e7-8525-7419aae1c3f8.png)

![github-test-service](https://user-images.githubusercontent.com/4527441/27515639-834807b0-59a8-11e7-8405-8c3183829e08.png)

![github-test-booking](https://user-images.githubusercontent.com/4527441/27515640-85745232-59a8-11e7-9434-62e7c7bb0e3b.png)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by dthunder746** [comment]
Hey,

Yes I'm using version 1.2.1
Are you able to book more than one attendee into that appointment? Because that's the issue i'm having. The appointment will appear, but I can only book in one person instead of 8.

**Comment by alextselegidis** [comment]
Hi yes you are right, you cannot add another appointment after the first one.

It will be fixed with v1.3

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by dthunder746** [comment]
Hey Alex,

Glad I'm not crazy! Looking forward to v1.3, do you have a rough plan for the release date?

thanks!

**Comment by alextselegidis** [comment]
Of course you're not crazy, I am!

I do not have a release date for v1.3, I'm gather some important features and bugfixes such as yours. Follow the project and stay up to date ;)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Elvin-Xhimitiku** [comment]
i think the multiple attendands still has problems guys. i am using 1.3.2 and its still not working
