### ISSUE TITLE
Installation and configuration problem

### ISSUE THREAD

**Issue by halalyon** [alextselegidis/easyappointments#338]
My server is Apache 2.4, php version is 5.6, Mysql version is 5.6. I think it suit for requiement. After following the installation guide, I face Http 500 Error on my server. When I debug the error, I found some lines in the index.php have problems. 
require_once __DIR__ . '/vendor/autoload.php';
require_once BASEPATH.'core/CodeIgniter.php';
I cannot figure them out.

**Comment by alextselegidis** [comment]
As it seems some files are missing from your repository. 

Make sure that the `vendor` and `system` directories are correctly uploaded.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by halalyon** [comment]
Which version do I need to clone? I try master code, but debug shows me it lacks "autoload_static.php" file in composer. When I try development version, it still doesn't work.

**Comment by alextselegidis** [comment]
Try the [bundled package](https://github.com/alextselegidis/easyappointments/releases/download/1.2.1/easyappointments_1.2.1.zip) of the official website. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by halalyon** [comment]
I also try the bundled package of the official website, it is still working with http 500. I double check the installation guide. I am sure I have the proper configuration as following the guide.

**Comment by alextselegidis** [comment]
Could you send me the exact error message from the logs? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
