### ISSUE TITLE
Date picker mobile

### ISSUE THREAD

**Issue by oxhey** [alextselegidis/easyappointments#34]
Iv added bootstrap to the backend to make it a bit more responsive on mobiles. On the calendar page with the modal add appointment , the date/ time picker slider doesn't work on mobiles. 

Is there any way to use the same date / time picker as the front end?

**Comment by flick36** [comment]
Take a look at this: http://touchpunch.furf.com/

**Comment by oxhey** [comment]
Its a bit annoying that the keyboard comes up , but it seems to work

**Comment by alextselegidis** [comment]
Frontend operates in a different way as backend. So this cannot be easily done. 

The solution of @flick36 seems promising, but still for the best user experience you will need to modify the UI and separate the hours from the dates.

**Comment by flick36** [comment]
You can use readonly="readonly" in the input, to avoid it the keyboard to be shown
