### ISSUE TITLE
Email Configuration

### ISSUE THREAD

**Issue by pablochaves085** [alextselegidis/easyappointments#341]
I have pluguin installed in wordpress. Is there any configuration that needs to be done? Do I have to install any other pluguin to be able to receive the reservation notification emails?

**Comment by alextselegidis** [comment]
The email notifications have to be configured directly from Easy!Appointments' back-end section. The WordPress plugin is only a helper to let you integrate Easy!Appointments in your pages.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
