### ISSUE TITLE
Create a new appointment overview in the backend section.

### ISSUE THREAD

**Issue by henkvalk** [alextselegidis/easyappointments#343]
Thanks for the great work.

I can't find the following possibility 
When a secretary login to the Backend it shows an overview of all the bookings of all the providers together in one calendar.

**Comment by alextselegidis** [comment]
Hi, thanks for the post. 

This could become a nice feature for an aggregated view, I will mark it as a feature ticket. 

In the meanwhile you can sync all the provider calendars to the same Google account and handle them from within Google Calendars. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by henkvalk** [comment]
Hi Alex,

Do you know when this feature is ready? 

In the meanwhile I synced all  the providers to Google Calendars. For the overview. But when they add a new appointment into the Google Calendar, this appointment will not synched back to easyappointments. Or am I doing something wrong?

**Comment by prossino83** [comment]
it would be very useful for me too. There's news about that?

Thanks for your work!!

**Comment by alextselegidis** [comment]
@prossino83 Not implemented yet, I forgot to set the ticket to v1.4. 

There is some internal refactoring going on, that will provide a more versatile code structure. 

Once this is done I will work intensively on bug fixing and new features. 

Thanks for all your support :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by KEMiCZA** [comment]
@alextselegidis hi, I was wondering if this feature is being worked on or panned in a future release?

**Comment by alextselegidis** [comment]
Hi @KEMiCZA, unfortunately I got no updates on this one yet. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

Quick updates, this feature is planned for v1.5.0 which will be released within in October 2021. 

Stay tuned for more updates. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Update: this one is committed in the develop branch and will be released with the next version. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
