### ISSUE TITLE
Missing '.../vendor/composer/autoload_static.php'?

### ISSUE THREAD

**Issue by adil192** [alextselegidis/easyappointments#345]
The autoload_static seems to be missing from the composer folder inside src. Is this a mistake or am I doing something wrong?

**Comment by alextselegidis** [comment]
You are right! It was accidentaly left out in master branch. 

It's fixed now, thanks for posting 👍 

https://github.com/alextselegidis/easyappointments/commit/fe3c9ba08e058a2bdd623866222a5ceb802ff1b1

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
