### ISSUE TITLE
Email Styling

### ISSUE THREAD

**Issue by adil192** [alextselegidis/easyappointments#346]
How do I edit the styling of the emails sent out when an appointment is submitted? Thanks

**Comment by alextselegidis** [comment]
The email template files are located in /application/views/emails directory. Their styling is mainly inline style attributes so you can adjust them easily :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
