### ISSUE TITLE
Emails on Mobile

### ISSUE THREAD

**Issue by adil192** [alextselegidis/easyappointments#347]
Just to make the mobile view of the emails generally better, I put a **max-width: 100%;** after the **width: 650px;** on the email_container of each email. Perhaps you could consider putting this into your code.

**Comment by alextselegidis** [comment]
Sounds good! I'll check this out, thanks :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
