### ISSUE TITLE
Can't find text in reminder email

### ISSUE THREAD

**Issue by Fridayjansson99** [alextselegidis/easyappointments#350]
Hi!

I want to change the text in the email reminder, but I can't find where.  

The text is: 
"Remind your booking at [company]"
"Please take note of the following booking details."

Can you help me?

Thanks!

**Comment by alextselegidis** [comment]
Hi! Check the engine/notifications/Email.php file and the application/views/emails/appointment_details..php. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Fridayjansson99** [comment]
Thank you!!

**Comment by TVBZ** [comment]
Hello..

I am looking for the email reminder option.
Is there such a function, so I could have an automatic email reminder sent? (for example 1 day before appointment)
If so, where can I find this option?


Many thanks! :) 


PS: the installation and configuration guides at https://easyappointments.org/installation-guide.md are not available (404 error).

**Comment by alextselegidis** [comment]
@TVBZ Try this link https://easyappointments.org/docs.html#1.3.2/installation-guide.md

Automated reminders are not available in the system. 

You can create a script that reads the appointment that come in day and send an email, all done with a Cron job.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
