### ISSUE TITLE
How to create days off for providers

### ISSUE THREAD

**Issue by henkvalk** [alextselegidis/easyappointments#352]
For employees / providers I want to insert days off for vacation, so they aren't selectable in the booking for the customers. 
So is there a possibility to create rules for days off?

**Comment by alextselegidis** [comment]
Hi there! You can currently do this with unavailability blocks. Just block off the entire days and no availabilities will be shown for these days.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
