### ISSUE TITLE
No form fields at step 3

### ISSUE THREAD

**Issue by Fridayjansson99** [alextselegidis/easyappointments#353]
Hi! 

I get stuck on step 3 and can't move on to the next step. I can't see the fields in the form, only the numbers at the top. 
This happens once in a while, and otherwise I can go through all of the steps.

Do you know why this happens? 

Here's the booking page: 
http://jacklinmichell.se/boka/

Thanks!

**Comment by alextselegidis** [comment]
Hi! I just tried your installation and it works so I'm guessing that this ticket can be closed.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
