### ISSUE TITLE
A provider should only make appointments  for him. A secretary should only be able to make appointments for the assigned providers

### ISSUE THREAD

**Issue by mardzo** [alextselegidis/easyappointments#356]
Is this possible? Because now a provider can also make appointments for other providers.

**Comment by alextselegidis** [comment]
Hello, 

yes this is possible with JavaScript modifications. 

Open the `backend_calendar_appointments_modal.js` and make a check for the `GlobalVariables.user.role_slug` value during initialization. If this value is equal to `provider` then you can disable the `#select-provider` select element and lock it to the value of the current user. 

As this is somewhat specific I will not integrate this to the app. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mardzo** [comment]
Hi, 

I cant find globalVariables.user.role_slug in backend_calendar_appointments_modal.js?

**Comment by alextselegidis** [comment]
This variables is defined in each view file so you'll have to search in `application/views/backend/calendar.php` for its definition.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
