### ISSUE TITLE
When booking through a google search-- times do not load & AJAX error

### ISSUE THREAD

**Issue by jacobandrews96** [alextselegidis/easyappointments#357]
Thank you so much for the wonderful booking system, been using it for awhile wonderfully! I did recently find an error though that is restricting many of my customers from scheduling appointments.

When someone googles my business, then go to my website from the google link. They are not able to schedule an appointment. 

Seen below:

<img width="1167" alt="screen shot 2017-09-11 at 2 23 21 pm" src="https://user-images.githubusercontent.com/24920817/30290287-d02d51c0-96fc-11e7-856f-d26eb4912a58.png">

If someone goes directly to my site, then schedules an appointment. There is no issues. 

Why would this be? & is there any way I can fix it?

If you want to try on your own:
thebarbershock.com
vs. 
https://www.google.com/search?q=thebarbershock&oq=thebarbershock+&aqs=chrome..69i57j69i60l4j0.4309j0j7&sourceid=chrome&ie=UTF-8

**Comment by jacobandrews96** [comment]
I figured out why, but not a solution!

So- it is dependent on the **base url.**
http://www.thebarbershock.com does not work
while
http://thebarbershock.com does work

Is there a way to add both as the Base Url?

**Comment by alextselegidis** [comment]
Hello @jacobandrews96!

You can easily solve this issue by having your server redirect from http://www.thebarbershock.com to http://thebarbershock.com

Use http://thebarbershock.com as your base URL. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
