### ISSUE TITLE
after installation i unable to go to backend,

### ISSUE THREAD

**Issue by JarbyA** [alextselegidis/easyappointments#36]
after i go to www.example.com/book/backend

i get the following mesage

No input file specified.

**Comment by thomas1216** [comment]
i see the issue, when i go to www.example.com/book/index.php/backend works, but if i go to customers the url go change again omitting the index.php (www.example.com/book/customers

**Comment by aymanrb** [comment]
You probably don't have Mod Rewrite enabled ... Try to change the content of the .htaccess to th content of [This Htaccess](https://gist.github.com/philipptempel/4226750)  and see if it works
