### ISSUE TITLE
REST API authentication problem.

### ISSUE THREAD

**Issue by PowerChaos** [alextselegidis/easyappointments#361]
hi,
i try to use the api to get some information
but as soon i try to authenticate , it fails to continue
or in short , it just refuse to authenticate

i tried it over SSH and direct browser acces
in the browser it keeps asking for username/pass
in the SSH it trows a error that it says that i am not authorised to access the api

i tried both my users , admin and member but they still give the same

can you check this please
ps: i only use HTTPS connection forced by htaccess
and i also got the htacces code for authentication included

Greets From PowerChaos

**Comment by alextselegidis** [comment]
Hello, 

could you please provide me with some error logs or further debug information? 

Logs are located in the storage/logs/* directory. 

Enable debugging by changing the setting inside the root config.php file. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by PowerChaos** [comment]
hmm
logs stays empty even when debug is set on TRUE

this are acces logs that i found but it doesnt provide any information

`62.205.74.26 - - [28/Sep/2017:19:56:31 +0200] "GET /index.php/api/v1/appointments HTTP/1.1" 401 38 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"`

`62.205.74.26 - - [28/Sep/2017:19:56:51 +0200] "GET /favicon.ico HTTP/1.1" 404 - "https://afspraken.hersteljepc.be/index.php/api/v1/appointments" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"`

`213.136.92.212 - - [28/Sep/2017:19:57:46 +0200] "GET /index.php/api/v1/appointments HTTP/1.1" 401 38 "-" "curl/7.29.0"`

`62.205.74.26 - - [28/Sep/2017:19:59:24 +0200] "GET /index.php/api/v1/appointments HTTP/1.1" 401 38 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"`

62.205.74.26 - - [28/Sep/2017:20:04:03 +0200] "GET /index.php/api/v1/appointments HTTP/1.1" 401 38 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"

but this is what i get as response from SSH (the following is a example, my real username/pass get used instead of admin:admin ) 

curl https://afspraken.hersteljepc.be/index.php/api/v1/appointments --user admin:admin
You are not authorized to use the API

and on the web htacces popup keeps showing again
until i press cancel ofcourse, then it shows the following error
You are not authorized to use the API.

but i saw some lightblue and darkblue text for a split second ( no idea whats on it , but it seems a page full ) 

i tried as provider username/pass and admin username/pass

hopely this can help you
Greets From PowerChaos

**Comment by alextselegidis** [comment]
Hmm strange, take a look at the authorization troubleshooting at the end of this document: 

http://easyappointments.org/docs#1.2.1/rest-api.md

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by muneebtariq1991** [comment]
Hi,
I'm trying to get data via API, its gives error "You are not authorized to use the API."
