### ISSUE TITLE
Add Arabic language

### ISSUE THREAD

**Issue by irashed** [alextselegidis/easyappointments#362]
[arabic.zip](https://github.com/alextselegidis/easyappointments/files/1347566/arabic.zip)

This is some of the file to add Arabic language also I want to add dir="rtl" to the html tag if someone use Arabic language for enabling HTML in right-to-left scripts such as Arabic, Hebrew, Syriac, and Thaana.

**Comment by alextselegidis** [comment]
Awesome! Thank you very much. 

Feel free to make a pull request for further changes but please use the develop branch. 

Regards

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdulhamid-ghannam** [comment]
thanks Rashed for Arabic package .
how can i add it to the Easy Appointment ?


Thanks

**Comment by alextselegidis** [comment]
Hi there, 

although I haven' test it yet, you just have to copy the `translations_lang.php`file in `application/language/arabic` and then update the list of available languages in `application/config/config.php`. 

You should then be able to select this language from the language dropdown menu. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdulhamid-ghannam** [comment]
Hi,
about Arabic language , can i translate the app from English to Arabic in the English file "translations_lang.php" ?

thanks

**Comment by alextselegidis** [comment]
Hi @abdulhamid-ghannam, the arabic translation is already included within the app. 

You can use it starting from v1.3.0.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdulhamid-ghannam** [comment]
Thanks Alex

**Comment by abdulhamid-ghannam** [comment]
Hi @alexandrurapanu  , the Arabic translation is not complete .. there are many words still in English .

can i translate it ? and how .

Thanks

**Comment by alextselegidis** [comment]
@abdulhamid-ghannam Oh yes, you are right. 

It would be great if you can help complete this before the final 1.3.0 release :) 

[Download this file](https://raw.githubusercontent.com/alextselegidis/easyappointments/develop/src/application/language/arabic/translations_lang.php) (right click --> save as) and send it back when you are ready.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdulhamid-ghannam** [comment]
Ok @alextselegidis  i will .

thanks

**Comment by abdulhamid-ghannam** [comment]
Hi @alextselegidis  ..
I have finished translating the file ..
but the Arabic lang it must to be from right to left not like English lang (left to right) 

this is the the Full Arabic Lang below .


Thanks 
[Full Arabic lang.zip](https://github.com/alextselegidis/easyappointments/files/1638699/Full.Arabic.lang.zip)

**Comment by alextselegidis** [comment]
@abdulhamid-ghannam Thank you very much! I'll update the translation file before the release of v1.3.0

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
