### ISSUE TITLE
Multiple User Calendar's for Sync

### ISSUE THREAD

**Issue by jacobandrews96** [alextselegidis/easyappointments#363]
Hi Alex,

Phenomenal software!

I was looking to add another user / provider on my system. How can I have it so their google calendar is where the appointments are placed and the sync can be enabled for him as well? When I do that, there is an oauth error..

Any thoughts if this is possible?

**Comment by alextselegidis** [comment]
Hi Jacob, 

I'm glad to read that you like the app :) 

Normally after you create a provider you should be able to head to the backend-calendar page and enable syncing for him without issues. 

I mean if this worked already for another provider there's no difference between the next ones. 

Is this you use case or are you trying to achieve something else? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacobandrews96** [comment]
<img width="923" alt="screen shot 2017-10-02 at 7 44 54 pm" src="https://user-images.githubusercontent.com/24920817/31104305-3dc6e594-a7aa-11e7-87c1-63fc45a6bd73.png">

This is the error I get when attempting to enable sync on a second provider with a different google calendar. 

Any thoughts? 

I am trying to achieve a second provider. Currently, I have one provider where people make appointments with me and it goes right to my calendar. Now, I am trying to add a second provider with the same set-up, just using their own google calendar.

**Comment by alextselegidis** [comment]
The authorized OAUTH redirect URL seems to be invalid. It should look like this `http://www.thebarbershock.com/appointent/index.php/google/oauth_callback`. 

You can adjust this in Google Cloud Console, under the Credentials page.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jacobandrews96** [comment]
Got it! Thank you! Quite the expert! This application gets even better!

**Comment by caskaid** [comment]
Would someone be kind enough to confirm/deny whether syncing of two separate provider's calendars is possible. It is not clear from the following line in the documentation, (at least for me) - as it simply states: 

_"Every provider user can be synced with only one Google Calendar account."_

Does this mean they can each have their respective calendars sync, or that they both need to be on a single combined calendar? 

Jacobandrews96's comment only adds to my confusion stating; _"I am trying to achieve a second provider. Currently, I have one provider where people make appointments with me and it goes right to my calendar. Now, I am trying to add a second provider with the same set-up, just using their own google calendar."_

**Comment by alextselegidis** [comment]
@caskaid Each provider can get his own Google Calendar synced :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
