### ISSUE TITLE
Silly question

### ISSUE THREAD

**Issue by zuliandres** [alextselegidis/easyappointments#366]
I am restricted to PHP v 5.5.14, is there anything I can do? or another tool you would recommend?
Thanks in advance!

**Comment by alextselegidis** [comment]
Hello @zuliandres, 

first of all I have to say that I don't believe that there are silly questions. 

Second, I would advice you to use v1.2 of Easy!Appointments: https://github.com/alextselegidis/easyappointments/releases/download/1.2.0/easyappointments_1.2.0.zip

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
