### ISSUE TITLE
Disabling booked Time slot

### ISSUE THREAD

**Issue by MyDcode** [alextselegidis/easyappointments#367]
thank you for a perfect application for appointments booking.

I would like to know, how to block (Disable) a time-slot being booked twice? Also it would be better to keep the booked date in the list but in disabled manner.

Thank you.

**Comment by alextselegidis** [comment]
Hi @MyDcode, are you referring to the backend or frontend section?

**Comment by MyDcode** [comment]
Hi Thank you for your reply, though I figured it out. I was asking about the front end.. later only realized that the system has a functionality.

**Comment by MyDcode** [comment]
If u don't mind delete this issue.. coz this won't help anyone... its a mistake! Thanks..
