### ISSUE TITLE
Change service selection on first page to radio button

### ISSUE THREAD

**Issue by LewisHalliday** [alextselegidis/easyappointments#368]
Hi,

Is it possible to change the service selection on the first page of the booking process to be a 'radio button' selection instead of a dropdown?

Thanks

**Comment by alextselegidis** [comment]
Sure @LewisHalliday, just edit the `application/views/appointments/book.php` file and turn the #select-service element into a radio button. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by LewisHalliday** [comment]
Thanks!

I've done that but im hitting a strange error.  I'm getting 

 `unavailableDates.indexOf is not a function`

and after selecting the relevant service it is showing all dates as available (with no times against them) instead of the standard only showing days that are in the working plan.

<img width="725" alt="screen shot 2017-10-17 at 11 04 42" src="https://user-images.githubusercontent.com/28866143/31659165-1a10875e-b32b-11e7-8c07-96bb838dc91e.png">
