### ISSUE TITLE
Datetimepicker bug

### ISSUE THREAD

**Issue by tommyb23** [alextselegidis/easyappointments#374]
Hello, 

I have changed the controlType of the datetimpicker to "select" due to the fact it is more user friendly on mobile as oppose to the slider. Unfortunately when I try to choose the hour, the select menu doesn't appear on mobile devices. Is there a quick fix to this?

Thanks

**Comment by alextselegidis** [comment]
Hi @tommyb23 which mobile device/browse are you using? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
