### ISSUE TITLE
email mandatory filed

### ISSUE THREAD

**Issue by Menkele** [alextselegidis/easyappointments#376]
Hi
Is it possible to remove email mandatory filed from customers?

**Comment by alextselegidis** [comment]
Hello @Menkele, I accidentally passed through this ticket and didn't post a comment before. 

This change requires many changes in the code that cannot simply described within a single post. 

Please do check the view files and the customer's model for further info on the required fields. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
