### ISSUE TITLE
Creating Appointments using REST API

### ISSUE THREAD

**Issue by Vanthiyadevan** [alextselegidis/easyappointments#380]
Hi,

I tried the REST API, while creating new appointments it asks for customer Id. Do I have create a new customer before creating a new appointment ? Single endpoint would be better.

Also, I tried to create new customer before creating new appointment, If a customer is already exists the API returns email id already exists of this customer. How can I get the ID of the existing customer because the existing customer Id is needed to create new appointments. Is there is any end point exists for Getting customer id if supplied customer email ? 

Am I doing it wrong or is there is anything you can help me out. Any thoughts will be much appreciated.Thanks.

End Point : 
```
POST - http://scheduleai.com/index.php/api/v1/appointments

With Basic AUTH header Admin/password

Body: 
{
        "firstName": "My F.name",
        "lastName": "my L.name",
        "email": "myemail@gmail.com",
        "start": "2017-12-14 10:00:00",
        "end": "2017-12-14 10:30:00",
        "providerId": 85
}

```

Error Message: 
``` 
"code": 500,
    "message": "Appointment customer id is invalid."
```

**Comment by LewisHalliday** [comment]
You can query the 'customers' endpoint.

So for example

[http://scheduleai.com/index.php/api/v1/customers?q=myemail@gmail.com](
http://scheduleai.com/index.php/api/v1/customers?q=myemail@gmail.com )

that would return back the user with that registered email. 

The API documentations is [here](https://github.com/alextselegidis/easyappointments/blob/develop/doc/rest-api.md)

**Comment by Vanthiyadevan** [comment]
Thanks for the clarification, It works. 

Easy appointment is awesome to use and great piece of work. Thanks.

**Comment by LewisHalliday** [comment]
Not my work, just a user. It is a great piece of work tho!

@alextselegidis is the developer
