### ISSUE TITLE
Auto-Sync appointments from Google to EasyAppointments

### ISSUE THREAD

**Issue by whitespring** [alextselegidis/easyappointments#385]
Hi! 
Great software, love it. 
One small request, and maybe I just didnt get it: 

Can we set a cron job to trigger syncing Google Calendar entries that were added by hand to Google Cal into the system so  EasyAppointments knows which slots to block for further online bookings?

Thanks, Thomas

**Comment by alextselegidis** [comment]
Hi! This is not possible yet. A solution for would be the creation of a cron job that will check once in a while if there are new events in google and bring them back to Easy!Appointments. I'll mark this as a feature request. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by whitespring** [comment]
Hi,

I have been trying that. Is there a function that I can call with the cron to do the sync? It seems to need the session token (be logged in) to trigger the calendar sync and I have not been able to realize that. 

I have been calling https://www.<myurl>/index.php/google/sync/92 and that worked when I did it manually and logged in, but not from a cron / PHP script.

**Comment by alextselegidis** [comment]
You could call the Google::sync method but you might need to do some modifications there in order to make this method work through the CLI. 

https://www.codeigniter.com/user_guide/general/cli.html

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by nab8** [comment]
An alternative we are trying out is having the calendar sync whenever the booking page is visited so they are only seeing free slots.  We tried doing it with a 15 minute cronjob but had issues where someone could visit between syncs.

**Comment by whitespring** [comment]
Could you elaborate on the proceedings / code on how you did that?
Ideally share the code?

Much appreciated,
Thomas

**Comment by nab8** [comment]
Sorry for the delay, we have quite a few customizations and I wanted to setup a test install to make sure I got all the needed edits. 

application/controllers/Google.php - comment out the login requirement for syncing (lines 102 &103)
```
public function sync($provider_id = NULL) {
        try {
            // The user must be logged in.
            //$this->load->library('session');
            //if ($this->session->userdata('user_id') == FALSE) return;
```

assets/js/frontend_book_api.js - export a googleSync function (line 28, right before the Get Available Hours comment block)
```
(function(exports) {

    'use strict';

    var unavailableDatesBackup;
    var selectedDateStringBackup;
    var processingUnavailabilities = false;

    exports.googleSync = function() {
        var provider_id= $('#select-provider').val();
        var getUrl = GlobalVariables.baseUrl + 'index.php/google/sync/' + provider_id;
        jQuery.get(getUrl,provider_id, console.log('Google sync successful'),'json');
    }
```

assets/js/frontend_book.js - call the googleSync function when selecting a provider or service (before line 162 and on line 194 in the Selected Provider "Changed" and "Selected Services "Changed" functions)
```
$('#select-provider').change(function() {
            FrontendBookApi.googleSync(); 
            FrontendBookApi.getUnavailableDates($(this).val(), $('#select-service').val(),
                    $('#select-date').datepicker('getDate').toString('yyyy-MM-dd'));
            FrontendBook.updateConfirmFrame();
        });
```
```
// Add the "Any Provider" entry.
            if ($('#select-provider option').length >= 1) {
                $('#select-provider').append(new Option('- ' +EALang['any_provider'] + ' -', 'any-provider'));
            }

            FrontendBookApi.googleSync();
            FrontendBookApi.getUnavailableDates($('#select-provider').val(), $(this).val(),
                    $('#select-date').datepicker('getDate').toString('yyyy-MM-dd'));
            FrontendBook.updateConfirmFrame();
             _updateServiceDescription($('#select-service').val(), $('#service-description'));
        });
```

**Comment by whitespring** [comment]
Great, thank you! This worked on several levels. I am also able to run a cron job (with a php function) to trigger the sync, so it always syncs, no matter how often someone checks the page.

**Comment by Jawn78** [comment]
@nab8 @whitespring I followed these steps and it is not working. Any help would be greatly appreciated

**Comment by nab8** [comment]
Sorry, this worked in 1.2.1 but I haven't tried it in any of the 1.3 releases.  It looks like 1.3.0 was a major refactoring and I'm not sure what changes would have affected this.

**Comment by nathanbriley** [comment]
We are finally updating to 1.3.2 so I'm looping back around to this.  The line numbers have changed but the only other change I came across was that baseUrl doesn't have a trailing slash so I had to change the exports.googleSync function in assets/js/frontend_book_api.js like so (forward slash before index.php):

```
exports.googleSync = function() {
        var provider_id= $('#select-provider').val();
        var getUrl = GlobalVariables.baseUrl + '/index.php/google/sync/' + provider_id;
        jQuery.get(getUrl,provider_id, console.log('Google sync successful'),'json');
    }
```

After that change it seems to be working for me again.
