### ISSUE TITLE
Service price should be optional. 

### ISSUE THREAD

**Issue by vitormfgoncalves** [alextselegidis/easyappointments#386]
Some organizations don't charge for appointments.
Public services for example.

**Comment by alextselegidis** [comment]
Thanks for posting :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mokkin** [comment]
I agree.
It should be optional or maybe hidden if price is set to zero.

**Comment by yrammos** [comment]
@mokkin's suggestion seems most elegant.

**Comment by alextselegidis** [comment]
This is merged on develop. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
