### ISSUE TITLE
Unable to send email. Log provided. 

### ISSUE THREAD

**Issue by thisisspeedy** [alextselegidis/easyappointments#391]
I would appreciate any help on this.  I'm not receiving emails nor is the person booking. 

> ERROR - 2017-12-28 16:54:56 --> Email could not been sent. Mailer Error (Line 137): Could not instantiate mail function.
> ERROR - 2017-12-28 16:54:56 --> #0 /home/franjirq/public_html/booking/application/controllers/Appointments.php(455): EA\Engine\Notifications\Email->sendAppointmentDetails(Array, Array, Array, Array, Array, Object(EA\Engine\Types\Text), Object(EA\Engine\Types\Text), Object(EA\Engine\Types\Url), Object(EA\Engine\Types\Email))
> #1 [internal function]: Appointments->ajax_register_appointment()
> #2 /home/franjirq/public_html/booking/system/core/CodeIgniter.php(532): call_user_func_array(Array, Array)
> #3 /home/franjirq/public_html/booking/index.php(353): require_once('/home/franjirq/...')
> #4 {main}

**Comment by alextselegidis** [comment]
Apparently the php mail function is not enabled on your server. A solution would be to go with some custom SMTP service and configure the app accordingly. 

For this you'll need to change the contents of the application/config/email.php file.

Reference: 

https://www.codeigniter.com/user_guide/libraries/email.html?highlight=email#email-preferences

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
