### ISSUE TITLE
Unable to connect to your database server

### ISSUE THREAD

**Issue by cedricpri** [alextselegidis/easyappointments#392]
Good evening,

I just discovered your plugin and would like to see if I can use it on a new website of mine. I'm currently trying to install it, but haven't be able to do it so far. 

I pushed easyappointments' folder to my server (which has mysql, php 7.1 and apache activated), copied the config-sample.php file and saved it as config.php, where I changed the BASE_URL and my newly created database credentials.

    const BASE_URL      = 'https://www.logmyhotel.net/ea/src';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = FALSE;

    const DB_HOST       = 'shareddb-f.hosting.stackcp.net';
    const DB_NAME       = 'calendar';
    const DB_USERNAME   = 'MyUsername';
    const DB_PASSWORD   = 'MyPassword'; 

When I access the index.php file within the src directory, I get the following error: 

**Unable to connect to your database server using the provided settings.
Filename: controllers/Appointments.php
Line Number: 28**

I tried adding at the end of the database.php file the following few lines and the connection seems to be active (I get the message "Connected successfully"), meaning that the data put in the config file seems to be fine, right?

    $servername   = Config::DB_HOST;     
    $database = Config::DB_NAME;
    $username = Config::DB_USERNAME;
    $password = Config::DB_PASSWORD;

    // Create connection
    $conn = new mysqli($servername, $username, $password);
    // Check connection
    if ($conn->connect_error) {
       die("Connection failed: " . $conn->connect_error);
    }
    echo "Connected successfully";

Any idea of what's happening? Thanks!

**Comment by alextselegidis** [comment]
My guess would be that there's an issue with passive connections on your server environment(?)

Try deactivating them within the application/config/database.php file. 
```php
$db['default']['pconnect'] = FALSE;
```

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@cedricpri Were you able to resolve your problem?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by cedricpri** [comment]
Sorry, I haven't found the time to work on my project in a while. I think I remember testing your suggestion without any changes though. I probably won't be able to work on this project for a while either and since this seems to be an error related to my server, so feel free to close this issue for now.

**Comment by alextselegidis** [comment]
@cedricpri Thanks for your prompt reply. 

Do open a new ticket if you experience any issues in the futures :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Oxigen-a** [comment]
Hi Alextselegidis. 
I have the same error as on the original report. Testing mysql/php access with a test script shows no issues. I tried with no success to set $db['default']['pconnect'] = FALSE under application/config/database.php
Any suggestion(s)? 

===
A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: controllers/Appointments.php
Line Number: 29
=== 
my OS is ubuntu server 18.4.s, 
mysql  Ver 14.14 Distrib 5.7.26 
PHP 7.2.19-0ubuntu0.18.04.1, 
Apache/2.4.29 (Ubuntu), 2019-06-28T16:49:35

below my config.php
===
class Config {

    // ------------------------------------------------------------------------
    // GENERAL SETTINGS
    // ------------------------------------------------------------------------

    const BASE_URL      = 'http://ea.test.com/ea';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = FALSE;

    // ------------------------------------------------------------------------
    // DATABASE SETTINGS
    // ------------------------------------------------------------------------

    const DB_HOST       = 'localhost';
    const DB_NAME       = 'ea';
    const DB_USERNAME   = 'root';
    const DB_PASSWORD   = 'toor';

    // ------------------------------------------------------------------------
== = the rest is default.
