### ISSUE TITLE
Start and end time do not update correctly during calendar time selection on iPad (and other Safari based devices). 

### ISSUE THREAD

**Issue by VyReN** [alextselegidis/easyappointments#396]
1.3.0-alpha

When long tapping a slot on the calendar, only on my iPad (Both Chrome and Safari), the start and end times do not update, they seem to default to today at midnight.  Works great on Android, Windows, but not the iPad.

Can anyone confirm this with another Apple device?

**Comment by alextselegidis** [comment]
Hmm, unfortunately I cannot test this with an iPad device but I can tell that in the next releases jQuery UI (the UI library Easy!Appointments uses) will be replaced with a more modern approach and therefore such issues will be solved. Till then I would recommend using the text input field for setting the date-times as it'll be easier for mobile devices. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Thanks to @popod I was able to reproduce this. 

There's an issue in the date formatting when parsing the dates from Safari based browsers. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
@alextselegidis I think that you could close this issue as my PR resolve it :)
