### ISSUE TITLE
Raising more useful exceptions and enable error logging by default.

### ISSUE THREAD

**Issue by xaglen** [alextselegidis/easyappointments#4]
In application/controllers/google.php the exceptions raised in function sync cause a JSON parse error. I believe this is why some people report an endlessly spinning circle when trying to get Google sync working.

This can be fixed by including a call to getMessage(). 

The code is currently at lines 203-207 (https://github.com/alextselegidis/easyappointments/blob/master/src/application/controllers/google.php#L205) and should be changed to this (only line 205 is changed, the rest is for context):

    catch(Exception $exc) {
            echo json_encode(array(
                'exceptions' => array($exc->getMessage())
            ))  ;
            }

**Comment by alextselegidis** [comment]
In the next release I will add error logging to the application so that developers will have extra information about what might go wrong. 

Good to notice though :)
