### ISSUE TITLE
All calendars will start with Sunday as the first day.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#403]

**Comment by Caine85** [comment]
Hello, thank you very much for your work!

I think it would be great to have the chance to choose which day the week starts. In many parts of Europe, for example, the week starts on Monday and this forced change can be a problem.

I tried to change the firstDay option on fullcalendar.js. The calendar changes the first day but the appointments are always displayed as if it were Sunday the first day.

Thank you so much again!

**Comment by alextselegidis** [comment]
@Caine85 You are right, I created another ticket for this setting: 

https://github.com/alextselegidis/easyappointments/issues/421

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Caine85** [comment]
Amazing!

Thank you again

**Comment by hontik** [comment]
Hi!
Here's a description of what step-by-step describes how you can convert.
https://rendszergazdamegoldasok.blog.hu/2018/09/14/easy_appointments_first_day_of_the_week
