### ISSUE TITLE
All attendants must be shown

### ISSUE THREAD

**Issue by virendahiya** [alextselegidis/easyappointments#404]
Hi Sir, 
First of all a big thanks for creating such a wonderful appointment system. I want to draw your attention to the following issues that are needed to be addressed for improving this software -
1) There should be option to display all attendants in the calendar altogether. ( at least in One Day View )(I am attaching a image for example ).
It is necessary to book the appointment without wasting customer's time. (by viewing availability of all attendants in any day altogether, and wasting time by viewing them one by one).
2) Popup box for making new appointment in the calendar is very large. It should be small for using it easily. ( now we are compelled to scroll down to save the appointment.

Thanks !
![capture](https://user-images.githubusercontent.com/35265321/34728314-9578cd84-f57f-11e7-887a-e1f3ed925b8f.JPG)

**Comment by alextselegidis** [comment]
Hi @virendahiya, you can already use the `table-view` that does exactly the same. Improvements to the calendar views are being made from release to release as this is a very important section of the app. Stay tuned for further updates. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
