### ISSUE TITLE
Select Service and Select Provider fields empty on Booking Page

### ISSUE THREAD

**Issue by pfizur** [alextselegidis/easyappointments#405]
I am new to Easy!Appointments so please forgive me if I've missed something obvious. I just installed Easy!Appointments v1.2.1 and the installation process was very easy and simple. I was able to login and services and users without a hitch. However when I go the booking page the drop downs for Select Service and Select Provider are empty/unpopulated. Is there something I need to do to have the services/providers I've added show up there?

**Comment by alextselegidis** [comment]
You must connect your services to their corresponding providers and then they'll be displayed in the booking page. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
