### ISSUE TITLE
Develop branch error on installation

### ISSUE THREAD

**Issue by dudunato** [alextselegidis/easyappointments#406]
I downloaded the develop branch to test the version with docker, but when I hit "install" it gives me the following error:

```
Error Number: 1146 Table 'easyapp.ea_settings' doesn't exist
SELECT *
FROM `ea_settings`
WHERE `name` = 'company_name'
Filename: models/Settings_model.php
Line Number: 39
```

Tried to troubleshot it but I couldn't figure that out. 
- When I run `docker-compose up` it runs fine
- The connection with the database is being successful

Any ideas?

**Comment by alextselegidis** [comment]
It seems that your database is not empty of E!A tables when you run the installation. 

Remoe all E!A tables and try to install the app again.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by dudunato** [comment]
Humm, I don't think this is the problem though. I've tried to clean it several times and it didn't work.

I even deleted all volumes and images from my docker to really start from scratch and nothing. So debugging the code my guess would be something related to the permissions granted to the www-data user. It seems that the queries from assets/sql/structure.sql are not being executed. :/

I'm not so experienced with Dockers though. Any thoughts?

**Comment by alextselegidis** [comment]
The only directory that requires writing permissions is the "storage" directory. Can you check if this is writable on you setup? 

Also can you try importing the `assets/sq/structure.sql` file manually just to make sure the queries in there are acceptable by your mysql database host?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by dudunato** [comment]
Hey @alextselegidis,

I found the problem and it has to do with the base URL. In my config.php it is set to http://localhost (without a trailing slash). Then the .js files are concatenating it adding one more slash:

```
var postUrl = GlobalVariables.baseUrl + '/index.php/installation/ajax_install';
```

But for some reason, my base_url is adding the trailing slash and to make it work I need to do this:

```
var postUrl = GlobalVariables.baseUrl + 'index.php/installation/ajax_install';
```

I wonder if there's something in my setup that is overriding it to the CodeIgniter default: 'http://localhost/'.

**Comment by dudunato** [comment]
Actually, CodeIgniter adds the trailing slash:

```
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|   http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
```

So I guess it's needed to go through the files and remove the slash. A difference from the master branch is that you just echo the $base_url variable instead of calling the base_url() function from CI.

Wonder how was it working for you? 🤔

**Comment by alextselegidis** [comment]
The thing is that the js files will use the plain value set in the root config.php and therefore there must be no trailing slash in there cause the rest of the code is adding it automatically. 

I'm already planning to create a base_url function for the javascript modules, similar to the one from CI to avoid such issues. 

This is also why in config.php I explicitely documented this https://github.com/alextselegidis/easyappointments/blob/develop/src/config-sample.php#L16

... but nevertheless this will be improved in before v1.3 hits a stable version. 

Thanks for posting 👍 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by akujti-ubt** [comment]
I did it by writing it like www.google.com and not like www.google.com/ so you have to remove the last slash from the url
