### ISSUE TITLE
ajax error

### ISSUE THREAD

**Issue by abdulhamid-ghannam** [alextselegidis/easyappointments#407]
Hi ,
i have this error : 

(index):1 Access to Font at 'http://[::1]/app/assets/ext/bootstrap/fonts/glyphicons-halflings-regular.woff2' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

(index):1 Access to Font at 'http://[::1]/app/assets/ext/bootstrap/fonts/glyphicons-halflings-regular.woff' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

(index):1 Access to Font at 'http://[::1]/app/assets/ext/bootstrap/fonts/glyphicons-halflings-regular.ttf' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

(index):1 Failed to load http://[::1]/app//index.php/appointments/ajax_get_unavailable_dates?provider_id=85&service_id=13&selected_date=2018-01-14&csrfToken=be1108c82ba7177b4f209dfc4680d7b3: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

can you help me please ?

Thanks

**Comment by alextselegidis** [comment]
Hi, it seems that you BASE_URL setting in the root config.php file is wrong. 

http://[::1]/app --> this is what this is failing 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdulhamid-ghannam** [comment]
Thanks Alex ,
what should the URL be ?

**Comment by alextselegidis** [comment]
The URL you are using to access the application. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdulhamid-ghannam** [comment]
Thanks Alex .

**Comment by amirakbulut** [comment]
How did you solve this? I have exactly the url of my application location (http://www.domain.com/easyappointments) and it's still returning this problem.. @abdulhamid-ghannam @alextselegidis
