### ISSUE TITLE
Time format from American style to European

### ISSUE THREAD

**Issue by Antonie44** [alextselegidis/easyappointments#410]
Hi, how i can change the American format (like 1:45 PM) to European format (like 13:45) ?

**Comment by alextselegidis** [comment]
Marked as a feature request. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@Antonie44  this feature will be integrated in 1.3.1, stay tuned!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
