### ISSUE TITLE
Apply flag or information of canceled scheduling.

### ISSUE THREAD

**Issue by srwastar** [alextselegidis/easyappointments#412]
Hi,
Can you add a canceled scheduling button, and keep the schedule but a canceled flag (red collor) or other place to see this information?

This is for visual information only, other scheduling can be done at the canceled time.

**Comment by alextselegidis** [comment]
Cancelled appointments will be removed from the system. Currently there're no plans in integrating a functionality like this, sorry. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
