### ISSUE TITLE
calendar usage limits exceeded

### ISSUE THREAD

**Issue by navinisaac** [alextselegidis/easyappointments#414]
Not sure that this is an EA issue as opposed to mitigation's put in place by Google, but wondering if anyone has been faced with this issue? 

![image](https://user-images.githubusercontent.com/25622779/35188445-5bc95c8e-fe03-11e7-8553-7e13876cc734.png)

**Comment by alextselegidis** [comment]
Google has sets daily limits on the allowed calendar requests. 

https://developers.google.com/google-apps/calendar/pricing

You probably hit that limit and therefore get this response.  

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
