### ISSUE TITLE
Is possible Enable BCC ???

### ISSUE THREAD

**Issue by BeatDeer** [alextselegidis/easyappointments#417]
I want to send to multiple internal person when place a schedule

**Comment by nizwa330** [comment]
I don’t want receive any email how could i do?

Sent from my iPhone

On Jan 25, 2018, at 6:16 PM, BeatDeer <notifications@github.com<mailto:notifications@github.com>> wrote:


I want to send to multiple internal person when place a schedule

**Comment by BeatDeer** [comment]
i can resolve my question...

`protected function _createMailer()
    {
        $mailer = new \PHPMailer;
        
        $list=array('jfierro@kaloni.com','yalanis@kaloni.com');
        foreach($list as $bccer){
           $mailer->AddBCC($bccer);
        }

        if ($this->config['protocol'] === 'smtp') {
            $mailer->isSMTP();
            $mailer->Host = $this->config['smtp_host'];
            $mailer->SMTPAuth = true;
            $mailer->Username = $this->config['smtp_user'];
            $mailer->Password = $this->config['smtp_pass'];
            $mailer->SMTPSecure = $this->config['smtp_crypto'];
            $mailer->Port = $this->config['smtp_port'];
        }

        $mailer->IsHTML($this->config['mailtype'] === 'html');
        $mailer->CharSet = $this->config['charset'];

        return $mailer;
    }`


I think this is a good new feature, you can considerate... @alextselegidis  please.

**Comment by alextselegidis** [comment]
Great!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
