### ISSUE TITLE
time selection bug

### ISSUE THREAD

**Issue by Andre32** [alextselegidis/easyappointments#418]
Hi, i have this error. When the my customers for example 20 register their appointment to the new customer when try to register an appointment show this: # #
![screenshot_1](https://user-images.githubusercontent.com/13755819/35473565-aa2a33c4-0382-11e8-8aa2-430b1b9fe83a.png)

No time and No Date to select. (This appointment have 20 slots don't occupied)

**Comment by Andre32** [comment]
@alextselegidis

**Comment by alextselegidis** [comment]
Answered in Support Forum :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
