### ISSUE TITLE
Installation Issue (php)

### ISSUE THREAD

**Issue by ddellostritto** [alextselegidis/easyappointments#420]
Hi!

Having some trouble installing Easy!Appointments, there's a log file in the directory where I installed. The error I'm seeing is: 

`PHP Fatal error:  require_once(): Failed opening required '/home/dellostr/public_html/toothcare/booking/config.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/dellostr/public_html/toothcare/booking/index.php on line 50
`
I am hosting with greengeeks.

Any help is much appreciated!!

**Comment by ddellostritto** [comment]
I updated to the new beta, still having problems though - the log isn't producing any hints as to why. Any help much appreciated!

**Comment by alextselegidis** [comment]
Hi @ddellostritto 

> PHP Fatal error: require_once(): Failed opening required '/home/dellostr/public_html/toothcare/booking/config.php'

After you upload Easy!Appointments you'll need to copy `config-sample.php` to `config.php` and update its contents accordingly. 

Further info here: http://easyappointments.org/docs#1.2.1/installation-guide.md


> Uncaught SyntaxError: Identifier 'o' has already been declared at s (content_script_bundle.js:1)

This is not an Easy!Appointments issue as there is no `content_Script_bundle.js` file in the project. This probably comes from a chrome extension, you can validate this by checking the page again in incognito mode. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ddellostritto** [comment]
Hi @alextselegidis, thanks for getting back to me!

I'm using the newest beta b/c I wasn't able to get 1.2 working either. I looked through the guide just in case (http://easyappointments.org/docs.html#1.2.0/faq.md).

My config file is "config.php", I've made sure to: 
- create a php file that successfully created tables (user/pass/db access and permissions are OK)
- tested the folder permissions, can write ok
- uploaded an .htaccess file with: 
`
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]
`

The last log file gave me the following error:
`
ERROR - 2018-02-08 00:33:45 --> Severity: Error --> Call to undefined function mysqli_init() /home/dellostr/public_html/toothcare/booking/system/database/drivers/mysqli/mysqli_driver.php 135
ERROR - 2018-02-08 00:36:14 --> Severity: Error --> Call to undefined function json_encode() /home/dellostr/public_html/toothcare/booking/application/views/general/installation.php 174
`
Since then, I've activated mysqli, json in the php extensions of my host; however, the logs aren't showing me anything.

I've got debug set on, but can't seem to get any clear reason why I'm failing here. Is there any other tests that I can perform? In the console I'm not seeing any messages either... 

Any help much appreciated!!

**Comment by alextselegidis** [comment]
So I suppose that your server does not have the mysql php extension installed/enabled. 

You can switch to MSSQL as you pointed out in your other thread but this will need some changes in the code. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ddellostritto** [comment]
It occurred to me to show the options that I can enable/disable, perhaps there's one I'm not seeing...

![screen shot 2018-02-15 at 18 54 29](https://user-images.githubusercontent.com/960610/36282985-bec21ae6-1281-11e8-9202-53586517ce2b.png)

Thanks again.

**Comment by gaspo53** [comment]
Hi! The same happens to me, and mysqli is enabled.

`An uncaught Exception was encountered
Type: Error

Message: Call to undefined function mysqli_init()

Filename: /var/www/easyappointments/src/system/database/drivers/mysqli/mysqli_driver.php

Line Number: 135`

**Comment by alextselegidis** [comment]
@gaspo53 Let's try switching to mysql extension and see if it works for you (even though this is not supported anymore). 

File: 

`/application/config/database.php`

Command: 

`$db['default']['dbdriver'] = 'mysqli';` --> `$db['default']['dbdriver'] = 'mysql';`

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by gaspo53** [comment]
Same thing. And I have all required extensions:

![image](https://user-images.githubusercontent.com/2250227/36672994-17fd3a3a-1ae0-11e8-8450-7f581228957a.png)
![image](https://user-images.githubusercontent.com/2250227/36673013-20ca4f9a-1ae0-11e8-8189-5ea7eb5c359c.png)

![image](https://user-images.githubusercontent.com/2250227/36673023-2a90ee08-1ae0-11e8-9bf7-9d968c016a92.png)
![image](https://user-images.githubusercontent.com/2250227/36673027-2ea1a53c-1ae0-11e8-875d-1e8f8c617263.png)


Bug? Or bad configuration?

**Comment by gaspo53** [comment]
Don't worry, it was my running it in nginx. Works fine with Apache. Sorry for wasting your time

**Comment by kominfosidik12** [comment]
> Don't worry, it was my running it in nginx. Works fine with Apache. Sorry for wasting your time

@gaspo53 have you found the solution? thx
