### ISSUE TITLE
Color code events by provider or service.

### ISSUE THREAD

**Issue by maxmedresearch** [alextselegidis/easyappointments#422]
Hello, it seems to me that it is possible to define the color of events via eventColor in fullcalendar.

would it be possible to add an option to be able to choose the display color of the services.

for example: "general consultation" services in blue and "pediatric consultation" in red.

thank you

**Comment by alextselegidis** [comment]
Hi! Marked as an upcoming feature. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
