### ISSUE TITLE
Enable book advance timeout values in days.

### ISSUE THREAD

**Issue by gireuno** [alextselegidis/easyappointments#428]
Hello! What is the maximum possible timeout that can be set in the Business Logic section? I set 1440 minutes but not work. Thank you!

**Comment by alextselegidis** [comment]
Hello @gireuno, the app will only use the book timeout for the same day and not for previous dates. So valid values are smaller than 1440.  

In the future the app will support days in the book timeout setting but this is not implemented yet. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
