### ISSUE TITLE
PHP warnings during E!A installation (BETA v1.1)

### ISSUE THREAD

**Issue by d1a8lo24** [alextselegidis/easyappointments#43]
Many share hosts have "allow_url_fopen" off for security reasons, and on your installation and I am not sure in how many other places you're using file_get_contents() function which should be tested if is disable on the system and try using other functions or libraries like Curl. Or at least make sure that before installing all the functions that are not part of a standard php installation are pre tested to see if they are enable in the system if not to give a warning about whats disable to the person so hey can see what they can do. In my case all I had to do was to turn on allow_url_fopen.

Also there seems to be some database request prior to setting up the database that causing problems on the initial install. Here is a small log file from the main CI system,

Query error: Table 'ea_user_settings' doesn't exist

Severity: Warning  --> mysql_num_rows() expects parameter 1 to be resource, boolean given /system/database/drivers/mysql/mysql_result.php line 37

The above 2 errors I think they are related since the table doesn't exist, 
The mysql error repeats it self 23 times, so I am guessing its the creation of the database or loading of information to the database.

Severity: Notice  --> Undefined variable: has_category /application/views/backend/calendar.php 129

This last error is also part of the installation which the variable should be set as FALSE from the beginning and be available in the scope of the view. if not it should be tested with isset() to see if the variable exist and if its equal to true else the warning from php will pop up as the variable doesnt exist.

if (isset($has_category) && $has_category)

**Comment by mehranhassany** [comment]
could these be the the reason that when i click on install nothing happens ?

**Comment by alextselegidis** [comment]
@mehranhassany d1a8lo24's issue refers to a PHP warning and it's not the same with the problematic installation. 

@d1a8lo24 I just noticed the same issue in the installation of the E!A v1.1 (mysql_num_rows warning) so I will fix it before the version is released.

**Comment by alextselegidis** [comment]
Issue was solved and will be released with BETA v1.1
