### ISSUE TITLE
Booked times are hidden

### ISSUE THREAD

**Issue by fkolar** [alextselegidis/easyappointments#430]
HI , 

EasyA. is great and we are using it. There is one thing that we are missing which is it hides already booked times and this is a problem. 

When people are booking times they are not sure if this is the error. Is it possible to show booked times and maybe grey them out ?

Thank you, 
Frank

**Comment by alextselegidis** [comment]
Hello Frank, 

I'm not sure which setup you are using that might cause this issue but I would suggest the newly releases v1.3.0 which has many fixes and might resolve your issue as well. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
