### ISSUE TITLE
Ability to enable period windows

### ISSUE THREAD

**Issue by gaspo53** [alextselegidis/easyappointments#431]
It will be helpfull to enable reservations within a period of time. For example, the system will take reservations only for March 1st to March 15th.

**Comment by alextselegidis** [comment]
Marked as a future feature.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sahlman** [comment]
Has anyone made own customization for this request? It would be very useful.

**Comment by alextselegidis** [comment]
@sahlman I recently merged this pull request

https://github.com/alextselegidis/easyappointments/pull/463

This is coming in 1.4.0

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
