### ISSUE TITLE
Allow admins to define the business closed dates (blocked-periods)

### ISSUE THREAD

**Issue by philipp-sumo** [alextselegidis/easyappointments#432]
it would be great if it were possible to add a section for specific dates to the business logic settings, where customers can't add any bookings.
this would be great for public holidays, bank holidays etc where the whole company is closed and so that unavailable dates don't have to be created for each individual provider repetitiously.

**Comment by alextselegidis** [comment]
Hi @philipp-sumo, good idea! It will be integrated for a future release. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Elvin-Xhimitiku** [comment]
any update on this?

**Comment by alextselegidis** [comment]
Hello @Elvin-Xhimitiku, 

unfortunately no update on this feature yet. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
This is completed in develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
