### ISSUE TITLE
Issue when adding multi-attendant appointment to only slot that will fit on a given day

### ISSUE THREAD

**Issue by EdB987** [alextselegidis/easyappointments#434]
In my testing of 1.2.1 - it seems that issue #298 and #247 of EA get at the issue of ANY PROVIDER.

There seems to be another problem. The search logic (in Appointments.php) seems to break down when the window of available time is less than 2X the service length . The calendar is not blocked by non working, break or not available time.

I'm new to the frame work so am just learning. In all, the tool is perfect for my needs (thank you Alex and Craig) and I'll keep plugging until I determine why the wizard is skipping over clearly available slots.

Thanks for any assistance in tracking this down!

**Comment by alextselegidis** [comment]
Hi @EdB987, can you try the latest release v1.3.0 and see if the issue persist? 

Download the package from easyappointments.org

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
