### ISSUE TITLE
Error on update process from 1.2.1 to 1.3.0

### ISSUE THREAD

**Issue by Caine85** [alextselegidis/easyappointments#438]
Hi! I have an error when I try to update EasyAppointments from the version 1.2.1 to the new version 1.3.0.

The error I get is:
```
Error Number: 1832

Cannot change column 'id_users_customer': used in a foreign key constraint 'ea_appointments_ibfk_2'

ALTER TABLE `ea_appointments` CHANGE `id` `id` int(11) AUTO_INCREMENT, CHANGE `id_users_provider` `id_users_provider` int(11), CHANGE `id_users_customer` `id_users_customer` int(11), CHANGE `id_services` `id_services` int(11)

Filename: migrations/009_change_column_types.php

Line Number: 42
```

I saw the migration file and I realised that is only a minor update for the database, in fact everything continues to work correctly even without the migration update.

Thank you so much!

**Comment by alextselegidis** [comment]
Hi @Caine85, thanks for reporting this issue. 

You are right, this is only a minor change in the schema and won't affect the way Easy!Appoinmtents work. It's only part of infrastructure improvement effort that is gradually integrated release by release. 

I'll take a look at the migration though and try to figure out the problem. 

Thanks for posting. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Pushed on `hotfix` branch.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
