### ISSUE TITLE
Multiple clients for overlapping time slots

### ISSUE THREAD

**Issue by Brixy** [alextselegidis/easyappointments#442]
Is it/it should be possible to set up a number of overlapping slots. Each slot should be bookable for n clients.

The following setup uses `n=4`:

The result could be four clients for 1) and two clients for 2) and one for 3) and 4) each.

Not possible should be: five clients for 1) …

1) 1:00 pm–3:00 pm
2) 1:15 pm–3:15 pm
3) 1:30 pm–3:30 pm
4) 1:45 pm–3:45 pm

Thank you very much.

**Comment by alextselegidis** [comment]
@Brixy you can already set the number of accepted appointments for a given time slot. The time slot size is being defined by the duration of the service. So Easy!Appointments will take these info into concern when generating the availabilities. Is this what you are looking or? :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Brixy** [comment]
Please excuse my late reply. Unexpectedly, I did not have access to our installation.

What you suggest is probably not exactly what is needed in our use case—or I did not get it ;-)

We need to provide four time slots, 120 mins each as shown above. For every slot only _one_ appointment should be accepted. Parallel bookings e. g. at 1pm are not an option here.

Is that possible already?

Thank you very much!

**Comment by alextselegidis** [comment]
Hi @Brixy, I can now understand your request and I have to say that this is not available in the app unfortunately. 

Code modifications can enable this behavior but there are no plans on integrating any time soon. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
