### ISSUE TITLE
Add notification service

### ISSUE THREAD

**Issue by maxmedresearch** [alextselegidis/easyappointments#444]
hello, I wonder if it would be possible to add a notification service. 

Most appointments services, integrates a messaging system between the secretariat and provider for anexes requests, specific appointments, etc.

This includes: date, secretary's name, message, customer's name and contact information, a button to validate if the message has been read or processed, and the opportunity to reply

I know it's big request, Thanks

**Comment by alextselegidis** [comment]
Hello, thanks for posting! 

Unfortunately there are many other things that can be improved that I will have to skip this one. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
