### ISSUE TITLE
Always off four hours

### ISSUE THREAD

**Issue by EricSlusarz** [alextselegidis/easyappointments#446]
Like the title says all my appoints are off a couple of hours when synced to google calendar. I'm trying to look for settings or configuration file that will see if the problem is a timezone error.

**Comment by alextselegidis** [comment]
@EricSlusarz Set up the correct timezone value in your php ini file. 

http://php.net/manual/en/timezones.php

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
