### ISSUE TITLE
Captcha error using docker (500 error). 

### ISSUE THREAD

**Issue by Hendrik44** [alextselegidis/easyappointments#447]
Using docker with easyappointments and the captcha feature will cause an 500 error. I tried to manually install gd but it doesnt solve the issues. 

What can i do to use the captcha feature in combination with the docker image?

**Comment by alextselegidis** [comment]
Do you have any php error messages for us? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Hendrik44** [comment]
I am only get this "GET /index.php/captcha?1521396520811 HTTP/1.0" 500" but noting in Stderr.
Also it seems to be make no sense if i host it on a real server or try it local. Both running into 500 error if i want using captchas.

**Comment by alextselegidis** [comment]
@Hendrik44 Can you also check in the php error log files?

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Hendrik44** [comment]
I tried enable debug mode, but i can't find any error log. So I tried to activate error-logs for php manually because its not active when using docker but the error log is empty. Also the apache error log shows no interesting entries.
![screen shot 2018-03-18 at 20 08 40](https://user-images.githubusercontent.com/4581596/37569940-c1596c70-2ae9-11e8-892d-4f4e940d6fd6.png)

**Comment by alextselegidis** [comment]
@Hendrik44 I'll try to reproduce this on my environment and see if the issue persists. 

If this is a misconfiguration error of Docker we'll be able to correct it with some minor tweaking. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop, the docker configuration also got updated (see docker directory). 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
