### ISSUE TITLE
Add secure flag to CI_SESSION when HTTPS is enabled.

### ISSUE THREAD

**Issue by fgeek** [alextselegidis/easyappointments#45]
Please implement functionality to automatically add Secure flag to ci_session session cookie when HTTPS is used to harden installations, thank you. If you need any more information please contact me.

https://www.owasp.org/index.php/SecureFlag
https://en.wikipedia.org/wiki/HTTP_cookie#Secure_cookie

```
A secure cookie can only be transmitted over an encrypted connection (i.e. HTTPS). This makes the cookie less likely to be exposed to cookie theft via eavesdropping.
```

**Comment by alextselegidis** [comment]
Sounds good :+1:

**Comment by alextselegidis** [comment]
Users can activate the secure flag for cookies by modifying the $config['cookie_secure'] value (to TRUE). 

https://codeigniter.com/user_guide/libraries/sessions.html#session-preferences

So the value is configurable.
