### ISSUE TITLE
'Any Provider' issue

### ISSUE THREAD

**Issue by LewisHalliday** [alextselegidis/easyappointments#451]
Hi, 

I'm having a bit of a strange bug. When selecting 'any provider' it's only showing a couple of days. 

For example;

Any provider selected, 2 dates are shown (22nd & 29th march) as only Thursdays are selected in the business logic (same applied to all providers), but then there is no available dates until november? unsure why that month is selected.

But, if you choose either of the 2 individual providers you can see every Thursday available.

Running version 1.3, PHP 7.1

**Comment by LewisHalliday** [comment]
Just tried the hotfix branch - same issue. Tried multiple browsers (Chrome, Firefox, Safari & IE) all same

**Comment by alextselegidis** [comment]
Hi @LewisHalliday, 

thanks for posting! Are you having more providers on your system? 

The any provider option will search for the first available provider and it could be that it uses a provider that does not share the Thursday only working plan.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
