### ISSUE TITLE
French Spelling

### ISSUE THREAD

**Issue by StansWorld6** [alextselegidis/easyappointments#455]
Hi,

could you, please correct the French Email Notification Title & Body with 'confirmé' instead of 'confimé'.
french/translations_lang.php Line37

Thanks for your fantastic job

**Comment by alextselegidis** [comment]
@StansWorld6, @AurelienC thank you for the contribution!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Merged in hotfix branch!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
