### ISSUE TITLE
NODEJS

### ISSUE THREAD

**Issue by ram-you** [alextselegidis/easyappointments#458]
Hi @alextselegidis 
I have analyzed the source code in detail. 
I noticed that the JAVASCRIPT code was very well written.
And just for that, I tell you **BRAVO**.
Which brings me to the following question :
"**Do you have a plan to migrate your application to NODEJS ?**"
Thank you.

**Comment by alextselegidis** [comment]
Hello @ram-you, I'm glad that you like the app and the codebase. 

Unfortunately at the time being no migration to node is planned but I'm pretty sure that future integrations will be published. 

Stay tuned! :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
