### ISSUE TITLE
Aggregate Appointment API crashes when a break was added

### ISSUE THREAD

**Issue by Caine85** [alextselegidis/easyappointments#459]
Hi!

There is an error using the Appointments API with the "_aggregates_" parameter when a provider adds a break.

A break has null customer and service data. Consequently, `$response['customer']` and `$response['service']` are null in every breaks. 

Therefore, the Appointments Parser crash at:
`$customerParser->encode($response['customer']);`
and at:
`$customerParser->encode($response['service']); `

I will make a pull request to fix this issue.

Thank you so much for all the work made!

**Comment by Caine85** [comment]
Pull request added: #460 .

**Comment by alextselegidis** [comment]
Thanks for the pull request, I will glady merge this but can you please clarify the following: 

*Consequently, $response['customer'] and $response['service'] are null in every breaks.* 

Do you mean breaks in the working plan? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Caine85** [comment]
Hi @alextselegidis !

Yes, I mean a custom break added to the working plan. For instance the break that it's possibile to add with the "Add Break" button on the top right of the backend calendar view.

When a break like that is added to the schedule, its var_dump of the API $response[] passed to the Parser is:
```
array (
  'id' => '82',
  'book_datetime' => '2017-11-13 00:03:37',
  'start_datetime' => '2017-12-25 08:30:00',
  'end_datetime' => '2017-12-25 19:00:00',
  'notes' => 'FESTA - NATALE',
  'hash' => NULL,
  'is_unavailable' => '1',
  'id_users_provider' => '85',
  'id_users_customer' => NULL,
  'id_users_creator' => NULL,
  'id_services' => NULL,
  'id_google_calendar' => NULL,
  'service' => NULL,
  'provider' => 
  array (
    'id' => '85',
    'first_name' => 'Simone',
    'last_name' => 'Bacci',
    'email' => 'simone.bacci@dentalray.it',
    'mobile_number' => '',
    'phone_number' => '3393463178',
    'address' => '',
    'city' => '',
    'state' => '',
    'zip_code' => '',
    'notes' => '',
    'id_roles' => '2',
    'id_users_creator' => NULL,
  ),
  'customer' => NULL,
)
```
In this scenario, `array_key_exists('customer', $response)` is **true** and so the nested code is executed:
```
if (array_key_exists('customer', $response))
        {
            $customerParser = new Customers();
            $customerParser->encode($response['customer']);
            $encodedResponse['customer'] = $response['customer'];
        }
```
But at `$customerParser->encode($response['customer']);` will be raised an error because `$response['customer']` is NULL, as you can see in the var_dump above.

In my pull request, instead of `array_key_exists()`, it's used `isset()` that check both if the key exists and even if the key is truly different from NULL.

This error appears even for the service key.

Thank you so much for you work!

I hope I explained myself well 😄

**Comment by alextselegidis** [comment]
Hi @Caine85, thanks for the clarifications! 

However the error does not lie in the custom breaks of the providers but in the fact that the appointments endpoint was returning unavailabilitites as well. This should not be the case though as there is another endpoint for the unavailabilitites. 

I will still merge your pull request though as it makes the code more robust 👍 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
