### ISSUE TITLE
Invalid working plan parsing for foreign languages on day view of the default calendar view.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#461]
When not using english the complete day is being displayed as non-working although the working plan might be differently set. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Caine85** [comment]
Related to #436 😄

**Comment by alextselegidis** [comment]
@Caine85 Oh, skipped that one! You are totally right :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
