### ISSUE TITLE
Open Api Spec

### ISSUE THREAD

**Issue by ChristopheCubat** [alextselegidis/easyappointments#462]
Any chance that you have written the Open Api spec to use with swagger?

**Comment by alextselegidis** [comment]
This is something I planned to do for a while but it's not ready yet. 

This will come with an upcoming release but feel free to make a pull request with the swagger files if you get it done beforehand. 

I'm currently preparing the 1.3.1 revision release. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Starting from v1.4.0 there's a swagger file in the docs directory.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
