### ISSUE TITLE
Not sending confirmation emails to customers upon them making an appointment

### ISSUE THREAD

**Issue by sgalla1994** [alextselegidis/easyappointments#467]
Hi I have installed easy appointments onto my server using v1.3.0 but how do I go about setting up the mailing system? so when a customer makes an appointment it sends an auto confirmation email to the customer? 

any help would be grateful! 

Thanks

**Comment by AurelienC** [comment]
Hello,

You could set params for mailing into email.php

[src/application/config/email.php](https://github.com/alextselegidis/easyappointments/blob/master/src/application/config/email.php)

**Comment by alextselegidis** [comment]
@
