### ISSUE TITLE
ERR_TOO_MANY_REDIRECTSsend @ jquery.min.js:5m.extend.ajax @ jquery.min.js:5m.(anonymous function) @ jquery.min.js:5(anonymous function) @ (index):60m.event.dispatch @ jquery.min.js:4r.handle @ jquery.min.js:4

### ISSUE THREAD

**Issue by thileepinfo** [alextselegidis/easyappointments#47]
GET http://www.website.com/ net::ERR_TOO_MANY_REDIRECTS

send @ jquery.min.js:5
m.extend.ajax @ jquery.min.js:5
m.(anonymous function) @ jquery.min.js:5
(anonymous function) @ (index):60
m.event.dispatch @ jquery.min.js:
4r.handle @ jquery.min.js:4

**Comment by alextselegidis** [comment]
Hello, can you provide extra information? 

... like which page has the problem, if you have managed to get the app working, which E!A version do you use, is it hosted in website.com ...
