### ISSUE TITLE
Add new system-wide setting that enable users to choose the first day of the week. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#471]
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
Hi Alex,

Further to our conversation in the google group and in my attempt to implement this feature, I have a question regarding `src\assets\js\backend_users_providers.js`.

It looks like `ProvidersHelper.prototype.editableBreakDay`  is not used. When editable breaks are displayed in the calendar, only `WorkingPlan.prototype.editableBreakDay` in `src\assets\js\working_plan.js` is used. 

Am I correct?

**Comment by alextselegidis** [comment]
Sorry for the late reply, you are right it is not being used. 

Such methods have to be removed.

Thanks for the pull request! I'll check this out and eventually merge with develop.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
I am working on having the days sorted also in the setting pages.
I will complete the pull request when it is finished.

**Comment by alextselegidis** [comment]
Great news! Looking forward to see this.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Your pull request is merged on develop. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
