### ISSUE TITLE
Getting blank Page after changing config.php file. 

### ISSUE THREAD

**Issue by 0lympic** [alextselegidis/easyappointments#472]
Before change to the config file:
Fatal_ error: require_once(): Failed opening required '/homepages/21/d195513253/htdocs/news/skedge/config.php' (include_path='.:/usr/lib/php5.4') in /homepages/21/d195513253/htdocs/news/skedge/index.php on line 40

After change to config file, a blank page, here's the contents:
    // ------------------------------------------------------------------------
    // GENERAL SETTINGS
    // ------------------------------------------------------------------------

    const BASE_URL      = 'http://www.olympicholidaysnewsletters.com/skedge';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = FALSE;

    // ------------------------------------------------------------------------
    // DATABASE SETTINGS
    // ------------------------------------------------------------------------

    const DB_HOST       = 'db736228640.db.1and1.com';
    const DB_NAME       = 'db736228640';
    const DB_USERNAME   = 'dbo736228640';
    const DB_PASSWORD   = ********';

    // ------------------------------------------------------------------------
    // GOOGLE CALENDAR SYNC
    // ------------------------------------------------------------------------

    const GOOGLE_SYNC_FEATURE   = FALSE; // Enter TRUE or FALSE
    const GOOGLE_PRODUCT_NAME   = '';
    const GOOGLE_CLIENT_ID      = '';
    const GOOGLE_CLIENT_SECRET  = '';
    const GOOGLE_API_KEY        = '';

So I'm not even getting to the install stage...

**Comment by oxteam** [comment]
I think you should better not provide such sensitive information like the db names and username even if you masked the password : it could help an attacker. Except if it is only a test server for the moment...

You should set DEBUG_MODE to TRUE, so that you may have useful debug information that could help to understand what occurred.

Hope it helps
