### ISSUE TITLE
Upgrade problem 1.2.1 to 1.3.1beta : all old data no accessible/shown

### ISSUE THREAD

**Issue by chtse53** [alextselegidis/easyappointments#473]
I tried upgrade from 1.2.1 to 1.3.0, error number 1832 occurred. When login backend, previous data not accessible. Calender, users, customers ... all blank data. The calendar was not shown at all. I tried upgrade from 1.2.1 to 1.3.1beta1.  It was said to be successful after running .../backend/update.  However, same thing happened: all old data not shown/blank.

**Comment by alextselegidis** [comment]
@chtse53 Thanks for posting this. 

Are you getting any JS errors? 

How do your db entries look like? Any corrupted data? Some migrations are being executed.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@chtse53 Any updates on this? 

I was checking the migration script and worked correctly locally. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by chtse53** [comment]
Thank you so much for creating the software and responded to my issue.  I am yet to check the issue more carefully.  At first it appeared to be an upgrade problem. I later tried a fresh install of 1.3.1beta on my ubuntu 14.04LTS server (php5.6 apache2) and I still got a blank calendar screen, not even the calendar frame was shown. So it probably is not related to the upgrade scripts.  I later tried fresh install of 1.3.0 on that same server and it appeared to work.  There might be something in the 1.3.1 beta that was not compatible with my setup.  I will continue to test and let you know if I got some clues.

 

Thanks again.

 

Chris Tse

**Comment by alextselegidis** [comment]
Thanks @chtse53 

Any error message or other info might be helpful to spot the issue. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
