### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by mugurcagdas** [alextselegidis/easyappointments#478]
Dear Sir/Madam,

I am computer engineer and graphic designer. I use your plugin in my customers' websites. I appreciate that.
I am writing you because I want to design a logo for this plugin.
May I ask, do you need a logo for this plugin?

Kindly waiting your answer.

Best Regards,
Musa Ugur Cagdas
Computer Engineer/Graphic Designer

**Comment by alextselegidis** [comment]
Hi @mugurcagdas, thank you for your kind message.

I'd like to update the logo of Easy!Appointments. Can you send me some sample designs on alextselegidis@gmail.com? 

Thanks! 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
