### ISSUE TITLE
Cross-Origin request blocked

### ISSUE THREAD

**Issue by lukasista** [alextselegidis/easyappointments#479]
Story:
On the start of installation, when I get first page, where I have to fill base information about me and my company, I gat error message: "Unexpected Issue: The operation could not complete due to unexpected issues."

Message in browser console:
Cross-Origin request blocked: A policy of the same origin does not allow loading of the remote source at http://lukaspivonka.cz/jojo/rezervace/index.php/installation/ajax_install. (Reason: CORS 'Access-Control-Allow-Origin' header is missing).

How I can fix it?

Thanks for any sollution of this issue

**Comment by benchaneikaiwa** [comment]
Same issue here.

**Comment by alextselegidis** [comment]
Adjust your config.php file and add `http://www.lukaspivonka.cz/jojo/rezervace` as your BASE_URL value. 

Also visit your page like from the exactly same address (including the `www`). 

The app normally does not have any problem with having www or not but some hosting environments unfortunately do.

Your hosting provider might be able to change this behavior of course :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
