### ISSUE TITLE
Make the app GDPR - new EU privacy regulations compliant.

### ISSUE THREAD

**Issue by bukowskiadam** [alextselegidis/easyappointments#480]
Hi there 👋 

I'm not an expert in this topic, but according to changes in all other services and my knowledge it seems that EasyAppointments requires some changes in the registration process according to upcoming EU regulations. User has to be aware why we need his data, that it's going to be used only for registration and he has to agree with that by action like checking checkbox.

Can someone confirm that?

**Comment by robertzaage** [comment]
The privacy policy needs to be accessible on the registration process and agreed by the customer before processing any of their data.

**Comment by alextselegidis** [comment]
Will be added for 1.3.1 

thanks for posting 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
FYI I'm currently working on the compliance of the app. An update will become available soon. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@bukowskiadam @robertzaage 

Here's the 1.3.2 beta 1 package that contains GDPR support: 

https://github.com/alextselegidis/easyappointments/releases/download/1.3.2-beta.1/easyappointments_1.3.2_beta.1.zip

Let me know if you find any issues. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bukowskiadam** [comment]
Finally I had some time to test it. It works great! I don't quite get the logic of updating consent record, because I don't see frontend part to use id returned by backend, but maybe it's for the future. Thanks again.

**Comment by alextselegidis** [comment]
I'm not really sure which ID you are referring to but the main idea is that all the user agreements are being stored with their info and IP address for future reference. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by bukowskiadam** [comment]
Sorry for not being precise. This one
https://github.com/alextselegidis/easyappointments/blob/master/src/application/models/Consents_model.php#L33

**Comment by alextselegidis** [comment]
Oh right, yeah currently there's no place that updates the consent but that may come in the future so I went ahead and used the same model schema as with other modules added support for updates. The whole model layer is very thin anyway :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rjrodriguezalvarez97** [comment]
Hello,
I've been testing E!A today and it looks great so far! After some tests I realized that the user is able to delete its personal information when he's updating his appointment. If so, that deletes all past appointments too. Is this the desired behaviour?

**Comment by alextselegidis** [comment]
Hi @rjrodriguezalvarez97, correct that's a desired behavior.

The new GDPR regulation requires that users have full control of their data and that means that they should also be able to remove their information from the system. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rjrodriguezalvarez97** [comment]
Hi @alextselegidis thanks for your reply.
I was thinking that it may be interesting to keep appointments data for statistics purposes or to keep a history record for providers.
As I saw online it is allowed by the GPDR to anonymize personal data from a user to this kind of purposes. In case that you are interested in change the behaviour I'm willing to offer myself to do it if necessary.
There are some apps that apply this behaviour: [source 1](https://gdpr-wp.com/knowledge-base/deleting-and-or-anonymizing-user-data/) [source 2](https://knowledge.hubspot.com/articles/kcs_article/contacts/how-do-i-perform-a-gdpr-compliant-delete-in-hubspot) [source 3](https://classic-infusionsoft.knowledgeowl.com/help/gdpr-anonymize-a-contact)
