### ISSUE TITLE
Support for international characters in site url

### ISSUE THREAD

**Issue by fallberg** [alextselegidis/easyappointments#482]
Hi Alex,
Would it be possible to get support to specify international characters in the site url so that the links in emails sent point to the same url as they used to book?
Example: "logopæden" has to be written "xn--logopden-n0a". Which appear quite unnerving to customers.

**Comment by alextselegidis** [comment]
Although an old ticket, this seems to be an issue not many users have reported and I will therefore close it for now. 

Do let me know if there are other cases similar to this one. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
