### ISSUE TITLE
No provider on the appointment page 

### ISSUE THREAD

**Issue by JullieMam** [alextselegidis/easyappointments#484]
I dont know how to delete the option to choose a provider when someone tries to make an appointment because i will only be using 1 and its a bit weird.

**Comment by alextselegidis** [comment]
Open `application/views/appointments/book.php` with an editor and add the `hidden` class to the provider form-group. 

``` 
<div class="form-group hidden">
    <label for="select-provider">
        <strong><?= lang('select_provider') ?></strong>
    </label>

    <select id="select-provider" class="col-xs-12 col-sm-4 form-control"></select>
</div>
```

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by skylarmt** [comment]
You'd also want to edit `application/language/english/translations_lang.php` and change `$lang['step_one_title'] = 'Select Service & Provider';` so it doesn't say "& Provider".
