### ISSUE TITLE
NginX difficulties 

### ISSUE THREAD

**Issue by partnerwerk** [alextselegidis/easyappointments#486]
Hi there, maybe anyone could help out...

I tried several solutions from the forum to get EA working with NginX. However I get 500 errors and don't know what to do.

Here is my current NginX vhost config:

```
index index.html index.htm index.php index.cgi index.pl index.xhtml;

location ~ \.php$ {
    try_files /2f12061db9b83d2f469d9690c03cbb71.htm @php;
}

location @php {
    try_files $uri =404;
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/var/lib/php7.0-fpm/web46.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_intercept_errors on;
}

location / {
        if (!-e $request_filename){
                rewrite ^(.*)$ /index.php?/$1 last;
        }

        try_files $uri $uri/ /index.php?/$args;
}

location /assets {
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
}
```

**Comment by alextselegidis** [comment]
Hello @partnerwerk, please try this official codeigniter recipe: 

https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

I had configured Easy!Appointments with NGINX in the past without problems. 

Hope that helps :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rafamerino** [comment]
Here's my working config for EA! 1.3.2 on nginx, for the sake of any person looking for a solution:

File: **/etc/nginx/sites-available/your.ea.conf**

`server {
        listen 80;
        server_name domain.com;
        root /var/www/your.path;
        index index.php;
        include snippets/php-nginx.conf; #PHP COMMON SETTINGS
        location ~ /\.ht {
        deny all;
        }
if (!-f $request_filename){
        set $rule_0 1$rule_0;
}
if (!-d $request_filename){
        set $rule_0 2$rule_0;
}
if ($rule_0 = "21"){
        rewrite ^/(.*)$ /index.php?/$1 last;
}

}`

File: **/etc/nginx/snippets/php-nginx.conf**

`location ~ \.php$ {
include snippets/fastcgi-php.conf;
fastcgi_pass       unix:/var/run/php/php7.2-fpm.sock;
fastcgi_param      SCRIPT_FILENAME $document_root$fastcgi_script_name;
include fastcgi_params;
fastcgi_read_timeout 100; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_connect_timeout 50; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_send_timeout 100; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_buffer_size 128k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_buffers 4 256k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_busy_buffers_size 256k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_temp_file_write_size 256k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
fastcgi_intercept_errors on;
}
`

**Comment by SweetSofiMC** [comment]
Just confirming @rafamerino solution works!

Here's my config for ssl https:

File: **/etc/nginx/sites-available/easyappointments.conf**
```
server {
    listen 80;
    server_name my.domain; # Change this
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name my.domain;  # Change this

    ssl_certificate /etc/letsencrypt/live/my.domain/fullchain.pem;  # Change this
    ssl_certificate_key /etc/letsencrypt/live/my.domain/privkey.pem;  # Change this

    root /var/www/ea;

    access_log /var/log/nginx/ea.app-access.log;
    error_log  /var/log/nginx/ea.app-error.log error;

    index index.php;
    include snippets/php-nginx.conf;

    location ~ /\.ht {
        deny all;
    }

    if (!-f $request_filename){
        set $rule_0 1$rule_0;
    }
    if (!-d $request_filename){
        set $rule_0 2$rule_0;
    }
    if ($rule_0 = "21"){
        rewrite ^/(.*)$ /index.php?/$1 last;
    }
}
```

And the snippet uses php7.4 instead of 7.2.
File: **/etc/nginx/snippets/php-nginx.conf**
```
location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 100; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_connect_timeout 50; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_send_timeout 100; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_buffer_size 128k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_buffers 4 256k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_busy_buffers_size 256k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_temp_file_write_size 256k; # >>> THIS IS VARIABLE UPON YOUR REQUIREMENTS
        fastcgi_intercept_errors on;
}
```
