### ISSUE TITLE
Email From

### ISSUE THREAD

**Issue by NTuneMusic** [alextselegidis/easyappointments#487]
I have noticed that when an email is sent, it says that it is from WordPress (and then our email address.) How can I change that to say our company name?

![easy-appointments](https://user-images.githubusercontent.com/35422914/40585444-d3f74b36-6180-11e8-8772-266b4730bf05.jpg)

**Comment by alextselegidis** [comment]
@NTuneMusic Check for the engine/Notifications/Email.php file 

There a new instance of PHPMailer is created and you can adjust which info shall be used for your notifications.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
