### ISSUE TITLE
Backend settings.php issue

### ISSUE THREAD

**Issue by chazdiezal** [alextselegidis/easyappointments#49]
In v1.1.0 there is a typo in the code where thursday should be, it is tuesday.  This was causing thursday to no be recognized in the backend business logic.
Thanks

                                       <div class="checkbox">
                                            <label>
                                                <input type="checkbox" id="tuesday" />
                                                    <?php echo $this->lang->line('tuesday'); ?>
                                            </label>
                                        </div>
                                    </td>
                                    <td><input type="text" id="thursday-start" class="work-start" /></td>
                                    <td><input type="text" id="thursday-end" class="work-end" /></td>

**Comment by alextselegidis** [comment]
Has been corrected. Thanks :+1:
