### ISSUE TITLE
Replace hardcoded string with translation in appointment details email template.

### ISSUE THREAD

**Issue by fallberg** [alextselegidis/easyappointments#491]
Hi Alex,
there appear to be a small translation bug in the confirmation email. It has hardcoded 'minutes' for appointment duration.
I suggest changing
`'$appointment_duration' => $service['duration'] . ' minutes',`
into something like
`'$appointment_duration' => $service['duration'] . ' ' . $this->framework->lang->line('minute'),`

**Comment by alextselegidis** [comment]
@fallberg Thanks for posting, will be included in 1.3.1

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
