### ISSUE TITLE
Multiple attendants within an hour appointment is not working

### ISSUE THREAD

**Issue by giconte** [alextselegidis/easyappointments#492]
Hello,

Trying to create a one hour appointment per week, with a maximum of 40 attendees.

I've set up Service Settings like the following:
Service duration: 60 minutes
Attendants number: 40

Working Plan is Thursday from 14:00 to 15:00 pm

The problem is that the when a person books the appointment it takes the whole hour, therefore; the other 39 people that would like to book for the same appointment can not do that.
Also, tested the booking system by reducing the service duration to 20 minutes and reduced the attendants number down to 10 for the same above working plan, the booking system should allow 30 attendees to book for the same appointment, but only 21 are allowed. I do not know if the 2 above mentioned problems are part of the same issue. I would like to know if there is a workaround for this problem

Thank you

**Comment by alextselegidis** [comment]
Hello @giconte, I'll try to reproduce this and find more info on the issue. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@giconte I tried reproduce the error but to no avail. For me it works just fine. 

Are you using the latest release? 

I would recommend testing with 1.3.2 beta 1 and see if there is an error there. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I still cannot reproduce this issue, it will be closed due to inactivity. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by div4d** [comment]
Hello, I am not sure if my issue is the same as per the above one. 
in one of my slots, I set up a maximum attendance of 10 persons but now that seven clients booked, no one can book that slot anymore. I am not sure if seven is the "correct" number, I just can only see seven persons in the calendar view (both table and default).
am I missing something in the calendar view or is there any automatic cap?
many thanks

**Comment by MARVINM22** [comment]
I have two services .. Service A with a time of 20 minutes and 3 attendants and Service B with 30 minutes and 1 attendants.

The system has already reserved for Service A, two hours. 9: 40-10: 00 and 10: 00-10: 20.

Service B is reserved only from 10:30 to 11:00;
When a customer tries to select Service B and select the 10:00 time, they send the following message:

The required quote is unfortunately not available. Please select a different time for your appointment.

Why?
