### ISSUE TITLE
Allowing Duplicate Emails for Providers\Customer

### ISSUE THREAD

**Issue by rbhattad31** [alextselegidis/easyappointments#504]
Hello,

Is it possible for us to allow multiple customers with same emails? We need to tracks customers at providerAl level.

Also is it possible to allow multiple providers with same email? Use case is corporate groups trying  to login with same email for different providers.

**Comment by alextselegidis** [comment]
For customers you must comment out the following block in Customers_model.php 

```
        // :: CHECK IF CUSTOMER ALREADY EXIST (FROM EMAIL).
        if ($this->exists($customer) && ! isset($customer['id']))
        {
            // Find the customer id from the database.
            $customer['id'] = $this->find_record_id($customer);
        }
```

For the multiple provider you have to comment out the following block fom Providers_model.php


```
$num_rows = $this->db
            ->select('*')
            ->from('ea_users')
            ->join('ea_roles', 'ea_roles.id = ea_users.id_roles', 'inner')
            ->where('ea_roles.slug', DB_SLUG_PROVIDER)
            ->where('ea_users.email', $provider['email'])
            ->where('ea_users.id <>', $provider_id)
            ->get()
            ->num_rows();

        if ($num_rows > 0)
        {
            throw new Exception('Given email address belongs to another provider record. '
                . 'Please use a different email.');
        }
```


<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by HybridRCG** [comment]
This document is now outdated as only commenting out does not resolve the question above.
