### ISSUE TITLE
Working plan created in version 1.2.1 wrongly displayed in backend with version 1.3.1

### ISSUE THREAD

**Issue by oxteam** [alextselegidis/easyappointments#506]
Hi Alex,

With version 1.3.1, weeks start with Sunday whereas with 1.2.1 it was starting with Monday.

Let's take the example of a user only working on Fridays with some breaks on Fridays.
His availability is displayed in the backend only for Fridays as seen in the below snapshot:
![freefriday_121](https://user-images.githubusercontent.com/38721222/41669407-0703ce2a-74b2-11e8-9d46-3817374e657e.PNG)

Now, if you migrate to v1.3.1, you can see that the backend displays the availability of this user not on Friday but on Thursday as seen in the below snapshot:
![freefriday_131](https://user-images.githubusercontent.com/38721222/41669546-5778b122-74b2-11e8-8d25-770a68465247.PNG)

I checked in the database.
When a provider and its associated working plan is created in a 1.2.1 version, the JSON in column working_plan of table ea_user_settings table is as follows:
{"monday":null,"tuesday":null,"wednesday":null,"thursday":null,"friday":{"start":"09:00","end":"18:00","breaks":[{"start":"10:00","end":"11:00"},{"start":"14:30","end":"15:00"}]},"saturday":null,"sunday":null}

Whereas, if you create the same user with the same working plan in a 1.3.1 version, the JSON will be:
{"sunday":null,"monday":null,"tuesday":null,"wednesday":null,"thursday":null,"friday":{"start":"09:00","end":"18:00","breaks":[{"start":"10:00","end":"11:00"},{"start":"14:30","end":"15:00"}]},"saturday":null}

Manually moving the "sunday" entry from the end to the beginning of the JSON structure in the database solves the display issue.

I've just realized that there is even an easier way to reproduce the problem.

1. Perform a fresh EA! v1.2.1 install
2. You see that John Doe works from Monday to Friday in the backend calendar.
3. Upgrade to EA! v1.3.1
4. Then in the backend, you can see that John Doe is displayed as if he would work from Sunday to  Thursday.

So it means that any working plan inherited form an EA! version using Monday as the first day of the week will be wrongly displayed in the backend with EA! v 1.3.1.

It is only a display issue, the availabilities are correctly managed in the booking page.

At last, after the migration, on Firefox, I had to clean my cache (ctr+F5) to have the calendar updated. So, the cache auto-refresh was not working. I am going to create an other issue for this topic.

**Comment by alextselegidis** [comment]
The pull request is merged, thanks!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
