### ISSUE TITLE
Need to manually clean the cache when migrating from EA! 1.2.1 to EA! 1.3.1

### ISSUE THREAD

**Issue by oxteam** [alextselegidis/easyappointments#507]
Hi Alex,

When you install version EA! 1.2.1 if you then upgrade to EA! 1.3.1, the backend calendar view is blank as seen in the below snapshot at least with Firefox.
![migration_121_131](https://user-images.githubusercontent.com/38721222/41670443-9a27b7b4-74b4-11e8-82c8-381ccc7d6f00.PNG)

I had to force a full refresh with ctrl-F5.

**Comment by alextselegidis** [comment]
@oxteam It seems that cache busting did not do the trick cause normally asset files are being loaded with a cache busting parameter. 

Can you check if caching is working for you on Firefox? Could it be that this is a server issue? Are you using apache or NGINX? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
For firefox, it is the stable release on Win10 with only 2 extensions (ublock origin and basic gestures).
I now have version 61 (it was a previous version when I opened the ticket).

I saw the problem by testing on my own computer with WAMP, so running Apache.
I do not use the zip archive, I use a git workspace and I have an Apache Virtual Host pointing to the src/ folder of my git workspace.

When testing version 1.2.1, I am synced on commit fe3c9ba08e058a2bdd623866222a5ceb802ff1b1 to have the autoload_static.php file ok.

When testing the migration to 1.3.1, I am synched on commit a2d72c068cf1baaf8322a7710756db2f4a351b1c  (tag 1.3.1).

I have just tested again with a fresh install of firefox and now it works.
So, I close the issue as I cannot reproduce with Firefox once it has been auto-updated.

However, please note that during the process update there is an error displayed which could surprise people who don't know they have to retype the update url.

With a 1.2.1 database, once synced on 1.3.1 source code, to update the database::

1. You go to `http://url-to-ea-installation/index.php/backend/update`:
2. You enter your admin login and password.

3. Then  you are redirected to `http://url-to-ea-installation/index.php/backend/` where the following message is displayed:
> **An uncaught Exception was encountered**
> Type: Exception
> Message: $name setting does not exist in database: time_format

4. You need then to retype  `http://url-to-ea-installation/index.php/backend/update` to have the update to be performed successfully.

I assume that some users may think the update has filed due to the message displayed in step 3 whereas it is not a blocking issue.

**Comment by oxteam** [comment]
Waiting ALex's reply on the opportunity to close this issue due to the second topic opened in this ticket.

**Comment by alextselegidis** [comment]
This will be closed for now, it does not seem to be an issue any more. 
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
