### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by gokkstudio** [alextselegidis/easyappointments#508]
Hi, is there a way to have fullscreen view on by default or based on device?
Thanks

**Comment by alextselegidis** [comment]
@gokkstudio You could add a small snippet in the backend_calendar.js initialize method that will check for your desired condition and trigger the fullscreen accordingly. 

`application/assets/backend_calendar.js`

You could for example check the viewport width: 

```
if (window.innerWidth < 468) {
  $('#toggle-fullscreen').trigger('click'); 
}
var defaultView = window.innerWidth < 468 ? 'agendaDay' : 'agendaWeek';
```

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
