### ISSUE TITLE
Session dir seems to want to write at the server base bath, not application base path

### ISSUE THREAD

**Issue by peteshaped** [alextselegidis/easyappointments#509]
I looked around but didn't see this question answered, apologies in advance if I missed something obvious.

I'm trying to create a booking page under a subdirectory on my hosting provider called 'booking' where easyappointments would run from. I've swapped my URL for www.example.com in the following. 

I unzipped 1.3.1 and the only lines I've changed in the config.php file looks like this (aside from database config):

```
    const BASE_URL      = 'http://www.example.com/booking';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = TRUE;
```

It seems that it's trying to find a session directory outside the BASE_URL path though, seemingly in /session which would resolve to `/var/www/vhosts/example.com/session`. 

This is the error I get after the config.php change and uploding to my site:

```
A PHP Error was encountered
Severity: Warning

Message: is_dir(): open_basedir restriction in effect. File(/var/www/vhosts/example.com/session) is not within the allowed path(s): (/var/www/vhosts/example.com/httpdocs:/tmp:/usr/share/pear)

Filename: drivers/Session_files_driver.php

Line Number: 134

A PHP Error was encountered
Severity: Warning

Message: mkdir(): open_basedir restriction in effect. File(/var/www/vhosts/example.com/session) is not within the allowed path(s): (/var/www/vhosts/example.com/httpdocs:/tmp:/usr/share/pear)

Filename: drivers/Session_files_driver.php

Line Number: 136

An uncaught Exception was encountered
Type: Exception

Message: Session: Configured save path '/var/www/vhosts/example.com/httpdocs/booking/application/config/../../storage/sessions' is not a directory, doesn't exist or cannot be created.

Filename: /var/www/vhosts/example.com/httpdocs/booking/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 138

A PHP Error was encountered
Severity: Warning

Message: file_exists(): open_basedir restriction in effect. File(cmt3rv530b89g1vj0iv7ei50k5cd364e) is not within the allowed path(s): (/var/www/vhosts/example.com/httpdocs:/tmp:/usr/share/pear)

Filename: drivers/Session_files_driver.php

Line Number: 170

A PHP Error was encountered
Severity: Warning

Message: fopen(): open_basedir restriction in effect. File(cmt3rv530b89g1vj0iv7ei50k5cd364e) is not within the allowed path(s): (/var/www/vhosts/example.com/httpdocs:/tmp:/usr/share/pear)

Filename: drivers/Session_files_driver.php

Line Number: 172

A PHP Error was encountered
Severity: Warning

Message: fopen(cmt3rv530b89g1vj0iv7ei50k5cd364e): failed to open stream: Operation not permitted

Filename: drivers/Session_files_driver.php

Line Number: 172

A PHP Error was encountered
Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/www/vhosts/example.com/session)

Filename: Unknown

Line Number: 0
```

I have tried editing the codeignitor config to hard code a session path, but it didn't help.

Thanks in advance for any help you can offer. Ideally I'm making a simple mistake which I am not able to see.

All the best,
Pete

**Comment by peteshaped** [comment]
I've worked around the issue for now by modifying the session drive to database. It would be nice to understand if there is any way to fix the original issue though.

Thanks again,
Pete

**Comment by alextselegidis** [comment]
Hi @peteshaped 

so basically the app will write sessions in the /storage/session/* directory. 

You will find the corresponding configuration `application/config/config.php`. 

It looks like this: 

```
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ea_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = __DIR__ . '/../../storage/sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
```

Reference: https://www.codeigniter.com/user_guide/libraries/sessions.html

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by peteshaped** [comment]
Hello @alextselegidis 

Ideally you'd have waited for a response before closing, but I understand this looks like a simple issue.

In fact I initially tried to have it write to the storage location in `/httpdocs/booking/storage/sessions` but as you can see from the errors above it wasn't able to do that. This is what my code looked like first:

`
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ea_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = __DIR__ . '/../../storage/sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
`

Since that didn't work (with the errors above, even though the easybooking scripts were able to write to the logs directory in the same tree (making me think permissions weren't the issue, rather that it seemed to want to write to `/httpdocs/session`, which it didn't have permissions for.

Anyway - this is the change I made to config in codeigniter to get it to work in the end:

`
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ea_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
`

And obviously, I had to make that table in the database as well:

`
CREATE TABLE IF NOT EXISTS `ci_sessions` (
    `id` varchar(40) NOT NULL,
    `ip_address` varchar(45) NOT NULL,
    `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
    `data` blob NOT NULL,
    KEY `ci_sessions_timestamp` (`timestamp`)
);
`

Oh, and one final change in database.php

`
$db['default']['pconnect'] = FALSE;
`

See this reference for further information in case you want to do anything with it regarding extending your project to optionally support a database for session data:

https://stackoverflow.com/questions/37776545/codeigniter-sess-driver-and-path

**Comment by alextselegidis** [comment]
Hi @peteshaped thanks for the feedback. 

I was thinking in the past to set the sessions write in the database but it seemed to me that the filesystem is the correct place to go. 

Actually what causes trouble for you is the `open_basedir` php.ini value setting. This one will disallow the app from storing the files in the `storage/session` directory. 

More info on the setting: http://php.net/manual/en/ini.core.php#ini.open-basedir

I closed the issue cause this is a server specific error. I would gladly reconsider to store sessions in the database but then the next feature that uses storage (e.g. logs, cache etc) will kick again so that is not really a solution. 

You did well though by using the database driver, probably this is something that needs to be written in the docs. 

Let me know how this works for you :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
