### ISSUE TITLE
Providers should not be able to create appointments for other providers in the backend calendar page. 

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#510]
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mylk** [comment]
Hello Alex.

Take a look at the pull request above, which limits the providers a user can see while creating appointments.

- Admin, of course, can see any
- A provider can see only himself.
- A secretary can see any provider that is assigned with.

**Comment by alextselegidis** [comment]
Hello @mylk, thanks you very much for the pull request. 

Unfortunately I'll have to close this as I'll be doing the validation in the javascript part. That way the fix requires a smaller change for the app.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
