### ISSUE TITLE
Only show appointments of the currently logged in provider.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#512]
In version 1.3.1 when you logged in as provider1 and selects customer on Customer Page, you can see appointments of customers of other providers.
To eliminate this "inconvinience" you can change the folowing code in file assets\js\backend_customers_helper.js
lines 320 - 328

```  
///Start

var start = GeneralFunctions.formatDate(Date.parse(appointment.start_datetime), GlobalVariables.dateFormat, true);
            var end = GeneralFunctions.formatDate(Date.parse(appointment.end_datetime), GlobalVariables.dateFormat, true);
            var html =
                '<div class="appointment-row" data-id="' + appointment.id + '">' +
                start + ' - ' + end + '<br>' +
                appointment.service.name + ', ' +
                appointment.provider.first_name + ' ' + appointment.provider.last_name +
                '</div>';
            $('#customer-appointments').append(html);

///End
```

```
//replace with:
///Start

if (GlobalVariables.user.id==appointment.id_users_provider || GlobalVariables.user.id=='1'){
            var start = GeneralFunctions.formatDate(Date.parse(appointment.start_datetime), GlobalVariables.dateFormat, true);
            var end = GeneralFunctions.formatDate(Date.parse(appointment.end_datetime), GlobalVariables.dateFormat, true);
            var html =
                '<div class="appointment-row" data-id="' + appointment.id + '">' +
                start + ' - ' + end + '<br>' +
                appointment.service.name + ', ' +
                appointment.provider.first_name + ' ' + appointment.provider.last_name +
                '</div>';
            $('#customer-appointments').append(html); 
                    }

///End
```
Where '1' is id of your administrator in database table _users. Good luck.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mylk** [comment]
Hello Alex.

The problem is on the endpoint the AJAX call is done to, on the Customers page.
A provider or secretary can see the customers of other.

That's what i tried to fix with the pull request above.
Please take a look
