### ISSUE TITLE
GDPR DB migration fails with MariaDB 5.5.x

### ISSUE THREAD

**Issue by oxteam** [alextselegidis/easyappointments#518]
Hi Alex,

On CentOS 7, the default supported version of MariaDB is MariaDB 5.5.x.
It is old, but it is the packet officially maintained by this distro.
The problem is that Mysql/Mariadb 5.5.x versions:
- do not support the `timestamp `attribute for `DATETIME` type;
- do not support more than one column with a `timestamp ` in a table with auto update of the field.

As a consequence, the migration script for GDPR fails when creating the ea_consents table:
`#1067 - Invalid default value for 'created'` 

It seems that newer branches of MySql/MariaDB support the syntax you used.
But on production servers, migrating to a newer major version of the database engine require testing. I assume it is the reason why CentOS maintainers do not use it.

Hopefully, a workaround exists. I found this post still [available on internet archive](https://web.archive.org/web/20160401143159/http://michaelkimsal.com/blog/mysql-using-two-timestamps-for-createdupdated-values/) :

> mysql>` create table sample ( timeUpdated TIMESTAMP, timeCreated TIMESTAMP, val INT );`
> Query OK, 0 rows affected (0.24 sec)
> 
> mysql> `insert into sample (timeUpdated, timeCreated, val) values (NULL,NULL,1);`
> Query OK, 1 row affected (0.00 sec)
> 
> mysql> `select * from sample;`
> +———————+———————+——+
> | timeUpdated | timeCreated | val |
> +———————+———————+——+
> | 2007-10-24 15:25:03 | 2007-10-24 15:25:03 | 1 |
> +———————+———————+——+
> 1 row in set (0.00 sec)
> 
> mysql>` update sample set val=val+1;`
> Query OK, 1 row affected (0.00 sec)
> Rows matched: 1 Changed: 1 Warnings: 0
> 
> mysql>` select * from sample;`
> +———————+———————+——+
> | timeUpdated | timeCreated | val |
> +———————+———————+——+
> | 2007-10-24 15:25:23 | 2007-10-24 15:25:03 | 2 |
> +———————+———————+——+
> 1 row in set (0.00 sec)
> 
> The basic idea is that by forcing NULLs in to the TIMESTAMP columns, they’ll both be triggered to use the current timestamp value. But when you don’t reference them, only the first TIMESTAMP column will be updated, and if you define it as the ‘last updated’ column, you’re good to go.

So, in my understanding of this post, it means that we could change the migration script like this (with `modified` before `created`):

```
CREATE TABLE IF NOT EXISTS `ea_consents` (
                `id` INT(11) NOT NULL AUTO_INCREMENT,
                `modified` TIMESTAMP,
                `created` TIMESTAMP,
                `first_name` VARCHAR(256),
                `last_name` VARCHAR(256),
                `email` VARCHAR(512),
                `ip` VARCHAR(256),
                `type` VARCHAR(256),
                PRIMARY KEY (`id`)
                )
```
When inserting a row in the table,  both `created `and `modified ` shall be added in the SQL query as  NULL values. But updating the table does not require to update  `created `and `modified `: the  `modified ` field will be automatically updated by the database system.

Do you think you could consider such a workaround for EA!? It would be very helpful for people running EA! on distro based on RHEL/CentOS.

**Comment by oxteam** [comment]
Hi again Alex,

I tested the trick I found.
It works well with Mysql / Maridb for versions 5.5.x.

However, the trick seems to be not compatible with newer versions. I tested with a Mysql on the 5.6.x branch and it does not trigger auto update for the 'modified' and 'created' fields.

But I found a solution as follows:

1. The `modified` field is declared as a `TIMESTAMP` + auto-update whereas  and the `created ` field is only declared as a `TIMESTAMP`. **`modified`must be declared first otherwise the older DB engine version rejects the request** :

```
        $this->db->query('
            CREATE TABLE IF NOT EXISTS `ea_consents` (
                `id` INT(11) NOT NULL AUTO_INCREMENT,
                `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
                ON UPDATE CURRENT_TIMESTAMP,
                `created` TIMESTAMP,
                `first_name` VARCHAR(256),
                `last_name` VARCHAR(256),
                `email` VARCHAR(512),
                `ip` VARCHAR(256),
                `type` VARCHAR(256),
                PRIMARY KEY (`id`)
            )
                ENGINE = InnoDB
                DEFAULT CHARSET = utf8;
        ');
    }
```

2. In `Consents_model.php`, the `created` field  is set to the SQL `NOW()` function through Code Igniter's `db->set()` function. It is not possible to directly use `db->insert()` because this function escapes all the array values.

Setting the `created` by the DB engine rather than setting its value in the PHP code ensure timezone consistency for both `created`  and `modified`. If the PHP server were not on the same machine as the DB server, such an inconsistency could occur.


I tested this new proposal on both DB versions (5.5.x and 5.6.x):  
- Creation and migration scripts work fine;
- New lines in the `ea_consents` table have their `created` and `modified` fields set to the time they have been created.

I am about to provide a pull request for this.

Hope it helps.

**Comment by alextselegidis** [comment]
See pull request comment for further information.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
