### ISSUE TITLE
Change the defautl Gregorian calendar to Hebrew or Solar Hijri calendars.

### ISSUE THREAD

**Issue by arkhatami** [alextselegidis/easyappointments#536]
how can i change default Gregorian calendar to  Hebrew or Solar Hijri  calendar ?

**Comment by alextselegidis** [comment]
Hi @arkhatami, unfortunately I do not have that experience. 

Maybe this helps? 

https://stackoverflow.com/questions/19462916/how-to-make-gregorian-and-islamic-calendar-in-one-javascript

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
