### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by shade73** [alextselegidis/easyappointments#537]
Seems that Easy!Appointments uses mcrypt in several files, and that is removed in PHP 7.2.

Is a PHP 7.2 compatible update planned?

Kind Regards

**Comment by alextselegidis** [comment]
Hello @shade73, 

are you getting any errors, warnings, notices etc? 

I will check again for compatibility issues. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by shade73** [comment]
Hello Alex,

I am preparing to upgrade to PHP 7.2, the server still runs PHP 7.1 so I have tested all running code on the server with:

phpcs --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.2 .

The especially encrypting libraries uses the removed mcrypt function.

Thanks.
S

**Comment by alextselegidis** [comment]
@shade73 Checking the app with php 7.2 leaded to no errors or warnings. 

It seems that CodeIgniter is still using mcrypt in some places but Easy!Appointments does not make use of that code, therefore not problem so far. 

I'll make sure that in the future the app will remain compatible to newer php versions. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
