### ISSUE TITLE
Set time how long an appointment has to be booked in advance

### ISSUE THREAD

**Issue by sebastianha** [alextselegidis/easyappointments#538]
Hi,

I really like your application but I think I found one thing which is currently not covered:

I want to define how long before an appointment it has to be booked. E.g. the appointment has to be booked 3 days in advance, so the calendar should not show available slots within the next three days.

I found the setting where I can set the time in minutes the appointments can be booked but this seems to work only on the current day. When I set it to 4320 (3 days in minutes) the current day is blocked but on the next day free appointments are available.

Would it be possible to add this feature? This would be great as I am dealing sometimes with long term appointments.

Thank you very much, Sebastian

**Comment by manioca** [comment]
Hi Sebastian, I had same problem and solution it has been simple.
In /application/controllers/Appointments.php inside ajax_get_unavailable_dates, after closing "for ($i = 1; $i <= $number_of_days_in_month; $i++)" write:

$today = (new DateTime())->format('Y-m-d');
$book_waiting_days = 3; // 3 days
$j = 1;
$k = 0;
while($k < $book_waiting_days){
	$d = date('Y-m-d', strtotime($today. ' + '. $j .' days'));
	$j++;
	
	// check if date is already unavailable
	if (in_array($d, $unavailable_dates)){
		continue;
	}
	
	// skip date if is weekend
	if($this->isWeekend($d)){
		continue;
	}
	$unavailable_dates[] = $d;
	$k++;
}

**Comment by sebastianha** [comment]
Hi,

thanks for your hint, I will try this. This should be definitely something which is going upstream!

**Comment by manioca** [comment]
Tell me about if you wish.
Marina martedì, 04 settembre 2018, 00:48PM +02:00 da Sebastian Hammerl  notifications@github.com :

**Comment by manioca** [comment]
Sorry, I forget the to add the function isWeekend public function ajax_get_unavailable_dates()

protected function isWeekend($date) {
	$weekDay = date('w', strtotime($date));
	return ($weekDay == 0 || $weekDay == 6);
}

**Comment by sebastianha** [comment]
This here did the trick for me:

```             $today = (new DateTime())->format('Y-m-d');
             $book_waiting_days = 3;
             $k = 0;
             while($k < $book_waiting_days){
                 $d = date('Y-m-d', strtotime($today. ' + '. $k .' days'));
                 // check if date is already unavailable
                 if (in_array($d, $unavailable_dates)){
                     continue;
                 }
                 $unavailable_dates[] = $d;
                 $k++;
             }
```

**Comment by alextselegidis** [comment]
There's already another ticket that requests the same feature so I'm going to close this one in favor of the other. 

https://github.com/alextselegidis/easyappointments/issues/428

Thanks for posting the solution!!!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
