### ISSUE TITLE
Default auto-complete for the appointment end time according to service duration.

### ISSUE THREAD

**Issue by lucianpp** [alextselegidis/easyappointments#54]
Will be great if end time of an appointment in the backend will be populated by default according to the service duration. To be editable but completed by default!
How can I achieve this?
Thank you!

**Comment by alextselegidis** [comment]
This can only be done with JavaScript. I implement it in one of the following releases.

**Comment by alextselegidis** [comment]
Apparently the issue was fixed by another commit :)
