### ISSUE TITLE
Getting AJAX error during installation request.

### ISSUE THREAD

**Issue by dezs12** [alextselegidis/easyappointments#540]
I think I have followed the steps right and meet the requirements.

Debug is enabled, 

How can I fix this, I am excited to use this

![screenhunter 160](https://user-images.githubusercontent.com/38948826/44620000-7b9d1480-a842-11e8-951b-a9bd3e6e9fef.png)

**Comment by alextselegidis** [comment]
@dezs12 There must be an error logged either in the storage/logs/* directory or in the server error logs. 

Please provide us the message and the offending file and line for further troubleshooting. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by benchaneikaiwa** [comment]
I'm having the same issue. According to konradwalsh's advice above I tried http, but still got the error.

Unfortunately, there is no error log file generated. Here's what console has to say:

![2018-11-22 11 52 16](https://user-images.githubusercontent.com/45249617/48879226-2034ef80-ee4e-11e8-91fa-5a7a0fa09a46.png)
![2018-11-22 11 52 31](https://user-images.githubusercontent.com/45249617/48879228-20cd8600-ee4e-11e8-9a65-d1e71df778ef.png)

**Comment by alextselegidis** [comment]
@benchaneikaiwa Already got in touch, just FYI he needed to add the www subdomain to get it working. 

Different server environment require different configuration. Normally there is no issue while being on the same domain but there are these exceptions ... 

Bottom line, check with your hosting provider for further information :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
