### ISSUE TITLE
Select Service drop-down only shows one service and not all of them

### ISSUE THREAD

**Issue by subless** [alextselegidis/easyappointments#542]
I've added a number of different services for demo purposes for a client, but it only will show the first one. I've checked in the latest versions of Safari, Chrome, and Firefox and all are showing only one service.

I've checked the database and all the services I have added are there. I even used the **?service=N** URL variable and tried the different service ID's found in the database and it still doesn't work.

**Comment by Jenot** [comment]
Check if service is assigned to selected provider (users page).

**Comment by subless** [comment]
I was not aware of having to select them for the providers. It works now as expected. Thank you.
