### ISSUE TITLE
Reports app

### ISSUE THREAD

**Issue by omagoobscuro** [alextselegidis/easyappointments#547]
how to use reports in the application, you have no option of printing the reports or generating

**Comment by alextselegidis** [comment]
I think that currently the best way is to use an existing tool that will read the database and allow you to make reports. 

Check out those links, they might help: 

* [jdorn/php-reports](https://github.com/jdorn/php-reports)
* [koolreport](https://www.koolreport.com/)
* [Top 10 MySQL Reporting Tools](https://www.databasejournal.com/features/mysql/slideshows/top-10-mysql-reporting-tools.html)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
