### ISSUE TITLE
Error installing on localhost

### ISSUE THREAD

**Issue by superh1k** [alextselegidis/easyappointments#548]
It says that i should remove trailing slash from base url but i dont have any.

![2](https://user-images.githubusercontent.com/25400830/46203844-59a02180-c31b-11e8-9a2e-082489cac3a9.JPG)

![1](https://user-images.githubusercontent.com/25400830/46203853-602e9900-c31b-11e8-8196-57beaf2e8545.JPG)

**Comment by alextselegidis** [comment]
Please use `[::1]/info` as your BASE_URL value. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rhiuxito** [comment]
http://localhost/info for me
