### ISSUE TITLE
Querying appointments API endpoint with the q parmeter produces PHP warnings.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#549]
The warnings are there due to str-handling the aggregated arrays. 

Example Error: 

```
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
    <h4>A PHP Error was encountered</h4>

    <p>Severity: Warning</p>
    <p>Message: stripos() expects parameter 1 to be string, array given</p>
    <p>Filename: Processors/Search.php</p>
    <p>Line Number: 64</p>
</div>
```

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by averagejoe3000** [comment]
I was getting the same error when trying to search for providers as well.
I update the _recursiveArraySearch to:
`protected static function _recursiveArraySearch(array $haystack, $needle)
    {
        foreach ($haystack as $key => $value)
        {
            $currentKey = $key;

            if (is_array($value)) {
                if (self::_recursiveArraySearch($value, $needle) !== FALSE) {
                    return $currentKey;
                }
            } else if (stripos($value, $needle) !== FALSE) {
                return $currentKey;
            }

        }

        return FALSE;
    }`
This is working properly now when I search for values that are on the root of the haystack or in a nested array.
I'll create a PR as soon as I have time
