### ISSUE TITLE
List of Appointments for the Day 

### ISSUE THREAD

**Issue by bkrajendra** [alextselegidis/easyappointments#55]
Is it possible to have json API or query to get List of Appointments for the Day for particular Provider.
I want to create simple mobile app to display today's booked appointments on mobile for providers.

**Comment by alextselegidis** [comment]
The implementation of a RESTful API is scheduled for the v1.2 release. Till then you can use a nice library for CodeIgniter in order to create a simple API. Check the following page for more information.

https://github.com/chriskacerguis/codeigniter-restserver

**Comment by bkrajendra** [comment]
@alextselegidis Thanks for quick reply.
