### ISSUE TITLE
Add support for vacation time periods.

### ISSUE THREAD

**Issue by pacostiro** [alextselegidis/easyappointments#552]
I did not find a possibility to easily block appointments for a time interval when an worker is in vacation.
It would help to be able to set vacation intervals.

Thank you!

**Comment by alextselegidis** [comment]
Hi @pacostiro, marked as an upcoming feature.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by varanasib** [comment]
This is the one feature I need.  The converse would also be good: allow a provider to schedule for certain time periods.

**Comment by davidperezgar** [comment]
Hello, You could sell Addons in order to make this project sustainable in the time.

I see that this feature is from 2018. Any update of this?

**Comment by alextselegidis** [comment]
Hello! 

Since v1.4.0 unavailable period events will be able to block times that span in multiple days. 

I will therefore close this ticket in favor of that handling. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rimas-kudelis** [comment]
Hi @alextselegidis, may I suggest to add a note under the Working Plan Exceptions table, directing the user to the calendar to enter a vacation time?

I just almost spent half an hour entering Working Plan exceptions for a month worth of someone's vacation. before I stumbled upon this issue and was reminded that I should do that from within the calendar instead.

**Comment by alextselegidis** [comment]
Hello! 

Yes that is a good idea 👍 


<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
