### ISSUE TITLE
How to configure E-mail on Easy Appointments v1.3.2 with xampp

### ISSUE THREAD

**Issue by alciomarhollanda** [alextselegidis/easyappointments#553]
Hello,

How to configure e-mail on Easy Appointments v 1.3.2 ? 

Do you have any step-by-step to use with xampp?

**Comment by alextselegidis** [comment]
Hi @alciomarhollanda, that may differ between many environments and there is therefore no direct guide for Easy!Appointments. The easiest way to is to find a mail provider and add your SMTP credentials to application/config/email.php file. 

Check this page for additional information. 

https://www.codeigniter.com/user_guide/libraries/email.html#email-preferences

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alciomarhollanda** [comment]
Hello, I tried with this but it did not work.

show this error

EA\Engine\Types\Type: Invalid argument value provided (/agendamento/index.php/appointments/index/dfd0bb132a76b088b1df0e0103355ef2)


```
<?php defined('BASEPATH') OR exit('No direct script access allowed');

// Add custom values by settings them to the $config array.
// Example: $config['smtp_host'] = 'smtp.gmail.com'; 
// @link https://codeigniter.com/user_guide/libraries/email.html

//$config['useragent'] = 'alciomarh@gmail.com';
$config['protocol'] = 'smtp'; // or 'smtp'
$config['mailtype'] = 'html'; // or 'text'
$config['smtp_host'] = 'smtp.gmail.com';
$config['smtp_user'] = 'alciomarh@gmail.com'; 
$config['smtp_pass'] = '123456';
$config['smtp_crypto'] = 'ssl'; // or 'tls'
$config['smtp_port'] = 465;
```

**Comment by alciomarhollanda** [comment]
I read this is helped me to solve the problem https://github.com/alextselegidis/easyappointments/issues/544

when show this error

EA\Engine\Types\Type: Invalid argument value provided (/agendamento/index.php/appointments/index/dfd0bb132a76b088b1df0e0103355ef2)


I only change `const BASE_URL      = '/agendamento';` to `const BASE_URL      = 'http://alciomar.iasp.br/agendamento/';`

This happened because I was using the local xampp

**Comment by alextselegidis** [comment]
@alciomarhollanda Glad to know that you solved it :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
