### ISSUE TITLE
App not connecting to MySQL. Fresh Docker run (master/develop)

### ISSUE THREAD

**Issue by gaspo53** [alextselegidis/easyappointments#557]
Hi! The app can´t connect to the database, using Docker. Any guess? Doing a **docker exec -ti bash** into the mysql, I can login to mysql  using the configured credentials. 

Thanks

![image](https://user-images.githubusercontent.com/2250227/47272371-07899f00-d55b-11e8-9961-2aebad737483.png)

**Comment by Tamps** [comment]
Same problem, when trying to run docker-compose up

**Comment by RobinQuetin** [comment]
This is likely due to changes in MySQL 8.0.4. MySQL 8.0.4 switched from native password authentication to SHA2 cached passwords while EasyAppointments is still trying to authenticate using the native way. I fixed my container setup by editing the `docker-compose.yml` as follows:

```bash
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
...
```

Then I removed the existing database container and executed `docker-compose up` again. Hope this helps!

**Comment by gaspo53** [comment]
That works on mine too! Thanks a lot

**Comment by alextselegidis** [comment]
@RobinQuetin Thanks for the fix, I'll check this out and finally integrate in the project. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Quinncuatro** [comment]
He said and didn't do. :P

**Comment by alextselegidis** [comment]
@Quinncuatro Very sorry for this, please give me another chance :D 

I'll get back to you soon. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
After pulling the latest mysql image I was able to reproduce the problem. 

The merge request from @CalvinMcGee is merged, 

Thanks you all for the help :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
