### ISSUE TITLE
Refresh of the page inserts 2 appointments in calendar.

### ISSUE THREAD

**Issue by lucianpp** [alextselegidis/easyappointments#56]
If  we refresh the page on the last step of app wizard, two appointments are inserted with same details.

**Comment by alextselegidis** [comment]
That's true ... 

The reason is that a POST request is done through the booking wizard so if you actually press the refresh button the browser is going to ask for confirmation of this act. I might change this behaviour with an AJAX request but certainly not now. 

Thank you for noticing though :)

**Comment by alextselegidis** [comment]
@chrispichardo Thanks :+1:
