### ISSUE TITLE
Unavailability periods with length of more than 1 day are not handled correctly.

### ISSUE THREAD

**Issue by comunebl** [alextselegidis/easyappointments#562]
Setting a period of non availability with a length of more than one day, when inserting an appointment the start of the non availability period is correctly handled but I can insert data for the next day of the same period; however, when confirming the appointmente (and rightly so) I get an error. The application shouldn't permit you to insert data at all during that period.

**Comment by alextselegidis** [comment]
Hi @comunebl, you are right on this one currently setting an unavailability bigger than a day will not be parsed correctly. Marked as a bug and for v1.4 release. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I checked this in the develop branch and it is no longer an issue. 

The 1.4 release is coming soon, stay tuned!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by patfrat** [comment]
Hello ! What is the bugfix for this one ? Can i apply it to a v1.3.2 version that i am configuring !

**Comment by Tyler-RCSD** [comment]
Would also like to know how I can patch 1.3.2 to correct this.

**Comment by Tyler-RCSD** [comment]
For the time being I have made changes at line 1124 of application/controllers/Appointments.php:

```
        $unavailabilities = $this->appointments_model->get_batch([
            'is_unavailable' => TRUE,
            'DATE(start_datetime) <=' => $selected_date,
	    'DATE(end_datetime) >=' => $selected_date,
            'id_users_provider' => $provider['id']
        ]);
```

This appears to do the trick but it's not been rigorously tested yet.
