### ISSUE TITLE
Description field overflows with long text.

### ISSUE THREAD

**Issue by comunebl** [alextselegidis/easyappointments#563]
When inserting long service descriptions the text overflows (no scrolling is activated) outside of the description area. Furthermore it's not possible to insert URL links in the description.

![cnhhemcdcmmgjfmb](https://user-images.githubusercontent.com/44799053/48051153-9fff6080-e1a4-11e8-809c-15094d2fc59b.png)

**Comment by alextselegidis** [comment]
@comunebl Thanks for posting this as well, the text area has to be styled to that it get's scrollbars.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
