### ISSUE TITLE
Sort providers alphabetically in the booking page.

### ISSUE THREAD

**Issue by RafVandelaer** [alextselegidis/easyappointments#568]
When choosing a provider, is it possible to sort the list alphabetically?

**Comment by Elvin-Xhimitiku** [comment]
this helped a lot but I would suggest adding the reordering ability in the backend itself. it would make more sense to have it there as a drag and drop for your main services, for whom you dant want to make alphabetical sorting.

**Comment by KibGim** [comment]
The issue is closed, but about @Elvin-Xhimitiku's comment:



> I would suggest adding the reordering ability in the backend itself. it would make more sense to have it there as a drag and drop for your main services, for whom you dant want to make alphabetical sorting.

This is related to https://github.com/alextselegidis/easyappointments/issues/1161 "Feature Request: add sort/order function for services" ,
this is still a thing, and yes, it would be greatly useful for many.
