### ISSUE TITLE
CURRENT_TIMESTAMP default value is not supported under MySQL versions older than 5.6. 

### ISSUE THREAD

**Issue by vibratim** [alextselegidis/easyappointments#569]
After a fresh install of E!A on a fresh Ubuntu 16.04 LTS VM I am getting this error:

```
A Database Error Occurred
		Error Number: 1067Invalid default value for 'created'

CREATE TABLE IF NOT EXISTS `ea_consents` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified` DATETIME DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
    `first_name` VARCHAR(256),
    `last_name` VARCHAR(256),
    `email` VARCHAR(512),
    `ip` VARCHAR(256),
    `type` VARCHAR(256),
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8Filename: controllers/Installation.phpLine Number: 82	
```

thank you in advance :)

**Comment by alciomarhollanda** [comment]
Whats is version your MySQL?

It's work when i update my database.

**Comment by BigJohn2703** [comment]
> 
> 
> After a fresh install of E!A on a fresh Ubuntu 16.04 LTS VM I am getting this error:
> 
> ```
> A Database Error Occurred
> 		Error Number: 1067Invalid default value for 'created'
> 
> CREATE TABLE IF NOT EXISTS `ea_consents` (
>     `id` INT(11) NOT NULL AUTO_INCREMENT,
>     `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
>     `modified` DATETIME DEFAULT CURRENT_TIMESTAMP
>     ON UPDATE CURRENT_TIMESTAMP,
>     `first_name` VARCHAR(256),
>     `last_name` VARCHAR(256),
>     `email` VARCHAR(512),
>     `ip` VARCHAR(256),
>     `type` VARCHAR(256),
>     PRIMARY KEY (`id`)
> )
>     ENGINE = InnoDB
>     DEFAULT CHARSET = utf8Filename: controllers/Installation.phpLine Number: 82	
> ```
> 
> thank you in advance :)

I had the same problem, solved it by changing \assets\sql\structure.sql create table statement to 

CREATE TABLE IF NOT EXISTS `ea_consents` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `created` DATETIME NULL,
    `modified` DATETIME NULL,
    `first_name` VARCHAR(256),
    `last_name` VARCHAR(256),
    `email` VARCHAR(512),
    `ip` VARCHAR(256),
    `type` VARCHAR(256),
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8;

Then changing the consents update code in \application\models\Consents_model.php to

    public function add($consent)
    {
        $this->validate($consent);

        if ( ! isset($consent['id']))
        {
			$consent['created'] = date("Y-m-d H:i:s");
			$consent['modified'] = $consent['created'];
            $consent['id'] = $this->_insert($consent);
        }
        else
        {
			$consent['modified'] = date("Y-m-d H:i:s");
            $this->_update($consent);
        }

        return $consent['id'];
    }

This emulates the timestamps.

**Comment by alextselegidis** [comment]
Thanks for the input! This should be fixed with this PR

https://github.com/alextselegidis/easyappointments/pull/522

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by clarkdeleon84** [comment]
DUDE!!!!!  @BigJohn2703  
FREAKING SMART!!!!
@alextselegidis 

 I successfully installed this on virtualmin.
