### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by ramirocorletti** [alextselegidis/easyappointments#571]
Hi Alex, than you for your software! I am trying to install in for testing my local Windows PC.

I get the following error:

> Unable to connect to your database server using the provided settings.
> 
> Filename: C:/xampp/htdocs/easyappointments_1.3.2/system/database/DB_driver.php
> 
> Line Number: 436

In config.php credentials for local database are correct, as follows:

>     const DB_HOST       = '127.0.0.1';
>     const DB_NAME       = 'easyapp';
>     const DB_USERNAME   = 'easyapp';
>     const DB_PASSWORD   = 'mypass';

**Comment by alextselegidis** [comment]
Hi @ramirocorletti, this is a configuration error and you can finetune the way the app works with the database by adjusting the configuration file located at application/config/database.php. 

For example it can be that your environment does not support passive connections, or thta there is an error in the credentials you provided.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
