### ISSUE TITLE
Translation guide missing

### ISSUE THREAD

**Issue by mokkin** [alextselegidis/easyappointments#574]
I'd like to help to translate easyappointments, but unfortunately the link to the wiki in the readme seems to be broken or the wiki is not activated:
https://github.com/alextselegidis/easyappointments#translate-easyappointments

**Comment by mokkin** [comment]
already solved in #555

**Comment by alextselegidis** [comment]
Thanks, pull request merged. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
