### ISSUE TITLE
Add place for service

### ISSUE THREAD

**Issue by mokkin** [alextselegidis/easyappointments#575]
It should be possible for the user to select between several places.
In our usecase this would be "online", "phone" or "office.

**Comment by alextselegidis** [comment]
@mokkin A modification like this requires code changes. 

* create a new field in the appointments table 
* add your location dropdown/checkboxes in the booking form 
* send the selected values when saving the appointment (frontend_book.js)
* apply the field values when the user edits the appointment 

To keep things simple for you I would advise you to store locations as comma separated values or as a JSON string. 

Of course if you can also store your data in a normalized way and have a table storing locations and then  an appointments - locations pivot table for the connection of both data. 

Hope that helps :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
