### ISSUE TITLE
Appointment cancelled exception not showing properly

### ISSUE THREAD

**Issue by rjrodriguezalvarez97** [alextselegidis/easyappointments#576]
Hi, I think there's a bug showing the exceptions. If you try to delete an appointment that doesn't exists the application says Appointment Cancelled and no information about the exception is shown.

Reproduce:
www.myEAserver.com/index.php/appointments/cancel/thisshouldnwork

Expected:
Unexpected Issues - No record matches the provided hash.

Real output:
Appointment cancelled - Your appointment has been successfully cancelled!

Here's the error: 
[views/appointments/message.php](https://github.com/alextselegidis/easyappointments/blob/master/src/application/views/appointments/message.php#L44) it should be `isset($exceptions)` but applications cancelled is still being shown

**Comment by alextselegidis** [comment]
@rjrodriguezalvarez97 Feel free to make a pull request on this. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
FYI Fixed on develop

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
