### ISSUE TITLE
Possibility to change "Providers" to "Teachers"

### ISSUE THREAD

**Issue by jarednash0** [alextselegidis/easyappointments#578]
Hi EasyAppointments community!

I am interested (maybe) in helping out. My feature request is to be able to change the terms used on the website (e.g. "Providers" to something else such as "Teachers"). If the feature already exists cool! If not, I'd like to help out if it's an easy enough change (I don't know php).

I took a stab at changing config/constants.php to use Teachers instead of Providers, and Lessons instead of Services. Turns out it didn't work.  Here's the error message I got: 

 AJAX Error: SyntaxError: Unexpected token < in JSON at position 0
    A PHP Error was encountered

    Severity: Notice
    Message: Trying to get property of non-object
    Filename: models/Providers_model.php
    Line Number: 541

    A PHP Error was encountered

    Severity: Warning
    Message: Cannot modify header information - headers already sent by (output started at /var/www/html/system/core/Exceptions.php:271)
    Filename: core/Common.php
    Line Number: 570

Database Error

::selection{ background-color: #E13300; color: white; }
::moz-selection{ background-color: #E13300; color: white; }
::webkit-selection{ background-color: #E13300; color: white; }

body {
	background-color: #fff;
	margin: 40px;
	font: 13px/20px normal Helvetica, Arial, sans-serif;
	color: #4F5155;
}

a {
	color: #003399;
	background-color: transparent;
	font-weight: normal;
}

h1 {
	color: #444;
	background-color: transparent;
	border-bottom: 1px solid #D0D0D0;
	font-size: 19px;
	font-weight: normal;
	margin: 0 0 14px 0;
	padding: 14px 15px 10px 15px;
}

code {
	font-family: Consolas, Monaco, Courier New, Courier, monospace;
	font-size: 12px;
	background-color: #f9f9f9;
	border: 1px solid #D0D0D0;
	color: #002166;
	display: block;
	margin: 14px 0 14px 0;
	padding: 12px 10px 12px 10px;
}

#container {
	margin: 10px;
	border: 1px solid #D0D0D0;
	-webkit-box-shadow: 0 0 8px #D0D0D0;
}

p {
	margin: 12px 15px 12px 15px;
}

	
A Database Error Occurred
		Error Number: 1048Column "id_roles" cannot be nullINSERT INTO `ea_users` (`first_name`, `last_name`, `email`, `phone_number`, `id_roles`) VALUES ("John", "Doe", "john@doe.com", "0123456789", NULL)Filename: models/Providers_model.phpLine Number: 131	

I am using docker-compose to run this.
If this is an easy enough feature to implement and you could use some help let me know

Thanks!

**Comment by alextselegidis** [comment]
The easiest way to do something like this is to directly adjust the translation files, located at application/language directory. 

Of course you can also rename files and symbols referring to providers but you have to make sure you haven't forgotten any file as something like this will most likely result on an error. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
