### ISSUE TITLE
RSS-Feed for the blog

### ISSUE THREAD

**Issue by saschafoerster** [alextselegidis/easyappointments#579]
I would like to get the news in my feedreader. 
This could help: https://github.com/hexojs/hexo-generator-feed 👋

**Comment by alextselegidis** [comment]
Hi @saschafoerster, thanks for mentioning this. Actually I think some time ago I had this integrated but I'm not 100% that it works. 

Try to import this XML to your feed reader: 

http://easyappointments.org/blog/atom.xml 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
