### ISSUE TITLE
Smtp not working with docker image

### ISSUE THREAD

**Issue by vincentrou** [alextselegidis/easyappointments#580]
I set the config/email.php variables and the .env variables with smtp. But I do not get it works.

Where do I get the log of phpmailer in the docker container ?

**Comment by alextselegidis** [comment]
Try for example creating a https://mailtrap.io/ account and set the SMTP credentials in config/email.php

If this works then the credentials you are using now might not be valid. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by vincentrou** [comment]
Thanks for the hint. It works now.
I should have use TLS instead of SSL.
