### ISSUE TITLE
Add support for the definition of custom web hooks via the settings page.

### ISSUE THREAD

**Issue by M-erb** [alextselegidis/easyappointments#581]
Hi everyone! This looks like a great appointment scheduling app. I am excited to use it but I have a question. Is there a web hooks like api for this? Looking in the documentation it seems a web hooks api is missing. What I am looking for is an easy way to notify a CRM like software that an appointment was set and the information about it to then automatically do its own thing with the information. I would rather not constantly ping easy!appointments to find new appointments. It seems the API for easy!appointments is not designed for this, but please correct me if I am wrong. Thank you!

**Comment by compucat** [comment]
Seconding this request. Has this been considered for implementation soon?

**Comment by loscil06** [comment]
Seconding as well.

**Comment by alextselegidis** [comment]
Already pushed in develop

**Comment by mrkylegp** [comment]
Really would love webhooks as well!

**Comment by alextselegidis** [comment]
Yeah, that will be a great feature! 🤩 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by arladmin** [comment]
This issue seems to have been closed.

Have webhooks been implemented and pushed to the latest release?

**Comment by arladmin** [comment]
> Already pushed in develop

This issue seems to have been closed.

Have webhooks been implemented and pushed to the latest release?

**Comment by arladmin** [comment]
> Hello! Yes there are ready for release and should be there for 1.5 stable. 
> 
> <small>
> <table>
> <tr>
> <td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
> <td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
> </tr>
> </table>
> </small> 

That's great to know!

Is there also an ETA for the release of 1.5 stable?

**Comment by alextselegidis** [comment]
I have a couple of tickets left to work on, so that should be any time soon ;)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by mrkylegp** [comment]
> I have a couple of tickets left to work on, so that should be any time soon ;)
> 
> ![](https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	Alex Tselegidis, Easy!Appointments Creator
> [Need a customization? Get a free quote!](https://easyappointments.org/get-a-free-quote)

Are webhooks in 1.5 dev at the moment or only coming in stable? Very keen!

**Comment by alextselegidis** [comment]
> Are webhooks in 1.5 dev at the moment or only coming in stable? Very keen!

They will come on the first alpha release (1.5.0-alpha.1)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Tobias-Conrad** [comment]
@alextselegidis nice to have webhooks, but when included?

**Comment by mrkylegp** [comment]
> @alextselegidis nice to have webhooks, but when included?
> Need them to integrate into email marketing if included i can use your plugin.

Alex literally just advised when they are coming in the reply above.
