### ISSUE TITLE
services filter for secretaries

### ISSUE THREAD

**Issue by prossino83** [alextselegidis/easyappointments#585]
in /index.php/backend if I log in as an administrator I can filter both for providers and for services.

If I log in as a secretary, I can only filter for providers. How can I add the services filter also for secretaries?

thank you

**Comment by alextselegidis** [comment]
Hi @prossino83, remove the code section of
``` 
if (GlobalVariables.user.role_slug == Backend.DB_SLUG_SECRETARY) {
            $('#select-filter-item optgroup:eq(1)').remove();
        }
```
from backend_calendar_default_view.js
