### ISSUE TITLE
403 Forbidden. Unexpected Issues:

### ISSUE THREAD

**Issue by oluwabukolatina** [alextselegidis/easyappointments#586]
I keep getting this alert error anytime i open the index and other pages
`Unexpected Issues
The operation could not complete due to unexpected issues.

Details`

On opening the network tab, it says
```
An Error Was Encountered
The action you have requested is not allowed
```

When i open the console, it says ` 403 forbidden` 
Please help me!

**Comment by alextselegidis** [comment]
Hi @oluwabukolatina, this seems to be a server environment issue. 

Can you provide us with a link? (or just send me a pm at alextselegidis@gmail.com) 

Did you make any adjustments to the platform? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oluwabukolatina** [comment]
hi @alextselegidis ,
i get the error on my local. i did not start the project myself, so yes, some adjustments must have been made to it already.

**Comment by alextselegidis** [comment]
Hi @oluwabukolatina, 

please try with a clean installation (without adjustments) and see if you still get the error. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by GalaxyCatD3v** [comment]
https://cal.galaxylabs.ca/index.php
this is a clean install, via docker. I get the same issues.
