### ISSUE TITLE
EA: Unable to make ajax request. Please try again later.

### ISSUE THREAD

**Issue by natalie-demetriou** [alextselegidis/easyappointments#589]
Hi, 

I used Easy Appointments before and everything was fine. I don't know if this has something to do with the recent update or not but unfortunately i cannot downgrade in order to check. 
Basically when a client selects the "Location" field the following message appears - "Unable to make ajax request. Please try again later." and the calendar appears to be loading constantly.

Easy Appointments is used here: http://www.imperioproperties.com/rentals/ and here http://www.imperioproperties.com/pantheon-hill-residences-104-rentals/ 

and also in some cases when i edit the 'Customize' page this message appears "There has been some error."

Thank you, 
Natalie.

**Comment by alextselegidis** [comment]
Hi @natalie-demetriou, apparently you are using another plugin and no the original Easy!Appointments platform. 

Please contact the plugin maintainer for further clarifications. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
