### ISSUE TITLE
Feature Request : Appointments statuses

### ISSUE THREAD

**Issue by lucianpp** [alextselegidis/easyappointments#59]
Related to #58.
After the scheduled time passed, if the customer did not came, would be great to have appointmets statuses, so the admin can change the status of thos appointments : As Scheduled; Not Arrived etc..

**Comment by lucianpp** [comment]
Hi all,

I have added the gui part and new column in appointment table but it seams that I can not make it to insert in db or retrieve the existing values.
Please advise were i can start..
Thank you!!

**Comment by lucianpp** [comment]
Hi,
I have managed to add the statuses and control them but I would like to add a css class to the appointment box in callendar to be able to have different colors for each appointment status.
Please help!!

**Comment by alextselegidis** [comment]
Hi, open the assets/js/backend_customers.js and find the Customers.prototype.display function definition. This is where the customer's appointments are being inserted into the dom. You can modify this in order to also output a status-color class.

**Comment by lucianpp** [comment]
Hi, 
I managed to do this also  by adding in db a new column named 'COLOR' which value is inserted once the appointment is created or updated(When appointment is created with status pendding a color blue will be inserted in db, when we update the appointment to status 'Arrived', color green is inserted etc..) The color then is loaded in each calendar event and all appointments are dispalyed according to them status, but..
Let's say I update an appointment from Pendding to Arrived and press save then I click insert new Appointmnt, the status of my new appointment will be auto completed to Arrived, even if I create a new  appointment. This filled is keeped from the previouse action each time I create new appointment.
Please help!! How  I do this field to reset? In HTML the pendding status is selected but is not working :(

**Comment by lucianpp** [comment]
all solved ;) thank you!!

**Comment by alextselegidis** [comment]
:+1:

**Comment by koboy55** [comment]
> Hi,
> I managed to do this also by adding in db a new column named 'COLOR' which value is inserted once the appointment is created or updated(When appointment is created with status pendding a color blue will be inserted in db, when we update the appointment to status 'Arrived', color green is inserted etc..) The color then is loaded in each calendar event and all appointments are dispalyed according to them status, but..
> Let's say I update an appointment from Pendding to Arrived and press save then I click insert new Appointmnt, the status of my new appointment will be auto completed to Arrived, even if I create a new appointment. This filled is keeped from the previouse action each time I create new appointment.
> Please help!! How I do this field to reset? In HTML the pendding status is selected but is not working :(


can you help me with the color?
