### ISSUE TITLE
Dot in Database Name results in Error

### ISSUE THREAD

**Issue by chrisspiegl** [alextselegidis/easyappointments#590]
I just tried to install the Easy!Appointments on my server and noticed that it resulted in an error when I use it with my database which I also use for my WordPress installation.

The error shown is that the name of the database is not supported. It is clear that this is because there is a `.` (dot) in the database name (e.g. `mydomain.com`).

This is a database name that works in many other cases and is not against standards. It might be a good idea to escape the database name in the code to also be compatible with these types of database names (and potentially prevent injections).

I understand that this is not necessarily a major problem but it was a hickup in my experience in an otherwise very promising application.

Thank you,
Chris

**Comment by alextselegidis** [comment]
Hi @chrisspiegl, this should actually work with Easy!Appointments as well. 

Can you please post the error message you are getting? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by chrisspiegl** [comment]
After setting up I noticed that EasyAppointments is not the right system for me to run. It does not offer everything I want. If you'd like we can close this issue, however, I do believe that the problem still exists but I don't have the time to troubleshoot it now and since I will not be using the software.

Thank you again for the help and the fact that you do develop this software, @alextselegidis .

**Comment by alextselegidis** [comment]
@chrisspiegl You are welcome, wish you all the best for your project :) 

I'll close the issue for now as I did not have any other user experiencing the same. 

If this comes up again we will take a closer look to the environment specifics. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
