### ISSUE TITLE
Unable to INSERT appointment

### ISSUE THREAD

**Issue by DomCostantino** [alextselegidis/easyappointments#595]
I'm trying to insert an appointment following API docs with a 
POST method and the following JSON object
```
{
    "book_datetime": "2019-07-08 12:57:00", 
    "start_datetime": "2019-07-08 18:00:00",
    "end_datetime": "2019-07-08 18:30:00", 
    "hash": null, 
    "notes": "These are some test notes.",
    "id_users_customer": 2,
    "id_users_provider": 2,
    "id_services": 2,
    "id_google_calendar": null
}
```
Request results in a 500 error, every APIs works fine with POST ( insert ).
Let me know if you need more information.

**Comment by alextselegidis** [comment]
Hi @DomCostantino, please send me detailed error message and stack trace if available. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
