### ISSUE TITLE
404 not found with rewrite conditions

### ISSUE THREAD

**Issue by essasix23** [alextselegidis/easyappointments#596]
Hi. 
I am using the following rewrite conditions in my htaccess file to hide file endings for example www.mysite/pricing.html -> www.mysite/pricing/ 

RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^([^.]+)$ $1.html [NC,L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^([^\.]+)$ $1.php [NC,L]

however after implementing these, my www.mysite/books/ no longer loads and returns a 404 not found page. Any ideas why this is happening?

**Comment by alextselegidis** [comment]
Hi @essasix23, 

please follow this guide for configuring Easy!Appointments with your Apache Server correctly: 

https://www.codeigniter.com/userguide3/general/urls.html

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
