### ISSUE TITLE
Json don't load this input in customers form. 

### ISSUE THREAD

**Issue by bartollo** [alextselegidis/easyappointments#597]
Hello,

I changed the customers page, added two others fields . This form insert and update in database , but don't display value in form fields. The event "Filter Entry" Click ""  in file "backend_customers_helper.js"  returns json with these two fields.

What i do for display these fields values in form input ?

Thanks!

**Comment by alextselegidis** [comment]
Hi @bartollo, 

backend_customers_helper.js has a method display, you will have to populate your two new fields with the data returned from your json file. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
