### ISSUE TITLE
Non-production docker compose doesn't work

### ISSUE THREAD

**Issue by eran101** [alextselegidis/easyappointments#598]
Ran git clone, then:
$ docker-compose up
Recreating easyappointments_database_1 ... done
Recreating easyappointments_application_1 ... done
Attaching to easyappointments_database_1, easyappointments_application_1
database_1     | 2019-02-16T22:07:59.630967Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
database_1     | 2019-02-16T22:07:59.631080Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 1
application_1  | Preparing Easy!Appointments development configuration..
database_1     | mbind: Operation not permitted
database_1     | mbind: Operation not permitted
database_1     | mbind: Operation not permitted
database_1     | mbind: Operation not permitted
database_1     | 2019-02-16T22:07:59.940011Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
database_1     | 2019-02-16T22:07:59.941926Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
database_1     | 2019-02-16T22:07:59.949499Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.infoschema@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.949595Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.949662Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.949697Z 0 [Warning] [MY-010315] [Server] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.949869Z 0 [Warning] [MY-010323] [Server] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.950056Z 0 [Warning] [MY-010323] [Server] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.950168Z 0 [Warning] [MY-010311] [Server] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.953534Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.953612Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1     | 2019-02-16T22:07:59.957884Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.11'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
application_1  | Starting Easy!Appointments production server..
application_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
application_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
application_1  | [Sat Feb 16 22:08:01.396788 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.0.33 configured -- resuming normal operations
application_1  | [Sat Feb 16 22:08:01.396861 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

Screenshot:
https://imgur.com/a/o6NCHcu

**Comment by alextselegidis** [comment]
Hello @eran101 

The Docker configuration got updated in the develop branch, try that one and let us know if you experience any problem. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
