### ISSUE TITLE
SMTP without encryption and authentication

### ISSUE THREAD

**Issue by BiGOUDx** [alextselegidis/easyappointments#599]
Hi,
I have a SMTP server on my network configured to allow emails without auth and encryption.

I had to configure this way to succeed to send an email : 

application/config/email.php
```
$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = 'smtp'; // or 'smtp'
$config['mailtype'] = 'html'; // or 'text'
$config['smtp_host'] = 'ip address';
$config['smtp_port'] = 25;
```

engine/Notifications/Email.php (lines 334)
```
            $mailer->isSMTP();
            $mailer->Host = $this->config['smtp_host'];
            $mailer->SMTPAuth = false;
            //$mailer->Username = $this->config['smtp_user'];
            //$mailer->Password = $this->config['smtp_pass'];
            //$mailer->SMTPSecure = $this->config['smtp_crypto'];
            $mailer->SMTPSecure = false;
            $mailer->SMTPAutoTLS = false;
            $mailer->Port = $this->config['smtp_port'];
```

I guess you can code that properly by using variables in the config file.

Hope it can help someone, I spent a couple of hours to find it.

**Comment by alextselegidis** [comment]
Hi @BiGOUDx 

thanks for posting this, hopefully it will help many other users that are have the same needs :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
