### ISSUE TITLE
Business Logic created is not getting assigned to Serviceprovider

### ISSUE THREAD

**Issue by bkrajendra** [alextselegidis/easyappointments#6]
Ive created Business Logic through admin login.
Not understanding how to assign it to service provider. It shows assigned logic name
but when we click on Providers working plan, it displays default working plan.

**Comment by alextselegidis** [comment]
If you change the general working plan you will have to go to backend/users page and edit the provider user. Click on the "Working Plan" tab and preset the reset. He's working plan will be changed to the "new" general working plan.

**Comment by bkrajendra** [comment]
Thanks for the reply.
i've resolved this issue.
But the most irritating problem i'm facing now is // in url. I've tries remove and adding this / at the end of base URL, Also altered my .htaccess file.
my url looks like this in ajax request:
http://localhost/appointments/easyappointments-master/src//appointments/ajax_get_available_hours

Also assets r loading with // in them.
Can u help me to resolve this,

**Comment by bikemike** [comment]
The code Alex recently committed[1] is causing the issue with the base url. Either you can revert the most recent changes he made to book.php, book_success.php, cancel.php, and message.php or wait for him to check in a fix.


[1] https://github.com/alextselegidis/easyappointments/commit/45753adbd089b29ba9af83c8498403f2f5a36cd6

**Comment by alextselegidis** [comment]
Fixed
