### ISSUE TITLE
Unable to select Language on mobile phone

### ISSUE THREAD

**Issue by Ferguson230** [alextselegidis/easyappointments#600]
Hi, selecting a language works great on the computer, but does not work on the phone for some reason. When I click on the English, it displays all the other languages but for some reason, it doesn't select any language when it is clicked on.

**Comment by alextselegidis** [comment]
Hi @Ferguson230, 

which device are you using for testing? 

I just checked on an Android/Chrome setup and could click the languages without problems. 

I do though have another issues that that is that if the booking page is short, I'm not able to navigate through the entire list of languages as it's being cut (after approximately 15 entries). 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Ferguson230** [comment]
Hello @alextselegidis, I tested it on iPhone 6 on different browsers including chrome and the result was same.

**Comment by yrammos** [comment]
@Ferguson230 see #550 for a *potential* temporary fix.

**Comment by alextselegidis** [comment]
I could finally reproduce the problem. 

Marking this for v1.4

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
This is now testing and fixed on develop. 

Will be released with v1.4.0 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
