### ISSUE TITLE
Installation error with 1.3.2

### ISSUE THREAD

**Issue by loganaden** [alextselegidis/easyappointments#601]
Here is the error when I enable debug mode:

A PHP Error was encountered
Severity: Compile Error

Message: Can't use method return value in write context

Filename: controllers/Appointments.php

Line Number: 355

**Comment by lokowebdesign** [comment]
I also have this error. Can anyone help? It seems that there isn't an installation page as noted in the documentation.

**Comment by clarkn** [comment]
Hi, I think you should check the version of PHP that you are using and make sure it is at least 5.6+

**Comment by alextselegidis** [comment]
Like @clarkn mentions, you have to upgrade to at least php 5.6. 

Please keep your PHP versions up to date as by not doing so you are becoming vulnerable to known security issues. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
