### ISSUE TITLE
"Unexpected Issues" on startup v1.3.2

### ISSUE THREAD

**Issue by fman29** [alextselegidis/easyappointments#602]
The index page gives me this popup message when I click "Install Easy!Appointments":

<img width="427" alt="screenshot 2019-03-07 at 10 49 33" src="https://user-images.githubusercontent.com/15417237/53943925-e323fe80-40c6-11e9-8cbe-22a5b9921ec2.png">

The console shows:
Access to XMLHttpRequest at 'https://clientwebsite.com/easyappointments/index.php/installation/ajax_install' from origin 'https://www.clientwebsite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Can you help me?

**Comment by altagir** [comment]
You defined your website in config as https://www.clientwebsite

But you entered https://clienwebsite

I am unsure how to write rule to rewritte it. But that s the reason

**Comment by fman29** [comment]
Awesome! That fixed it!! Thank you for taking the time to respond so quickly!
