### ISSUE TITLE
Backend problem - asking for user and password

### ISSUE THREAD

**Issue by csilvino** [alextselegidis/easyappointments#603]
Hello! I am having problems in the backend, after installation, where its permanently request user and password, being sure that I am entering the correct data. I'm using PHP 7.2.15.

**Comment by alextselegidis** [comment]
Please make sure you re-install the software and that your storage directory is writable. 

At first sight, this seems to be a problem with sessions, like as if your server would not store them. 

You can also try the docker configuration for a pre-configured server environment. 

I'll close the ticket but feel free to post again back here if you have new findings :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
