### ISSUE TITLE
Impossible to install on nginx

### ISSUE THREAD

**Issue by shakisha** [alextselegidis/easyappointments#606]
I have tried everything, read all the issues here but impossible, still 404 error even making redirections, following recipes....

**Comment by shakisha** [comment]
UPDATE: I managed to run at least installation, this is my nginx config:

server {
        listen 80;
        server_name ea.mydomain.com;
        root /var/www/ea;
        index index.php;
        if (!-e $request_filename){
                rewrite ^(.*)$ /index.php?/$1 last;
          }


	location ~ \.php$ {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_read_timeout 300; 
          fastcgi_connect_timeout 100; 
          fastcgi_send_timeout 300; 

          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $request_filename;
      }
  }


---------------------

This is what i'm getting after clicking on green button "install easyappointments": 

<img width="1047" alt="Captura de pantalla 2019-03-27 a las 0 53 07" src="https://user-images.githubusercontent.com/7482626/55040874-b199b580-502a-11e9-8ff3-5978f340b176.png">


In the console there is only this error: 

POST http://ea.mydomain.com/index.php/installation/ajax_install 504 (Gateway Time-out)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
(anonymous) @ installation.js:42
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3

**Comment by shakisha** [comment]
http://ea.mydomain.com/index.php/installation/ajax_install  is giving 504, gateway timeout :-(

**Comment by charrismatic** [comment]
I was able to get it working with no issues with nginx. Are you sure that the problem is not with the application config?  I had some trouble with cross-site origins and requests dying when I first set it up.

What do you server logs say?


```sh
# /etc/nginx/sites-enabled/appointments.conf

# HTTP -> HTTPS 
server {
    listen 80;
    server_name appointments.mydomain.com;
    return 301 https://$host$request_uri;
}

# EASY APPOINTMENTS SERVICE 
server {
    listen 443;
    server_name appointments.mydomain.com;

    root /opt/appointments/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/appointments.mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/appointments.mydomain.com/privkey.pem;

    location / {
	try_files $uri $uri/ index.php =404;
    }

    location ~ \.php$ {
	 include snippets/fastcgi-php.conf;
         fastcgi_pass unix:/run/php/php7.2-fpm.sock;
    }

    location ~ /\.ht {
         deny all;
    }

    if (!-e $request_filename){                
	rewrite ^(.*)$ /index.php?/$1 last;        
    }
}
```

**Comment by alextselegidis** [comment]
@shakisha This config is working 

https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

(tested that myself)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
