### ISSUE TITLE
A Database Error Occurred: 1.3.2 Installation Nginx

### ISSUE THREAD

**Issue by OrionNet** [alextselegidis/easyappointments#607]
Hello,
I am trying to install on easyappointments on nginx but getting the following error. I tried the following suggestion 

$db['default']['pconnect'] = FALSE;

**config.php**
 const BASE_URL      = 'http://easyappointments/';

Unable to connect to your database server using the provided settings.
Filename: controllers/Appointments.php
Line Number: 29.

Any suggestions/ideas?

NR

**Comment by bon8519** [comment]
I have the same issue.  Did you find any solution yet?

**Comment by alextselegidis** [comment]
Hi @OrionNet, 

I don't think that the db connection issue has to do with the nginx configuration. 

It seems that the MySQL service is not running under the connection info you've entered and therefore you'll have to change them. 

If you feel there's a custom configuration needed for the connection I would recommend that you try to connect with a simple php script and figure out what's exactly missing from the Easy!Appointments configuration. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
