### ISSUE TITLE
New Tab on settings

### ISSUE THREAD

**Issue by richosr** [alextselegidis/easyappointments#608]
I am trying to add a new settings tab. Everything works fine if I put my new fields on an existing tab, but if I try to add to a new tab it says it is saving settings ok but does not save them. As I said if I add these settings to an existing tab they save perfectly. What am I missing?

**Comment by alextselegidis** [comment]
Check the `backend_settings` javascript file and the `backend_settings_system`, they both have logic for storing such values. 

E.g. 

```
<div class="form-group">
                                <label for="company-link"><?= lang('company_link') ?> *</label>
                                <input id="company-link" data-field="company_link" class="required form-control">
                                <span class="help-block">
                                    <?= lang('company_link_hint') ?>
                                </span>
                            </div>
``` 

Also for your markup notice the `data-field` attribute. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
