### ISSUE TITLE
Accessing on LAN

### ISSUE THREAD

**Issue by YawZha** [alextselegidis/easyappointments#609]
Hi I just finished setting up Easy!Appointments on my PC and I wanted to access it using a different PC that is connected by LAN, but this is what it looks like when opened from a different PC.
![image_2019_03_29T10_37_35_233Z](https://user-images.githubusercontent.com/49063364/55227310-197e1500-5252-11e9-9a1c-3597e62562df.png)

What can I do to fix it?

**Comment by alextselegidis** [comment]
@YawZha your base url setting in the root `config.php` file is invalid and therefore the css files cannot be loaded. 

Make sure you've set the correct value based on the installation documentation of Easy!Appointments. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
