### ISSUE TITLE
Token based authentication for the Rest API.

### ISSUE THREAD

**Issue by hoabuiduy** [alextselegidis/easyappointments#610]
Hi,
Now i see your api does not support to authentication ( token )

It would be great if you guys add Customer Login and Authentication to source

Thanks,

**Comment by alextselegidis** [comment]
@hoabuiduy 

> Now i see your api does not support to authentication ( token )

Will be there fore 1.4

> Customer Login

That'll come a bit later but fill free to come up with a pull request. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by muneebtariq1991** [comment]
Hi, How can I check user login in API?

**Comment by alextselegidis** [comment]
@muneebtariq1991 Can you elaborate a little bit more? I'm not sure I understand the question :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
