### ISSUE TITLE
Double replacement when using translation to other languages

### ISSUE THREAD

**Issue by diegales1** [alextselegidis/easyappointments#611]
When doing the joint 'translation and email content' replacements in lines 168 and 273 (for precision, calls to $this->_replaceTemplateVariables) of /engine/Notifications/Email.php, the replacement array ($replaceArray) defines the translations from the language translation file (lang) before defining the email content translations. 

This leads to iterative translations. 

Example:

'$appointment_service' => $service['name'], ( == "EndFoo")
followed by
'End' => $this->framework->lang->line('end'), (line('end') = "FinalBar")

Resulting in the appointment service being displayed as FinalBarFoo instead of EndFoo (given the second replacement of the word "End"). 

For now I've avoided the use of regex's and simply have inverted the definition of the replacement arrays. As an example the first array is left as follows (starting in line 135) : 

```
        $replaceArray = [
            // Translations
            'Appointment Details' => $this->framework->lang->line('appointment_details_title'),
            'Service' => $this->framework->lang->line('service'),
            'Provider' => $this->framework->lang->line('provider'),
            'Start' => $this->framework->lang->line('start'),
            'End' => $this->framework->lang->line('end'),
            'Customer Details' => $this->framework->lang->line('customer_details_title'),
            'Name' => $this->framework->lang->line('name'),
            'Email' => $this->framework->lang->line('email'),
            'Phone' => $this->framework->lang->line('phone'),
            'Address' => $this->framework->lang->line('address'),
            'Appointment Link' => $this->framework->lang->line('appointment_link_title'),

            //Email texts
            '$email_title' => $title->get(),
            '$email_message' => $message->get(),
            '$appointment_service' => $service['name'],
            '$appointment_provider' => $provider['first_name'] . ' ' . $provider['last_name'],
            '$appointment_start_date' => date($date_format . ' ' . $timeFormat, strtotime($appointment['start_datetime'])),
            '$appointment_end_date' => date($date_format . ' ' . $timeFormat, strtotime($appointment['end_datetime'])),
            '$appointment_link' => $appointmentLink->get(),
            '$company_link' => $company['company_link'],
            '$company_name' => $company['company_name'],
            '$customer_name' => $customer['first_name'] . ' ' . $customer['last_name'],
            '$customer_email' => $customer['email'],
            '$customer_phone' => $customer['phone_number'],
            '$customer_address' => $customer['address']

        ];
```

Hope this helps a bit. 

*(p.s. Also, I've completed the missing lines for the Spanish translation if anyone is interested.)

**Comment by alextselegidis** [comment]
@diegales1 thanks for posting, I will fix this for v1.4

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
