### ISSUE TITLE
Remove index.php from URL

### ISSUE THREAD

**Issue by MartinH0** [alextselegidis/easyappointments#613]
Hi guys, is it possible to remove the `index.php` from every URL in easyappointments?

Thanks in advance!

**Comment by charrismatic** [comment]
Theres guidance for how you can do this in the comments of the main config file.

Reference this line: 
https://github.com/alextselegidis/easyappointments/blob/c68fe9fb0cd9d7653a32edb6bcb5b6d8926585aa/src/application/config/config.php#L41

```php
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';
```

Just set this value to an empty string and the urls will resolve without `/index.php/` being needed. You can still get to end up on pages that still have the `/index.php/` in the path but you can take that out with a small `.htacess` rule.

**Comment by GiorgosK** [comment]
@charrismatic the workaround you mentioned does not work and leads to  `/installation/index'  with WSOD with message `NOT found`

.htaccess file seems it is needed

```ssh
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.php$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.php [L]
</IfModule> 
```

**Comment by alextselegidis** [comment]
Hello!

Indeed an .htaccess file with rewrite rules is needed. 

For NGINX you will need a proper configuration object. 

The app has index.php in the url by default, as this is the config that will work in almost all servers without additional configuration. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
