### ISSUE TITLE
Providers are only locations, not people

### ISSUE THREAD

**Issue by ognik777** [alextselegidis/easyappointments#615]
Hi - v1.3.2.   I want to be able to select a location, instead of a person.

Customers will choose from a number of locations and each location will have it's own working plan.  (All locations offer the same services)

What the best way to load the data?  I'm putting the city in 1st name, a short description in last name.
I'm hoping there is a better idea, or maybe a mod that is better?

Thanks

**Comment by alextselegidis** [comment]
@ognik777 Check in the develop branch, I've added a location field lately. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
