### ISSUE TITLE
Service name could not be Russian

### ISSUE THREAD

**Issue by daniilsavchuk** [alextselegidis/easyappointments#616]
Hi colleagues, 

Thank you very much for such an awesome software!

Although I could be wrong it seems my issue does not exist here.

So I successfully installed the **easyappoinments** via docker and started to fill up the content when notice that **service name, price, category, and description** could not be Russian (I assume any layout instead of EN). 

I found the workaround, if I put the Russian text to URL encode (for instance here: https://www.urlencoder.org/) it works and even properly shows the Russian content however I think it is really easy to fix this and perform URL encode for the fields before sending the request on the frontend side, what do you think? 

The error occurs when trying Russian service name is like I forgot to fill this field

Thank you in advance!

**Comment by alextselegidis** [comment]
@daniilsavchuk I'm not sure if I got you right, can you post a screenshot? 

I checked the russian translation and it seems to be working for me. 

![Capture](https://user-images.githubusercontent.com/4527441/59963207-16609100-94f0-11e9-81ed-2df8a8843909.PNG)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by HADDADENICAR** [comment]
same issue , where can we change the  service name ?

**Comment by alextselegidis** [comment]
Hello! 

The problem with this ticket is that your database collation is wrong. 

Create a database that has the `utf8_unicode_ci` or `utf8mb4_unicode_ci` collation and you won't have such problems. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
