### ISSUE TITLE
Category not showing

### ISSUE THREAD

**Issue by ognik777** [alextselegidis/easyappointments#617]
Hi - I have 3 categories setup in the backend, but the third one ('General', with 1 service) doesn't show in the 'select service' dropdown.  How can I fix this please?

Snip from backend below.

Please see https://ea.clinicalthermography.co.nz/book/index.php and let me know what other info I should provide?

![image](https://user-images.githubusercontent.com/43224653/57262689-65c63b80-70c1-11e9-860e-25bc1dcfb18e.png)

**Comment by aptonline** [comment]
I’m seeing a similar issue. Multiple categories and services but only some services showing in front end even though assigned to categories.

**Comment by ognik777** [comment]
I made the same mistake somehow, I was sure I had added the services, but when I checked they weren't there.  So issue closed now, thanks
