### ISSUE TITLE
Confirming Appointment Error: undefined index post_data

### ISSUE THREAD

**Issue by zcopland** [alextselegidis/easyappointments#619]
Receiving this error when trying to confirm an appointment on the customer side:

> AJAX Error: SyntaxError: Unexpected token < in JSON at position 0
>     A PHP Error was encountered
> 
>     Severity: Notice
>     Message: Undefined index: post_data
>     Filename: controllers/Appointments.php
>     Line Number: 715
> 
> {"exceptions":["{\"code\":0,\"file\":\"\\\/var\\\/www\\\/html\\\/appt\\\/application\\\/models\\\/Services_model.php\",\"line\":281,\"message\":\"Invalid argument provided as $service_id: \",\"previous\":null,\"trace\":\"#0 \\\/var\\\/www\\\/html\\\/appt\\\/application\\\/controllers\\\/Appointments.php(717): Services_Model->get_value('duration', NULL)\\n#1 \\\/var\\\/www\\\/html\\\/appt\\\/application\\\/controllers\\\/Appointments.php(469): Appointments->_check_datetime_availability()\\n#2 \\\/var\\\/www\\\/html\\\/appt\\\/system\\\/core\\\/CodeIgniter.php(532): Appointments->

The error log contains:

> ERROR - 2019-05-15 12:24:26 --> Severity: Warning --> count(): Parameter must be an array or an object that implements Countable /var/www/html/appt/vendor/gregwar/captcha/CaptchaBuilder.php 333
> ERROR - 2019-05-15 13:38:13 --> Severity: Notice --> Undefined index: post_data /var/www/html/appt/application/controllers/Appointments.php 715

My E!A can be accessed at zachcopland.com/appt

**Comment by alextselegidis** [comment]
Hello @zcopland 

I tried to make an appointment and got to see the error myself. 

The problem now is that from the request you can see that we clearly send the post_data variable 

![Capture](https://user-images.githubusercontent.com/4527441/58746657-d19d8900-8460-11e9-88b0-685b2e3d32cb.PNG)

Are you able to log in into the backend? 

Any other problems using the app? 

Can you try the docker environment and see if you can reproduce the problem there? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by zcopland** [comment]
@alextselegidis I am able to log into the backend. Also, even though there are multiple services an admin and user only sees one for some reason.

**Comment by alextselegidis** [comment]
@zcopland Have you made any changes in the code that might have broken the functionality? 

I'm going to need more information in order to understand what might be wrong with your installation :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by zcopland** [comment]
@alextselegidis I did a clean install and everything seems to be working normal again. Thank you!
