### ISSUE TITLE
Create a "Display all appointments" option in the backend/calendar page.

### ISSUE THREAD

**Issue by alextselegidis** [alextselegidis/easyappointments#62]
It would be useful for admins to check all the calendar entries into one display (#58).

**Comment by jqtank** [comment]
Another vote for this display option! Did a mock up on photoshop. Will it be something like this or similar?

![easyapptview](https://cloud.githubusercontent.com/assets/10160433/23826607/1e236ece-0665-11e7-83a5-dd31f4592880.jpg)
