### ISSUE TITLE
Entering same mail address overwrites previous user

### ISSUE THREAD

**Issue by didros** [alextselegidis/easyappointments#621]
I was testing using the same mail address for test convenience. I found out that when creating a new appointment, if I use the same mail address as an existing user (customer) in the database, the new user's information are overwritten with the new user information.
They should a message telling that this mail address already exists. But what to do then? Deny, in that case the same client cannot book many times. Accept? This might be a security issue as clients are not authenticated.

**Comment by alextselegidis** [comment]
Hello @didros 

the idea behind this solution is to use the email as a unique customer identifier within the app, since customers do not have login credentials. 

You can quickly deactive this in code by editing the customers_model class.  The `exists` method must always return `false`

```
public function exists($customer)
{
        return false; // Add this command

        if ( ! isset($customer['email']))
        {
    
```

easy@

**Comment by didros** [comment]
I see. Thanks for the feedback Alex.

**Comment by angad305** [comment]
This works perfectly. What i was trying to achieve here was limiting customer booking to one per day. I still was not able to achieve that. Any help would be appreciated!
