### ISSUE TITLE
Feature request: Book multiple services at once.

### ISSUE THREAD

**Issue by EggermontRob** [alextselegidis/easyappointments#622]
I think the title speaks for itself. It would be very nice if my customers could select multiple services at once when making an appointment.

**Comment by alextselegidis** [comment]
Hello @EggermontRob 

This is a duplicate of an older ticket 

https://github.com/alextselegidis/easyappointments/issues/72

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
