### ISSUE TITLE
Slow frontend calendar generation

### ISSUE THREAD

**Issue by ICS35** [alextselegidis/easyappointments#627]
Version 1.3.2

The frontend calendar take 4-5 sec before disable unavailable days.

I found that the SQL requests generated by ajax_get_unavailable_dates function don't have the selected_date input in the where conditions :

> SELECT * FROM `ea_appointments` WHERE `id_users_provider` = '85'

So for each day of the month, the request retrieve all appointments (6000 row).

The ajax_get_unavailable_dates function call _get_provider_available_time_periods function with a date ( application/controllers/Appointments.php ) :

```
$empty_periods = $this->_get_provider_available_time_periods($curr_provider_id,
	$service_id,
	$current_date->format('Y-m-d'), $exclude_appointments);
```
	
In _get_provider_available_time_periods function, the date is not provided to appointment_model object :
```
$provider_appointments = $this->appointments_model->get_batch([
        'id_users_provider' => $provider_id,
    ]);
```

I tested by adding the date in the array passed to the function :
`'DATE(start_datetime)' => $selected_date,`

The SQL requests are now crafted with the date :

> SELECT * FROM `ea_appointments` WHERE DATE(start_datetime) = '2019-07-01' AND `id_users_provider` = '85'
> SELECT * FROM `ea_appointments` WHERE DATE(start_datetime) = '2019-07-02' AND `id_users_provider` = '85'
> ...
> SELECT * FROM `ea_appointments` WHERE DATE(start_datetime) = '2019-07-31' AND 
`id_users_provider` = '85'

The calendar generation take 0.2 sec.

Is this code modification can have bad effects on other application functionnality ?

Thank you for your help.

**Comment by alextselegidis** [comment]
I see how the current code gets slower if many appointments are there and it definitely has to be improved. Your suggestion is almost correct, basically we need to include events that share some time with the selected date, i.e. if an event starts a day before and ends some time in the selected date it should also be taken into concern. 

I am planning to rewrite the availability generation flow soon, so I will be closing the ticket and come back when the time is right. 

For your use case you can use queries you posted if all your events belong to the same day. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
