### ISSUE TITLE
booking_minimum_24_hours_before_event

### ISSUE THREAD

**Issue by Raigan21** [alextselegidis/easyappointments#628]
Hi.
First, thanks for this great app.
I know that this feature is set up at 3 h before the event but how can I customize it?

**Comment by alextselegidis** [comment]
Hey @Raigan21, use the book advance timeout setting for this in the backend section. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Raigan21** [comment]
I Tried with that option for the beginning but the time out is still 4 hours not matter of I increased or make it lower
