### ISSUE TITLE
Define work days for certain categories

### ISSUE THREAD

**Issue by Nikoxx99** [alextselegidis/easyappointments#630]
Im have a certain category that only works on thursday, how can i define this death period?

**Comment by alextselegidis** [comment]
Right now you should just apply this to all services that belong to this category directly. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
