### ISSUE TITLE
Questions about plugin...

### ISSUE THREAD

**Issue by dglite** [alextselegidis/easyappointments#632]
Hi: I would like to get your plugin but have the following questions…
– can I add all the payment methods of Woocommerce? (in my case mercadopago)?
– can it work for the reservation of tennis court = select date + hour, etc.;
Pls let me know so I can buy it, thks…

**Comment by alextselegidis** [comment]
@dglite We do not sell any plugin as of now. You can download the wordpress plugin from the marketplace https://wordpress.org/plugins/easyappointments

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
