### ISSUE TITLE
Change default 30 mins backend calendar slot

### ISSUE THREAD

**Issue by naguera** [alextselegidis/easyappointments#633]
Similar to this "Flexible time slots in backend calendar view. #201" but for the current release, I really need to view slots of 10 minutes instead 30 in the calendar backend... Is it possibile?

**Comment by alextselegidis** [comment]
Hey @naguera 

head to the Appointments.php controller and change the interval to 30 on the ajax_get_available_hours method. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
