### ISSUE TITLE
Multiple Employee calender

### ISSUE THREAD

**Issue by nscpro** [alextselegidis/easyappointments#634]
Hi. I really need multiple employee calender looking.

I add picture what i mean. Maybe this coming soon?

![Screenshot 2019-07-10 at 19 45 42](https://user-images.githubusercontent.com/16063685/60988077-950c5980-a34b-11e9-84df-82506d57e699.png)

**Comment by alextselegidis** [comment]
I think a "global" calendar view where admins can see the events of all providers will do the same and still keep the ui consistent.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
