### ISSUE TITLE
Full day appointments

### ISSUE THREAD

**Issue by richosr** [alextselegidis/easyappointments#635]
cannot get appointments for services greater than 300 minutes in duration. Have set providers to have no breaks and working schedule 8:30 - 18:30 and Business logic the same. But any service longer than 300 minutes will not appear available.

**Comment by alextselegidis** [comment]
Hi @richosr, this is already marked as a future enhancement, thanks for posting. 

https://github.com/alextselegidis/easyappointments/issues/428

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
