### ISSUE TITLE
Unable to connect to your database server using the provided settings

### ISSUE THREAD

**Issue by Oxigen-a** [alextselegidis/easyappointments#636]
I have the same error as posted in #392 on 29 Dec 2017 [here](https://github.com/alextselegidis/easyappointments/issues/392) . 

- Testing mysql/php access with a test-script (to verify credentials) shows no issues. 
- I tried, with no success, to set $db['default']['pconnect'] = FALSE under application/config/database.php

Any other suggestions?

Error displayed on the web-page 
-----------------
A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: controllers/Appointments.php
Line Number: 29
-----------------------------------------------------------------

my OS is ubuntu server 18.4
mysql Ver 14.14 Distrib 5.7.26
PHP 7.2.19-0ubuntu0.18.04.1
Apache/2.4.29 (Ubuntu), 2019-06-28T16:49:35

below my config.php

class Config {

// ------------------------------------------------------------------------
// GENERAL SETTINGS
// ------------------------------------------------------------------------

const BASE_URL      = 'http://ea.test.com/ea';
const LANGUAGE      = 'english';
const DEBUG_MODE    = FALSE;

// ------------------------------------------------------------------------
// DATABASE SETTINGS
// ------------------------------------------------------------------------

const DB_HOST       = 'localhost';
const DB_NAME       = 'ea';
const DB_USERNAME   = 'root';
const DB_PASSWORD   = 'toor';

// ------------------------------------------------------------------------
--------- the rest is default.

**Comment by alextselegidis** [comment]
@Oxigen-a It seems that the default database configuration will not work for your mysql server. Follow the instructions of this page to change connection settings.

https://www.codeigniter.com/user_guide/database/configuration.html

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by michael-keyes** [comment]
How is this "closed" when it's never properly addressed?
