### ISSUE TITLE
how can i use Persian calendar instead of Georgian one?

### ISSUE THREAD

**Issue by sxshateri** [alextselegidis/easyappointments#637]
hey guys.
first of all thanks for this wonderful code.
I would like to know how can I utilize the Persian calendar instead of the Georgian one?

there is [this](https://momentjs.com/docs/#/use-it/browser/) script which I used before on my web designs but can't figure out how to implement it with easyappointments.
the scrip gives us the ability to use multiple types of calendars aside from Georgian one. might be a good idea to use on feature updates.
for example to use persian calendar we can use this API and `moment().locale('fa').format('YYYY/M/D');` to get the current date in Persian calendar type.

**Comment by alextselegidis** [comment]
Hi @sxshateri you can still change the format to YYYY-MM-DD from the backend settings page.
