### ISSUE TITLE
File not found after installation

### ISSUE THREAD

**Issue by WhiteTiger-IT** [alextselegidis/easyappointments#638]
I installed EA with Softaculous in a VPS with Plesk Onyx.
The installation did not report any errors, but then the "File not found" error appears with the URL ... /easyapmt/index.php/backend

VPS: 6 core 12GB RAM
OS: Ubuntu 18.04 LTS
Plesk Onyx + Softaculous
Apache with Nginx as Reverse Proxy
PHP 7.2.20 FPM with Nginx as service

**Comment by alextselegidis** [comment]
Your nginx configuration is unfortunately not valid, use this guide to fix it: 

https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
