### ISSUE TITLE
Email notifications are not working. Pls help!

### ISSUE THREAD

**Issue by oladimejiajayi** [alextselegidis/easyappointments#643]
Email notifications for all users aren't working at all.

Kindly help! I have configured the email.php file that exists in /application/config/email.php but it still does not send any email. 

Please help with a solution. Thanks.

**Comment by alextselegidis** [comment]
Hello @oladimejiajayi 

this seems to be a configuration issue, as the app does not have any custom logic you will first have to make sure that php can send and email (or use SMTP). 

If you go for the `mail` function I would suggest that you create a simple file on your server with this code: 

```
<?php
$to      = 'nobody@example.com';
$subject = 'the subject';
$message = 'hello';
$headers = 'From: webmaster@example.com' . "\r\n" .
    'Reply-To: webmaster@example.com' . "\r\n" .
    'X-Mailer: PHP/' . phpversion();

mail($to, $subject, $message, $headers);
```

and change the placeholder values to your emails and execute it either from the terminal of from the browser while you try to configure your server for the mail function. 

Hope that helps :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
