### ISSUE TITLE
Too many open pull requests

### ISSUE THREAD

**Issue by samtuke** [alextselegidis/easyappointments#644]
Short feedback here on the number of open pull requests: having so many is discouraging to potential contributors as it gives the impression that contributions may not ever be reviewed. It's unclear what affiliation the open PRs have (primary project contributors or others), but reducing the number of old open PRs, eg especially ones from last year, help give the impression that the project has a healthy review process and workflow. Sorry if I've misinterpreted the situation.

**Comment by alextselegidis** [comment]
Hello @samtuke 

you are totally right, the last month (or two) I was going through the older merge requests and try to get the code inside. 

It's sadly true that after so much time you cannot get the most out of a merge request but they won't be abandonded. 

So I am setting a new goal to merge them all within the next month.

Thanks for posting :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by samtuke** [comment]
That's awesome - thanks and good luck @alextselegidis!
