### ISSUE TITLE
Select provider first and then service which is offered by selected provider

### ISSUE THREAD

**Issue by Elvin-Xhimitiku** [alextselegidis/easyappointments#645]
Hello and great work with this amazing platform.

My question and use case is this: i need the person to first select the provider (City 1 or City 2 etc) and then display the services that only the selected provider offers. 

Its the reverse on how it is now. That depending on the service, it filters the providers.

p.s. i am using v. 1.3.2

thanks

**Comment by alextselegidis** [comment]
Hi @Elvin-Xhimitiku 

you must edit the `frontend-book.js` file and reverse the logic of the select options population.

Currently the provider options are changed once the user selects a new service (see on change event callback), so you just revert the logic there and populate the services when the user selects a provider. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
