### ISSUE TITLE
Delete personal information

### ISSUE THREAD

**Issue by ICS35** [alextselegidis/easyappointments#648]
Hello,

Somes of our users use the delete personal information function without understand that it delete all of their appointment.
It could be helpfull to add an aditionnal information message for point it out.

I have add a line in translations_lang.php : 
`$lang['delete_personal_information_hint_2'] = 'Be careful, this will also remove all your appointments : the old ones, this one and those to come.';`
(Not sure of the meaning in English, this sentence is translated from French)

In application/views/appointments/book.php line 74 i add : 
`<p style="color:red;font-weight:bold"><?= lang('delete_personal_information_hint_2') ?></p>`

**Comment by alextselegidis** [comment]
Hi @ICS35 

thanks for pointing this out, I will update the message.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
