### ISSUE TITLE
Multiple providers with the same email address don't show in the provider list

### ISSUE THREAD

**Issue by Samimelki** [alextselegidis/easyappointments#649]
Hello,

I have been trying to setup easy appointments to use with a clinic but I need to setup multple providers with the same email address. In a previous post I read about removing the check in providers-model.php. When I do that I can register a new provider with the same email however it now will show the latest user in the provider column and not the old ones too. When I check the ea-users database, all the providers are there. What am I missing?

Thanks

Sami

**Comment by alextselegidis** [comment]
Hi @Samimelki 

there must be a group clause that blocks all providers from being shown under the same email. 

Check the Backend_api.php controller as well, in the `ajax_filter_providers` method you will see how the provider records get filtered and returned as a response. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
