### ISSUE TITLE
BaseUrl error in config.php and installation button greyed out

### ISSUE THREAD

**Issue by m45t3rc0d3r** [alextselegidis/easyappointments#650]
Hi,
i am new in php... so i really need help. 

I am using WAMP. For EA project directory, i named the folder 'ehelpdesk' and the database as 'ehelpdesk'

after unzipping all the EA files into Wamp directory and setting up the database for EA to work, i encountered problems at the installation page. It says "Please remove any trailing slashes from your BASE_URL setting of the root config.php file and try again."

I initially changed the BASE_URL to 'localhost' but it wont work because the URL in the browser will show a Not Found error page with the browser URL automatically revert to: 'http://localhost/ehelpdesk/localhost/index.php/installation/index'. 

It seems whatever BASE_URL entry that i write will be put **after** the word 'ehelpdesk' in "http://localhost/ehelpdesk" 

So, I edited the config.php file and simply put it blank: 
const BASE_URL      = '';

Apparently that is the only way to initiate the installation page. However, as I've mentioned above, the trailing slash error will appear and the install button is greyed out. 

I am trying to installing EA in a local running server (intranet). The server configuration may have caused this to happen.. i can only think of **httpd.conf** or **httpd-vhosts.conf.** as the culprit. Because any changes of attributes I do will only be in these two files. Some of those attributes:

httpd.conf
----------------------------------------------------
ServerName pbroombooking.upnm.edu.my

DocumentRoot "C:/wamp64/www"
<Directory "C:/wamp64/www/">

----------------------
 httpd-vhosts.conf
-----------------------------------------------------
<VirtualHost *:80>
    DocumentRoot "C:/wamp64/www"
    ServerName  localhost
    ServerAlias localhost
    <Directory  "C:/wamp64/www">
        AllowOverride All

#this is my current project running in the server
<VirtualHost *:80>
	ServerName pbroombooking
	DocumentRoot "c:/wamp64/www/classroombookings"
	<Directory  "c:/wamp64/www/classroombookings/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require all granted
		Require local
	</Directory>
</VirtualHost>

#this is the EA configuration
<VirtualHost *:80>
	ServerName ehelpdesk
	DocumentRoot "c:/wamp64/www/ehelpdesk"
	<Directory  "c:/wamp64/www/ehelpdesk/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

p/s
Additional information

In my WAMP page, I have two projects listed; 1)classroombookings and 2)ehelpdesk.  Hovering on the first project show directory 'localhost/classroombookings/', while the EA project will show 'localhost/ehelpdesk/'. Clicking the classroombookings will direct me to the intended page which is 'http://pbroombooking.U***.edu.my/classroombookings/index.php/login. 

Clicking on ehelpdesk will direct me to http://localhost/ehelpdesk/localhost/index.php/installation/index

hope this info helps

**Comment by traalala** [comment]
i got the same ERRORR. and this worked.
do not keep base url empty instead write the base URL in this format :

eg. http://localhost/ehelp
const BASE_URL      = 'http://localhost/ehelp';

**Comment by m45t3rc0d3r** [comment]
> i got the same ERRORR. and this worked.
> do not keep base url empty instead write the base URL in this format :
> 
> eg. http://localhost/ehelp
> const BASE_URL = 'http://localhost/ehelp';

Thanks alot
