### ISSUE TITLE
hooks

### ISSUE THREAD

**Issue by joshp23** [alextselegidis/easyappointments#651]
I apologize if this has been addressed, but I am wondering about existing hooks in your code for the purpose of easy extensibility, such as plugin writing? Adding filter and action hooks would make extending a lot easier for users if it isn't in there already.

**Comment by alextselegidis** [comment]
Hello @joshp23, 

a plugin system is planned for release v1.5.0, though this is very draft, it should allow plugins to change the core behavior of the app in any way. 

For this to happen though I shall first do some refactoring which will take some time. 

Stay tuned :) 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
