### ISSUE TITLE
address already in use when running docker compose

### ISSUE THREAD

**Issue by RenFinkle** [alextselegidis/easyappointments#653]
When I run: docker-compose up
I get the following:
```
Removing easyappointments_application_1
Starting easyappointments_database_1 ... done
Recreating f1a8604df92d_easyappointments_application_1 ... error

ERROR: for f1a8604df92d_easyappointments_application_1  Cannot start service application: b'driver failed programming external connectivity on endpoint easyappointments_application_1 (e74ff05f35f82f5ad935d82de9eba1f5049e61dba32165fee936e0c956a41ebd): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'

ERROR: for application  Cannot start service application: b'driver failed programming external connectivity on endpoint easyappointments_application_1 (e74ff05f35f82f5ad935d82de9eba1f5049e61dba32165fee936e0c956a41ebd): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'
ERROR: Encountered errors while bringing up the project.
```
Here's my redacted .env:
```
DB_USERNAME=
DB_NAME=

# before deploying to production change to harder password, and don't commit it to git
DB_PASSWORD=

# change to your installation address
APP_URL=localhost
APP_HOST=0.0.0.0
APP_PORT=8391

# email settings - set to 'smtp' and provide SMTP settings if you want to send emails
EMAIL_PROTOCOL=mail
SMTP_HOST=smtp.gmail.com
SMTP_USER=user
SMTP_PASS=password
SMTP_CRYPTO=ssl
SMTP_PORT=25
```
Should I be editing something other than the .env to set the port?

**Comment by alextselegidis** [comment]
Hello @RenFinkle 

I didn't have the time to check on this yet, but I would like to ask if anyone else had a similar issue. 

In general I would like to update the docker config of the project, so there'll be updates on this soon. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
This ticket got forgotten but in the meanwhile there is updated docker configuration in the develop branch. 

Use that instead. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by nouhouari** [comment]
Hi, the port already in use is the port 80.
You can change this port in the docker-compose file like this:
ports:
    - ${APP_HOST}:**8380**:80
 environment:
      - APP_URL=localhost:**8380**
Alternatively, you can stop the process that is using the port 80 on your host.
