### ISSUE TITLE
Creating an appointment requires user to enter their phone number

### ISSUE THREAD

**Issue by sandbergja** [alextselegidis/easyappointments#655]
The phone number field is required on the form that customers fill out to book an appointment.  However, some workplaces might not want the phone number field to be required, for reasons such as:

1. The workplace might not offer phone service, and wants to simplify the user experience.
2. The workplace might want to be more accessible or welcoming to Deaf people (see [this article about required phone number fields](https://audio-accessibility.com/news/2012/12/accessible-forms-for-deaf-people/) and [this presentation on accessible experiences for Deaf users](https://www.youtube.com/watch?v=AEXKOASrTVM&list=PLn7dsvRdQEfFd5n_h8gltIoTfzUE_zywu))

One solution might be simply removing the required attribute from the phone number input, both in the customer and staff forms.  Another solution might be to give an administrator the ability to make this field required or optional, depending on the needs of the workplace.

Thanks!

**Comment by alextselegidis** [comment]
@sandbergja Thanks for posting! I like this *Another solution might be to give an administrator the ability to make this field required or optional, depending on the needs of the workplace.* 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by sandbergja** [comment]
Thanks, @alextselegidis.  I will work on a pull request that implements that enhancement as something that an administrator could configure.

**Comment by alextselegidis** [comment]
Merged on develop, thanks!
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
