### ISSUE TITLE
Automatically detect browser language

### ISSUE THREAD

**Issue by yrammos** [alextselegidis/easyappointments#659]
It would make strong business sense to automatically render the UI in the browser's primary language. Thank you.

**Comment by yrammos** [comment]
Done, see PR #662

**Comment by alextselegidis** [comment]
Merged on develop, thanks!
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
