### ISSUE TITLE
Trouble with breaks for providers

### ISSUE THREAD

**Issue by martinhalfer** [alextselegidis/easyappointments#66]
If the breaks for each provider are not entered in the correct order, the booking page will show too many available booking sessions.

**Comment by bikemike** [comment]
https://github.com/bikemike/easyappointments/commit/38691a40547d145078697752f4eb27d43a016360

https://github.com/bikemike/easyappointments/commit/b95e2d28282031beb6a80842853565660b19d1f1

https://github.com/bikemike/easyappointments/commit/72e425c734ed9ce06beb6e7babefee251fed4096

**Comment by alextselegidis** [comment]
Will be fixed for 1.1
