### ISSUE TITLE
Language selector not working under legacy iOS (v. 10.3.1).

### ISSUE THREAD

**Issue by yrammos** [alextselegidis/easyappointments#663]
The list of languages does pop up but the individual languages are not clickable.

You may reproduce this on a Mac by downloading, for instance, an iPad Air simulator running iOS 10.3.1.

**Comment by yrammos** [comment]
Update: Will try to get around replacing jQuery with newer versions of the library and report back. I have a hunch this could be a jQuery issue.

**Comment by yrammos** [comment]
Fixed, see PR #666.

**Comment by alextselegidis** [comment]
Merged on develop, thanks!
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
