### ISSUE TITLE
How to edit the  frontend  of easyappointments ?

### ISSUE THREAD

**Issue by HADDADENICAR** [alextselegidis/easyappointments#667]
I want to customize easyappointments with some css styles and images (changing the login for example) , i checked the view folder  i didn't find where to edit , i thought that it can be index.html  but it  dosen't seem : 

      <html>
       <head>
	     <title>403 Forbidden</title>
       </head>
      <body>

            <p>Directory access is forbidden.</p>

        </body>
      </html>

so i how can i change the style ?

**Comment by dmorgan20** [comment]
To change the style you need to find the folder called CSS, from memory the I think the file is called front-end.php
