### ISSUE TITLE
Adding new item to the menu

### ISSUE THREAD

**Issue by dmorgan20** [alextselegidis/easyappointments#669]
How do you add a new item to the menu in the backend?

I've amended the header and added a new constant called PRIV_content. But it won't show because of permissions I think.

Not sure what I need to change

**Comment by alextselegidis** [comment]
@dmorgan20 Adding a new link in the header.php and checking directly against the database should do the trick as well. 

For logged in users you could also check for the user role with 

$this->session->role_slug

This will give you values like administrator, secretary, provider 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
