### ISSUE TITLE
How to change time format to european ?

### ISSUE THREAD

**Issue by HADDADENICAR** [alextselegidis/easyappointments#670]
Where in your code  i can change the display of the time format to european ?

**Comment by alextselegidis** [comment]
Hello @HADDADENICAR 

the latest Easy!Appointments version has a new setting in the backend settings page for this. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
