### ISSUE TITLE
My project isn't working, it trows this AJAX without any error message, can anyone help me?

### ISSUE THREAD

**Issue by delubiod** [alextselegidis/easyappointments#675]
My project is on http://www.delvero.com.br
then you click AGENDA.
![Screen Shot 2019-11-18 at 08 48 06](https://user-images.githubusercontent.com/37295365/69050240-56189f80-09e0-11ea-80f0-b8f0670e9fbb.png)
Any idea where to look for a solution to this problem?
I am new to PHP.
Any help I will appreciate.

**Comment by alextselegidis** [comment]
Hello! 

Please check the check at the storage/logs/* for additional debug information. 

There's a PHP error happening during the request. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I just made a test booking on your installation and everything worked correctly. I will therefore close this ticket ;)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
