### ISSUE TITLE
Custom confirmation page

### ISSUE THREAD

**Issue by Mack1980** [alextselegidis/easyappointments#676]
Hi Alex
![book php](https://user-images.githubusercontent.com/58037286/69343687-5af28300-0c6e-11ea-84bc-e60d62a937dc.png)

I have already hidden the fields I didn't need (address, zip code, city) from the third page (customer data, wizard-frame-3). 
I wanted to ask you:
how can I delete the fields: address, zip code and city on the confirmation page (wizard-frame-4).
I would like to leave only: customer name, email and phone.
I think I have identified the file to modify (see image), but I don't understand how to modify it.
Can you help me please?

**Comment by HADDADENICAR** [comment]
same issue here  ,i didn't find how to change that last page, i deleted the calendar and replaced it with FullCalendar now the custom confirmation page looks empty.

i searched and i found that the  ids : **appointments-details** and  **customer-details** are available in **frontend_book.js**:

        var html =
            '<h4>' + $('#select-service option:selected').text() + '</h4>' +
            '<p>'
            + '<strong class="text-primary">'
            + $('#select-provider option:selected').text() + '<br>'
            + selectedDate + ' ' + $('.selected-hour').text()
            + servicePrice + ' ' + serviceCurrency
            + '</strong>' +
            '</p>';

          $('#appointment-details').html(html);



            html =
                '<h4>' + firstName + ' ' + lastName + '</h4>' +
                '<p>' +
                EALang.phone + ': ' + phoneNumber +
                '<br/>' +
                EALang.email + ': ' + email +
                '<br/>' +
                EALang.address + ': ' + address +
               '<br/>' +
                EALang.city + ': ' + city +
               '<br/>' +
               EALang.zip_code + ': ' + zipCode +
               '</p>';

          $('#customer-details').html(html);

but even tought i delete that code , nothing is changed !?

**Comment by Mack1980** [comment]
Hi HADDADENICAR
Actually I had already tried, commenting on the code (see image 1), but the fields still appear. (see image 2)
Am I wrong?
Do you have any idea?
Thanks
![image 1](https://user-images.githubusercontent.com/58037286/69354625-b299ea00-0c80-11ea-9c0f-80bbb837df77.png)
![image 2](https://user-images.githubusercontent.com/58037286/69354626-b3328080-0c80-11ea-8600-fc1672af3806.png)

**Comment by HADDADENICAR** [comment]
I really don't know , we should wait for an admin to answer us

**Comment by Mack1980** [comment]
ok, thanks anyway for the help.
I'm losing my hair to solve the problem ... help! :-)

**Comment by Mack1980** [comment]
Resolved!
Cursed cache! ... I deleted the browser cache and now everything works ... I hear your laughter, have pity :-)

**Comment by HADDADENICAR** [comment]
Cool for you , i solved my problem too by just elimnating this condition :

    if ($('.selected-hour').text() === '') {
            return;
        }

from  exports.updateConfirmFrame

**Comment by alextselegidis** [comment]
Glad you got it solved, closing the ticket... .

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
