### ISSUE TITLE
Business Booking hours showing wrong.

### ISSUE THREAD

**Issue by hackswitch** [alextselegidis/easyappointments#678]
My hours for Employees are set to 8:00 - 19:00       8a-7p cst
Location set to match employee, 
Onthe frontend, when I go to book an apt, it only gives me options (Blocks on bottom left)  starting at 3:00 in the afternoon.  

Not sure what to adjust to allow booking blocks to show-AM; 8:00 9:00 10:00 11:00 12:00 1:00 2:00 
I'm sure this is something simple..
Thanks for the help all
switchbox33.com

**Comment by alextselegidis** [comment]
Hello @hackswitch, 

please make sure that all of your providers share the same working plan as the global one you've set in the settings page. 

The app will use the provider specific overrides for this and not the global one. 

The global one is being used as a default for all providers. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
