### ISSUE TITLE
Allow admins or secretaries to be providers as well (i.e. multiple roles)

### ISSUE THREAD

**Issue by daniele-athome** [alextselegidis/easyappointments#679]
In small organizations it may happen that an admin is also a provider. It also may happen that a super-provider (in E!A would be a secretary role) also manages the work of the providers below him/her - but he/she is also a provider.

What I mean here is a user could have multiple roles (so a user instance is created once and can be changed privileges easily). I know this can be done by creating multiple users, but it's really annoying to logout/login everytime. I can't find any issue here mentioning this. If you (project admins) think that there might be space for something like this, I'm willing to help in the medium term.

EDIT: the problem here is mainly for non-admin users, since admin can see pretty much whatever they want. For provider-admins, I could create a fake provider user that can be used to assign services. But super-providers are a different thing. Maybe I'm talking about a whole new role here, not really a secretary...

Thanks for this great software!

**Comment by alextselegidis** [comment]
Hello @daniele-athome, 

thanks for posting and for your suggestion. 

I can understand the logic behind your request but the role system Easy!Appointments has right now would not support this scenario that easily. 

With that being said I can see the role system being updated in the future but that's not a priority right now. 

I will therefore close the ticket for now, we may revise this at some point in the future. 

Thanks again for your support! 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
