### ISSUE TITLE
Generate new password in the generate_random_string function may create duplicate passwords, plus it is not secure enough.

### ISSUE THREAD

**Issue by mortezasaki** [alextselegidis/easyappointments#680]
In the "generate_random_string()" function, that is in the "general_helper.php" file, rand function does not good for generate random password and maybe create duplicate password. 
**It's better to use random_int(),random_bytes(), or openssl_random_pseudo_bytes() instead.**

https://www.php.net/manual/en/function.rand.php

**Comment by alextselegidis** [comment]
Hello @mortezasaki, 

that's true, I wanted to replace this method some time now, thanks for the reminder.

Set up for v1.4

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
