### ISSUE TITLE
CalDav integration

### ISSUE THREAD

**Issue by staykov** [alextselegidis/easyappointments#682]
Hey everyone,
I was curious is it possible to integrate Easy! with a CalDav calendar like OwnCloud? Thanks.

**Comment by alextselegidis** [comment]
Hello, 

this is already a requested feature, I will close this one. 

https://github.com/alextselegidis/easyappointments/issues/209

Thanks for posting!

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
