### ISSUE TITLE
Easy! website embed

### ISSUE THREAD

**Issue by staykov** [alextselegidis/easyappointments#683]
Hey everyone,
I was curious if it's possible to embed Easy! on your website so visitors don't have to leave the website to book an appointment?

Thanks

**Comment by alextselegidis** [comment]
Hello, 

yes that is possible with the use of an iFrame. 

If you are using WordPress, you can skip the manual integration and use the official WordPress plugin instead. 

Easy!Appointments comes with iframe-resizer integration out of the box which means that by activating the iframe-resizer in the host page you get the right iframe height automatically. 

In addition you can use the dedicated provider/service links to pre-select the service/provider depending on the page the iframe is being displayed. 

Hope that helps. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
