### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by mjhd** [alextselegidis/easyappointments#686]
This project is absolutely amazing - it would however be cool if it could be used in a completely portable fashion, say embedded in an HTML wiki, on a thumb-drive...

SQLite to the rescue?
If you're interested I would be glad to help!

Just a thought of mine - thx for all the hard work :D

**Comment by alextselegidis** [comment]
Hello @mjhd, 

I can see how practical that would be and CodeIgniter already supports SQLite databases so the migration shouldn't be that hard. 

However on the long term I find it very difficult to be able to support both databases with the same quality of features equally and I will therefore not start working on it. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
