### ISSUE TITLE
Errors when the provider modify an appointment

### ISSUE THREAD

**Issue by wolfygit** [alextselegidis/easyappointments#687]
Hi!
1 error: When the provider try to modify the appointment from the link's mail the provider field not autofill and not appear in the list, you have to change the service and return to the first one to get the provider.

2 error: When the appointment is modified by the provider his mail subject is $lang['appointment_details_changed'] and the client subject $lang['appointment_changes_saved'], it should be the opposite.

Sorry for my English!

**Comment by alextselegidis** [comment]
Hello @wolfygit, 

thanks for your post. I confirm number 1 is an issue but I cannot see how number 2 is a problem. 

Can you please elaborate? 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by wolfygit** [comment]
> Hello @wolfygit,
> 
> thanks for your post. I confirm number 1 is an issue but I cannot see how number 2 is a problem.
> 
> Can you please elaborate?
> ![](https://camo.githubusercontent.com/c099d8c84ee6739ccb2f789fc6c9310965553f53/687474703a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67) 	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Contact me in person!](http://alextselegidis.com)

If the provider modifies and appointment the text of $lang['appointment_changes_saved'] should be received by himself who is the person that made the change and not by the customer. By default this text is always send to the customer.

**Comment by alextselegidis** [comment]
Committed in develop
<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
