### ISSUE TITLE
Select multiple time slots in frontend

### ISSUE THREAD

**Issue by idandylux** [alextselegidis/easyappointments#690]
Hi,
It would be a great amelioration if you could select multiple time slots. It makes live much easier to select multiple slots instead of reserving each slots separately.
.

**Comment by alextselegidis** [comment]
Hello @idandylux, 

thanks for posting! This could make a good feature but to very certain cases as most of the events refer to a single time slot. 

I will therefore have to turn this down for now at least. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
