### ISSUE TITLE
Display Provider Info on Step Four

### ISSUE THREAD

**Issue by DrMondesire** [alextselegidis/easyappointments#692]
In step four (step_four_title) of the reservation wizard, is it possible to display the provider's address on the confirmation page?

I am looking at the frontend_book.js, just above $('#appointment-details').html(html);. I see '#select-provider option:selected' returns the first and last name of the provider but I do not see how I can get access to the provider's other attributes, like address, from there. I was able to get this in Email.php with $provider['address'] but not on step four.

**Comment by alextselegidis** [comment]
Hello @DrMondesire, 

For this you will have to make some changes in the app: 

* You will need to go to the `Appointments.php` controller, in the `index` method and make sure you include the provider address settings. 
* Then edit `frontend_book.js`, and change `updateConfirmFrame` method to display this info for the selected provider. 


For the email you will need to set new variables in the email template and replace them with the real values. This logic is located in the `src/engine/Notifications/Email.php` class.

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by DrMondesire** [comment]
@alextselegidis I see the areas you are referring to that need updating. Thank you for your response!

**Comment by Saphareas** [comment]
Hi @alextselegidis 
I'm sorry to open this again, but I need a bit more assistance with this.
In Appointments.php I've added address, city and zip code to the stripped_data array. But how do I access this information in the frontend_book.js?

**Comment by alextselegidis** [comment]
Hi @Saphareas,

These information are currently available from the window.GlobalVariables.availableProviders array that contains all the public provider info. 

Find your provider object in this array and you will be able to display and use these info. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
