### ISSUE TITLE
I cannot perform the application installation (php v5.3 or older)

### ISSUE THREAD

**Issue by Myslenky** [alextselegidis/easyappointments#693]
Parse error: syntax error, unexpected '[' in /ogles/www/easyappointments/application/config/config.php on line 97 Parse error: syntax error, unexpected '[' in /ogles/www/easyappointments/application/config/config.php on line 97

97  ::

$config['available_languages'] = [
    'arabic',
    'bulgarian',
    'chinese',
    'danish',
    'dutch',
    'english',
    'finnish',
    'french',
    'german',
    'greek',
    'hindi',
    'hungarian',
    'italian',
    'japanese',
    'luxembourgish',
    'polish',
    'portuguese',
    'romanian',
    'russian',
    'slovak',
    'spanish',
    'turkish'
];

358  ::             $config['csrf_exclude_uris'] = ['api/v1/.*'];

The code does not install

**Comment by alextselegidis** [comment]
Hello @Myslenky 

your PHP version is too old for the application. 

I will recommend you to use the latest one if possible. 

Using an old PHP version might also lead to security implications. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Myslenky** [comment]
I am using php 5.3

**Comment by OscarKolsrud** [comment]
> I am using php 5.3

PHP 5.3 Is old and is far out of life.
Update immediately!
