### ISSUE TITLE
Appointment time excluding 

### ISSUE THREAD

**Issue by DcubeIT** [alextselegidis/easyappointments#697]
i have set a time interval for a single service to one hour (3:00-4:00) and once this time is get booked for a provider i want it to be excluded/disabled from the booking page because that time is reserved. any help please

**Comment by alextselegidis** [comment]
Hello @DcubeIT 

You will need to update the working plan of the service provider user to only work for those two hours. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
