### ISSUE TITLE
What about SMS function addition file path?

### ISSUE THREAD

**Issue by pranaydam** [alextselegidis/easyappointments#698]
I want to add SMS api , in which file of easy appointments i should place sms function code?

**Comment by alextselegidis** [comment]
Hello @pranaydam 

You can copy the engine/Notifications/Email.php file that has the email notification logic and integration your SMS gateway. 

Then check for the Appointments.php and Backend_api.php controllers and call your new class to send the SMS notifications, in the same way the email notifications are being sent. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
