### ISSUE TITLE
SMS support

### ISSUE THREAD

**Issue by kaustubhk24** [alextselegidis/easyappointments#699]
How should I add support for sending sms?
I have ready API code where I just want to ping to my provider then It will send sms but Im unble to understand In which file I should add code for sms

**Comment by alextselegidis** [comment]
Hello @kaustubhk24 

Check this issue:

https://github.com/alextselegidis/easyappointments/issues/698

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
