### ISSUE TITLE
Thursday is displayed as Tuesday in italian version

### ISSUE THREAD

**Issue by Sparta123** [alextselegidis/easyappointments#70]
I've checked the working_plan.js and all is good you can find on pastebin my working plan:

http://pastebin.com/FxQ4G5Ts

and this is my language file:

http://pastebin.com/baPdzWxz

In italian thursday is displayed usually as 'Giovedì' but in the backend provider I see 'Martedì' that's tuesday, what is wrong?

**Comment by alextselegidis** [comment]
Hello, this is already fixed for v1.1

https://github.com/alextselegidis/easyappointments/commit/6d10b3364ea7a5ecaeedfbb4fc26ff25b227c7a9

**Comment by Sparta123** [comment]
Hi @alextselegidis could you tell me which fix you've applied? So I can edit my code without waiting the 1.1 release.

**Comment by alextselegidis** [comment]
I actually send you the link with the commit:

https://github.com/alextselegidis/easyappointments/commit/6d10b3364ea7a5ecaeedfbb4fc26ff25b227c7a9

**Comment by Sparta123** [comment]
@alextselegidis there's another file bugged? 'cause I've inserted the edit you've linked but I've the same problem..

**Comment by Sparta123** [comment]
I mean the working plan of providers not the working plan in the settings...

**Comment by alextselegidis** [comment]
fe0df9ecdfae1cffe782d788bfb2ac9bec250561
