### ISSUE TITLE
Unexpected Issues during the installation: AJAX Error:  it require http access ?

### ISSUE THREAD

**Issue by JOduMonT** [alextselegidis/easyappointments#701]
Hi;

Based on this https://github.com/alextselegidis/easyappointments/issues/540
I understand it means EasyAppointments need to run unencrypted ?
this is very bad and sad because we are not in 1990 anymore and https is a minimum when you exchange personal information and/or username and password such as during an installation.
-----
I have few apps working inside my docker-compose.yml which most are them are LEMP stack and I'm able to reach the URL and fell the installation form but I'm unable to finish the installation because AJAX give me an unknown error:
_Note in my stack I have nextcloud which also use AJAX._

![image](https://user-images.githubusercontent.com/5204724/74121310-a8411980-4bf9-11ea-89ef-142e91de3193.png)

What I could say ?
1. my port 80 is close and everything is http is redirected to https by cloudflare
2. my nginx proxy is linuxserver/letsencrypt and this is my proxy-config for easyAppointment
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name meet.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;
    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        proxy_pass http://easyappointments:80;
    }
}
```

**Comment by lupin3rd** [comment]
I confirm the problem in my installation :-(

**Comment by 8sd** [comment]
Same here

**Comment by 8sd** [comment]
So I was able to install it. It was a mess but here is a workaround:

1. Clone the repo
2. Change `BASE_URL = 'http://url…'` to `BASE_URL = 'https://url…'` in `src/config-sample.php`
3. Start with `docker-compose up -d`

I did it only with docker but this might help you even if you do it otherwise.

**Comment by alextselegidis** [comment]
Hello! 

Errors that happen during the installation will most likely be in the storage/logs directory. 

Enable the DEBUG_MODE in the root config.php and try again. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
