### ISSUE TITLE
cant install the software

### ISSUE THREAD

**Issue by Slader10** [alextselegidis/easyappointments#702]
When i try to install the software it seems like try to find the https://mydomain/index.php/installation/index folder or file but i dont have in any part those files

**Comment by nl0pvm** [comment]
i solved this by changing the try_files in my nginx config to:


```
    location / {
		index index.php;
		try_files $uri $uri/ /index.php$is_args$args;
    }
```
      
```
	location ~ \.php$ {
		#try_files $uri =404;
		fastcgi_pass unix:/var/php-nginx/#################.sock/socket;
	}
```

**Comment by alextselegidis** [comment]
NGINX users try this recipe: 

https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
