### ISSUE TITLE
The alert notification of the installation is not being displayed on error.

### ISSUE THREAD

**Issue by athAtp** [alextselegidis/easyappointments#705]
![image](https://user-images.githubusercontent.com/61126747/74655055-5f0e3e00-5194-11ea-978f-0e0efff2a360.png)

Hello.
    
    If you make mistakes when entering data (for example, the password length is less than 7 characters) and press the "Install Easy!Appointments" button. After that, the block "Alert" (div class="alert hidden") does not appear. 

It is necessary to add code (".removeClass('alert-danger')" and ".addClass('alert-danger')") to the file installation.js (lines 74 and 120).

Great job! Thanks for the great program!

**Comment by alextselegidis** [comment]
Hello @athAtp 

Thanks for posting, this is indeed a bug. 

It's fixed on develop and will released with v1.4

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
