### ISSUE TITLE
Unable to log in to backend

### ISSUE THREAD

**Issue by 640miles** [alextselegidis/easyappointments#71]
The login form is available. After entering login and password and pressing the button, the filled data in the form resets.
And if I type in browser mysite.../index.php/backend the system lets me to get inside and use the backend without asking for logins and passwords.
Could you please help me to solve this issue?

.htaccess
Options +FollowSymlinks
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L] 

Don't know, whether it could influence. The EA uses the same DB with Joomla.

**Comment by alextselegidis** [comment]
Hello, I don't really get the problem. Can you give me a clear example so that I can reproduce the problem?

**Comment by 640miles** [comment]
It was missing slash sign in the address line.
Thank you.
