### ISSUE TITLE
Unable to connect to your database server using the provided settings

### ISSUE THREAD

**Issue by tanmayag97** [alextselegidis/easyappointments#711]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: controllers/Backend_api.phpLine 
Number: 36

**Comment by alextselegidis** [comment]
Hello @tanmayag97 

It seems that you have provided invalid database connection credentials cause the app cannot connect to your MySQL server. 

Please check the root config.php file and make sure the connection credentials are valid. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ekordev** [comment]
I'm having the same issue. 
I've tested the credentials they are correct. Can't seem to get around this.
