### ISSUE TITLE
Modifying an appointment to a service with different duration

### ISSUE THREAD

**Issue by SeAIMe** [alextselegidis/easyappointments#712]
Hi,

if a customer is modifying a previously booked appointment, by using the appointment-link in the email he received, to a different service that has a different duration, the time slots aren't updated to this new duration.

Steps to reproduce:
1. Create two services. One with a duration of 60 min and the other one with 120 min. Both as fixed slots
2. Book the 60 min appointment.
3. Click on the appointment-link in the email to modify the appointment.
4. Choose the 120 min appointment.
5. Choose a starting time that is less than 120 min before shop closing time.
6. Go to the confirmation page (page 4) and click on 'update'.
7. An 'unexpected issues' error is shown saying that 'the requested hour is unavailable'.

I would appreciate if you could have a look into this.

Regards

**Comment by alextselegidis** [comment]
Hello @SeAIMe 

If you reschedule the end date time get adjusted to the service duration. You will find this logic in the frontend_book.js file. 

If you get the 'the requested hour is unavailable' error that means that the new service you want to book does not fit to the current working schedule which is also a good thing cause you do not want people to double book when they reschedule. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
