### ISSUE TITLE
Wiki missing?

### ISSUE THREAD

**Issue by daguar** [alextselegidis/easyappointments#713]
Hello! The README here on GitHub has a link to a Wiki, but it appears to simply redirect back to the front page of the repo itself.

**Comment by alextselegidis** [comment]
Hi @daguar The README page got updated. 

Check the "docs" directory for further documentation. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
