### ISSUE TITLE
How to display multiple staff/resources in day view?

### ISSUE THREAD

**Issue by ezxcess** [alextselegidis/easyappointments#714]
Hi. Is there a way to display more that 1 staff or resources in a day view? Eg. show both Jane's and John's appointments at the same time rather than just Jane's or John's? This will allow admins to drag and drop appointments between staff/resources easily. Thanks.

![image](https://user-images.githubusercontent.com/1163793/75884223-277be300-5e70-11ea-80c0-7abd8b72f993.png)

**Comment by alextselegidis** [comment]
Hello @ezxcess 

The new release v1.4 has a table view that displays all the provider plans for a certain day, side by side. 

It looks like this: 

![Screenshot 2020-06-18 at 14 14 04](https://user-images.githubusercontent.com/4527441/85018750-01075c80-b16e-11ea-8445-215960521aae.png)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
