### ISSUE TITLE
**solved** Email fails to send notifications. (No envía correos de notificación) **solved**

### ISSUE THREAD

**Issue by luis141284** [alextselegidis/easyappointments#716]
After a while I couldn't send emails, I found the solution ... the problem is the PHPmailer version 5.2.23 fails and only works with version 5.2.6

You just have to replace the folder \vendor\phpmailer\phpmailer
 and voila.

Después de un tiempo que no podía enviar correos, encontre la solucion... el problema es el PHPmailer falla la version 5.2.23 y con la que funciona es la version 5.2.6

Solo tienen que remplazar la carpeta de \vendor\phpmailer\PHPMailer y listo.

[PHPMailer-master.zip](https://github.com/alextselegidis/easyappointments/files/4379741/PHPMailer-master.zip)

Espero y les sirva - - - - - - I hope it works for you

**Comment by clarkdeleon84** [comment]
it works if installed in mac. but not in virtual min
