### ISSUE TITLE
URL misbehaves when $APP_URL is set to https://example.com

### ISSUE THREAD

**Issue by derekpovah** [alextselegidis/easyappointments#717]
The URL gets rewritten to `http://url-to-easyappointments-directory/index.php/installation/index` when  `$APP_URL` is set to something like `https://example.com`.

At first glance of [`docker-entrypoint.sh`](https://github.com/alextselegidis/easyappointments/blob/0fe96a28d4c9f04426b6c82d2d6a91a1eb93b303/docker-entrypoint.sh#L18), it looks like this is because the `$APP_URL` environment variable is being dropped directly into the `sed` call that updates the `BASE_URL` config entry. This results in unescaped slashes and means `BASE_URL` doesn't actually get updated. 

It also appears that only `url-to-easyappointments-directory` is being replaced by that `sed` call. This means if we set `$APP_URL` to an actual [URL](https://tools.ietf.org/html/rfc1738) (including the `http://` or `https://`) it will break as well.

**Comment by FacundoAcevedo** [comment]
Hello, I've fixed this replacing this sed line with:
`    sed  -i  "s|url-to-easyappointments-directory|$APP_URL|g" $PROJECT_DIR/config.php`
I think it didn't work because of the / used in  $APP_URL. Besides that I'm experiencing issues because mixed content

**Comment by alextselegidis** [comment]
Hello @derekpovah 

The docker configuration is updated for v1.4 (develop branch), this should not be an issue any more. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
