### ISSUE TITLE
Email configuration can't be set in config.php

### ISSUE THREAD

**Issue by derekpovah** [alextselegidis/easyappointments#718]
I think it would be great to have all configuration options in one place.

**Comment by andresfabianguerrero** [comment]
same here, I want to implement mailchimp in order to track emails

**Comment by alextselegidis** [comment]
Hello @derekpovah @andresfabianguerrero 

There is actually a place where you can add email configuration and that is in `application/config/email.php`. 

https://codeigniter.com/userguide3/libraries/email.html?highlight=email#setting-email-preferences

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
