### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by tondemut** [alextselegidis/easyappointments#722]
Getting an error on setup

An unexpected error occurred in file /home/main/public_html/wp-content/plugins/easyappointments/core/ValueObjects/Path.php (line 35): Invalid $path argument provided

**Comment by alextselegidis** [comment]
Hello @tondemut 

Please post future plugin errors to https://github.com/alextselegidis/easyappointments-wordpress-plugin

As the error says the path value you provided is not a valid path, does not exist in the system or is not writable. 

Please provide an absolute path in the input field. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
