### ISSUE TITLE
Backend calendar can fail to display events from Google Calendar

### ISSUE THREAD

**Issue by sandbergja** [alextselegidis/easyappointments#724]
At times, the backend view fails to load any events from Google Calendar.  In the console, I got the error "Unable to read property length" on this line:

https://github.com/alextselegidis/easyappointments/blob/513b0101ebf636536ca8fe812350bc5ec0f1c2d5/assets/js/backend_calendar_default_view.js#L909

I think that it should check the length of `notes`, rather than `unavailable.notes`

**Comment by alextselegidis** [comment]
Hello @sandbergja 

We already had the conversation on this on your PR so I'm closing this ticket. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
