### ISSUE TITLE
PHPmailer Issue with using virtuamin server | unable to send email. 

### ISSUE THREAD

**Issue by clarkdeleon84** [alextselegidis/easyappointments#727]
I guess there's no way around this issue. 

When I send email from MAMP server, it works but when I send email from my virtuamin server it fails. 

what is the best server to host this app? i may have to get a dedciated?

**Comment by alextselegidis** [comment]
Hello @clarkdeleon84 

One way is to use some mailing service like Mailgun, Sendgrid etc. 

The other way is to ensure your hosting environment supports mails through PHP. 

Finally you could install postfix or some other mail server tool to create your own email functionality from your server. This is not an easy task though and it requires some configuration knowledge that can be nevertheless found on the web. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by clarkdeleon84** [comment]
thanks, I used sendgrid.

Clark de Leon
Team Up Telecom

Is your number SMS enabled? Click here<https://www.youtube.com/watch?v=yaWz_id2k10> for more info.


clark@t<mailto:clark@gulfworx.com>eamuptelecom.com<http://eamuptelecom.com>
Schedule a Free Consultation<https://meetings.hubspot.com/clark21>
Call or Text 904.539.8765
Fax: 904-456-0828
Website: www.teamuptelecom.com<http://www.teamuptelecom.com>


[cid:e0aac6be-dc4c-40d2-be5b-1102105f427a]


________________________________
