### ISSUE TITLE
Official version of the docker image

### ISSUE THREAD

**Issue by halkeye** [alextselegidis/easyappointments#728]
I tried looking through the existing issues but didn't see anything.

Is there any reason you don't have an official version release for the docker images? If you use docker hub's ci it'll create a specific image for each tag, which would be amazing.

**Comment by alextselegidis** [comment]
Hello @halkeye 

The app comes with docker configuration that can be used for local development or for production. 

So far this worked in various cases very well in various use cases. 

Let us know if there is any use case that is not covered by the currently available setup. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by halkeye** [comment]
so in a cloud provider that runs docker apps, i'd have to check out the version, build it, then push it to docker hub. Which a lot of people have done. But there's no official version which would make that process easier, which is why i opened a ticket.
