### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by Johnowen043** [alextselegidis/easyappointments#729]
Ajax error: Syntaxerror: unexpected end of json input, on instalation pages, how i can fix this?

**Comment by alextselegidis** [comment]
Hello @Johnowen043 

Check the error logs of your installation for further troubleshooting. 

There was a server error when hitting the install button. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
