### ISSUE TITLE
Cannot read property 'service' of undefined

### ISSUE THREAD

**Issue by Sparta123** [alextselegidis/easyappointments#73]
Seems that If I've an "unavailable" event type on my scheduler and I click on the "title" there is no problem the content of the event is displayed correctly. But if I click on the hours to the top of the event I get this error: 

      Cannot read property 'service' of undefined

the problem seems that the .has class can't find the fc-unavailable class in the calendarEventClick
how can I fix this?

**Comment by alextselegidis** [comment]
Can you be more specific with "But if I click on the hours to the top of the event"? 

I do not understand which "hours" you mean exactly?
