### ISSUE TITLE
How to connect with jitsi meet?

### ISSUE THREAD

**Issue by expertsupervisor** [alextselegidis/easyappointments#731]
I'm using easyappoinments for customers and because of corona-virus i can't meet customers personally. So now i want to try out jitsi meet. Jitsi in connecttion with easyappointments. 
If customers book new appointment, they get an email, but i want to have the jitsi meet link for videoconferencing automatically in the email notification. Does anyone have any ideas? How to connect easyappointments with jitsi?

**Comment by Grisu1959** [comment]
If you have a fixed link for jits (ex jitsi.meet.si/expertsupervisor )
you can modify the tamplate of the email and write it inside (with the password if you set it)

if you have a variable link I think it  could be not possible

**Comment by alextselegidis** [comment]
Hello @expertsupervisor 

For now I would put the link in the template file, located in the `application/views/email/appointment_details.php`. 

In the future a more sophisticated template editor will be part of the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
