### ISSUE TITLE
Google Calendar sync won't put the same event on multiple providers' calendars

### ISSUE THREAD

**Issue by sandbergja** [alextselegidis/easyappointments#733]
All our providers have our team meeting on their calendar.  However, the Google Calendar sync checks to make sure there are no duplicate values in the `id_google_calendar`.  This means that the first provider to sync their calendar will get the team meeting added to their EasyAppointments calendar, but other providers won't get it added.

I will prepare a pull request that allows various providers to have the same Google Calendar meeting added to their EasyAppointments calendars and submit it soon.

**Comment by alextselegidis** [comment]
Closing this, more info in the PR

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by o62** [comment]
Hi Alex, is there a fix to this issue? We are using 1.4.3 and we have the same problem. We have many team events where the same providers meet together and need all of their calendars show as unavailable. As described by sandbergja, only the first user to sync will get the event to show up as unavailable.
