### ISSUE TITLE
New problem, appointments get from 15 min to 15 min.

### ISSUE THREAD

**Issue by jesusmoreno24** [alextselegidis/easyappointments#736]
I enclose a screenshot so you can see it.

https://i.gyazo.com/1de982f90e92927b2dbea927fb8d04f1.png

How do I fix this?

**Comment by mirlipili** [comment]
Hello, 
I made these changes in "appointment.php" in the ~/application/controllers folder.

search for "15" and change to 30.


I changed both in line 1086 and in line 1144 (but I'm not sure both are needed).
That way, the only slots available are every 30 min.

**Comment by yayitazale** [comment]
Changed that and still same 15 minutes slots

**Comment by mirlipili** [comment]
I just checked, changed it in line 1086, in ~/application/controllers/Appointment.php
from: 
$interval = $availabilities_type === AVAILABILITIES_TYPE_FIXED ? (int)$service_duration : 15;
to:
$interval = $availabilities_type === AVAILABILITIES_TYPE_FIXED ? (int)$service_duration : 30;

no apache reload or anything else, just a page reload and it shows immediately.

The other edit in line 1144 is for multiple attendants appointments, but I don't use them, so changing it doesn't make a difference for me.

**Comment by makayabou** [comment]
I think you can also choose Fixed as service's availability. see screenshot
![Capture d’écran de 2020-06-14 02-40-13](https://user-images.githubusercontent.com/25554584/84582316-ca86b600-adea-11ea-8c54-5e7a64e5806c.png)
