### ISSUE TITLE
Feature request - available days for employee

### ISSUE THREAD

**Issue by semaf** [alextselegidis/easyappointments#738]
Hey,

All employees are not daily available but appointments can be done daily. Would be great to set to users different available days and user can select only if a user is available or a specific user.

**Comment by alextselegidis** [comment]
Hello @semaf 

Right now this is solved with the working plans. 

In the upcoming v1.4 you will be able to set custom working days do (outside the normal plan). 

Stay tuned for more updates. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
