### ISSUE TITLE
Add custom field in backend service

### ISSUE THREAD

**Issue by plcdnl** [alextselegidis/easyappointments#740]
Is it possible to add a custom field when i create a new service in backend ? If yes, how can i do? Thank u in advance.

**Comment by alextselegidis** [comment]
Hi @plcdnl 

You will need to create the HTML for this in views/backend/services.php 

Then change the backend_services_helper to save and display the field.

Probably add some validation in the Services_model.php class. 

And of course add the new field to the database. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
