### ISSUE TITLE
only 5 days sincronized

### ISSUE THREAD

**Issue by Grisu1959** [alextselegidis/easyappointments#742]
At last I could syncronize Easyappointment and calendar

but are syncro only 5 days

What I have to change?

**Comment by alextselegidis** [comment]
Hi @Grisu1959 

5 was set in the past for performance reasons but this will be changed for 1.4.0. 

For now you can manually change the database rows of `ea_user_settings` and set a higher number for the `sync_past_days` and `sync_future_days` fields.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
