### ISSUE TITLE
Appointment not deleted

### ISSUE THREAD

**Issue by Grisu1959** [alextselegidis/easyappointments#744]
Hello
if a costumer delete an appointment 
it is deletede on the EASYAPP caledar
but NOT on Google calendar
Wich could be the error?
Thanks

**Comment by alextselegidis** [comment]
Hi @Grisu1959 

if the event is deleted in Easy!Appointments and it belongs to a provider that is synced with a Google Calendar then the synced event must be automatically removed too. 

If the synchronization is not active then there's no way to remove the event from the remote calendar. 

Please make sure the syncing works by connecting to a remote Google Calendar event and making some test changes to ensure they are probably delegated to the external calendar. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Grisu1959** [comment]
Hello
the syncronization is active (infact the meeting was automaticaly register on google calendar)
but don't works properly when a costumer delete and appointment
