### ISSUE TITLE
Add appointment notes preview in the event popover. 

### ISSUE THREAD

**Issue by enrilor** [alextselegidis/easyappointments#745]
If customer should leave some note for special request, should be important to see it in calendar or at least see it on preview. Now you can only see it if you try to modify appointment.

**Comment by alextselegidis** [comment]
Commited on `develop`.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
