### ISSUE TITLE
Transfer more informations to Google Calendar

### ISSUE THREAD

**Issue by Grisu1959** [alextselegidis/easyappointments#746]
Hello
I would like understand how can I transfer more informations to google calendar 
as name of the costumer 
and subject of the meeting

Regards

**Comment by alextselegidis** [comment]
Hi @Grisu1959 

adding more information will require code customizations in the Google_sync.php file inside the `application/libraries` directory. 

You can fine tune the information being sent to a Google. 

Similarly you can modify the `application/controllers/Google.php`. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
