### ISSUE TITLE
Actions are no more displayed in notifications

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#753]
On branch develop, the "action" button is no more displayed in notifications. For exemple: undo notifications when an appointment is moved in the calendar.

This is due to commit 83fd802f57af71db8905aaa1a88c7142fee94c10 which changes the `displayNotification()` function.

**Comment by alextselegidis** [comment]
Hi @popod 

Thanks for posting, indeed the action was added to the wrong element.

This is now fixed on develop. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
