### ISSUE TITLE
[Docker] Mixed content 

### ISSUE THREAD

**Issue by FacundoAcevedo** [alextselegidis/easyappointments#754]
Hello, I'm dealing with this issue. I've configured the URL in the .env file like this:
`APP_URL=turnos.valid.domain.com`
It is running behind Ha proxy with SSL offloading  so I hit the web using:
https://turnos.valid.domain.com

Using Firefox the app does not load correctly, I'm getting Mixed content errors while trying to get assets like: date.js, jqery.js, bootstrap-min.js, etc...

If I edit the .env file and set this (patching docker-entrypoint.sh to make sed work with slashes):
`APP_URL=https://turnos.valid.domain.com`
It doesn't work, I think because the app is running at port 80 :P

**Comment by alextselegidis** [comment]
Hi @FacundoAcevedo 

please try the updated docker configuration of the `develop` branch and let me know if you experience any issues. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by FacundoAcevedo** [comment]
I switched to develop branch, renamed  config-sample.php  and setted up as I needed, but when I run docker-compose up --build I cant reach the website from outside I get:
    Incorrect URL
If I run docker-compose exec server curl localhost :
`br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or d
irectory in /var/www/html/index.php on line <i>63</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>410632</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/index.php' bgcolor='#eeeeec'>.../in
dex.php<b>:</b>0</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_
path='.:/usr/local/lib/php') in /var/www/html/index.php on line <i>63</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0019</td><td bgcolor='#eeeeec' align='right'>410632</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/index.php' bgcolor='#eeeeec'>.../in
dex.php<b>:</b>0</td></tr>
</table></font>
`

There is no vendor directory in /var/www/html

**Comment by makayabou** [comment]
Same error for me using docker-compose with develop branch:
`There is no vendor directory in /var/www/html`

**Comment by alextselegidis** [comment]
@FacundoAcevedo @makayabou Did you previously install the composer dependencies with `composer install`?

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by StarWhiz** [comment]
I still have the same problem as OP in docker

![image](https://user-images.githubusercontent.com/9423276/86986764-4a354580-c149-11ea-9b2f-45901276f285.png)

Am using caddy. And have set these as my .env

`APP_URL=subdomain.mydomain.com
APP_HOST=0.0.0.0
APP_PORT=80`

**Comment by StarWhiz** [comment]
I seem to get similar errors on the development branch.

![image](https://user-images.githubusercontent.com/9423276/86990293-2249e000-c151-11ea-98a6-89cc863780ae.png)
