### ISSUE TITLE
Multiple working plan for the same provider

### ISSUE THREAD

**Issue by Back2TheFuture** [alextselegidis/easyappointments#76]
This feature is present in almost all professional scheduler. Currently ea_appointments allows the creation of a single working plan for each provider. My proposal would be to create multiple work plans. For example in a work plan number 1 is added as working only on Thursdays and Fridays. In a second work only on Mondays and Saturdays. Each week the system will have to change as a work surface 1 to 2 work plan for each supplier. This is very useful because not all providers are the same hours. You think you can implement something like that in 1.1? Would you do me really happy. Thank you. @alextselegidis

**Comment by alextselegidis** [comment]
Hello

I'm sorry to inform you that this feature will not be added for 1.1. If you really need to switch between multiple working plans for each provider try to create two providers with the same name and manually disable the services of each one depending on your requirements.

A provider will not be shown on the booking list if he does not have any services to serve. 

You could also automate this process with a cron job. Try to create a new php procedure that will change the "ea_services_providers" connections by updating the id_users to the second provider record and vice versa. You the db credentials of the config.php file like E!A does.
