### ISSUE TITLE
Customizations possibilities

### ISSUE THREAD

**Issue by EdG91** [alextselegidis/easyappointments#760]
Hello,
I am looking for some informations, this is not really issues.
I have set a fresh installation of easyapppointments (centos 8, mariadb, apache).
1. is there a documentation to install phpmailer for mail notification ?
2. how to secure this installation if exposed to internet ? I thought to use a reverse proxy apache, with fail2ban, mod_evasive, mod_security ? Can it work with mod_security in front without needs to disable some mod_security rules ?
3. How to set "all available person" by default in public portal ? and remove choices of others persons ?

Best Regards

**Comment by alextselegidis** [comment]
Hello @EdG91 

> is there a documentation to install phpmailer for mail notification ?
PHPMailer is already part of the app. 

> how to secure this installation if exposed to internet ? I thought to use a reverse proxy apache, with fail2ban, mod_evasive, mod_security ? Can it work with mod_security in front without needs to disable some mod_security rules?
I do not think that enabling those modules will be able problem, as long as the PHP requests can still be executed properly on your server. 

> How to set "all available person" by default in public portal ? and remove choices of others persons?
You probably refer to the booking page, there is an option called "Any Provider" and it uses an internal algorithm to resolve the first available provider of the system. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
