### ISSUE TITLE
How to add / change fields from the customers form ?

### ISSUE THREAD

**Issue by EdG91** [alextselegidis/easyappointments#762]
How to add some fields, put them compulsory, or remove some in the customer front end ?

The form where the customer add his firstname, lastname, phone number, etc...

I would like by example add the field "date of birth"

Best Regards

**Comment by jinformatique** [comment]
Hello, 
Thank you for this great project and all the work already done.

I agree with this request. Would be great to be able to add a customized question for the audience.
By the way, when a user want to book a time, he adds a comment and on the next screen, the comment is not taken into account.

All the best.

**Comment by alextselegidis** [comment]
Hello @EdG91 @jinformatique 

Please check the documentation of CodeIgniter (v3)

https://codeigniter.com/userguide3/index.html

Once you learn how the framework works, you will be able to make changes to the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by JDeepix** [comment]
Hiding fields is pretty simple. We needed only the fields of the first column, so I added the class "invisible" in views\appointments\book.php to the fields I didn't need. In my case the whole 2nd column.

Adding or changing fields requires a lot more programming, since the database-model needs to change.
