### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by derekpovah** [alextselegidis/easyappointments#763]
I'm not usually one to put in issues without doing research first, but I'm in a bit of a time crunch here.

Is this app managing connections to MySQL with a connection pool? It seems like connections to MySQL are staying open a long time.

If I set `wait_timeout` or `interactive_timeout` can I trust that Easy!Appointments will gracefully handle connections being terminated from the MySQL server side?

For context, I'm seeing the following:

```
AJAX Error: SyntaxError: Unexpected token < in JSON at position 0
    A PHP Error was encountered

    Severity: Warning
    Message: mysqli::real_connect(): MySQL server has gone away
    Filename: mysqli/mysqli_driver.php
    Line Number: 201
```

**Comment by alextselegidis** [comment]
Hello @derekpovah 

There is a single connection that exists for the whole request lifecycle. 

This does seem to be a MySQL server configuration issue, though I am not sure what needs to be changed exactly. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
