### ISSUE TITLE
Function to print all appointements for a day or a week

### ISSUE THREAD

**Issue by EdG91** [alextselegidis/easyappointments#764]
Is there a way to print all appointements for a day or a week, without using File / Print menu of the browser ?
The print result is not very redeable by this way.

Best Regards

**Comment by alextselegidis** [comment]
Hello @EdG91 

That is not available right now. 

In a future release there will a report feature in the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
