### ISSUE TITLE
How to protect backend access

### ISSUE THREAD

**Issue by EdG91** [alextselegidis/easyappointments#765]
Hello,
Is there a way to protect backend access ?
I mean via ip fitering to restrict access to backend only for specific subnet of internal LAN,
and not allow for internet IP (e.g. internet IP are customers, they can only access to front end).

**Comment by alextselegidis** [comment]
Hello @EdG91 

On the software side you could add IP filtering on the Backend pages by adjusting the controller classes of the app. 

Server side configuration could also be a good option for this too. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
