### ISSUE TITLE
Error Invalid day index at unavailable dates

### ISSUE THREAD

**Issue by hmpcarvalho** [alextselegidis/easyappointments#768]
Good afternoon ,

My thanks in advance for making this project available.

I am having an Invalid day index error on the browser console in the following piece of code:

// Grey out unavailable dates.
        $('#select-date .ui-datepicker-calendar td:not(.ui-datepicker-other-month)').each(function (index, td) {
            selectedDate.set({day: index + 1});
            if ($.inArray(selectedDate.toString('yyyy-MM-dd'), unavailableDates) != -1) {
                $(td).addClass('ui-datepicker-unselectable ui-state-disabled');
            }
        });

Inside  function _applyUnavailableDates on frontend_book_api.js

I changed it to this:

$('#select-date .ui-datepicker-calendar td:not(.ui-datepicker-other-month)').each(function (index, td) {
        	let tdtable = $(this);
        	var value = index + 1;
        	var selectDate = new Date(selectedDate);
        	selectDate.setDate(selectDate.getDate() + value);
            console.log("dATASelect",selectDate);
            if ($.inArray(selectDate.toString('yyyy-MM-dd'), unavailableDates) > -1) {
            	console.log("entrounoArrayDataSeleccionada",selectDate.toString('yyyy-MM-dd'));
            	tdtable.addClass('ui-datepicker-unselectable ui-state-disabled');
            }
        });

The aRRAY I have with the unavailable dates is this:
 ["2020-05-01", "2020-05-02", "2020-05-03", "2020-05-04", "2020-05-05", "2020-05-06", "2020-05-09", "2020-05-10", "2020-05-16", "2020-05-17", "2020-05-23", "2020-05-24", "2020-05-30", "2020-05-31"]

It is no longer an error, but when I go to the calendar in the frontend the days that are unavailable do not all appear to me with the css class that was assigned to it.

And if you change the month and then go back to the days that were with that class, you will be left without the respective classes and change that same class of css to other days.

Am I doing something wrong?
Thanks a lot

**Comment by alextselegidis** [comment]
Hello @hmpcarvalho 

I cannot reproduce this problem. 

Have you made any adjustments to your installation? 

Which Easy!Appointments version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
