### ISSUE TITLE
Can't set host name dynamically

### ISSUE THREAD

**Issue by hopeseekr** [alextselegidis/easyappointments#77]
```
class Config {
     const BASE_URL = 'http://www.somedomain.com/appointments/';
}
```

So how do you handle multiple environments? What if I need `www.somedomain.com` on production, but `dev.somedomain.com` and `qa.somedomain.com`? What is the solution?

**Comment by hopeseekr** [comment]
Right now I literally have a cludge where I made the config.php writable only by root. Surely this isn't a viable situation, long-term.

**Comment by alextselegidis** [comment]
You actually just have to update the BASE_URL constant. There is no other dependency from the installation URL.
