### ISSUE TITLE
Do not open the "new appointment" modal on simple click

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#771]
In the backend, we should not open the "new appointment" modal each time the user click on the calendar.. This is not very friendly.. I think that doing this action only on double-click is better to prevent opening this modal by error.

**Comment by alextselegidis** [comment]
Hello @popod 

On the contrary, based on experience I've gather through tons of scheduling installations I see that people really like the direct click - creation behavior. 

Google Calendar and other calendaring system do also work in a similar way. 

I will therefore keep it this way. 

Thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
