### ISSUE TITLE
Allow to hide timezone informations

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#776]
An option to disable the display of timezone informations in the user interface. We could keep the setting active, but hide this informations to customers and providers if not needed will be a good user interface improvement.

**Comment by alextselegidis** [comment]
Hello @popod 

Timezones is now a very important information for each event scheduling in the system. 

I would rather not hide at any time but probably allow for more configuration in the future (like local or locked timezones etc). 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
