### ISSUE TITLE
Problems sending mails

### ISSUE THREAD

**Issue by luisbernas** [alextselegidis/easyappointments#782]
Good afternoon,

First of all congratulations for the easy!appointments. Great work!

My problem: 
- I add the custom values in the email.php;
- i went to the booking page and made an appointment;
- at the end - "Your appointment has been successfully registered! An email with the appointment details has been sent to you."

And i don't receive any mail in inbox (or in the SPAM folder).

The strange thing is in the contact page of the site the SMTP server and phpmailer it's well configured and it's working. I have put exactly the same values in email.php and i'm not receiving any email ....

Any idea? Right now i'm pulling my hair out!!!! :-(

Thanks in advance for your help.
Luis Bernardo.

**Comment by luisbernas** [comment]
My configurations in the application/config/email.php

$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = 'smtp'; // or 'smtp'
$config['mailtype'] = 'html'; // or 'text'
$config['smtp_host'] = '***';
$config['smtp_user'] = '***@***.***'; 
$config['smtp_pass'] = '***';
$config['smtp_crypto'] = 'ssl'; // or 'tls'
$config['smtp_port'] = 465;

I've been struggling with this problem for a few days ... i think i'm going to QUIT ..... :-(

**Comment by willouch** [comment]
Hi,
Same problem, mail is not send with last version

**Comment by MARVINM22** [comment]
Good morning, Luisbernas!

Did you manage to solve that problem?
I have the same problem, but for some reason it works for me using the PHP 7.1 version, and not with the PHP 7.3 version.
The appointment is recorded successfully, but the mail does not arrive; but in PHP 7.1 it does arrive without problem.

What version do you use?, or Did you manage to solve the problem?

**Comment by luisbernas** [comment]
Hello Marvin!

I resolve it. But i had to create an GMAIL account for this purpose AND had to enable insecure applications within Gmail too ...... With this GMAIL account all went well.

(My PHP version in 5.6.40).

I hope this can help .... if you need anything else, don't hesitate!

**Comment by MARVINM22** [comment]
Thank you Luisbernas; good that it works well for you.

In my PHP 7.3.12 it doesn't work for me, I also have that configuration. On the server I have with PHP 7.1 if mail is sent.

I will do another test by installing version 7.3.12 on another server and test if it works.

Thank you

**Comment by alextselegidis** [comment]
Hello!

Email configuration is a topic that is not that obvious for many developers indeed. 

I think eventually the missing piece here is to allow the configuration to be done from the UI at some point. 

I would rather not add many info to the root config file cause it will eventually get bloated. 

Bottom line on the issue: 

* Ensure your server can send mails with PHP (there are plenty of guides online on how to check that).
* If this is not possible try using a 3rd party SMTP service and add your credentials in `application/config/email.php`.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
