### ISSUE TITLE
Translation tag 'cancel' needs a twin

### ISSUE THREAD

**Issue by idstam** [alextselegidis/easyappointments#785]
In Swedish there are different words for cancel depending on context. Sometimes it doesn't matter that much but there is a big difference between 'canceling an appointment' and 'canceling an update operation in the admin ui'

Therefore I would like to create a new cancel_appointment tag. I could add it to all existing translations and copy the existing translations.

Should I go ahead an create a PR or should I keep the change in my own fork?

**Comment by alextselegidis** [comment]
Hello @idstam 

I do not speak sweedish myself, but I can imagine that every language has its own way of expressing certain situations. 

Feel free to make a PR but please make sure the contents represent the english version of the strings and not a subjective view of the project and its functionality. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
