### ISSUE TITLE
Placeholder issues

### ISSUE THREAD

**Issue by mwadudjar** [alextselegidis/easyappointments#786]
I can't seem to add a placeholder for the #select-service. 
I tried to add `<option disabled selected> Choose a service </option>` to the <select> element but then the calendar will make unavailable dates clickable.

**Comment by alextselegidis** [comment]
Hello @mwadudjar 

This change needs adjustments to the forntend_book.js file. 

Check the `initialize` method. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
