### ISSUE TITLE
Option to prevent updating past events

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#787]
I think that a new setting "do not allow to update past events" will be really nice ! This will prevent users to move a past event by error in the backend calendar.

**Comment by alextselegidis** [comment]
Hello @popod 

You mean that you want to block customers from editing appointments that belong to the past right? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
@alextselegidis No, I mean for backend users.. I think to only allow to remove and edit past events.. but not to move them it in the backend calendar (to prevent errors).

**Comment by alextselegidis** [comment]
Writing back here after a while ... 

I think that is too specific for an option to be created. 

After all if it's their appointments they should be able to edit them. 

Possibly that could also become a role option in the future, but I will skip adding this for now for the sake of simplicity in the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
Hi @alextselegidis

I understand your point of view, but I think that this option will be very interesting and needed for some users because :

- If an user update/move/delete a past appointment in the backend, the end customer will receive a notification email ! We should not send notifications emails for past events..
- If the admin use appointments for some accounting or else, we should provide an option to prevent backend users to remove/edit past appointments.

I think that adding this option (disabled by default) will be really useful for customers.

What do you think about that ?
