### ISSUE TITLE
Enable the change of the brand logo and colors from the backend.

### ISSUE THREAD

**Issue by fdefilippo** [alextselegidis/easyappointments#789]
Could you add the icon-logo variable for the brandname in the frontend header?

thnx.

**Comment by div4d** [comment]
you could save your logo in the asset folder with the same name as the og one.
mine is /easyappointments/assets/img/logo.png
so save your logo there as a png and should be fine.
same for the favicon if you were wondering

**Comment by fdefilippo** [comment]
Yes I know but I would prefer to have a template/variables to modify instead of touching up the source.  Something that will allow to customize as follows:

![chrome_dRoil25Svo](https://user-images.githubusercontent.com/16714986/82894521-fc76cc00-9f52-11ea-8715-aad39160b147.png)

**Comment by davidperezgar** [comment]
It should be nice to have like a template directory in order to save the changes there.

**Comment by davidperezgar** [comment]
I don't see the logo, How could I show it?

**Comment by fdefilippo** [comment]
change application/views/backend/header.php so look like, about line 37:

            <div id="header-logo" class="navbar-brand">
                <img src="<?= base_url('assets/img/logo.png') ?>">
                <span><?= $company_name ?></span>
            </div>

**Comment by div4d** [comment]
I know pretty much nothing about php, this is the first time I am dealing with it... but I can see that there are some parameters specified in the code such as the $company_name, so I guess that we could create a page to change the colours of the front-end using those. 
Do you know if it is possible to do so?

**Comment by alextselegidis** [comment]
Hello!

Theming will come in the future for sure. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by stonespheres** [comment]
Alex are you happy for me to jump in on this? 
I'm familiar with PHP, etc. Believe I may be able to help with this feature.

**Comment by vitormattos** [comment]
I made a pull request #1052 adding setting to define a custom script block for all pages. This pull request can be used to apply CSS.

In fact it allows you to insert any HTML in the appointment. You can create a JS and a CSS and use the code from this PR to resolve this issue.
