### ISSUE TITLE
Impossible to Install

### ISSUE THREAD

**Issue by hopeseekr** [alextselegidis/easyappointments#79]
Yeah....

Clicking on the Install button redirects the app to http://example.com/appointments/index.php/appointments/ajax_install

which then fails with a 500 error, because it tries to load the 404 page, which tries to query a non-existant database, and then **BOOM!**

The correct URL seems to be http://example.com/appointments/index.php/installation/ajax_install

**Comment by weyderfs** [comment]
Here when I click the button appears the animation processing, but does not forward, stands on the same page

**Comment by alextselegidis** [comment]
Hi, it happened to fix the issue before you made the pull request. My commits are in the develop branch which will be merged to the master soon. 

If you need a more stable version use 1.0 from the official website: http://easyappointments.org

**Comment by hopeseekr** [comment]
There were several things missing from your fix in Develop, notably the README.md instructions and choosing the correct location of the `assets/sql` folder.
