### ISSUE TITLE
Attendants cap?

### ISSUE THREAD

**Issue by div4d** [alextselegidis/easyappointments#792]
Hello, there. I think I might found an issue
In one of my slots, I set up a maximum attendance of 10 persons. Seven clients have now booked and no one can book that slot anymore. 
I am not sure if seven is the actual number, I just can only see seven persons in the calendar view (both table and default).
am I missing something in the calendar view or is there any automatic cap?
many thanks

**Comment by issacblunt** [comment]
I has the same problem when it was querying the existing appointments  for that day it wasn't taking into account the service id. I tracked it down to the query grouping being in the wrong place. The changed to the following in Appointments_model.php fixed it for me from line 497:
 public function get_attendants_number_for_period(DateTime $slot_start, DateTime $slot_end, $service_id)
    {
        return (int)$this->db
            ->select('count(*) AS attendants_number')
            ->from('ea_appointments')
            ->group_start()
            ->where('start_datetime <=', $slot_start->format('Y-m-d H:i:s'))
            ->where('end_datetime >', $slot_start->format('Y-m-d H:i:s'))
            ->or_group_start()
            ->where('start_datetime <', $slot_end->format('Y-m-d H:i:s'))
            ->where('end_datetime >=', $slot_end->format('Y-m-d H:i:s'))
            ->group_end()
            ->group_end()
            ->where('id_services', $service_id)
            ->get()
            ->row()
            ->attendants_number;
    }
  
Great app by the way

**Comment by alextselegidis** [comment]
Hello! 

The new beta v1.4.0 will become available in the next couple of days. 

This issue is fixed in there. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
