### ISSUE TITLE
[v1.3.2] Problems with Sync Google Calendar

### ISSUE THREAD

**Issue by alternadom** [alextselegidis/easyappointments#793]
Hi,

First, thanks a lot for your work, this project is awesome!

My problem, we added the google sync, it is working but not at real time.
Ours calendars do not seem to sync if I do not push the "Sync" button.
Even if I push it, i have a notification "successful" but no update :(

What can I do for a refresh in real time ?

Thanks for the support!

(I am so excited about v1.4)

**Comment by alternadom** [comment]
And if it sync, it only works for the week.. not the others :(

**Comment by alextselegidis** [comment]
Hello! 

Refreshing pulling remote Google Calendar changes automatically will become available with v1.4.0 and you will need to configure a cron job. 

For the synced schedule you will need to change the sync_past_days and sync_future_days fields of the user_settings table to a value more than 5 days in the database. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
