### ISSUE TITLE
book appointment: choose a time before the current one.

### ISSUE THREAD

**Issue by fdefilippo** [alextselegidis/easyappointments#795]
in the second step, selecting the date and time, it must not be possible to choose an hour behind the current one. Is there any fix ?

![chrome_xlGcqCf2rN](https://user-images.githubusercontent.com/16714986/83242342-88c7ff80-a19c-11ea-859e-0ac5da575a9e.png)

**Comment by mirlipili** [comment]
If you mean the timefame where customers aren't allowed to take new appointments, it's in:
settings - business logic . scroll down and adjust the "Book advance timeout" option.
In Italian (I assume) : Impostazioni - Business logic, "Tempo limite prenotazione"

**Comment by fdefilippo** [comment]
obviously I was unclear. You shouldn't be able to book an appointment for a time earlier than now.

![chrome_puvHTbi5Gl](https://user-images.githubusercontent.com/16714986/83392281-1e5dcc00-a3f5-11ea-8783-20ac4de05565.png)

**Comment by mirlipili** [comment]
Maybe check your server's time? It could be on GMT, which would explain the 2 hours difference.
There is also a setting in application/config/config.php under "Master Time Reference" (line 390) where you can choose between local and gmt.

**Comment by alextselegidis** [comment]
Hello!

Please change the server timezone or add it in the root index.php file like this: 
```
<?php 

date_default_timezone_set('Europe/Berlin');

...
```

List of supported timezones 

https://www.php.net/manual/en/timezones.php

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
