### ISSUE TITLE
Date and Time When People Can Schedule

### ISSUE THREAD

**Issue by IamAlta** [alextselegidis/easyappointments#796]
Hi,
We love this program and edited for scheduling pickups at a brick-n-mortar store. Kudos!

We need to change the date that the user can select from to be starting the next day. 
That is, no scheduling for the current day.
Where and how might I change that? 

Thank you!

**Comment by mirlipili** [comment]
In settings - business logic, you can adjust the "book advance timeout".
If you change it to 12h (in minutes), next availability will be 12 hours later. It's not perfect, but it might help

**Comment by alextselegidis** [comment]
Hello! 

Add an unavailable period event for the selected date and there will be no availability generated. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
