### ISSUE TITLE
Can you disable the possibility for providers to delete customers?

### ISSUE THREAD

**Issue by Answerx32** [alextselegidis/easyappointments#800]

**Comment by alextselegidis** [comment]
Hello! Change the roles table and set the appointments value for providers to 8. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
