### ISSUE TITLE
Allow to disable help popovers in backend pages

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#806]
It would be nice to add a setting option to disable help popovers (qtip2).

**Comment by alextselegidis** [comment]
Hello! 

I do not think that's necessary. 

Upgrading the tooltip lib though is something that will happen soon. 

There are more modern solutions out there to work with and they are pretty good. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
