### ISSUE TITLE
Maximum number of appointments in a schedule

### ISSUE THREAD

**Issue by Alexsanderjs** [alextselegidis/easyappointments#810]
Hello my name is Alex.
I loved your project, it helped me a lot even in my Wordpress. I believe that a function that manages to limit the number of vacancies for the same schedule. For example: on 07/17 at 15:00 PM the maximum number for appointments at that time is max 10 people.
Thank you! <3

**Comment by alextselegidis** [comment]
Hello!

You can set the number of accepted attendants for each service individually. 

The app will then only allow that many appointments to be booked with your providers. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
