### ISSUE TITLE
Hide index.php from url

### ISSUE THREAD

**Issue by Answerx32** [alextselegidis/easyappointments#811]
How can I hide index.php from urls?

**Comment by alextselegidis** [comment]
Hello!

Apache: 

https://www.edureka.co/blog/codeigniter-removing-index/

NGINX: 

https://thephpcode.com/blog/view/remove-indexphp-for-codeigniter-on-nginx.html#:~:text=php%20in%20application%2Fconfig%20path,use%20for%20your%20dynamic%20pages.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
