### ISSUE TITLE
Problem with links in legal content

### ISSUE THREAD

**Issue by dymitar** [alextselegidis/easyappointments#813]
There is a problem with links in legal content. The links are removed (the href part)
I think it is related to some CI_Input feature, but I cannot find the reason.
Tried with:

		$this->config->set_item('global_xss_filtering', false);
                $settings = json_decode($this->input->post('settings'), TRUE);
		$this->config->set_item('global_xss_filtering', true);

But it is not working

**Comment by dymitar** [comment]
It is working using this:
$settings = json_decode($this->input->post('settings', **false**), TRUE);

**Comment by alextselegidis** [comment]
Hello!

This is indeed an issue. It will be fixed for v1.4.0

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
