### ISSUE TITLE
Language popup cannot be closed when booking an appointment

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#815]
On the appointment booking page, if I click on the language button (to change the language of the page), the popup open's, but I cannot close it by clicking somewhere else in the page..

Same for this popup in backend pages too..

This is possible that all popups are affected !

**Comment by alextselegidis** [comment]
Done!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
