### ISSUE TITLE
Consent save error when booking an appointment

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#816]
If consent is active in the settings, I've get this error when validating customer data in the appointment booking process.

```
Error Number: 1292
Incorrect datetime value: '1592314098' for column 'created' at row 1
INSERT INTO `ea_consents` (`first_name`, `last_name`, `email`, `type`, `ip`, `created`, `modified`) VALUES ('fes', 'fes', 'faewyge@fe.dh', 'privacy-policy', '::1', 1592314098, 1592314098)
Filename: models/Consents_model.php
Line Number: 83
```

**Comment by alextselegidis** [comment]
Hello! 

That was really an issue on develop, it's fixed now. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
