### ISSUE TITLE
Select fields are no more disabled in patients/services backend forms

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#818]
For exemple, on the users page, timezone select is never disabled.

**Comment by alextselegidis** [comment]
Merged on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
