### ISSUE TITLE
Is support for RBAC Access desired?

### ISSUE THREAD

**Issue by hopeseekr** [alextselegidis/easyappointments#82]
Hi,

Do you want my contributed RBAC access for Calendaring systems?

I'm about to start a project that will allow Certain Users to see and/or modify Certain Providers calendars for Certain Services. 

Example:
- Secretary A:
  - Can view and manage appointments for only her Boss
  - Can view appointments for every lawyer in her Firm.
- Secretary B:
 - Can view and manage appoints for every lawyer in her Firm, except the CEO.
 - Can view appointments for Friend Lawyers at Firms B, C, and E.
- CEO 
 - Can view and manage appointments for literally everyone in Company A
 - Can view and mange contractors appointments at Companies B and E.

I'm going to use my own implementation of RBAC, licensed MIT.

**Comment by alextselegidis** [comment]
Do you thing there is an issue with the current role-system?
