### ISSUE TITLE
all employee schedules in a single vertical panel

### ISSUE THREAD

**Issue by certtech** [alextselegidis/easyappointments#821]
Good evening.

This is my first post. Sorry for any error in the place of posting this question / improvement.

It would be interesting to be able to see on the backend all employee schedules in a single vertical panel. It's possible?

Thank you for developing this technology tool.

Att. Paulo Lisboa.

**Comment by alextselegidis** [comment]
Hello! 

This is already possible with the table view. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
