### ISSUE TITLE
Adding an unavailable period from the backend calendar do not works

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#822]
PR #755 could helps to fix an error.

**Comment by alextselegidis** [comment]
Merged in develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
