### ISSUE TITLE
Bug with appointment details in client page

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#823]
When you go to the client page, select a client and then click on its appointments (`#customer-appointments`), `#appointment-details` display the informations. But if you click in an other appointment, the `#appointment-details` is not cleaned before display the new informations..

**Comment by alextselegidis** [comment]
Merged on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
