### ISSUE TITLE
Time Zone Conversion

### ISSUE THREAD

**Issue by Martinest04** [alextselegidis/easyappointments#828]
Hi, there is an issue with time conversion from Easy Calendar to the auto-generated appointment in the Google Calendar. I have my Google calendar set for GMT+2 and in the settings for Easy Calendar [Customize > Date & Time > Calendar localization] I also tried to set it for GMT+2 (no). However, when I create an appointment for 2 pm, it saves in my Google calendar as 4 pm. Then I tried to change the time zone to GMT+0 (en-GB), but it still saves a 2pm appointment in Easy Calendar to 4pm in my Google calendar. 

Is this a bug? And if not, how do I get the right time zone conversion so that it's not chronically scheduling my appointments 2 hours late in my Google calendar?

Thanks heaps, 
Martine

**Comment by john1361** [comment]
Hello Martinest04, you can solve it by adding to the beginning of the index.php the following line date_default_timezone_set('America/Los_Angeles'); // Use your own timezone string.
You can search the area here [https://www.php.net/manual/en/timezones.php](url)

**Comment by wvdvegt** [comment]
Maybe the patch in #826 might solve the issue.

**Comment by alextselegidis** [comment]
Hello @Martinest04! 

For aligning the timezone with your Google Calendar use the solution proposed by @john1361 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
