### ISSUE TITLE
Appointment confirmations not sent.

### ISSUE THREAD

**Issue by wvdvegt** [alextselegidis/easyappointments#829]
In **engine/Notifications/Email.php** there are two functions **sendAppointmentDetails** and **sendDeleteAppointment** that try to load a non-existing model called '**timezones_model**'. It seems to be called '**timezones**' in the develop branch, but it is already loaded by the framework.

So in both functions the lines:
`$framework->load->model('timezones_model');`
can be removed (or made conditional if the model has not been loaded yet).

**Comment by wvdvegt** [comment]
See the proposed patch for mail.php in #826

**Comment by iekor** [comment]
#848 My pull request corrects this

**Comment by alextselegidis** [comment]
Hello @wvdvegt! 

Thanks for mentioning this, this is a problem in the `develop` branch that will be fixed. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
