### ISSUE TITLE
Help Wanted: How to hide or remove Currency, Price & Duration

### ISSUE THREAD

**Issue by KyleL144** [alextselegidis/easyappointments#830]
Hey,

I am trying to hide or remove duration, price and currency of the backend and the booking page as I don't really need them.

Thanks in advance and any help appreciated.

**Comment by anderoy** [comment]
I had the same issue and I was able to get the price removed from the frontend by making the changes from  [this commit](https://github.com/alextselegidis/easyappointments/commit/2e9d8c963e9f0323a2b4764d442ffd2d2d87738d) to the assets/js/frontend_book.js file.
