### ISSUE TITLE
Differentiated working days

### ISSUE THREAD

**Issue by Lasse-Niller** [alextselegidis/easyappointments#832]
Hey.
Is it possible to have 
Employee A works monday 1200-1300 and thursday 1600-1700 in week 1, wednesday 1100-1200 in week 2 and so on. So every weeks is unique?

Best,
Lasse

**Comment by alextselegidis** [comment]
Hello @Lasse-Niller! 

This is not possible right now but in the future the app will support arbitrary working plans that do not follow the same schema. 

Starting from v1.4.0 you will be able to define custom working periods that are outside the normal working plan. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
Seems linked with #1125

**Comment by alextselegidis** [comment]
Right @popod, the two tickets seem to be relevant

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
