### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ahmadsyafiqkamil** [alextselegidis/easyappointments#835]
hello, i dont know how to solve this error

![image](https://user-images.githubusercontent.com/5411221/86502612-a3af1480-bdd7-11ea-9dac-aaff17ab50c6.png)

**Comment by alextselegidis** [comment]
Hello @ahmadsyafiqkamil! 

Have you made any adjustments to the original code base? 

This error shouldn't normally happen. 

Which version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by wvdvegt** [comment]
Try to use the F12 debugging tools or fiddler to catch the 'json'. The error suggests a html error is returned instead of json.
