### ISSUE TITLE
ea_migrations table does not have any primary key

### ISSUE THREAD

**Issue by rgtzths** [alextselegidis/easyappointments#837]
So, I'm trying to create a high availability MySQL Cluster to deploy with the application.

But when using MySQL Group Replication, I need a primary key for the tables.

Can you help me out with this?
Just need to have this done and the application will be able to be deployed.

When I'm finished I pretend to leave the docker-compose for a swarm available, so if you could help me out. 
I would appreciate it.

**Comment by alextselegidis** [comment]
Hello @rgtzths! 

The `ea_migrations` table is actually based on the CodeIgniter v3 framework, which includes the code required for the migrations to work. 

You can simply mark the `version` field as primary key and you will therefore have no problems with your hosting environment. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
