### ISSUE TITLE
Query strings are removed.

### ISSUE THREAD

**Issue by wvdvegt** [alextselegidis/easyappointments#838]
In our setup we need to use easyappointments as a tool returning both the appointment and an identifier for the user it is passed when appointments are to be made. For this we need the query string easyappointments is passed preserved and to be returned as well.

```
diff --git a/assets/js/frontend_book_api.js b/assets/js/frontend_book_api.js
index dc2ef92c..b04573a5 100755
--- a/assets/js/frontend_book_api.js
+++ b/assets/js/frontend_book_api.js
@@ -225,7 +225,7 @@ window.FrontendBookApi = window.FrontendBookApi || {};
                 }
 
                 window.location.href = GlobalVariables.baseUrl
-                    + '/index.php/appointments/book_success/' + response.appointment_hash;
+                    + '/index.php/appointments/book_success/' + response.appointment_hash + window.location.search;
             })
             .fail(function (jqxhr, textStatus, errorThrown) {
                 $('.captcha-title small').trigger('click');
```

**Comment by alextselegidis** [comment]
Hello @wvdvegt! 

Thanks for providing the information but it seems that this change applies to your own use case. 

I will close the ticket for now, but feel free to come back with a solution that can benefit the application. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
