### ISSUE TITLE
Provider is missing on appointment modal opened after a click on the link sent with the provider email confirmation

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#839]
When an appointment is booked, the provider receive an email with `$provider_link` (route: backend/index/<appointment_hash>).

When we click on this link, the backend calendar page is displayed and the appointment modal is automatically opened with the appointment informations.

But in this modal, providers list is empty ! This seems to be because the `$('#select-service').change()` events is not yet available when we call it from `backend_calendar_default_view.js` !

**Comment by alextselegidis** [comment]
Hello @popod!

Thanks for reporting the issue. 

I will check this before v1.4.0 is released and make sure this does not happen. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
