### ISSUE TITLE
Developer Installation

### ISSUE THREAD

**Issue by psicote** [alextselegidis/easyappointments#84]
We can have some instruction how to install the 1.1 version?
For example
Download the file
unzip it
use composer to exstract dependency
create a DB
change config.ini

**Comment by alextselegidis** [comment]
Hi, you will get complete instructions once the version is ready and published. Currently it's under development and some things might change until the release. 

Actually the released file will already contain the Composer dependencies so that users do not have to do this on their own.

**Comment by psicote** [comment]
I have been using the program for more than two years and I would like to
give my contribution. Why I don't have an installation page after
downloaded the program and extracted the dependency with composer?
I need to do something else?
Sam

Psico-therapy
London UK
Puglia IT
On-line
www.psicote.com
07770617364
3397437299

**Comment by alextselegidis** [comment]
Hey Sam,

check the apache error logs for more info. I cannot understand what your current issue is.

**Comment by psicote** [comment]
[10-Nov-2015 09:52:45 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/easyappointments-master/src/config.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/easyappointments-master/src/index.php on line
14
[10-Nov-2015 09:52:45 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/easyappointments-master/src/config.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/easyappointments-master/src/index.php on line
14
[10-Nov-2015 09:59:01 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/easyappointments-master/src/config.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/easyappointments-master/src/index.php on line
14
[10-Nov-2015 09:59:01 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/easyappointments-master/src/config.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/easyappointments-master/src/index.php on line
14
[10-Nov-2015 09:59:08 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/easyappointments-master/src/config.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/easyappointments-master/src/index.php on line
14
[10-Nov-2015 09:59:08 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/easyappointments-master/src/config.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/easyappointments-master/src/index.php on line
14
[12-Nov-2015 09:57:09 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/config.php): failed to open
stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 14
[12-Nov-2015 09:57:09 UTC] PHP Fatal error:  require_once(): Failed opening
required '/home/psicote/public_html/sam/config.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 14
[12-Nov-2015 10:09:21 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:09:21 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:00 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:00 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:03 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:03 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:44 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:44 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:45 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:45 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:45 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:45 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:46 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:46 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:46 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:46 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:46 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:10:46 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:11:08 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 10:11:08 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 11:41:08 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 11:41:08 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 11:41:25 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 11:41:25 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 12:03:52 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 12:03:52 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 12:15:08 UTC] PHP Warning:
 require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
failed to open stream: No such file or directory in
/home/psicote/public_html/sam/index.php on line 27
[12-Nov-2015 12:15:08 UTC] PHP Fatal error:  require_once(): Failed opening
required
'/home/psicote/public_html/sam/application/third_party/autoload.php'
(include_path='.:/usr/lib/php:/usr/local/lib/php') in
/home/psicote/public_html/sam/index.php on line 27

On Thu, Nov 12, 2015 at 5:56 PM, Alex Tselegidis <notifications@github.com>
wrote:

> Hey Sam,
>
> check the apache error logs for more info. I cannot understand what your
> current issue is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alextselegidis/easyappointments/issues/84#issuecomment-156183840>
> .
>



-- 
Psico-therapy
East London UK
Puglia IT
www.psicote.com
07770617364
3397437299

**Comment by psicote** [comment]
[12-Nov-2015 15:01:51 UTC] PHP Fatal error:  Class 'Config' not found in
/home/psicote/public_html/sam/easyappointments-master/application/config/config.php
on line 19

On Fri, Nov 13, 2015 at 9:31 AM, Psico Therapy <info@psicote.com> wrote:

> [10-Nov-2015 09:52:45 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/easyappointments-master/src/config.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/easyappointments-master/src/index.php on line
> 14
> [10-Nov-2015 09:52:45 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/easyappointments-master/src/config.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/easyappointments-master/src/index.php on line
> 14
> [10-Nov-2015 09:59:01 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/easyappointments-master/src/config.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/easyappointments-master/src/index.php on line
> 14
> [10-Nov-2015 09:59:01 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/easyappointments-master/src/config.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/easyappointments-master/src/index.php on line
> 14
> [10-Nov-2015 09:59:08 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/easyappointments-master/src/config.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/easyappointments-master/src/index.php on line
> 14
> [10-Nov-2015 09:59:08 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/easyappointments-master/src/config.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/easyappointments-master/src/index.php on line
> 14
> [12-Nov-2015 09:57:09 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/config.php): failed to open
> stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 14
> [12-Nov-2015 09:57:09 UTC] PHP Fatal error:  require_once(): Failed
> opening required '/home/psicote/public_html/sam/config.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 14
> [12-Nov-2015 10:09:21 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:09:21 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:00 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:00 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:03 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:03 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:44 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:44 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:45 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:45 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:45 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:45 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:46 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:46 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:46 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:46 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:46 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:10:46 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:11:08 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 10:11:08 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 11:41:08 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 11:41:08 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 11:41:25 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 11:41:25 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 12:03:52 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 12:03:52 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 12:15:08 UTC] PHP Warning:
>  require_once(/home/psicote/public_html/sam/application/third_party/autoload.php):
> failed to open stream: No such file or directory in
> /home/psicote/public_html/sam/index.php on line 27
> [12-Nov-2015 12:15:08 UTC] PHP Fatal error:  require_once(): Failed
> opening required
> '/home/psicote/public_html/sam/application/third_party/autoload.php'
> (include_path='.:/usr/lib/php:/usr/local/lib/php') in
> /home/psicote/public_html/sam/index.php on line 27
>
> On Thu, Nov 12, 2015 at 5:56 PM, Alex Tselegidis <notifications@github.com
> > wrote:
>
>> Hey Sam,
>>
>> check the apache error logs for more info. I cannot understand what your
>> current issue is.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/alextselegidis/easyappointments/issues/84#issuecomment-156183840>
>> .
>>
>
>
>
> --
> Psico-therapy
> East London UK
> Puglia IT
> www.psicote.com
> 07770617364
> 3397437299
>



-- 
Psico-therapy
East London UK
Puglia IT
www.psicote.com
07770617364
3397437299
