### ISSUE TITLE
[BUG] Start/end datetime are not correctly initialized on Safari when the appointment modal is opened after a click in the backend calendar

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#840]
With Safari: after a click on the backend calendar, the new appointment modal opens. In this modal, `start_datetime` and `end_datetime` are not correctly initialized..

**Comment by alextselegidis** [comment]
Hello @popod 

Is the problem related to Safari or IE? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
The problem appears on Safari (tested on latest version). I don't know about IE.

**Comment by alextselegidis** [comment]
I check Safari and this is indeed an issue. 

I just merged your PR to develop, thanks!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
