### ISSUE TITLE
add picture when register appoinment

### ISSUE THREAD

**Issue by ahmadsyafiqkamil** [alextselegidis/easyappointments#842]
i want add some picture/files when register appoinment

**Comment by alextselegidis** [comment]
Hello @ahmadsyafiqkamil 

This is a custom request that I cannot add to the original app. 

Not with this form at least. 

Consider making a new ticket with more generic purpose fields or opt in for a customized build. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
