### ISSUE TITLE
calendar issue

### ISSUE THREAD

**Issue by div4d** [alextselegidis/easyappointments#843]
Hi all,
there is an issue in the calendar view of my installation of easyappointments. 
Basically, for some services, I can't see the scheduling of the current week, but if I move forward to the next one, voilà, everything is back to normal. 
I had this issue before & resolved it getting rid of everything and reinstalling easyappointments. Of course I had to manually copy back every appointment already booked. Now I wouldn't do it again (it's kind of tedious and a waste of time) I would prefer to figure the problem out and to solve it.
Attached the screenshot showing the problem I have.
Please do ask if I was not clear or if you need additional info to understand the problem.
Many thanks :) 

![screen1](https://user-images.githubusercontent.com/7011711/86964729-73ac9c00-c15e-11ea-994d-f27ee74c28f0.png)
![screen2](https://user-images.githubusercontent.com/7011711/86964743-79a27d00-c15e-11ea-93c5-decf940d121c.png)

**Comment by alextselegidis** [comment]
Hello @div4d 

From your description I can tell that there is a javascript error for the week that you do not get any result, but unfortunately I cannot tell exactly what it is. 

Please open the browser dev tools and look for the console for more information and post them here. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Close due to inactivity. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
