### ISSUE TITLE
Double booking with "Any Provider"-option (cf. bug #31)

### ISSUE THREAD

**Issue by FRB1994** [alextselegidis/easyappointments#845]
Dear Alex,

first of all thank you for your wonderful software ! It was and still is a big help for us (a small municipial public administration) in times of Corona. However, we still encounter the described double-booking bug with the "Any Provider" functionality both within our EA-installation and when simultaneously booking from two browser instances within the https://demo.easyappointments.org/ demo-version. Due to our organisational structure, we cannot allow customers to choose their appointment based on the respective provider/desk, but only based on the respective service (which is why we cannot switch from the "Any Provider"-preselection. Due to the large number of customers, we have around 40 double bookings/week.
Is there any recommended quick fix for this problem ? 

Best regards and thank you again for providing such a useful, accessible  and thought-out solution via Open Source ! =)

_Originally posted by @FRB1994 in https://github.com/alextselegidis/easyappointments/issues/31#issuecomment-657436763_

**Comment by alextselegidis** [comment]
Hello @FRB1994 

Do you get double bookings for a service whose attendants number value is **1**? 

Can you share your service and provider information? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by FRB1994** [comment]
Dear Alex,

thank you very much for your answer ! Yes, I get double bookings for multiple services, whose attendant number values are set to 1 (cf. one of multiple examples in the Screenshots).  I have multiple providers working on the same multiple services (with the "Any Provider"-function as standard, so that customers do not have to choose or see any of the providers).  Maybe the problem could result from this ? However, you have maybe already found the solution to the problem - in contrast to a month ago I can no longer replicate my initial error on  https://demo.easyappointments.org/. Did you change anything, which could relate to this ?

![Provider](https://user-images.githubusercontent.com/20640802/89431740-98d20180-d740-11ea-953b-efbb41ea2a4b.png)
![Service](https://user-images.githubusercontent.com/20640802/89431743-996a9800-d740-11ea-899d-b1eef78a8778.png)
![MultipleBookings](https://user-images.githubusercontent.com/20640802/89431745-9a032e80-d740-11ea-91eb-036171ec705f.png)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for providing debug information, that's really helpful. 

Can you please confirm that you can reproduce this with the codebase from the master branch? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by wngr** [comment]
Hey!
I'm seeing similar behaviour. Especially weird is, that given another `Cookie` / `csrfToken`, I get different responses for the same provider and same service:
```
➜  easyappointments git:(master) ✗ curl 'https://REDACTED/index.php/appointments/ajax_get_available_hours' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0' -H 'Accept: */*' -H 'Accept-Language: en,en-US;q=0.7,de;q=0.3' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://REDACTED' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://REDACTED/index.php?provider=3&service=3' -H 'Cookie: csrfCookie=49c066bfd51d6f8a10c91a43fdf09770; ea_session=d5d41e3e68f72ce5ae42b07a41fa8aae3f79a8c3' -H 'Sec-GPC: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: Trailers' --data-raw 'csrfToken=49c066bfd51d6f8a10c91a43fdf09770&service_id=3&provider_id=3&selected_date=2021-01-23&service_duration=20&manage_mode=false&appointment_id='
["09:00","09:15","09:30","09:45","10:00","10:15","10:30","10:45","11:00","11:15","11:30","11:45","12:00","12:15","12:30","12:45","13:00","13:15","13:30","13:45","14:00","14:15","14:30","14:45","15:00","15:15","15:30","15:45","16:00","16:15","16:30","16:45","17:00","17:15","17:30"]%                                                                                                
➜  easyappointments git:(master) ✗ curl 'https://REDACTED/index.php/appointments/ajax_get_available_hours' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0' -H 'Accept: */*' -H 'Accept-Language: en,en-US;q=0.7,de;q=0.3' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://REDACTED' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://REDACTED/' -H 'Cookie: csrfCookie=4901db9bd15373155a1de10229867ef9; ea_session=17621d001aae48bdf98a09a9ad24fd53ea6018f3' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: Trailers' --data-raw 'csrfToken=4901db9bd15373155a1de10229867ef9&service_id=3&provider_id=3&selected_date=2021-01-23&service_duration=20&manage_mode=false&appointment_id='
["09:50","10:05","10:20","10:35","10:50","11:05","11:20","11:35","11:50","12:05","12:20","12:35","12:50","13:05","13:20","13:35","13:50","14:05","14:20","14:35","14:50","15:05","15:20","15:35","15:50","16:05","16:20","16:35","16:50","17:05","17:20","17:35"]%
```

**Comment by alextselegidis** [comment]
@wngr Different responses may have to do with the selected user timezone, as availability get's converted on the fly. 

The final v1.4.0 had some availability fixes and improvements that should block cases like the one described in this ticket. 

I will therefore close it as not applicable. 

Feel free to open a new one with reproduction steps, based on the latest stable release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
