### ISSUE TITLE
Select Service error

### ISSUE THREAD

**Issue by efiopops** [alextselegidis/easyappointments#847]
https://annarz.com/zapyt/

When i try to change service always get error.
![image](https://user-images.githubusercontent.com/48172415/87653265-f7b5e380-c75d-11ea-8654-c86177d88a7e.png)

How can i fix that?

**Comment by alextselegidis** [comment]
Hello @efiopops 

Can you please post the working plans of your provider user?

The error is related to that. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by efiopops** [comment]
> Hello @efiopops
> 
> Can you please post the working plans of your provider user?
> 
> The error is related to that.
> 
> ![](https://camo.githubusercontent.com/8cff9d0a6daf9fd5c73786aa4e74f327b5a5ac9b/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Contact me in person!](https://alextselegidis.com)

Thank you <3
