### ISSUE TITLE
JsPane scrolling not working

### ISSUE THREAD

**Issue by Back2TheFuture** [alextselegidis/easyappointments#85]
It seems that the page Customer and perhaps also in the other where this container jspane is displayed happens this: if I have many clients you activate the scroll bar but apparently although I try to make scrolling the items in the container remain fixed. I do not know what causes this bug, but I think that such a thing has already been settled. If so, you can show the changes to be done to fix?

**Comment by alextselegidis** [comment]
I cannot reproduce :/
