### ISSUE TITLE
Email sends on appointment cancelation but not on creation

### ISSUE THREAD

**Issue by IgrutinovicL** [alextselegidis/easyappointments#857]
Email sends normally when i manually delete the appointment from the company but not when i create an appointment.

I didn't manage to find this issue posted here so sorry if it already existed.

I looked into every file and it seems like the function is not being called or something.

I tried for days but to no avail. If you have any ideas i might try please tell me.

<3

**Comment by wvdvegt** [comment]
Did you check #848 and #829 ?

**Comment by IgrutinovicL** [comment]
> Did you check #848 and #829 ?

Those lines of code do not exist in my code. I only have this:

`protected function _set_date()
	{
		$timezone = date('Z');
		$operator = ($timezone[0] === '-') ? '-' : '+';
		$timezone = abs($timezone);
		$timezone = floor($timezone/3600) * 100 + ($timezone % 3600) / 60;

		return sprintf('%s %s%04d', date('D, j M Y H:i:s'), $operator, $timezone);
	}`

**Comment by wvdvegt** [comment]
The patch was for the develop branch and a few commit back.

**Comment by wvdvegt** [comment]
The file is engine/Notifications/Email.php (and not src/system/libraries/Email.php)

**Comment by iekor** [comment]
What branch are you using?

**Comment by IgrutinovicL** [comment]
The newest one.

**Comment by iekor** [comment]
Master or develop?

**Comment by IgrutinovicL** [comment]
Could be master actually. Should I try develop?

**Comment by iekor** [comment]
The fix for this that was mentioned earlier is from the develop branch so
using it in master wouldn't help and could possibly cause more problems.

Idk if you can switch to the develop branch without doing a complete wipe
then fresh install. Also you'll have to install dependencies and build the
assets if you know how to do that then using the develop branch could help.

**Comment by IgrutinovicL** [comment]
Thanks, i didn't even check the branches. I will move to the dev branch since the project is still in development.
