### ISSUE TITLE
InnoDB: Cannot allocate memory for the buffer pool

### ISSUE THREAD

**Issue by jaindamini1111** [alextselegidis/easyappointments#860]
There is problem in loading the page.

Had created a mysql database. Checked the logs and found this:

> Wampserver trace report -
File created by Wampserver install
2020-07-28T07:03:55.832449Z 0 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
2020-07-28T07:03:55.837215Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2020-07-28T07:03:55.890792Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
2020-07-28T07:03:55.892712Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2020-07-28T07:03:55.895151Z 0 [ERROR] Failed to initialize builtin plugins.
2020-07-28T07:03:55.898287Z 0 [ERROR] Aborting

> 2020-07-28T07:04:27.496784Z 0 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
> 2020-07-28T07:04:27.499138Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
> 2020-07-28T07:04:27.502186Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
> 2020-07-28T07:04:27.503094Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2020-07-28T07:04:27.504097Z 0 [ERROR] Failed to initialize builtin plugins.
> 2020-07-28T07:04:27.505028Z 0 [ERROR] Aborting
> 
> 2020-07-28T07:19:44.095132Z 0 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
> 2020-07-28T07:19:44.173182Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
> 2020-07-28T07:19:44.206726Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
> 2020-07-28T07:19:44.208743Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2020-07-28T07:19:44.210791Z 0 [ERROR] Failed to initialize builtin plugins.
> 2020-07-28T07:19:44.212490Z 0 [ERROR] Aborting
> 
> 2020-07-28T07:32:13.516764Z 0 [Warning] InnoDB: Resizing redo log from 2*3072 to 2*16384 pages, LSN=2632843
> 2020-07-28T07:32:14.139386Z 0 [Warning] InnoDB: Starting to delete and rewrite log files.
>  100 200
>  100 200
> 2020-07-28T07:32:44.665833Z 0 [Warning] InnoDB: New log files created, LSN=2632843
> 

**OS**: Windows 10
using WAMP

**Comment by alextselegidis** [comment]
Hello @jaindamini1111 

This is a server specific issue. 

See here for more information: 

https://stackoverflow.com/a/61744085/1718162

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
