### ISSUE TITLE
Cannot config the mailer

### ISSUE THREAD

**Issue by Jairgo** [alextselegidis/easyappointments#861]
I'm having this error, any help?

**Email could not been sent. Mailer Error (Line 179): Could not instantiate mail function.**

**Comment by alextselegidis** [comment]
Hello @Jairgo 

The server mail configuration is invalid and emails cannot be sent. 

If you do not have a PHP configured to send emails you can disable the customer and provider notifications from the backend section. 

If you have an SMTP server, you can add its credentials in the `application/config/email.php` file. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
