### ISSUE TITLE
Question regarding Google calendar sync

### ISSUE THREAD

**Issue by RaviVinnakota** [alextselegidis/easyappointments#865]
Hi,

Let's say I have 1000 users in the application, they are providers e.g., doctors. All of them have separate mail accounts. Is it possible to sync each users calendar to his own mail account? If so, could you please let me know how?

Thanks,
Ravi.

**Comment by alextselegidis** [comment]
Hello @RaviVinnakota 

Yes this is possible with the Google Calendar synchronization feature. 

You can basically connect each provider to a separate Google account and have them sync their events between their accounts. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
