### ISSUE TITLE
delete all customer info giving this error

### ISSUE THREAD

**Issue by prdatta** [alextselegidis/easyappointments#867]
It opens a window saying 'Unexpected issues'
The operation could not complete due to unexpected issues.

Customer ID could not be found, please reload the page and try again.

I used the link given in the confirmation email.

**Comment by alextselegidis** [comment]
Hello @prdatta 

Can you please check your database and make sure the customer, appointment, provider and service records exist? 

It seems like there are missing data, which means that we first need to make sure that we do not miss any records. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by prdatta** [comment]
" make sure that we do not miss any records",

yes. all these records exist. I get confirmation email with a link and a hash no and using the same link to modify/delete appointment. modify/delete specific appt works. But, not the delete all info button in red.

**Comment by prdatta** [comment]
Is the page rendered correctly? This is a snippet of the page. While 'cancel' button has a hash in the link and a method to POST, 'detele all' has nothing. pardon me I'm a novice.

   <div id="cancel-appointment-frame" class="booking-header-bar row">
                    <div class="col-xs-12 col-sm-10">
                        <p>Press the "Cancel" button to remove the appointment from the company schedule.</p>
                    </div>
                    <div class="col-xs-12 col-sm-2">
                        <form id="cancel-appointment-form" method="post"
                              action="https://localhost/easyappt132/index.php/appointments/cancel/a49a6b335d43a6ea014d675f01ece43d">
                            <input type="hidden" name="csrfToken" value="60de2a790473a450686e17e79d97cfc1" />
                            <textarea name="cancel_reason" style="display:none"></textarea>
                            <button id="cancel-appointment" class="btn btn-default btn-sm">Cancel</button>
                        </form>
                    </div>
                </div>
                <div class="booking-header-bar row">
                    <div class="col-xs-12 col-sm-10">
                        <p>Delete all personal information from the system.</p>
                    </div>
                    <div class="col-xs-12 col-sm-2">
                        <button id="delete-personal-information" class="btn btn-danger btn-sm">Delete</button>
                    </div>
                </div>

**Comment by alextselegidis** [comment]
The page rendered correctly, that button does not have a URL because it works with javascript and AJAX. 

Please share some debug logs if available. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by derekpovah** [comment]
If we can't find the ID of the user in the DB, isn't it safe to assume the user in question has already been deleted? We should gracefully handle the error is this case, right?

**Comment by alextselegidis** [comment]
@derekpovah Yeah, one could safely assume that. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I tried again with the latest development state and get not problem. 

The only way this could be an issue is if the customer uses the link but before hitting the delete a backend user removes the user from the backend. 

The app would then try to remove the user again but of course he won't be found in the database and thus produce the error. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
