### ISSUE TITLE
Impossible to add "extra working day" from the backend

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#868]
With the develop branch of 1.4.0.

The end date input seems to be misformated !

**Comment by alextselegidis** [comment]
Hello!

That is true, there are some bugs in the integration along with some improvements that need to be implemented. 

I'm still working on it, thanks for posting!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
