### ISSUE TITLE
Backend UI is broken

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#869]
With the develop branch of 1.4.0.

![Capture d’écran 2020-08-17 à 12 12 56](https://user-images.githubusercontent.com/3807312/90385189-09ebb000-e083-11ea-8acd-e5315087dd0c.png)

**Comment by prdatta** [comment]
True, even for a booked appointment, the buttons like 'close', 'edit' not working at all.

**Comment by alextselegidis** [comment]
Hello! 

These are all fixed now. 

Bear in mind that develop currently has a work in progress state. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
