### ISSUE TITLE
Timezone in email to clients is incorrectly the provider TZ.

### ISSUE THREAD

**Issue by wvdvegt** [alextselegidis/easyappointments#872]
In the develop branch (c437c65), the notification e-mail shows the provider TZ (instead of the customer's 's one).

In 'engine\Notifications\Email.php' line 127 should read:

`    $appointment_timezone = $timezones[$customer['timezone']];`

so it matches the customer's time.

**Comment by alextselegidis** [comment]
Hello!

The displayed date is the provider's date. 

If the date gets converted then we should have used the customer's timezone ;) 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
