### ISSUE TITLE
show the total cost of the service provided in the management panel

### ISSUE THREAD

**Issue by Ajanso** [alextselegidis/easyappointments#873]
Can we show the total cost of the services provided in the management panel? Example: 5 appointments have been made and the total amount of them is 50 $. The purpose here is to analyze how much money has been earned.

**Comment by daletnt** [comment]
I would like this to

**Comment by alextselegidis** [comment]
Hello! 

Statistics will be part of a future Easy!Appointments release.

This will be a more sophisticated page or dashboard demonstrating the current booking data.  

For now I will have to close this ticket as I cannot yet tell when it will be added to the app. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
