### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by koboy55** [alextselegidis/easyappointments#874]
Hi, 
I managed to do this also  by adding in db a new column named 'COLOR' which value is inserted once the appointment is created or updated(When appointment is created with status pendding a color blue will be inserted in db, when we update the appointment to status 'Arrived', color green is inserted etc..) The color then is loaded in each calendar event and all appointments are dispalyed according to them status, but..
Let's say I update an appointment from Pendding to Arrived and press save then I click insert new Appointmnt, the status of my new appointment will be auto completed to Arrived, even if I create a new  appointment. This filled is keeped from the previouse action each time I create new appointment.
Please help!! How  I do this field to reset? In HTML the pendding status is selected but is not working :(

_Originally posted by @lucianpp in https://github.com/alextselegidis/easyappointments/issues/59#issuecomment-147233430_

**Comment by daletnt** [comment]
following

**Comment by alextselegidis** [comment]
Hello! 

There is a resetAppointmentDialog in backend_calendar_appointments_modal.js 

Add your reset logic in there and the field will be get back to its initial state every time you try to create a new appt or edit a new one. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
