### ISSUE TITLE
Next Button in step 2 obscured by Slots

### ISSUE THREAD

**Issue by wvdvegt** [alextselegidis/easyappointments#879]
With a wider browser the Back/Next buttons in the 2nd screen (slot selection) seem to be obscured by the slots and not clickable. 

Making the browser less wide moves the two buttons underneath the slots where they are clickable as expected.

Not working Next button:

![image](https://user-images.githubusercontent.com/1768983/92103261-fad56380-eddf-11ea-8abe-edd641cc2603.png)

Working Next button:
![image](https://user-images.githubusercontent.com/1768983/92103322-1476ab00-ede0-11ea-9ea0-6474148dc616.png)

**Comment by alextselegidis** [comment]
Hello!

Thanks for checking this early enough but the available hours got changed already. 

Pull the latest changes to see the difference. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
