### ISSUE TITLE
Nothing displays after pushing "Refresh" button

### ISSUE THREAD

**Issue by IOpaXou** [alextselegidis/easyappointments#88]
There are a lot of appointments in database and all of them take in consideration during booking on the client side (it displayed as reserved), but nothing could be seen in admin menu "Appointments" part. It's not a problem of picking correct date. The version of the plugin is 1.60. Compatibility mode is on.
On the version 1.50 had the same problem with the exception that message "Loading table" was always on the screen.

**Comment by alextselegidis** [comment]
Hello, 

I cannot really understand the problem. Which plugin are you referring to?
