### ISSUE TITLE
easyappointments with nginx, php and mariadb doesn't work

### ISSUE THREAD

**Issue by Edgard21031969** [alextselegidis/easyappointments#882]
Hello,
I tried to install version 1.3.2 of easyappointment on ubuntu 16.04 with ngins, php and mariadb but it doesn't work.

My config.php is:
sudo nano /var/www/html/easyappointments/config.php

const BASE_URL      = 'http://192.168.43.154/easyappointments';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = FALSE;

    // ------------------------------------------------------------------------
    // DATABASE SETTINGS
    // ------------------------------------------------------------------------
    const DB_HOST       = 'localhost';
    const DB_NAME       = 'easyappointmentsdb';
    const DB_USERNAME   = 'adminea';
    const DB_PASSWORD   = 'passer1234';

My easyappointments.conf is:
sudo nano /etc/nginx/sites-available/easyappointments.conf

server {
    listen 80;
    listen [::]:80;
    root /var/www/html/easyappointments;
    index index.php index.html index.htm index.nginx-debian.html;
    server_name 192.168.43.154;

    location /appointments {
        try_files $uri $uri/ /appointments/index.php;
    }

}

I started all services 
sudo ln -s /etc/nginx/sites-available/easyappointments.conf /etc/nginx/sites-enabled/
sudo systemctl start php7.1-fpm
systemctl enable php7.1-fpm
sudo systemctl reload nginx
sudo systemctl enable nginx.service
sudo systemctl restart nginx.service
sudo systemctl status nginx.service 

The status is ok, But if I connect on http;//192.168.43.154/easyappointments , I have following message error:

404 Not Found nginx/1.10.3 (Ubuntu)

The error is the same with the following configuration
server {
	listen 80;
	root /var/www/html/easyappointments;
	index index.php index.html index.htm index.nginx-debian.html;
	server_name 192.168.43.154;

	location / {
	try_files $uri $uri/ =404;
	}

	location ~ [^/]\.php(/|$) {
	include snippets/fastcgi-php.conf;
	fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location ~ /\.ht {
	deny all;
	}
}

Please help.

**Comment by alextselegidis** [comment]
Hello!

It seems that NGINX cannot serve your files correctly. 

Please try this recipe: 

https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Edgard21031969** [comment]
Hello,

My problem is not solve.
After making a change in the configuration, if I try to connect on http://http://192.168.43.154/ea, I have error message : 502 Bad Gateway nginx/1.10.3 (Ubuntu)
I didn't use Mysql but I used Mariadb, did easyappointments support MariadB? Just because in the documentation, I see only MySQL.

My configuration is
a) for nginx: 
sudo nano /etc/nginx/sites-available/ea

server {
        server_name 192.168.43.154;

        root /var/www/html/ea;
        index index.html index.php;

        # set expiration of assets to MAX for caching
        location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
                expires max;
                log_not_found off;
        }

        location / {
                # Check if a file or directory index file exists, else route it to index.php.
                try_files $uri $uri/ /index.php;
        }

        location ~* \.php$ {
                fastcgi_pass 127.0.0.1:9000;
                include fastcgi.conf;
        }
}

b) for php
cd /var/www/html/ea
sudo cp config-sample.php config.php

sudo nano /var/www/html/ea/config.php

    const BASE_URL      = 'http://192.168.43.154/ea';
    const LANGUAGE      = 'english';
    const DEBUG_MODE    = FALSE;

    // ------------------------------------------------------------------------
    // DATABASE SETTINGS
    // ------------------------------------------------------------------------

    const DB_HOST       = 'localhost';
    const DB_NAME       = 'easyapp_db';
    const DB_USERNAME   = 'adminea';
    const DB_PASSWORD   = 'passer1234';

I already configured easyappointment with Apache, PHP and MySQL successfull.
Now I try with Nginx, PHP, Maraidb unsuccessfull.

Please some help

**Comment by alextselegidis** [comment]
Dear @Edgard21031969 

As I already mentioned this is most likely problem with the NGINX. 

Unfortunately I cannot tell exactly why it cannot connect to PHP without having access to the server. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by timepigeon** [comment]
Seems nginx has trouble with the rewrite structure of easyappointments, this did the trick for me: https://github.com/alextselegidis/easyappointments/issues/294#issuecomment-499176343 (remember to adjust the try_files path to your own subdirectory scheme). 

Maybe it should be documented somewhere as a potential error resolution for nginx.
