### ISSUE TITLE
[BUG] Appointment date is wrongly changed to today in some case !

### ISSUE THREAD

**Issue by popod** [alextselegidis/easyappointments#883]
This bug appears with v1.3.2 or v1.4.0-beta !

When the appointment modal is automatically opened with this url `/backend/index/<appointment hash>`, if the modal is closed by using the "save" button without any changes, the appointment date is wrongly updated to the current date !

**Comment by alextselegidis** [comment]
Thanks for posting!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by popod** [comment]
@alextselegidis as you merged my PR which fix this bug, I think that you could close this issue.
