### ISSUE TITLE
Any provider issue

### ISSUE THREAD

**Issue by VijayakumarSVk** [alextselegidis/easyappointments#885]
![image](https://user-images.githubusercontent.com/23375379/93124382-22350600-f6e7-11ea-90d4-2e9ceff86dc6.png)

Hi alex,
I selected any provider and while confirming appointment its showing above error.

note : i have provider and selected available appointment time.

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting this. 

I confirm that this is a bug with the development build. 

I will provide a fix for this soon. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
