### ISSUE TITLE
Extra working day - how to modify for non-administrators

### ISSUE THREAD

**Issue by philjak** [alextselegidis/easyappointments#888]
Hello everyone,

we have the following use-case: We want to schedule appointments but rather than assuming the provider is available from 9 to 5, we want to go the other way round. We want to define slots where a booking can happen. From what I saw, the best approach is to deactivate all days in the provider's working schedule and use "extra working days".

Regardless of the fact, that if a provider creates a "extra working day" through the calendar, the it's currently not working because the time is not stored correctly (always 00:00 to 00:00: `{"2020-09-19":{"start":"00:00","end":"00:00","breaks":[]}}`), I'm wondering how a provider could modify those extra days. It's working in the backend but only for administrators.

I tested it with the latest develop commit (1.4.0-dev)

Thanks,
philjak

**Comment by alextselegidis** [comment]
Hello!

This is a current development bug, but it will be fixed before the release v1.4.0 

Update your installation once the release is out (within September 2020). 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
