### ISSUE TITLE
v1.4.0 develop branch - Google Sync Error 400: invalid_request Missing required parameter: scope

### ISSUE THREAD

**Issue by angela-d** [alextselegidis/easyappointments#890]
PHP 7.4.10

v1.4.0 develop 

While using v1.3.2 this error message did not appear, you were able to log in and get to the consent screen.

I'm not seeing any errors in the Google Developer Console, so the request doesn't appear to make it out of Easy Appointments.
`storage/logs` has nothing of interest.

In `config.php` all Google constants are populated and **GOOGLE_SYNC_FEATURE** is set to `TRUE`

The "scope" appears to be in `./application/views/appointments/book_success.php` as well as vendor files:
```text
./vendor/google/apiclient/docs/oauth-server.md:6.  In the **One or More API Scopes** field enter the list of scopes that your application should be granted access to. For example, if your application needs domain-wide access to the Google Drive API and the Google Calendar API, enter: https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/calendar.
./vendor/google/apiclient-services/src/Google/Service/Calendar.php:      "https://www.googleapis.com/auth/calendar";
./vendor/google/apiclient-services/src/Google/Service/Calendar.php:      "https://www.googleapis.com/auth/calendar.events";
./vendor/google/apiclient-services/src/Google/Service/Calendar.php:      "https://www.googleapis.com/auth/calendar.events.readonly";
./vendor/google/apiclient-services/src/Google/Service/Calendar.php:      "https://www.googleapis.com/auth/calendar.readonly";
./vendor/google/apiclient-services/src/Google/Service/Calendar.php:      "https://www.googleapis.com/auth/calendar.settings.readonly";
./application/views/appointments/book_success.php:            googleApiScope: 'https://www.googleapis.com/auth/calendar'
```

This is the **Enable Sync** button I'm clicking that yields that error:
![enable-sync](https://user-images.githubusercontent.com/33108490/94042611-6ed8ab00-fd91-11ea-9600-6a8f0efcbb73.png)

![400](https://user-images.githubusercontent.com/33108490/94043013-df7fc780-fd91-11ea-9aa3-ff6ade49c244.png)

Did I overlook a setting somewhere?

**Comment by alextselegidis** [comment]
Hello! 

You are right, this is currently a problem on develop. 

I will fix this soon. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by angela-d** [comment]
No longer get that error, now this appears (fresh install, too):

![undefined](https://user-images.githubusercontent.com/33108490/94171538-00f6b700-fe57-11ea-8ab4-9b023eed1b7c.png)

This appears once you click the "Enable Sync" button

**Comment by alextselegidis** [comment]
Please pull and try again as I've made some additional fixes on this. 

The problems got introduced by the upgrade of the google client library. 

Some things changed there. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by angela-d** [comment]
Ran into a few more, seems to be a bit different depending on browser.

Firefox (blank page, right-click > Inspect Element > Console):
![firefox](https://user-images.githubusercontent.com/33108490/94458660-da4cbf00-017b-11eb-9048-54d3dafad4df.png)

Got a little farther in Vivaldi, this occurs after sign in to google:
![aftergsignin](https://user-images.githubusercontent.com/33108490/94458717-ec2e6200-017b-11eb-9889-c10fd74ccd88.png)

Chrome (after you pick the calendar you want to sync):
![chrome](https://user-images.githubusercontent.com/33108490/94458932-46c7be00-017c-11eb-85e8-53b57ce92b19.png)

storage/logs (relational only to the latest git pull):
```text
ERROR - 2020-09-28 10:43:10 --> Severity: Notice --> Undefined property: stdClass::$refresh_token /var/www/application/controllers/Backend_api.php 1815
ERROR - 2020-09-28 10:43:21 --> Severity: Notice --> Undefined property: stdClass::$refresh_token /var/www/application/controllers/Backend_api.php 1815
ERROR - 2020-09-28 10:43:29 --> Severity: Notice --> Undefined property: stdClass::$refresh_token /var/www/application/controllers/Google.php 165
ERROR - 2020-09-28 10:49:13 --> Severity: Notice --> Undefined property: stdClass::$refresh_token /var/www/application/controllers/Backend_api.php 1815
ERROR - 2020-09-28 10:58:12 --> Severity: Notice --> Undefined property: stdClass::$refresh_token /var/www/application/controllers/Google.php 165
ERROR - 2020-09-28 10:58:29 --> Severity: Notice --> Undefined property: stdClass::$refresh_token /var/www/application/controllers/Google.php 165
```

**Comment by alextselegidis** [comment]
Thanks for the input, I will take a closer look and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
