### ISSUE TITLE
How can I enable google calendar sync afrer intallation

### ISSUE THREAD

**Issue by rajeev13** [alextselegidis/easyappointments#893]
I need to setup google calendar sync after installtion and what is google o-auth url ,in documentation its provided like
"http://url/to/easyappointments/installation/index.php/google/oauth_callback"  seems it can be used at the time of installtion.
please help.  
Also google controller doesn't have the function "oauth_callback".

**Comment by alextselegidis** [comment]
Hello, 

Please follow this guide: 

https://easyappointments.org/docs.html#1.3.2/google-calendar-sync.md

That's the method you are looking for: 

https://github.com/alextselegidis/easyappointments/blob/master/src/application/controllers/Google.php#L60

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
