### ISSUE TITLE
Sync with Google: (403) Requests from referer  are blocked.

### ISSUE THREAD

**Issue by BoraDevelop** [alextselegidis/easyappointments#894]
Hi there,
Everything works just fine until I try to sync with Google calender. I reseave the following error: (403) Requests from referer  are blocked. I've called Google if there is some blok on the calender but the answer was that everything should work and my requests should be proceded. Is there anything i should do to make it work? Is this a knowing issue? Please help with this matter.

**Comment by alextselegidis** [comment]
Hello! 

This should help: https://stackoverflow.com/a/54079955/1718162

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
