### ISSUE TITLE
Add Invoice Ninja client list integration

### ISSUE THREAD

**Issue by skylarmt** [alextselegidis/easyappointments#899]
Invoice Ninja is a popular open source invoicing platform. It includes client management features, and I use it to keep track of my clients. When I add an appointment to my schedule in EA, it would be a nice quality of life feature if it could fetch and autofill client details (email, phone, address, etc) from Invoice Ninja.

What this would mean is adding two configuration lines, one for the Invoice Ninja server URL and one for the API key, then using Invoice Ninja's PHP API library to fetch a list of clients, like below, then displaying them in the existing customer selection box.

```php
use InvoiceNinja\Config as NinjaConfig;
use InvoiceNinja\Models\Client as NinjaClient;

NinjaConfig::setURL("https://invoiceninja-url/api/v1");
NinjaConfig::setToken("truty534w98tt354rthtr6t73458t35tretgher");
NinjaConfig::setPerPage(9999);

$clients = NinjaClient::all();

foreach ($clients as $client) {
    echo "Name: " . $client->display_name;
    if (!empty($client->work_phone)) {
        echo "Phone: " . $client->work_phone;
    } else if (!empty($client->contacts[0]->phone)) {
        echo "Phone: " . $client->contacts[0]->phone;
    }

    if (!empty($client->contacts[0]->email)) {
        echo "Email: " . $client->contacts[0]->email;
    }

    echo "Address: " . ($client->shipping_address1 ?? ($client->address1 ?? ""));
    echo " " . ($client->shipping_address2 ?? ($client->address2 ?? ""));
    
    echo "City: " . ($client->shipping_city ?? ($client->city ?? ''));
    echo "ZIP: " . ($client->shipping_postal_code ?? ($client->postal_code ?? ''));

    echo "Public Notes: " . $client->public_notes;
    echo "Private Notes: " . $client->private_notes;
}
```

**Comment by alextselegidis** [comment]
Hello! 

There will probably be an Invoice Ninja integration in the future, but it will come as a standalone package/repository and won't be part of the original system. 

This will help us keep the core lightweight, with code that is only required for the booking. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by lublasco** [comment]
Hi, any news regarding the integration with Invoice Ninja? I agree with @skylarmt that this would be the perfect complement for EA to make it easy to invoice appointments.

**Comment by lublasco** [comment]
Thanks for the info, Alex. No worries, I'm sure there are other interesting features coming soon.

**Comment by alextselegidis** [comment]
Sure thing :)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
