### ISSUE TITLE
Insert New Appointment, don't show my "Services" or "Porvider"

### ISSUE THREAD

**Issue by sergioguedes** [alextselegidis/easyappointments#9]
Hi,
I create one service, with admin account !
After, still using the backend, I tray create a new  "+ Appointment" from "Calendar" view, but when the New Appointment windows open I dont see my Services / Proviser, created before !

![services](https://cloud.githubusercontent.com/assets/11735609/6917280/1088bda0-d79b-11e4-9701-48b2ac19527e.png)
![new_appointment](https://cloud.githubusercontent.com/assets/11735609/6917281/108b635c-d79b-11e4-86d2-37fc51001b18.png)

**Comment by alextselegidis** [comment]
You have to assign the services at your providers to see them in the booking form. Go to backend/users/providers and edit your preferred provider. Check the services he provides and save. Now  go to the booking page and you will be able to select this provider.
