### ISSUE TITLE
EasyAppointment doesn't working properly on server

### ISSUE THREAD

**Issue by JJTOkenizer** [alextselegidis/easyappointments#90]
Hi there,

I've configured my application for working on Hostinger free host, the app is developed in CodeIgniter and can be found here: http://primodebug.esy.es/Debug/user/login
When I enter my credential to access in the backend I got in the network tab console:
Failed to load response data
I don't know how, on local all working good and the redirect after the login is performed succesfull but on this host seems that the content isn't readed.
If you want try the credentials are this: (just for debug scope):
Username: Test
Password: 123456789
How you can see the login it's executed but the backend isn't loaded, I've also tried with other browser 'cause similar question on StackOverflow propose to disable adblock, but I've tried with: Microsoft Edge, Chrome, Mozilla and the error still the same.
The incriminated code seems this:

        $this->session->set_userdata('dest_url', $this->config->item('base_url') . 'backend');

        if (!$this->hasPrivileges(PRIV_APPOINTMENTS)) exit();

Is possible found this code in the index function in the backend, anyway, if I put this code on comment I can access to the backend but I also get a series of errors.. This situation happean also on another hosting: altervista.

How I can fix this? Seems that the Hosting can't read correctly something of CodeIgniter, please help me it's important.

**Comment by alextselegidis** [comment]
Seems that you do not have the problem any more.
