### ISSUE TITLE
REST API: create  provider return 200 with error message on dev mode

### ISSUE THREAD

**Issue by nouhouari** [alextselegidis/easyappointments#901]
Hi,
I'm trying to create a provider from the rest api using the following url:

`http://localhost/index.php/api/v1/providers`

with the following data:

`
{
        "id": 3,
        "firstName": "John",
        "lastName": "Doe",
        "email": "john.doe@gmail.com",
        "password": "john",
        "mobile": "",
        "phone": "+446111111111",
        "address": "Eeasy Residency",
        "city": "Hong Kong",
        "state": "Hong Kong",
        "zip": "68000",
        "notes": "",
        "services": [
            "1"
        ],
        "settings": {
            "username": "john_provider",
            "notifications": true,
            "calendarView": "default",
            "googleSync": false,
            "googleCalendar": null,
            "googleToken": null,
            "syncFutureDays": 5,
            "syncPastDays": 5,
            "workingPlan": {
                "sunday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                },
                "monday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                },
                "tuesday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                },
                "wednesday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                },
                "thursday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                },
                "friday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                },
                "saturday": {
                    "start": "09:00",
                    "end": "18:00",
                    "breaks": [
                        {
                            "start": "11:20",
                            "end": "11:30"
                        },
                        {
                            "start": "14:30",
                            "end": "15:00"
                        }
                    ]
                }
            }
        }
    }
`
The provider is created with a returned status code of 200 but I can see an error message:
`
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
	<h4>A PHP Error was encountered</h4>

	<p>Severity: Notice</p>
	<p>Message: Undefined index: password</p>
	<p>Filename: models/Providers_model.php</p>
	<p>Line Number: 137</p>
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
	<h4>A PHP Error was encountered</h4>

	<p>Severity: Warning</p>
	<p>Message: Cannot modify header information - headers already sent by (output started at
		/var/www/html/system/core/Exceptions.php:271)</p>
	<p>Filename: V1/Response.php</p>
	<p>Line Number: 145</p>
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
	<h4>A PHP Error was encountered</h4>

	<p>Severity: Warning</p>
	<p>Message: Cannot modify header information - headers already sent by (output started at
		/var/www/html/system/core/Exceptions.php:271)</p>
	<p>Filename: V1/Response.php</p>
	<p>Line Number: 146</p>
</div>
{
"id": 7,
"firstName": "Dias",
"lastName": "Guni",
"email": "gunanga.dias@gmail.com",
"mobile": null,
"phone": "+446193311801",
"address": "B16-03A Serin Residency",
"city": "Hong Kong",
"state": "Hong Kong",
"zip": "68000",
"notes": null,
"services": [
"1"
],
"settings": {
"username": "dias_provider",
"notifications": true,
"calendarView": "default",
"googleSync": false,
"googleCalendar": null,
"googleToken": null,
"syncFutureDays": 5,
"syncPastDays": 5,
"workingPlan": {
"sunday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
},
"monday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
},
"tuesday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
},
"wednesday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
},
"thursday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
},
"friday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
},
"saturday": {
"start": "09:00",
"end": "18:00",
"breaks": [
{
"start": "11:20",
"end": "11:30"
},
{
"start": "14:30",
"end": "15:00"
}
]
}
}
}
}
`

_**Note**_: The error is NOT visible in **production** mode.

**Comment by alextselegidis** [comment]
Hello! 

Please move the `password` property inside the `settings` object. 

This fine detail is missing from the docs. 

I will make sure it goes inside and also plan to prepare an open api spec file that will make things easier for 3rd party developers. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
