### ISSUE TITLE
BUG - Appointment's duration not shown correctly in frontend

### ISSUE THREAD

**Issue by PierfrancescoElia** [alextselegidis/easyappointments#907]
Hi everyone,
My situation is the following. I have 4 services (=offices) where the duration of the single appointment is currently set to 15 minutes. At the same time, I have 2 other services (total is 6) where the duration is set to 10 minutes.

When in the first step I choose the service I correctly see the duration (10 or 15 minutes), but when I proceed to the second step **independently** from the service I chose, I always see time slots every 15 minutes (e.g. 9:00 - 9:15 - 9:30). 

I'd expect to see 10-minutes slots when I try to book to _short services_.

Is that a conf problem or a bug?

Thanks in advance.

**Comment by alextselegidis** [comment]
Hello!

Change the availability type of your service from Flexible to Fixed. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by PierfrancescoElia** [comment]
Hi, 
thanks for your help.

Sorry if I ask, but what's the difference between Flexible and Fixed? Apparently I can't find any sort of documentation about it.

Thanks again, have a nice day!

**Comment by alextselegidis** [comment]
It has to do with how availability is generated: 

**Fixed** will generate available hours based on the service duration (e.g. service of 30 minutes will generate 09:00, 09:30, ...)

**Flexible** will generate available hours every 15 minutes, as long as there is no other booking in the schedule (e.g. 09:00, 09:15, ...)

In the future this part will be improved, as it's currently not that obvious. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
