### ISSUE TITLE
Config email notifications

### ISSUE THREAD

**Issue by Podolyan98** [alextselegidis/easyappointments#909]
Hi,

I have a SMTP server(MailCow). I'm trying to configure email.php:
```
$config['useragent'] = 'Easy!Appointments';
$config['protocol'] = 'smtp'; 
$config['mailtype'] = 'html'; 
$config['smtp_host'] = 'email.blinddate.vip';
$config['smtp_user'] = 'user';
$config['smtp_pass'] = 'pass';
$config['smtp_crypto'] = 'tls';
$config['smtp_port'] = 465;
```
On Booking page I click Confirm and the page freezes. After that I get the error:

`Email could not been sent. Mailer Error (Line 179): SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
`

This is a working configuration for other services. Also I tried to change the port/crypto, but I get the error:
`Email could not been sent. Mailer Error (Line 179): Could not instantiate mail function.`

**Comment by alextselegidis** [comment]
Hello! 

The application couldn't indeed connect to the SMTP server. 

Make sure the connection information are valid, as this is not a problem with Easy!Appointments. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
