### ISSUE TITLE
The comments do not display in the confirmation email

### ISSUE THREAD

**Issue by cleclemence** [alextselegidis/easyappointments#911]
Hello, 

When I book an appointment and leave a comment on step 3, I don't see it in the confirmation email. Is there a way to fix this? 

Thanks!

**Comment by alextselegidis** [comment]
Hello! 

You can edit the engine/notifications/Email.php file and the application/views/emails/appointment_details.php and add them to the content. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
