### ISSUE TITLE
Small TZ Issues

### ISSUE THREAD

**Issue by wvdvegt** [alextselegidis/easyappointments#914]
I did a fresh install of the latest pre-release.

Logged in as admin and set the TZ of John Doe to Azores (-1). Working schedule unchanged (9:00-18:00)

1. Accessing customers booking page (Paris+1 TZ) the correct slots but the customer confirmation mail shows the services TZ (Azores (-1)) instead of the customers one (Amsterdam (+1)).

       <table id="appointment-details">
            <tr>
                <td class="label" style="padding: 3px;font-weight: bold;">Service</td>
                <td style="padding: 3px;">Test Service</td>
            </tr>
            <tr>
                <td class="label" style="padding: 3px;font-weight: bold;">Provider</td>
                <td style="padding: 3px;">John Doe</td>
            </tr>
            <tr>
                <td class="label" style="padding: 3px;font-weight: bold;">Start</td>
                <td style="padding: 3px;">23/10/2020 10:00</td>
            </tr>
            <tr>
                <td class="label" style="padding: 3px;font-weight: bold;">End</td>
                <td style="padding: 3px;">23/10/2020 10:30</td>
            </tr>
            <tr>
                <td class="label" style="padding: 3px;font-weight: bold;">Timezone</td>
                <td style="padding: 3px;">**Azores (-1:00)**</td>
            </tr>
        </table>

1. The invitation.ics file seems correct but the provider one shows the customer TZ, expected would be the providers time/timezone.

A new appointment has been added to your plan.
TZID:**Europe/Berlin**
BEGIN:STANDARD
DTSTART:19691231T230000
TZOFFSETTO:+0100
TZOFFSETFROM:+0100
DTSTART:20201023T100000
DTEND:20201023T103000

**Comment by alextselegidis** [comment]
Hello!

Thanks for reporting that, I'll fix that before the final release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
