### ISSUE TITLE
selecting any provider leads to error

### ISSUE THREAD

**Issue by mokkin** [alextselegidis/easyappointments#917]
Error after selecting "any provider" on test installation with only one provider.
```
$service_id argument is not an numeric (value: "2020-10-26")
```
Version 1.4.0 - Beta.1 

![DeepinBildschirmfoto_Bereich auswählen_20201024215855](https://user-images.githubusercontent.com/2938748/97093157-ee37f380-1649-11eb-8118-2edc9ac86885.png)

**Comment by alextselegidis** [comment]
Hello!

Thanks for posting! This is indeed an error when selecting the -Any Provider- option. 

I will fix this before the final release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop.

**Comment by mrkylegp** [comment]
It's also an issue if you have one service with no providers assigned. Not a likely use case scenario but a bug anyway.

![Screenshot 2020-11-23 230554](https://user-images.githubusercontent.com/52687659/99960334-ae972f80-2de0-11eb-9f67-b8cce411199b.png)

**Comment by alextselegidis** [comment]
@mrkylegp That's an issue with the beta version that is already fixed. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
