### ISSUE TITLE
1.4beta Categories GET broken

### ISSUE THREAD

**Issue by DumahBrazorf** [alextselegidis/easyappointments#919]
Hi, if I request the list of categories from the API with the command
mydomain/index.php/api/v1/categories
I get this error:

```
A Database Error Occurred
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IS NULL' at line 3

SELECT * FROM `ea_service_categories` WHERE IS NULL

Filename: models/Services_model.php

Line Number: 488
```

If I request a specific one like mydomain/index.php/api/v1/categories/1  it works properly

**Comment by alextselegidis** [comment]
Hello! 

You are right, this is indeed an issue with the beta release. 

I will fix this before the stable release is out. 

Thanks for reporting!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop
