### ISSUE TITLE
Captcha dont show the image.

### ISSUE THREAD

**Issue by Presidents** [alextselegidis/easyappointments#92]
Hello, after install the version master the captcha image dont show...and in the packcage dont have nothing with Gregwar captcha.

simply dont make any appointment becouse acont see the image...

and after refresh image dont show nothing too.

thank you

**Comment by alextselegidis** [comment]
Hello, do you have the GD extension installed on your server? It is required for the image generation.

**Comment by Presidents** [comment]
gd in my php info

GD Support	enabled
GD Version	bundled (2.1.0 compatible)
FreeType Support	enabled
FreeType Linkage	with freetype
FreeType Version	2.3.11
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	6b
PNG Support	enabled
libPNG Version	1.2.49
WBMP Support	enabled
XBM Support	enabled

**Comment by Presidents** [comment]
i am download the original package of Gregwar and all running ok...
and to running i need put the composer complete folders and archive in third_party and the archive autoload.php to the aplication running ok....but with no captcha shoing.

**Comment by alextselegidis** [comment]
hmm that's strange,

can you tell me which version have you installed now so that I can compare it with the one I have installed. 

BTW I don't have any problems :/

**Comment by Presidents** [comment]
ok, was installed the master version 1.1 from

 https://easy-appointments.googlecode.com/files/easyappointments_1.0.zip

**Comment by alextselegidis** [comment]
Oh sorry, my question was not clear. I ment which version of Gregwar's CAPTCHA have you installed.

**Comment by Presidents** [comment]
i have here in other wamp archive to test this version...and all its ok to show the captchas...ok

https://github.com/afterlogic/plugin-gregwar-captcha/tree/master/libs/Gregwar/Captcha

**Comment by Presidents** [comment]
In this master.zip package dont have all archives to running after put in cpanel folder, its necessary put composer, and captcha dont show image normally or with refresh button. Thank you.

**Comment by alextselegidis** [comment]
Normally your are not supposed to use Easy!Appointments directly from GitHub. You will first have to install the composer dependencies as stated in the README file. You should download version 1.0 from the website.

**Comment by alextselegidis** [comment]
I'm also curious why this https://github.com/Gregwar/Captcha did not work for your server. I plan to release a new version with it and I need to be sure that it will work in common server configurations.

**Comment by Presidents** [comment]
ok, i have here in my server the codes from https://github.com/Gregwar/Captcha  and work fine, ok.

Ok, about the version, its in version 1.0 dont have responsive functions like master version...ok...


and congrats about the project...very good.

can you give only the lines of code to dont use captchas...only this its necessary to me runnng one appointment...ok...tks

**Comment by alextselegidis** [comment]
Glad it work for you and thanks for using E!A. 

So, if I understood well you actually need a way to disable CAPTCHA from v1.1 code branch?

**Comment by Presidents** [comment]
ok, in the last post i write about this https://github.com/Gregwar/Captcha always work in the test pages on the server...ok.

with the master.zip 1.1 codes dont show the image of captcha.

and if possible can you give me the code with no captcha...to complete the appointments..ok?


tks

**Comment by Presidents** [comment]
let me explain...after install the version 1.1...the image of captcha
![see](https://cloud.githubusercontent.com/assets/6377812/11964001/b6091d62-a8d1-11e5-9d52-7dfc51bfeac5.png) dont show.

**Comment by alextselegidis** [comment]
Checkout the project to this commit d1b5d66acca1835c3bcd158e61ac702cf6e222bd

**Comment by Presidents** [comment]
My friend...i put all archives in the server with all modifications in this https://github.com/alextselegidis/easyappointments/commit/d1b5d66acca1835c3bcd158e61ac702cf6e222bd

but dont show the image of captcha, please, can you upload yours master archives to the download link, i dont now what i am making wrong!

thank you for your time with me.

**Comment by alextselegidis** [comment]
No you have to checkout the project in this commit and put it on the server. It is not about the modifications of this commit.

Actually when you checkout this commit you will have an Easy!Appointments installation without the CAPTCHA addition and ready to use in your server. 

Be careful though because at this stage version 1.1 is not stable.

**Comment by Presidents** [comment]
ok, my friend, i undestood all about this modifications in commit explaned by you.

Only one question, please.


When i download the master package after all mods executed by this captcha commit and i running this script in my cpanel with all mods captcha in...the captcha dont show the image...ok.

 can you test this easyappointments-master.zip package separed in your server to you see running exactly  mine archives?

thank you

**Comment by Presidents** [comment]
in book.php archive near line 372
its correct this link ?


 <img class="captcha-image" src="<?php echo $this->config->item('base_url'); ?>/index.php/captcha">


thank you

**Comment by Presidents** [comment]
Why you close this ?

The main question its about SHOW THE CAPTCHA.

After install .

I dont want remove the captcha.

I only want see the image.

With the archives here ...after install version 1.1 dont show the image captcha.

Dont have all dependencies of greg captcha to running...

And i dont now where can i put this to running captcha correct...ok?

You are the man to solve this problem...

Becouse anothers person will take some problem in the future installations...only this.

Thanks

Merry chistmas.

**Comment by Presidents** [comment]
hello. alex

in folder src/ application/views/appointments
 the archive

book.php

in line

  <img class="captcha-image" src="<?php echo $this->config->item('base_url'); ?>/index.php/captcha">

calls in php function the captcha, but dont show nothing

where the calls to 
include ('base_url'.'/application/controllers/CaptchaBuilderInterface.php');
include ('base_url'.'/application/controllers/PhraseBuilderInterface.php');
include ('base_url'.'/application/controllersCaptchaBuilder.php');
include ('base_url'.'/application/controllers/PhraseBuilder.php');

how the captcha will running with this missing archives?


tks

**Comment by alextselegidis** [comment]
Hi again, 

now I can finally say that I get your problem. You will have to install the composer dependencies first. This is clearly stated in the README file. 

Composer Installation Page: https://getcomposer.org/doc/00-intro.md

After that you will have the complete v1.1 files.

**Comment by Presidents** [comment]
ok, but when i put archives of 1.1 master install , how can i put this dependences? thank you

**Comment by Presidents** [comment]
why you dont put all dependences in master 1.1 archives? anyone needs install this dependences...?

**Comment by Presidents** [comment]
my friend please, i am so sorry, but only now i descovery...my server cant install composer, becouse its a shared accounts in hostgator.

and i will descovery how can i put this to running...

sorry.

**Comment by Presidents** [comment]
no problem now...i put manually composer in the server...and i can running the master 1.1 script....but the captcha dont show nothing....

:-(

i dont know what i am making wrong....


i put here src/application/third_party
one folder called gregwar and put all archives of gregwar captchas in...

ok?

**Comment by Presidents** [comment]
alex.

please.

let me ask only one more.

Can you create the version 1.2 in other folder with all archives, libraries, dependencies, all archives to running without composer instaler?


thank you.


president

**Comment by alextselegidis** [comment]
I see that other users have the same problem as well, so I will modify the Composer installation procedure and will include the vendor files in the repository so that you can use E!A directly from the master branch.

**Comment by Presidents** [comment]
ok, this great....i am very thank you.

:-)

when can you will made this?

**Comment by alextselegidis** [comment]
Today or tomorrow it will be ready, I will post here again.

**Comment by Presidents** [comment]
great. congrats..  waiting....the update.

**Comment by alextselegidis** [comment]
Hey, the BETA is almost ready (just need to do some extra testing). You can try the new files from the master branch and tell me if you had any problems.

**Comment by Presidents** [comment]
ok, thanks...let me check.
