### ISSUE TITLE
No Docker Support for 1.4.0-Beta?

### ISSUE THREAD

**Issue by kbrewer76** [alextselegidis/easyappointments#920]
Is there any docker support

**Comment by alextselegidis** [comment]
Hello!

Yes, you can head to the "docker" repository and execute "docker-compose up" to start the containers. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
