### ISSUE TITLE
Can't run code 

### ISSUE THREAD

**Issue by DoaaIkzamia** [alextselegidis/easyappointments#921]
Good morning @alextselegidis ,

I can not run the code and this error appears

**Warning: require_once(C:\xampp\htdocs\doaa\easyappointments-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\doaa\easyappointments-master\index.php on line 63

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\doaa\easyappointments-master/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\doaa\easyappointments-master\index.php on line 63**

Please support

**Comment by sarfarazengglb** [comment]
how u closed the problem? i am still facing the same issue??

Please advise.I am trying to setup netbeans with this project

**Comment by alextselegidis** [comment]
Please run `composer install` to get the dependencies or use the pre-built package form the website. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by otheus** [comment]
Please update documentation, step 3; for both v1.4.0 and v1.4.1. (I don't think this problem applies to previous versions. 1.4.0 is needed, sadly due to the php5 dependency)
