### ISSUE TITLE
Changing the default language from config file not working

### ISSUE THREAD

**Issue by Ferguson230** [alextselegidis/easyappointments#922]
Hello, I tried to change the default language that is automatically loaded on first site visit (english) to french.
I changed from `$config['language'] = defined('Config::LANGUAGE') ? Config::LANGUAGE : 'english';  to `$config['language'] = defined('Config::LANGUAGE') ? Config::LANGUAGE : 'french';` in /appointment-booking/application/config/config.php` around line 85, but english is still loading though I cleared caches.

**Comment by alextselegidis** [comment]
Hello!

You can change the default language to the root config.php file which overrides the one you've updated. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
