### ISSUE TITLE
Integration with external applications

### ISSUE THREAD

**Issue by leonardorame** [alextselegidis/easyappointments#924]
Hi, I would like to know if there are "hooks" to let us create integrations with external applications, for example, after an appointment is created a message should be sent to ERPNext. Is there a way to do this without changing the source code?.

**Comment by alextselegidis** [comment]
Hello! 

You can use the CodeIgniter hooks for that: 

https://codeigniter.com/userguide3/general/hooks.html

<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
