### ISSUE TITLE
Array sorting exception is thrown if `working_plan_exceptions` is null

### ISSUE THREAD

**Issue by lexod** [alextselegidis/easyappointments#926]
https://github.com/alextselegidis/easyappointments/blob/6bf4e8b4eaf35cf002178f8a8dadd8ee912818a4/application/models/Providers_model.php#L328

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting, I will check. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Although I cannot reproduce this behavior inside the UI, as the app will always set a value to the working plan exceptions, I've added a check to make sure the error will never happen. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
