### ISSUE TITLE
there are days there are no hours of service

### ISSUE THREAD

**Issue by ahmadsyafiqkamil** [alextselegidis/easyappointments#929]
![image](https://user-images.githubusercontent.com/5411221/98223795-93799280-1f8d-11eb-96c0-06e6c806057e.png)

![image](https://user-images.githubusercontent.com/5411221/98223944-c91e7b80-1f8d-11eb-8d67-7868e2ce316d.png)

hello, can you help me about this error? 
i was checking in backend there is not appointment, but we cant see the hours of service. what should i do?

**Comment by alextselegidis** [comment]
Hello! 

Please share the working plan of your provider. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ahmadsyafiqkamil** [comment]
dear @alextselegidis 

this is my working plan

![image](https://user-images.githubusercontent.com/5411221/98684149-cb734200-23a0-11eb-871c-5d44d2025c6f.png)

**Comment by alextselegidis** [comment]
Your working plan is fine. 

By the screenshots I cannot tell if you have selected the correct provider but you should not have a problem. 

Consider booking the Technical Support service: info@easyappointments.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
