### ISSUE TITLE
Unavailable blocking is only in effect for the start date

### ISSUE THREAD

**Issue by unimodern** [alextselegidis/easyappointments#93]
If you block from 2015-12-12 14:30 to 2015-12-28 16:45, customers can still book appointments from 2015-12-13 to  2015-12-28 16:45, but not for the 2015-12-12.

**Comment by alextselegidis** [comment]
Hi, which version are you using? 

I cannot reproduce in v1.1

**Comment by unimodern** [comment]
Hi
I pulled it and looks ok now. Thanks for this great tool.
