### ISSUE TITLE
Medical equipment scheduling

### ISSUE THREAD

**Issue by leonardorame** [alextselegidis/easyappointments#930]
Hi, I'm testing 1.4beta and trying to setup a site where the user (a patient) appoints for medical equipments (CTs, MRIs, Ultrasound) and Any Provider (better if not showing the provider's list). So, it would be better if the user only see the service.

Apart from that, each service has a list of procedures where each procedure duration can be different, for example, an chest CT takes more time than a brain CT.

Is there a way to setup this?.

**Comment by alextselegidis** [comment]
Hello!

The simplest way to go with this structure would be to separate the similar services with different duration to multiple records in the system: 

* chest CT
* brian CT 
* .. 

Then assign the services to the correct providers and let the -Any Provider- feature to the work. 

Consider booking the Customization Service if you need to change more things to your installation. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
