### ISSUE TITLE
1.4.0-Beta1 Non-English languages cause issues in Default calendar view

### ISSUE THREAD

**Issue by KRUAndu** [alextselegidis/easyappointments#931]
Hello,

If using a Non-English language in the backend Calendar view, it causes non-working times and working plan exceptions to be missing (in week view). Although all appointments are shown, it confuses whether a person is working or not.  
If the language is set to English, everything is fine. It seems to be the only language where this problem doesn't occur.
![image](https://user-images.githubusercontent.com/38133229/98485366-9ccd5e00-221e-11eb-8e99-356017f15543.png)

I must specify - Table view (1 and 3day) and **default view (only day and month views)** are unaffected by this bug.

console debug error (MS Edge Chromium):
```
backend_calendar_default_view.min.js?824HX:formatted:531 Uncaught TypeError: Cannot read property 'start' of undefined
    at Object.<anonymous> (backend_calendar_default_view.min.js?824HX:formatted:531): null !== h[u] ? (Y = h[u].start.split(":"),
    at c (jquery.min.js?824HX:formatted:1298)
    at Object.fireWith [as resolveWith] (jquery.min.js?824HX:formatted:1351)
    at l (jquery.min.js?824HX:formatted:3739)
    at XMLHttpRequest.<anonymous> (jquery.min.js?824HX:formatted:3861)
```
This does not tell me much either, as almost all JS and CSS files have been _min_'d... 
due to this, debugging is annoying now.

server:
- php7.2
- 10.2.33-MariaDB

client:
- MS Edge (chromium 87.0.664.24 )
- this also happens with regular Chrome, Safari, Firefox

**Comment by alextselegidis** [comment]
Hello!

Thanks for reporting, I'll take a look and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by yannicklebras** [comment]
I had the same problem for french language.
I tried to solve it and it seems to be a problem with days traduction.
I put 
`var traduction = {"lundi":"monday",
					      	"mardi":"tuesday",
						"mercredi":"wednesday",
						"jeudi":"thursday",
						"vendredi":"friday",
						"samedi":"saturday",
						"dimanche":"sunday"};
weekdayName = traduction[calendarDate.format('dddd').toLowerCase()];`
on line 1248 of file backend_calendar_default_view.js and i had the good behavior. Of course it's not a bug fix, but can give you an idea of how to solve it ?

**Comment by alextselegidis** [comment]
Hello! 

Thanks for posting here. 

I was able to reproduce and fix the problem in develop. 

It will be working correctly for the stable release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by KRUAndu** [comment]
Thanks!
