### ISSUE TITLE
any way to get availabilities for multiple days with one call?

### ISSUE THREAD

**Issue by sherif807** [alextselegidis/easyappointments#932]
I have multiple providers in the same day and I want to pre-load the available times for today,tomorrow and the next day

I see I have to make 3 calls to /availabilities/$providerId

is this the only way? thank you

**Comment by alextselegidis** [comment]
Hello! 

You will need to make multiple requests as generating availability is a time consuming tasks, we make sure it only happens for the selected date. 

Consider booking the Customization Service if you need a customized bundle. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
