### ISSUE TITLE
Fatal error: require_once(): Failed opening required './vendor/autoload.php' 

### ISSUE THREAD

**Issue by chazhenry** [alextselegidis/easyappointments#933]

**Comment by alextselegidis** [comment]
Hello!

You will need to install the composer components with `composer install`.

https://getcomposer.org/

If you are not sure on how to do that, download the pre build package from the website.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by abdennour** [comment]
and when you run `composer install`, you got "PHP extension gd is missing from your system". 

These kind of issues should not appear in this era .

Installation steps should be packaged as software called ansible role, helm chart, . ...as per your deployment way.

Please put an end for this type of issues to guarantee the sustainability of your software.

**Comment by alextselegidis** [comment]
Hello @abdennour, 

Please make sure your server has the php-gd extension installed as it is required by the captcha library Easy!Appointments is using.

Based on your environment the installation of the extension may differ, but here is how this would work on Ubuntu as an example: 

https://stackoverflow.com/questions/44718896/how-to-install-php-gd-in-ubuntu

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
