### ISSUE TITLE
Rest API availabilities edition

### ISSUE THREAD

**Issue by nouhouari** [alextselegidis/easyappointments#938]
I would like to suggest one enhancement and include the availabilities creation/update/delete from the REST API.
As for now, only GET is available. Is this in the roadmap of the API ?
Many thanks

**Comment by alextselegidis** [comment]
Hello! 

The availability gets generated based on the working plan and the events of a provider. 

You cannot therefore create/update/delete it. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
