### ISSUE TITLE
Public metting page displays the busy hours

### ISSUE THREAD

**Issue by antonio-fr** [alextselegidis/easyappointments#939]
Maybe related to https://github.com/alextselegidis/easyappointments/issues/691 and possibly this is just I don't know how to activate an option or set up.

I setup "full hours" in Business Logic such as 10AM-6PM, then fixed services with 1 hour length, so that people can easy schedule an hour "full" during the week with a provider, e.g. Wed 3PM-4PM. This is like is cut my business week in 1 hour layers.
Then with the admin panel and the admin account I create a meeting with a customer and this provider at Wed 3PM-4PM.

Finally, when a new customer want a new meeting in the booking page, the Wed 3PM is displayed (as it shouldn't), but the error throws "busy, there's a meeting". Clicked on Edit the first meeting, save, without any modification it send an email of modification (I'll open a new ticket about this)
I tried a second try "public booking" to confirm : same provider, same service, same hour : now It works "successfully", and I have 2 meetings at the same hour, same service, same provider in the schedule.

What did I miss? For now, the Booking Page is always proposing a busy time window. And then it is either an "unexpected" error only at the very end, or I have 2 scheduled superposing. This functionality is the basis of the system I expect. I feel I'm still don't know the system and use it incorrectly.

After the second meeting added, I can't now book this slot.

- The slots are only hidden when they are added from the Booking Page , and still displayed if added from the admin panel?
- The Book Advance Timeout can have some effect on this ? For example only hide a meeting after this 30 mn timeout after the creation?

**Comment by antonio-fr** [comment]
Doing more tests and digging [into the code base](https://github.com/alextselegidis/easyappointments/blob/8c836bf10cd70df7e5478c41824a753943f1dd5a/application/libraries/Availability.php#L59), I finally found what was the issue. It was related to the number of attendants. One service was with 2 attendant , and the other 8. So the first one was disappearing after 2 meetings at the same time. I set 1 attendant only, it it works as expected.

One issue I can see is that when you select an other service with the same provider, the available slots should hide the slots taken by the other service. For now, it displays it, but throws an error message at the very end "not available". It should display the availability for only a specific service when it is selected in the first screen.

**Comment by alextselegidis** [comment]
Hello! 

The attendants number are bound to a service and not a provider. 

This feature was indented to serve cases like group appointments. 

If there are appointments for a service then there will be no availability generated for any other service for that time, even if the other services also accept multiple attendants. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
