### ISSUE TITLE
Can't install EA! XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by JackIlPAZZO** [alextselegidis/easyappointments#94]
XMLHttpRequest cannot load http://www.mywebsite.it/calendar/index.php/appointments/ajax_install. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mywebsite.it' is therefore not allowed access. The response had HTTP status code 403.

This happean on my hosting xlogic, but in localhost I got no error, what should I do?

**Comment by alextselegidis** [comment]
Hello, this a server configuration problem. 

Easy!Appointments v1.0 uses mod_rewrite for rewriting the URLs. You will have to work around that in your hosting company. Also check the support group of E!A, there are also some similar situations solved.

**Comment by JackIlPAZZO** [comment]
Hi @alextselegidis thanks for the answer. What edit I should execute? Maybe in .htaccess? I'm not an expert of this, could you help me?

**Comment by alextselegidis** [comment]
The .htaccess would be a nice place to start but you should better discuss the matter with you hosting company because it also involves server configuration.

**Comment by JackIlPAZZO** [comment]
@alextselegidis  Okay I've contacted my host, anyway this is my .htaccess content:

Options +FollowSymlinks
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L] 
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
