### ISSUE TITLE
PHP errors when deploying with docker

### ISSUE THREAD

**Issue by matletix** [alextselegidis/easyappointments#941]
I just cloned the repository and followed the instructions at [docs/docker.md](https://github.com/alextselegidis/easyappointments/blob/master/docs/docker.md).

When I load http://localhost:8000 in my browser, I get the following PHP error :
![image](https://user-images.githubusercontent.com/19894690/100132737-23707500-2e86-11eb-9502-a56868d353af.png)

**Comment by alextselegidis** [comment]
Hello!

Please install the composer dependencies with `composer install` first. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by matletix** [comment]
@alextselegidis 

Ok, it's not obvious these steps need to be done beforehand as containers usually install all the components they need so that no dependencies are needed on the host. May be useful to include them in the docker documentation or to add them to the Dockerfile.

1. Clone repository
2. copy config-sample.php to config.php and fill in the correct configuration
3. run npm install and composer install (need NodeJS installed)
4. cd docker && docker-compose up

```bash
git clone https://github.com/alextselegidis/easyappointments.git
cd easyappointments
cp config-sample.php config.php
$EDITOR config.php
npm install && composer install
cd docker && docker-compose up
```

**Comment by alextselegidis** [comment]
Agreed, these steps are in the README and they are taken for granted, but it's true that someone might jump right into the docker documentation without performing these steps first. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
