### ISSUE TITLE
In v1.4.0 Beta.1 the confirmation of a booking fails when multiple attendants

### ISSUE THREAD

**Issue by thomasdilts** [alextselegidis/easyappointments#942]
in v1.4.0 Beta.1 function controllers.Appointments.check_datetime_availability does not take into consideration multiple attendants. Therefore whenever you try to use multiple attendants the function returns a fail message. This does work well in version 1.3.2 however.

**Comment by alextselegidis** [comment]
Hello! 

The `check_datetime_availability` is using the same library as the `ajax_get_available_hours` for generating hours:

```
        $available_hours = $this->availability->get_available_hours($date, $service, $provider, $exclude_appointment_id);
```

The availability library takes into concern the multiple attendants. 

This will be there for the final v1.4.0 release. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
