### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Podolyan98** [alextselegidis/easyappointments#944]
Hey. I installed EA on a new server and followed the instructions:
```
git clone https://github.com/alextselegidis/easyappointments.git
cd easyappointments
sudo chown -R www-data:www-data /var/www/html/easyappointments
sudo chmod -R 775 /var/www/html/easyappointments
npm install && composer install
npm start
```
```
cp config-sample.php config.php
vim config.php
```

I have connected to an old database. This is what I saw in the browser:
![image](https://user-images.githubusercontent.com/68119338/101243392-9a203480-3708-11eb-941e-f7ab60d86140.png)

Nginx:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.php index.html index.htm index.nginx-debian.html;

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;

        }
}
```

**Comment by alextselegidis** [comment]
Hello!

You are missing some setting entries as the error dictates. 

Please download the latest release and install again: 

https://easyappointments.org/docs.html#1.4.0/installation-guide.md

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
