### ISSUE TITLE
Eroor after new install

### ISSUE THREAD

**Issue by Leonex123** [alextselegidis/easyappointments#947]
When i installed 1.4.0 on first run(open web location after install) i get in error_log

Availability.php unexpected ? line 111

**Comment by Leonex123** [comment]
[10-Dec-2020 13:12:34 Europe/Zagreb] PHP Parse error:  syntax error, unexpected '?' in /home/xxx/public_html/xxx/xxx/xxx/application/libraries/Availability.php on line 111

**Comment by Leonex123** [comment]
My php was 5.6 on cpanel, after upgrading to 7.0 it works now...

But as i know, null coalescing operator( ?? ) is supported from PHP 7.0 and documentation says 5.6 is ok for easy appointments 1.4.0 ....

**Comment by alextselegidis** [comment]
Hello! 

I will need to update the documentation for this. 

Thanks for posting!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
