### ISSUE TITLE
[v1.40] Instant Error 500 calling API from .NET

### ISSUE THREAD

**Issue by DumahBrazorf** [alextselegidis/easyappointments#951]
Pretty strange.
No problems within 1.40beta1, 1.40 stable returns instantly error 500 at any call from my program. 
My program is in VB.NET and I'm using the WebRequest and WebResponse classes. It's not a matter of using credentials or the new token, it get error 500 even passing nothing. 
Reverting to 1.40beta1 it works like before.
Calling the API using a browser or PostMan always works like a charm. 
What changed? 
PHP version on the server: 7.0.33  <-- could be it

**Comment by DumahBrazorf** [comment]
I think the 1.4.0 (<---forgot a point...) is causing some "PHP Fatal error: Allowed memory size of xxx ..." errors.
Tryed to step up the memory from 128MB to 256MB but had the same error.
On the client side no luck also using HttpWebRequest and WebClient classes.

**Comment by alextselegidis** [comment]
Hello!

Which request are you making? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by DumahBrazorf** [comment]
I'm trying to understand what I'm doing wrong.
Installed 1.4.0 in a different server with newer PHP. Now my program, PostMan and also Chrome can't login via APIs, constant error 401 - You are not authorized to use the API. Normal login to the backend via browser works.

**Comment by alextselegidis** [comment]
It seems that your server won't pass the authorization header to the app. 

Check the docs on how to do that (bottom section of the page):

https://easyappointments.org/docs.html#1.4.0/rest-api.md

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by DumahBrazorf** [comment]
Ok, the .htaccess mod was the trick. It seems it wasn't needed befero 1.4.0.
