### ISSUE TITLE
All the user roles with access to the backend calendar page can filter by services.

### ISSUE THREAD

**Issue by Leonex123** [alextselegidis/easyappointments#956]
I dont know if this is a bug or feature, but when i assign secratie to be admin for providers she can only see providers in calendar and not their services?

**Comment by alextselegidis** [comment]
Set as a feature for v1.5.0

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
