### ISSUE TITLE
(enhancment/help)

### ISSUE THREAD

**Issue by Leonex123** [alextselegidis/easyappointments#957]
Can new version have ALL services appointments on one calendar view or ALL providers appointments on one calendar view option?

I had this made by myself on 1.3.2 but now when i tried to adjust it for 1.4.0 or 1.4.1 like i had in 1.3.2 i get:

$service_id argument is not an numeric (value: "")
becaose value of option is "ALL" in backend_api.php and in backend_calendar_default_view but it doesent seem to work now.

Do you maybe have a solution how to make this work in 1.4.x

Thank you!

**Comment by alextselegidis** [comment]
Hello! 

I would need to work on that too. 

You can book the Customization Server: info@example.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
