### ISSUE TITLE
Appointment times

### ISSUE THREAD

**Issue by Leonex123** [alextselegidis/easyappointments#959]
When you create a service that lasts for 2 hours and you have avalible slots from 7AM to 7PM you can book that service every 2H instead whenever you want ,for example it gives you to book 07:00 then 09:00 ,and you also have 08:00 avalible,why cant you book at 08:00 or lets say 10:00 it only gives you options to book every 2H.
there are no breakes configured and timeout is set to 30minutes.

**Comment by popod** [comment]
Set "Availabilities Type" to "Flexible" in the service properties and you will no more hare the 2 hours steps.

**Comment by Leonex123** [comment]
Yes but then i will have option to book every 30 minutes since book timeout is set to 30 minutes and i can not allow overlapping

**Comment by alextselegidis** [comment]
There won't be any overlapping, it's just how availability renders in the booking page.

Everything else is being calculated normally. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
