### ISSUE TITLE
Providers break

### ISSUE THREAD

**Issue by JackIlPAZZO** [alextselegidis/easyappointments#96]
Hi there,

In my company there is some appointments that have a duration of 120 minutes or more. Now, the problem is that if I set a break for a particular provider and try to take the appointment with this long service I get false from: check_datetime_availability 'cause the appointment duration exceeds the period ends. Now I want to know how I can edit the code for allow my customer to take the appointments. The breaks are only a time slot for the selected hours windows in the front end, I don't want that the breaks prevent my clients to make an appointment. Which change I should do? Thanks and happy new year.

I also opened a topic here:

https://groups.google.com/forum/#!category-topic/easy-appointments/troubleshooting/Mdt98fbF8hE

**Comment by alextselegidis** [comment]
Answered here in the support group: 
https://groups.google.com/d/msg/easy-appointments/Mdt98fbF8hE/aBtHr38kFAAJ
