### ISSUE TITLE
DST not properly handled (calendar invite, list of timezones)

### ISSUE THREAD

**Issue by xfxf** [alextselegidis/easyappointments#962]
I am in a timezone currently experiencing DST/daylight savings (GMT+11).
The calendar invite that is sent from an attachment does not seem to understand DST.  The appointment calendar attachment is a hour out, so people are getting the wrong time put into their calendar.
The confirmation email text has the correct time (but lists the timezone incorrectly, see below).

Additionally, the list of timezones appears to be hardcoded in the PHP file, incorrectly stating that many timezones are static (it lists Melbourne as GMT+10.  It is only GMT+10 for some parts of the year).

**Comment by alextselegidis** [comment]
Hello! 

So whenever the ICS file or Google Sync gets used from the app, the configured timezone will be used.  

The timezone is a named string as shown in this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

As you can see of course there's not differentiation between daylight savings and normal time. 

Can you please elaborate and provide some steps to reproduce the error? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Any updates on this? 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by xfxf** [comment]
Sorry, I modified my production copy of Easy!Appointments (in a fairly hacky way) to work around the issue, so it's difficult to reproduce right now.  I will do that on a local copy in the coming days and supply some examples of the invalid ICS file.

**Comment by mrkylegp** [comment]
I found a solution by updating the jasvrcek ICS library with icvalyssa's fork fixed this issue for me.

https://github.com/icvalyssa/ICS

I copied and replaced the entire src directory and set permission and owner for my webserver after the fact.

Imported ICS files now work properly under Google Calendar, Windows Calendar, etc.

**Comment by xfxf** [comment]
@alextselegidis wish to reopen this, this still doesn't seem to be fixed.

Will paste some screenshots below.  This is reproducable on a plain version of the software, latest version.

I am in Melbourne (GST +10).  The problem exists when somebody tries to book an appointment from the US, which is generally 1 day before us, it leads to massive confusion.

I have overridden some wording (as we're using this to book technical checks for a virtual conference), but the software underneath is vanilla Easy!Appointments.

First, the booking in Sydney time, note 13th:
![image](https://user-images.githubusercontent.com/138684/125367295-399e5780-e3bb-11eb-94de-b96fce9e989e.png)

If this was changed to a US timezone, note it still says the 13th, even though the booking is actually the 12th:

![image](https://user-images.githubusercontent.com/138684/125367370-5fc3f780-e3bb-11eb-8ef9-a14a73c03636.png)

The final confirmation screen says the 13th:
![image](https://user-images.githubusercontent.com/138684/125367471-88e48800-e3bb-11eb-9811-b50ad3ad3e92.png)

But the email says the correct date:
![image](https://user-images.githubusercontent.com/138684/125367588-b92c2680-e3bb-11eb-8ac4-9833cdd59ebf.png)

**Comment by viperman26** [comment]
Hello, I am experiencing the same problem so reopening the issue. User selected timezone Bratislava(+1), times in the text of the email were correct, however gmail loaded the ICS file with wrong times(added an extra hour, I suppose because of DST). Screenshot and ics file attached.

Is there any fix?

Thank you.
![icsproblem](https://user-images.githubusercontent.com/11892543/197151168-3fe374bb-303e-4539-b050-a9ad25e46365.JPG)
[invitation (1).txt](https://github.com/alextselegidis/easyappointments/files/9837201/invitation.1.txt)
