### ISSUE TITLE
The operation could not complete due to unexpected issues.  → No error information provided.

### ISSUE THREAD

**Issue by bajramia** [alextselegidis/easyappointments#963]
Hi All,
I have installed and configure EasyAppointments Im having issue when im confirming the appointment when I hit confirm I get this error.
when i login to backend I do see the appointment is on the calendar.

**Comment by alextselegidis** [comment]
Hello! 

Which error are you referring to? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
