### ISSUE TITLE
Add custom fields

### ISSUE THREAD

**Issue by roncam82** [alextselegidis/easyappointments#964]
Hello,

Im using the latest easyappointments and im trying to add some custom fields.

I followed the below but still not managing. Actuall I managed to add the custom field to the booking form but it is not being shown in the Appointment Confirmation and it is not being sent to the mysql database.

First modify the ea_users table of the database and add the fields you need. Then modify the /application/controllers/appointments.php controller as needed. You will also need to display the data in booking form so modify the /application/views/appointments.php. Finally update the frontend_book.js so that your data are collected from the booking form as done with the rest of the fields. 

can you help me please ?

thanks
ronald

**Comment by alextselegidis** [comment]
Already anwered this one in the community group. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
