### ISSUE TITLE
Schedule Reports Feature

### ISSUE THREAD

**Issue by budihartono** [alextselegidis/easyappointments#965]
Please add reports so that admin can view all Service Provider’s schedules in a time range like a week or a month. That way we can tell how productive a service provider is, or maybe we’d want to calculate the commission that particular service provider will get. In addition, if it can be printed, it will help a lot.

**Comment by alextselegidis** [comment]
Hello! 

Reports is a topic that has to be explored into more detail and probably be split into multiple chunks. 

This will happen some time in the future. 

Till then I will close this ticket and open new ones when the time comes. 

Thanks for posting!

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
