### ISSUE TITLE
Payment integration

### ISSUE THREAD

**Issue by Khattak24** [alextselegidis/easyappointments#968]
Can you please tell me is their any payment method added in easyappointments or not?

**Comment by alextselegidis** [comment]
Hello! 

No there is no official payment integration but you could order your customized package by contacting: info@easyappointments.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
