### ISSUE TITLE
Custom Roles for Specific Users.

### ISSUE THREAD

**Issue by Shadief** [alextselegidis/easyappointments#972]
this issue was raised before but was kind of solved : 
https://github.com/alextselegidis/easyappointments/issues/800

but the solution is made for all the providers. can i make custom roles for each provider ?
for example i have three providers and i want each off them to have the following roles :

1. Provider One : **Read, Write.**
2. Provider Two : **Read, Write, Edit.**
3. Provider Three : **Read, Write, Edit, Delete.**

please suggest something, i can code in php but i don't want to take a deep look into it, i thought i should ask first maybe there is a quick way.

**Comment by alextselegidis** [comment]
Hello! 

In general the app will split the app data in resources that can work with view, add, edit, delete permissions. 

The resources are various data of the systems, e.g. services, customers, appointments etc. 

With this system you can add any user role you want and the app will react accordingly. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
