### ISSUE TITLE
Add custom Matomo analytics integration.

### ISSUE THREAD

**Issue by skylarmt** [alextselegidis/easyappointments#974]
I don't want Google spying on my customers while they're on my website, so I use self-hosted open source [Matomo](https://matomo.org/) for analytics. It would be great if I could easily integrate Matomo into Easy!Appointments.  The simplest and easiest way would be to have a textbox on the backend that administrators can paste code into, which would be added to the frontend page header. The slightly harder way would be adding multiple boxes for the Matomo URL, the site ID, and the other options Matomo's tracking code can set, and then building the JavaScript snippet from that info.  If that happened, E!A could be added to Matomo's [integrations](https://matomo.org/integrate/) gallery and in general would be good for Internet privacy.

**Comment by alextselegidis** [comment]
Hello! 

Matomo integration would be nice for the project but I'd have to come up with an elegant solution for adding such things into the app. 

Till then what you can do is change the application/helper/google_analytics_helper.php and add your snippet in there. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
