### ISSUE TITLE
Password reset does not work in Bulgarian language

### ISSUE THREAD

**Issue by Aztks** [alextselegidis/easyappointments#975]
Hi, just to share that the password reset does not work in Bulgarian language.
Whenever this language is set for the interface, the mail which is received with the new password has only "...." for passord.
In English works ok.
Seems bug to me.

**Comment by alextselegidis** [comment]
Hello! 

I just tried that locally and works without problems. 

Please check the error logs and the browser devtools for error info and post them here.

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
