### ISSUE TITLE
Already booked slot still available for booking on mobile browser.

### ISSUE THREAD

**Issue by ARHlgomez** [alextselegidis/easyappointments#977]
Slots already booked still available for booking on mobile browser (tested with firefox and chrome on Android).
Very annoying issue.

Example :
3rd February 2021 14h00 slot

**On Chrome Windows 10**
![booking-01](https://user-images.githubusercontent.com/77383853/104431434-29cac580-5588-11eb-9161-6b12163cd647.png)

**On Chrome Android**
![Screenshot_20210113-100546](https://user-images.githubusercontent.com/77383853/104431714-7f06d700-5588-11eb-8aee-0c05363f209c.png)

**On Firefox Android**
![Screenshot_20210113-101756](https://user-images.githubusercontent.com/77383853/104432009-da38c980-5588-11eb-8f35-b121e7f53192.png)

**Comment by alextselegidis** [comment]
Hello! 

Which Easy!Appointments version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by ARHlgomez** [comment]
Easy!Appointments v1.4.0

**Comment by ARHlgomez** [comment]
After updating, the issue is gone.
Sorry for disturbing you for nothing. I didn't notice the update since i installed your webapp in december.
Thank for your quality work.

**Comment by alextselegidis** [comment]
Stay tuned for future updates :)

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
