### ISSUE TITLE
Web browser timezone

### ISSUE THREAD

**Issue by thor432** [alextselegidis/easyappointments#978]
Is it possible to disable web browser timezone, so the site only uses the server/or practitioners timezone?

Can't remember i had to modify this behaviour in 1.3.x?

**Comment by alextselegidis** [comment]
See answer in this ticket https://github.com/alextselegidis/easyappointments/issues/961

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
