### ISSUE TITLE
Getting `No direct script access allowed` when opening the app in the browser.

### ISSUE THREAD

**Issue by mr-omidnaderi** [alextselegidis/easyappointments#979]
Hi
I did everything but it gives the error,
How do I fix the problem?
please help

**Comment by mr-omidnaderi** [comment]
![Capture](https://user-images.githubusercontent.com/27927279/104941344-3310c380-59c8-11eb-920c-d9a54651d92f.PNG)

erorr

**Comment by alextselegidis** [comment]
Hello! 

Something is problematic with your instance as it seems there's a file being accessed without the root index.php being called, which is also the file that has to be executed first on each request.

You can try that yourself by editing the root index.php file and writing `die('test');` as the first command after `<?php`. 

You should normally see `test` as an output. 

Can you confirm that? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mr-omidnaderi** [comment]
Hi yes I did, I can see
Where is the project problem now? Please help

**Comment by alextselegidis** [comment]
Try visiting the installation page by opening `http://127.0.0.1/easyappointments/index.php/installation` and submitting the form. 

Does this work for you? 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by mr-omidnaderi** [comment]
![یبیب](https://user-images.githubusercontent.com/27927279/105354671-21b4fa80-5c06-11eb-8661-813b62ee6b0c.PNG)

The problem was not solved unfortunately

**Comment by mr-omidnaderi** [comment]
I went through these steps correctly but it did not work
Is the version inside GateHub the latest version?
Maybe the problem is the script inside the gate hub?

**Comment by mr-omidnaderi** [comment]
Hello, thank you for guiding me on this.

**Comment by Chtulhu2021** [comment]
Sounds like a permission directory problem in your server.

**Comment by alextselegidis** [comment]
Yes, the master branch has the files of the latest release. 

Your service does not execute the index.php file correctly when you point your browser to your URL. 

This is a configuration issue that cannot be solve here. 

Consider booking the Installation Service for professional support: info@easyappointments.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
