### ISSUE TITLE
Date displayed as DMY but write as MDY

### ISSUE THREAD

**Issue by nigelirvine** [alextselegidis/easyappointments#98]
when I add a new appointment or update one, it is stored in appointments table with day/month inverted

**Comment by alextselegidis** [comment]
Hello 

Yes, this is happening because the dates are stored in the default MySQL format "YYYY-MM-DD HH:MM:SS"

http://dev.mysql.com/doc/refman/5.7/en/datetime.html

Best Regards, 

Alex
