### ISSUE TITLE
 BUG - Appointment's duration not shown correctly in backend

### ISSUE THREAD

**Issue by Chtulhu2021** [alextselegidis/easyappointments#981]
Hi and thanks for your work!

 I set up a 20 minutes service. End time do not show up correctly during calendar time selection on a Linux Desktop with Mozilla Firefox. It is still stuck to the default 15 minutes duration. I have to pick a "dummy service" then to pick back the 20 minutes service to properly book the service with the right duration.

Changing the availability type of the service from Flexible to Fixed does not fix this.

Using E!A v1.4, apache 2.4.38 and MariaDB 10.3.27

Best regards

**Comment by alextselegidis** [comment]
Hello! 

> during calendar time selection

Are you referring to the selection inside the calendar widget, or to the use of the datepickers inside the appointment modals? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Chtulhu2021** [comment]
Here it is:
![Capture du 2021-01-22 09-43-50](https://user-images.githubusercontent.com/77326404/105467747-67b99f00-5c96-11eb-92a1-f9788286a4da.png)

**Comment by alextselegidis** [comment]
I cannot reproduce this one. 

When I change the service the end time gets updated too. 

Are you using the latest release (v1.4.1 at the time of writing)? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Chtulhu2021** [comment]
Yes I do.
When I change the service the end time is right. The problem appears only with the "default" service.

**Comment by alextselegidis** [comment]
This should not be the case since: 

https://github.com/alextselegidis/easyappointments/commit/23ac39797ba98311371fd55b7dab7e001a51d066

Make sure the commit's change is also part of your installation. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
