### ISSUE TITLE
Wrong timezone in email customer notification if appointment taken from backoffice

### ISSUE THREAD

**Issue by AlessioArtini** [alextselegidis/easyappointments#985]
I experienced that when we take an appointment from backoffice system send email notification to customer with wrong timezone.
The notification to provider is correct.

**Comment by alextselegidis** [comment]
Hello! 

Which version are you using? 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by AlessioArtini** [comment]
> Hello!
> 
> Which version are you using?
> ![](https://camo.githubusercontent.com/30676c4987784d10e020c434b4519580e70da2388d2b1032698121af407caeff/68747470733a2f2f656173796170706f696e746d656e74732e6f72672f696d672f656173796170706f696e746d656e74732d7369676e61747572652e706e67)	  Alex Tselegidis, Easy!Appointments Creator
>   [Need a customization? Contact me in person!](https://alextselegidis.com)

latest 1.4.1

**Comment by skylarmt** [comment]
I'm also having this issue, a customer was confused when they received an email for an appointment at 8:30 PM (UTC) instead of 1:30 PM local time!

**Comment by skylarmt** [comment]
Looks like this is fixable by simply adding an option somewhere to set the default timezone for customers.  Looks like it defaults to UTC right now, but nearly all my customers are local so it would be much better if I could set the default timezone to the local one.

**Comment by skylarmt** [comment]
I found a workaround for setting the default timezone: Connect to the database and run, for example,

```sql
ALTER TABLE ea_users ALTER COLUMN timezone SET DEFAULT "America/Denver";
```

which will make all new users (including customers) default to the chosen timezone instead of UTC.

While you're in there, to retroactively change all existing users to your timezone of choice, run:
```sql
UPDATE ea_users SET timezone="America/Denver";
```

You can find a list of valid timezones in `application/libraries/Timezones.php`.

**Comment by alextselegidis** [comment]
Hello!

I also think that setting a default global timezone would be important. 

This will be part of the overall services improvements where there will be new settings for configuring local and remote events and therefore allow flexible or fixed timezones. 

Till this is implemented you can use @skylarmt's solution. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
