### ISSUE TITLE
Seeing customers of other providers

### ISSUE THREAD

**Issue by Mohamed-Messai** [alextselegidis/easyappointments#994]
Hi and Thank you for your work, 
is there a way to show for each provider only its customers (also for a secretary) ?
Best regards,

**Comment by alextselegidis** [comment]
Hello! 

This behavior requires code changes at the core of the app. 

If you are not sure on how to proceed you can book the Customizations Service and get a ready made package for your server: info@easyappointments.org

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
