### ISSUE TITLE
Double booking

### ISSUE THREAD

**Issue by axlmurman** [alextselegidis/easyappointments#996]
The service I have added only accept one attendants at a time but I can it's still see, select and book an unavailable time. This bug only seems to be if I'm not logged in. The service only accept one attendants at a time but has now multiple bookings in the calendar.

**Comment by axlmurman** [comment]
It seems that the problem is when you have accepted one (1) booking at a time. Then I can book as many as I like ... If I have two bookings at the time available, you can only book two then it will be full.

**Comment by alextselegidis** [comment]
Hello! 

Which version are you using? 

I cannot replicate the issue with the provided information, can you please elaborate? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
