### ISSUE TITLE
Last booking of the day displayed as duplicate of the previous in table view when logged in as non-admin

### ISSUE THREAD

**Issue by szekrenyigabor** [alextselegidis/easyappointments#998]
Hi,
In EasyAppointments 1.4.1, if you book two or more appointments for a provider for different times on the same day, the last two bookings of the day are merged side-by-side into a single line on backend / calendar / table view.  Also, all the details of the very last booking of the day are replaced with the parameters of the last-but one, making it look like a duplicate. This issue is present in both Calendar and List view, but **only when logged in as non-admin**. When logged in as admin, all bookings are displayed correctly. Also, Default calendar view displays bookings correctly regardless of user role.

![1](https://user-images.githubusercontent.com/48789609/106873434-bf173080-66d4-11eb-8247-23bfb3ef728c.png)
![2](https://user-images.githubusercontent.com/48789609/106873438-bfafc700-66d4-11eb-9c82-d58b7e6d56c9.png)
![3](https://user-images.githubusercontent.com/48789609/106873439-c0485d80-66d4-11eb-8e66-232d40c7133e.png)

**Comment by szekrenyigabor** [comment]
Dear Alex,

thank you for your reply. I was able to reproduce the issue at demo.easyappointments.org too. Below I describe the minimum steps needed to see the issue. Please remember that the issue only happens when logged in as secretary or provider. If you log in as admin, all is OK.

1.) Login at demo.easyappointments.org as an administrator
2.) Create a provider and assign services to him
3.) Add a new secretary and assign all providers to him
4.) Logout from the admin backend
5.) In the front-end, book two appointments for the SAME DAY, to the SAME PROVIDER: for example, one for 15/feb/2021 10:00 a.m, another for 15/feb/2021 16:00 p.m.
6.) Log in as the SECRETARY you created in step 3 (not as admin!), notice that the two appointments are displayed correctly in default calendar view.
7.) Now click the top right icon to switch the calendar to table view and select the day you booked to (15/feb/2021 in the example). Notice that the there is no booking at 16:00, but the two bookings are diplayed in one line, with the same details. Normally they should be on separate lines with their own parameters. This means that the booking that should be at 16:00 is instead shown at 10:00.
8.) Click on List view button and see that instead of showing two different bookings, you see the first booking twice.

Thank you for your help.

![1](https://user-images.githubusercontent.com/48789609/107499065-caff6880-6b94-11eb-932f-2a096af70a55.png)
![3](https://user-images.githubusercontent.com/48789609/107499066-cb97ff00-6b94-11eb-8ac8-70c2fd623ce1.png)
![4](https://user-images.githubusercontent.com/48789609/107499068-cc309580-6b94-11eb-92f2-7b2755c01040.png)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for the detailed steps. 

So I tried doing the same thing on demo.easyappointments.org and I still do not get the same behavior. 

![Screenshot 2021-02-15 at 15 17 48](https://user-images.githubusercontent.com/4527441/107957557-11900100-6fa1-11eb-8382-daebcff3c850.png)

Are your screenshots coming from the demo installation or your own personal one? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by szekrenyigabor** [comment]
Hi Alex,
following the steps from my previous post, I made a screencast of the issue for you to see. Yes, it was recorded at demo.easyappointments.org, but the same happens in my own installation too.

Please have a look at the non-pubilc YouTube video at https://youtu.be/Fg2uoLDjzb0

Thank you, best regards:
Gábor

**Comment by JDeepix** [comment]
Same problem here.
Secretary AND Provider shows wrong last entry in List-View but not in Calender-View.
Sysadmin shows all correct.

I'll look into the code. Hopefully I'll find something.

regards,
Jens

**Comment by JDeepix** [comment]
Problem already solved:
#1023 
One line helps. Would have never find that one :-)
Thanks @winniae

**Comment by alextselegidis** [comment]
Thanks @JDeepix 

@szekrenyigabor Can you please confirm this solves your problem? 


<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by szekrenyigabor** [comment]
Yes, @winniae 's solution linked by @JDeepix solved the problem, thank you very much!

**Comment by alextselegidis** [comment]
Great, I'll merge this and release with 1.4.2

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
