### ISSUE TITLE
Filtering by provider doesn't work in table view when logged in as non-admin

### ISSUE THREAD

**Issue by szekrenyigabor** [alextselegidis/easyappointments#999]
Hi, 
In EasyAppointments 1.4.1, filtering to one provider on the backend still displays all existing providers in table view when logged in as non-admin. However, when logged in as admin, the filter works as expected.

![4](https://user-images.githubusercontent.com/48789609/106876265-d1df3480-66d7-11eb-83a5-345b1afc47ec.png)

**Comment by alextselegidis** [comment]
Hello!

Once again I tried that on demo.easyappointments.org and could not reproduce (I was only getting a single provider record). 

Please make sure you are not logged in as a secretary, cause secretaries can see the calendars of multiple providers. 
<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by szekrenyigabor** [comment]
Dear Alex,

thank you for your reply. Take an example of the following: there is a user with "secretary" role with two or more providers assigned to him. If I log in as this secretary and (very importantly) **switch to Table View**, by default I see the view of a day with a separate column for all the providers I am assigned to (e.g. James Ricardo, Jane Doe, Tom Test). Now, if I choose to filter the view to a single provider, I select Jane Doe from the Provider filter dropdown, I assume that I should only see Jane Doe's calendar for that day. Instead, nothing changes and still I see all providers. Please note that we are still in table view. If I switch back to default view, the filter dropdown on the top left does its job as expected. Also, doing the same when logged in as admin, filtering works as well even in table view. 

Thank you for looking into it.
![1](https://user-images.githubusercontent.com/48789609/107501923-4f9fb600-6b98-11eb-8966-10e7581df4b9.png)
